RDoc-1763
ravendb/docs pull request #1192
Opened 2020-08-17 03:59 UTC by reebhub

session-context load balancing documentation (API & Studio)

2020-08-20 11:44 UTC, ayende requested changes

2020-08-20 11:44 UTC, ayende commented on Documentation/5.0/Raven.Documentation.Pages/client-api/session/configuration/use-session-context-for-load-balancing.markdown
> +* Using pre-set topologies enables clients and administrators to load-balance requests
```suggestion
* Using preset topologies enables clients and administrators to load-balance requests 

```

2020-08-20 11:44 UTC, ayende commented on Documentation/5.0/Raven.Documentation.Pages/client-api/session/configuration/use-session-context-for-load-balancing.markdown
> +  handled by an "**employees_top**" and a "**products_top**" topologies, respectively.
I don't understand what you mean here

2020-08-20 11:44 UTC, ayende commented on Documentation/5.0/Raven.Documentation.Pages/client-api/session/configuration/use-session-context-for-load-balancing.markdown
> +    and to server write requests by the [Preferred Node](../../../client-api/configuration/load-balance-and-failover#preferred-node)
```suggestion
    and to serve write requests by the [Preferred Node](../../../client-api/configuration/load-balance-and-failover#preferred-node) 

```

2020-08-20 11:44 UTC, ayende commented on Documentation/5.0/Raven.Documentation.Pages/client-api/session/configuration/use-session-context-for-load-balancing.markdown
> +    and to server write requests by the [Preferred Node](../../../client-api/configuration/load-balance-and-failover#preferred-node)
That said, the phrasing is awkward

2020-08-20 11:44 UTC, ayende commented on Documentation/5.0/Raven.Documentation.Pages/client-api/session/configuration/use-session-context-for-load-balancing.markdown
> +       topology that would handle client requests by its hash seed.
Unclear what this means. Admins can either disable this feature or add a hash that would mix the topology if needed (rare)

2020-08-20 11:44 UTC, ayende commented on Documentation/5.0/Raven.Documentation.Pages/client-api/session/configuration/use-session-context-for-load-balancing.markdown
> +  Enabling this feature increases the chance for conflicts,
Can we tone down the alarm level here?
This is usually not going to happen because in this model, you'll only write to nodes on your own tags

2020-08-20 11:44 UTC, ayende commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/client-configuration-per-database.markdown
> +  * Optionally, select a hash seed to fix the topology that clients would use.
```suggestion
  * Optionally, select a hash seed to randomize the topology that clients would use.  
```

2020-08-20 11:44 UTC, ayende commented on Documentation/5.0/Samples/csharp/Raven.Documentation.Samples/ClientApi/Configuration/Cluster.cs
> +                    #region ReadBalanceBehavior
Missing the DocumentsConventions context, so user will know how to set it

2020-08-20 11:44 UTC, ayende commented on Documentation/5.0/Samples/csharp/Raven.Documentation.Samples/ClientApi/Configuration/Cluster.cs
> +                    LoadBalanceBehavior = LoadBalanceBehavior.UseSessionContext
same

2020-08-20 11:44 UTC, ayende commented on Documentation/5.0/Samples/csharp/Raven.Documentation.Samples/ClientApi/Session/Configuration/ChooseTopology.cs
> +        public DocumentStore getDocumentStore()
```suggestion
        public DocumentStore GetDocumentStore()

```

2020-08-20 12:13 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/client-api/session/configuration/use-session-context-for-load-balancing.markdown
> +* Using pre-set topologies enables clients and administrators to load-balance requests
done

2020-08-20 12:29 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/client-api/session/configuration/use-session-context-for-load-balancing.markdown
> +  handled by an "**employees_top**" and a "**products_top**" topologies, respectively.
is this clearer? - 
* Clients and administrators can use tags to load-balance traffic, e.g. by requesting **employee** documents from a topology tagged "employee" and **product** documents from a topology tagged "products".

2020-08-20 13:02 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/client-api/session/configuration/use-session-context-for-load-balancing.markdown
> +    and to server write requests by the [Preferred Node](../../../client-api/configuration/load-balance-and-failover#preferred-node)
* `None`  
    Read requests are handled based on the [ReadBalanceBehavior convention](../../../client-api/configuration/load-balance-and-failover#readbalancebehavior-options).  
    Write requests are handled by the [Preferred Node](../../../client-api/configuration/load-balance-and-failover#preferred-node) calculated by the client.

2020-08-20 13:17 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/client-api/session/configuration/use-session-context-for-load-balancing.markdown
> +       topology that would handle client requests by its hash seed.
what does "mix the topology" mean?
for now - 

* Administrators can disable this feature or add a hash to choose the topology.

2020-08-20 13:22 UTC, ayende commented on Documentation/5.0/Raven.Documentation.Pages/client-api/session/configuration/use-session-context-for-load-balancing.markdown
> +  handled by an "**employees_top**" and a "**products_top**" topologies, respectively.
That isn't how it works. 
You'll typically use something like the user id, or the tenant id to have the same topology for user / tenant.
That isn't on a per collection basis.

2020-08-20 13:23 UTC, ayende commented on Documentation/5.0/Raven.Documentation.Pages/client-api/session/configuration/use-session-context-for-load-balancing.markdown
> +    and to server write requests by the [Preferred Node](../../../client-api/configuration/load-balance-and-failover#preferred-node)
ok

2020-08-20 13:23 UTC, ayende commented on Documentation/5.0/Raven.Documentation.Pages/client-api/session/configuration/use-session-context-for-load-balancing.markdown
> +       topology that would handle client requests by its hash seed.
The hash they add is used to randomize the topology that is selected for the client when they set a tag

2020-08-20 17:59 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/client-api/session/configuration/use-session-context-for-load-balancing.markdown
> +  Enabling this feature increases the chance for conflicts,
{NOTE: }
  Conflicts may rarely happen, when multiple sessions that use different tags 
  modify a shared document concurrently. 
  {NOTE/}

2020-08-20 18:06 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/client-api/session/configuration/use-session-context-for-load-balancing.markdown
> +  handled by an "**employees_top**" and a "**products_top**" topologies, respectively.
i see. thanks.
can you give an example please, to a situation in which a user would want to always use the same topology?

2020-08-20 18:11 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/client-api/session/configuration/use-session-context-for-load-balancing.markdown
> +       topology that would handle client requests by its hash seed.
done.

* Administrators can disable this feature, or add a hash to randomize the topology that would be selected for the client when it uses a tag.

2020-08-20 18:12 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/client-configuration-per-database.markdown
> +  * Optionally, select a hash seed to fix the topology that clients would use.
done

2020-08-20 18:23 UTC, reebhub commented on Documentation/5.0/Samples/csharp/Raven.Documentation.Samples/ClientApi/Configuration/Cluster.cs
> +                    #region ReadBalanceBehavior
fixed

2020-08-20 18:23 UTC, reebhub commented on Documentation/5.0/Samples/csharp/Raven.Documentation.Samples/ClientApi/Configuration/Cluster.cs
> +                    LoadBalanceBehavior = LoadBalanceBehavior.UseSessionContext
fixed

2020-08-20 18:27 UTC, reebhub commented on Documentation/5.0/Samples/csharp/Raven.Documentation.Samples/ClientApi/Session/Configuration/ChooseTopology.cs
> +        public DocumentStore getDocumentStore()
fixed

2020-08-25 12:20 UTC, ayende requested changes

2020-08-25 12:20 UTC, ayende commented on Documentation/5.0/Raven.Documentation.Pages/client-api/session/configuration/use-session-context-for-load-balancing.markdown
> +  modify a shared document concurrently.
```suggestion
  modify a shared document concurrently. This is handled by RavenDB according to your conflict resolution strategy.
 
```

And add a link to the relevant docs.

2020-08-25 12:20 UTC, ayende commented on Documentation/5.0/Samples/csharp/Raven.Documentation.Samples/ClientApi/Session/Configuration/ChooseTopology.cs
> +                    LoadBalancerPerSessionContextSelector = db => context
Do something like "CurrentUser.UserId" or something like that, `context` is too vague

2020-08-25 12:20 UTC, ayende commented on Documentation/5.0/Raven.Documentation.Pages/client-api/session/configuration/use-session-context-for-load-balancing.markdown
> +
```suggestion


For example, consider a database with three nodes: `A`,`B` and `C`. With `LoadBalanceBehavior` set to `None`, the 
cluster will designate one of the nodes in the cluster as the primary, which will be used for both reads and writes.
You can use the `ReadBalanceBehavior` to spread the load among all the nodes of the database, but writes will
always go to the same primary node (which may change in case of failure).

he `LoadBalanceBehavior` convention allows you to specify a `tag`, which will mean that all sessions sharing
the same tag will have a _different_ primary node in the database topology. For example, if you are using a per
user context, sessions using the tag `users/1-A` will use node B as the primary (for reads and writes) while 
sessions using `users/2-A` will use node C as the primary.

Aside for the primary selection by the session, RavenDB continues to behave in the same manner. Replication 
between nodes in the database will operate normally and writes that were sent to one node would be replicate
to all the other nodes. 

This feature is useful when you have a degree of separation in your system, where a certain set of sessions 
will typically work on specific set of documents. Common examples include setting the context to the current user
or the current tenant. 
This will allow the client side to spread the write and read load across the nodes in the cluster on a fair basis

Failure of a particular node is handled normally, even if it is the primary node for a particular `tag` and will not
be visible to your code. Fail over to another node in the database will happen automatically and transparently. 

```

2020-08-25 14:29 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/client-api/session/configuration/use-session-context-for-load-balancing.markdown
> +  modify a shared document concurrently.
done

2020-08-25 14:40 UTC, reebhub commented on Documentation/5.0/Samples/csharp/Raven.Documentation.Samples/ClientApi/Session/Configuration/ChooseTopology.cs
> +                    LoadBalancerPerSessionContextSelector = db => context
string currentUserID = "usersTopology";

2020-08-27 13:05 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/client-api/session/configuration/use-session-context-for-load-balancing.markdown
> +
reshaped the page
* there's a "LoadBalanceBehavior Usage" panel
* revised the information about administrator interferences in the "LoadBalanceBehavior Options" panel

2020-09-02 11:47 UTC, ayende approved these changes

2020-09-25 13:17 UTC, merged