RDoc-1825-fix-typo-stockprice fixed some typos
ravendb/docs pull request #1272
Opened 2020-11-08 17:10 UTC by morhilai

StockPrice => StockPrices
HeartRate => HeartRates
In aggregation-and-projections.markdown, user => employee

2020-11-09 06:25 UTC, karmeli87 requested changes

2020-11-09 06:25 UTC, karmeli87 commented on Documentation/5.0/Samples/csharp/Raven.Documentation.Samples/DocumentExtensions/TimeSeries/TimeSeriesTests.cs
> +                store.TimeSeries.Register<User, HeartRates>();
Does you class defined as `public class HeartRate` or `public class HeartRates`.
To be consistent with any other generic convention it should be in the singular form.
So it should be `store.TimeSeries.Register<User, HeartRate>();`

2020-11-09 06:26 UTC, karmeli87 commented on Documentation/5.0/Samples/csharp/Raven.Documentation.Samples/DocumentExtensions/TimeSeries/TimeSeriesTests.cs
> +                store.TimeSeries.Register<User, HeartRates>();
same for `StockPrice`

2020-11-11 15:45 UTC, morhilai commented on Documentation/5.0/Samples/csharp/Raven.Documentation.Samples/DocumentExtensions/TimeSeries/TimeSeriesTests.cs
> +                store.TimeSeries.Register<User, HeartRates>();
Fixed

2020-11-16 14:09 UTC, karmeli87 approved these changes

2020-11-18 08:37 UTC, merged