RDoc-1803 - Hub/Sink Replication documentation
ravendb/docs pull request #1280
Opened 2020-11-17 13:48 UTC by reebhub

2020-11-18 11:52 UTC, karmeli87 approved these changes
Very clear and fluent!

2020-11-18 11:52 UTC, karmeli87 commented on Documentation/5.1/Raven.Documentation.Pages/studio/database/tasks/ongoing-tasks/hub-sink-replication/overview.markdown
> +  keep the Hub's public key and its own priivate key.
typo `priivate`

2020-11-18 11:52 UTC, karmeli87 commented on Documentation/5.1/Raven.Documentation.Pages/studio/database/tasks/ongoing-tasks/hub-sink-replication/overview.markdown
> +# Hub/Sink Replication: Overview
I think we need to mention a word or two about backward compatibility and interversion comp, that if you have an already defined pull replication everything will continue to work, also if you upgrade only sink/hub the existing pull replication will continue to operate.
Only if you what to use the filtering or the `sink to hub`, you need upgrade.

2020-11-18 13:12 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/studio/database/tasks/ongoing-tasks/hub-sink-replication/overview.markdown
> +  keep the Hub's public key and its own priivate key.
fixed

2020-11-18 14:16 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/studio/database/tasks/ongoing-tasks/hub-sink-replication/overview.markdown
> +# Hub/Sink Replication: Overview
added the Server article (server/ongoing-tasks/hub-sink-replication) a **backward-compatibility** section:

{PANEL: Backward Compatibility}

RavenDB versions that precede 5.1 support **Pull Replication**, which allows 
you to define *Hub and Sink* tasks and replicate data from Hub to Sink.  

In RavenDB 5.1 and on, the *Pull Replication* feature is **replaced** by 
the *Hub/Sink Replication* that allows everything *Pull Replication* does 
and adds to it *Sink to Hub* replication and *Replication Filtering*.  

* Pull Replication tasks defined on a RavenDB version earlier than 5.1, 
  **will remain operative** when you upgrade to version 5.1 and on.  

* A Hub or a Sink task that runs on a RavenDB version earlier than 5.1, 
  **can** connect a Hub or a Sink defined on RavenDB 5.1 and on.  
  You do **not** need to upgrade the task's instance to keep the task operative.  

{INFO: }
Upgrade RavenDB from a version earlier than 5.1 if you want to implement 
*Hub/Sink Replication* added features, i.e. Sink-to-Hub replication and 
Replication Filtering.  
{INFO/}

{PANEL/}

2020-11-19 10:01 UTC, ayende requested changes

2020-11-19 10:01 UTC, ayende commented on Documentation/5.1/Raven.Documentation.Pages/studio/database/tasks/ongoing-tasks/hub-sink-replication/replication-hub-task.markdown
> +   Turning this option OFF will open a similar input box and
This is confusing

2020-11-19 10:01 UTC, ayende commented on Documentation/5.1/Raven.Documentation.Pages/studio/database/tasks/ongoing-tasks/hub-sink-replication/replication-sink-task.markdown
> +     * You can define wildcards using `*`.
Same, only on the end, only after `/` or `-`

2020-11-19 11:43 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/server/ongoing-tasks/hub-sink-replication.markdown
> +   For each access, you need to issue a certificate with the Hub's public key and with a private
removed

2020-11-19 12:05 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/server/ongoing-tasks/hub-sink-replication.markdown
> +   key (that the Hub task doesn't keep) for Sink tasks that need to connect the Hub using this access.
1. **A Hub task**  
2. **Hub Access/es**  
   Multiple Sink tasks can connect the Hub using each access.  
   For each access, you need to issue a certificate with the Hub's 
   public key; Sink tasks will use the key to connect the Hub using 
   this access.  
3. **Filtering**
   Choose whether data filtering is enabled or not, and specify 
   paths to allowed documents if needed.  
4. **Sink task/s**

2020-11-19 12:09 UTC, ayende commented on Documentation/5.1/Raven.Documentation.Pages/server/ongoing-tasks/hub-sink-replication.markdown
> +   key (that the Hub task doesn't keep) for Sink tasks that need to connect the Hub using this access.
"Hub's public key; " - this is public - everyone knows it.
You need for each access the _sink_ certificate.

2020-11-19 12:29 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/server/ongoing-tasks/hub-sink-replication.markdown
> +   key (that the Hub task doesn't keep) for Sink tasks that need to connect the Hub using this access.
1. **A Hub task**  
2. **Hub Access/es**  
   Multiple Sink tasks can connect the Hub using each access.  
   For each access, you need to issue a certificate with a private key 
   (that the Hub task doesn't keep) for Sink tasks that need to connect the 
   Hub using this access.  
3. **Filtering**
   Choose whether data filtering is enabled or not, and specify 
   paths to allowed documents if needed.  
4. **Sink task/s**

2020-11-19 12:29 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/server/ongoing-tasks/hub-sink-replication.markdown
> +{CODE-BLOCK: JSON}
fixed

2020-11-19 12:31 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/studio/database/tasks/ongoing-tasks/hub-sink-replication/overview.markdown
> +  A Hub can access many Sinks.
corrected

2020-11-19 12:35 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/studio/database/tasks/ongoing-tasks/hub-sink-replication/overview.markdown
> +   * On board ships that sail offshore and offline
added

2020-11-19 12:36 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/studio/database/tasks/ongoing-tasks/hub-sink-replication/overview.markdown
> +  The Hub can serve and be served by many Sinks using the same
done

2020-11-19 12:39 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/studio/database/tasks/ongoing-tasks/hub-sink-replication/overview.markdown
> +    security cameras) collect their records locally and replicate
done

2020-11-19 12:55 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/studio/database/tasks/ongoing-tasks/hub-sink-replication/overview.markdown
> +  each camera's replication to a single collection.
yeah, i thought a reasonable scenario would be replicating from each camera to its own collection, named after its serial number maybe. 

* **As an additional security measure**  
  A central database that an array of traffic enforcement cameras replicate 
  speed tickets to, for example, can use Filtered Replication to restrict 
  each camera's replication to just tickets generated by this camera.  
  This will prevent a potential hacker from replicating a stolen camera's 
  speed tickets as if they were collected by another camera (e.g. to overrun 
  a ticket collected by any chosen camera, with a blank one).

2020-11-19 12:56 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/studio/database/tasks/ongoing-tasks/hub-sink-replication/overview.markdown
> +  speed tickets to any other collection (e.g. in order to overrun existing
see previous reply

2020-11-19 12:57 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/studio/database/tasks/ongoing-tasks/hub-sink-replication/overview.markdown
> +     document IDs ('companies/88-A').
done

2020-11-19 13:04 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/studio/database/tasks/ongoing-tasks/hub-sink-replication/overview.markdown
> +  Each Access can be used by Sink tasks to connect the Hub.
done

2020-11-19 13:07 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/studio/database/tasks/ongoing-tasks/hub-sink-replication/overview.markdown
> +  Each Access can be used by Sink tasks to connect the Hub.
but can you explain please? many sinks will be able to use this access, right?

2020-11-19 13:10 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/studio/database/tasks/ongoing-tasks/hub-sink-replication/overview.markdown
> +  Hub's Public key and a Private key for Sink tasks that wish to connect the
* **Creating Accesses**  
  When you create or edit a Hub task, you can add it [Accesses](../../../../../studio/database/tasks/ongoing-tasks/hub-sink-replication/replication-hub-task#access-configuration).  
  Each Access can be used by a Sink task to connect the Hub.  
  You are required to issue a certificate for each Access, that would 
  identify Sinks that connect the Hub via this Access.

2020-11-19 13:26 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/studio/database/tasks/ongoing-tasks/hub-sink-replication/overview.markdown
> +  keep the Hub's public key and its own priivate key.
After using the Hub task creation page to issue the certificate, 
  you need to export the certificate to a file.  
  When you create a Sink task, you are given the option to load 
  the certificate so the Sink may use it to access the Hub.

2020-11-19 13:33 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/studio/database/tasks/ongoing-tasks/hub-sink-replication/replication-hub-task.markdown
> +     the Private key (which will be removed from the Hub task's reach
done

2020-11-19 13:42 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/studio/database/tasks/ongoing-tasks/hub-sink-replication/replication-hub-task.markdown
> +    * You can define wildcards using `*`.
* You can define a prefix that uses a wildcard (`*`).  
      Locate the wildcard in the prefix' suffix, after `/` or `-`.  
      e.g. `products/*`  
    * You can provide exact document IDs.

2020-11-19 13:43 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/studio/database/tasks/ongoing-tasks/hub-sink-replication/replication-sink-task.markdown
> +     * You can define wildcards using `*`.
done

2020-11-19 14:28 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/studio/database/tasks/ongoing-tasks/hub-sink-replication/replication-hub-task.markdown
> +   Turning this option OFF will open a similar input box and
3. **Use above prefixes (Hub to Sink) for both directions**  
    * You can define a single list of prefixes, that would be used for 
      the filtering of both **incoming** and **outgoing** documents.  
      To define a single list, toggle the switch **ON**.  
    * You can also define two different prefix lists: one for 
      *incoming* documents, and another for *outgoing* documents.  
      You can use this, for example, to allow the reception of 
      a document but not its delivery (or vice versa).  
      To define two separate lists, toggle the switch **OFF**.

2020-11-19 14:35 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/studio/database/tasks/ongoing-tasks/hub-sink-replication/overview.markdown
> +
You mean besides what's written in the info box? it currently says (right after the tickets example) - 

{INFO: }

* **Both Hub and Sink tasks can filter data.**  
   Only documents defined by both tasks will be replicated.  
* **Documents are selected by path.**  
   * A path can include wildcards ('companies/*') and 
     exact document IDs ('companies/88-A').  
   * Each task (Hub and Sink) can define separate paths 
     for **incoming** and **outgoing** replication.  
{INFO/}

2020-11-20 12:33 UTC, ayende commented on Documentation/5.1/Raven.Documentation.Pages/studio/database/tasks/ongoing-tasks/hub-sink-replication/overview.markdown
> +
Okay, looks good

2020-11-20 12:34 UTC, ayende commented on Documentation/5.1/Raven.Documentation.Pages/studio/database/tasks/ongoing-tasks/hub-sink-replication/overview.markdown
> +  keep the Hub's public key and its own priivate key.
You are using the term hub's public key here, which is wrong.
The certificate that was generated is a separate one from the hub, even if it was generated by it.
Talk to me about this on Sunday, it is an important concept that we have to be clear about

2020-11-22 08:10 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/studio/database/tasks/ongoing-tasks/hub-sink-replication/overview.markdown
> +  keep the Hub's public key and its own priivate key.
fixed

2020-11-23 08:42 UTC, ppekrol commented
@ayende @karmeli87 can you review latest changes?

2020-11-23 09:16 UTC, ayende commented on Documentation/5.1/Raven.Documentation.Pages/studio/database/tasks/ongoing-tasks/hub-sink-replication/overview.markdown
> +   * Using a cellular phone that may not always have connectivity
```suggestion
   * Using a cellular network that may not always have connectivity  
```

2020-11-23 09:16 UTC, ayende commented on Documentation/5.1/Raven.Documentation.Pages/studio/database/tasks/ongoing-tasks/hub-sink-replication/overview.markdown
> +   Only documents defined by both, will be replicated.
```suggestion
   Only documents matching the filters defined by both, will be replicated.  
```

2020-11-23 09:32 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/server/ongoing-tasks/hub-sink-replication.markdown
> +     Hub using this access.
done

2020-11-23 10:32 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/server/ongoing-tasks/hub-sink-replication.markdown
> +
RavenDB instances distributed onboard mobile library busses, for example, 
can collect data locally (e.g. bus GPS coordinates and books returns and 
borrows), and replicate it via local Sink tasks to the central library's 
Hub whenever they are online.

2020-11-23 10:34 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/server/ongoing-tasks/hub-sink-replication.markdown
> +var pullCert = new X509Certificate2(File.ReadAllBytes(certificates.ClientCertificate2Path),
done

2020-11-23 10:35 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/server/ongoing-tasks/hub-sink-replication.markdown
> +        CertificateBase64 = Convert.ToBase64String(pullCert.Export(X509ContentType.Cert))
done

2020-11-23 10:37 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/server/ongoing-tasks/hub-sink-replication.markdown
> +of nodes from the Hub cluster. If defined, the preferred node will be
As part of the connection handshake, the Sink fetches an ordered list 
of nodes from the Hub cluster. If a preferred node is defined, it will 
be first in this list.

2020-11-23 10:55 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/studio/database/tasks/ongoing-tasks/hub-sink-replication/overview.markdown
> +  A Hub can be used by many Sinks.
done

2020-11-23 10:56 UTC, ayende commented on Documentation/5.1/Raven.Documentation.Pages/server/ongoing-tasks/hub-sink-replication.markdown
> +of nodes from the Hub cluster. If defined, the preferred node will be
great

2020-11-23 10:56 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/studio/database/tasks/ongoing-tasks/hub-sink-replication/overview.markdown
> +   * Using a cellular phone that may not always have connectivity
fixed

2020-11-23 10:57 UTC, ayende commented on Documentation/5.1/Raven.Documentation.Pages/server/ongoing-tasks/hub-sink-replication.markdown
> +
Looks good, yes.

2020-11-23 10:57 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/studio/database/tasks/ongoing-tasks/hub-sink-replication/overview.markdown
> +   Only documents defined by both, will be replicated.
done

2020-11-24 10:54 UTC, merged