R doc 1852 encryption js console
ravendb/docs pull request #1295
Opened 2020-12-30 14:12 UTC by morhilai

2021-01-22 11:36 UTC, ppekrol requested changes

2021-01-22 11:36 UTC, ppekrol commented on Documentation/4.0/Raven.Documentation.Pages/server/security/encryption/secret-key-management.markdown
> +server.ServerStore.PutSecretKey(string base64, string name, bool overwrite)
I think we need to remove 'string' and 'bool' from here. This is not a proper JS. Types are defined below anyway.

2021-01-24 09:57 UTC, iftahbe requested changes

2021-01-24 09:57 UTC, iftahbe commented on Documentation/4.0/Raven.Documentation.Pages/server/security/encryption/secret-key-management.markdown
> +3. [Advanced: Using the Admin Console](../../../server/security/encryption/secret-key-management#using-the-admin-js-console)
This is not a third way to handle secret protection.
It's a way to retrieve/change a database key in case of a user change when relying on the OS protection.

2021-01-24 09:57 UTC, iftahbe commented on Documentation/4.0/Raven.Documentation.Pages/server/security/encryption/secret-key-management.markdown
> +A master key can be modified with the script:
I would make it more clear that here we change a **database** master key even though we do an operation against the server store. 
The server store holds the database master keys.

2021-01-24 09:57 UTC, iftahbe commented on Documentation/4.0/Raven.Documentation.Pages/server/security/encryption/secret-key-management.markdown
> +| **base64** | `string` | The new master key for the server store |
The new master key for the selected database

2021-01-24 09:57 UTC, iftahbe commented on Documentation/4.0/Raven.Documentation.Pages/server/security/encryption/secret-key-management.markdown
> +| **overwrite** | `string` | If this is false, an exception will be thrown. Be sure that this is what you want to do. |
an exception will be thrown **if a key exists**

2021-01-24 09:57 UTC, iftahbe commented on Documentation/4.0/Raven.Documentation.Pages/server/security/encryption/secret-key-management.markdown
> +{PANEL/}
Here I would add a section with detailed steps on how to change a user:
1. Read the database master key using: `return database.MasterKey`
2. Change a Windows user
3. Inject the old key into the server store using: `server.ServerStore.PutSecretKey(string base64, string name, bool overwrite)`

2021-02-28 14:44 UTC, morhilai commented on Documentation/4.0/Raven.Documentation.Pages/server/security/encryption/secret-key-management.markdown
> +server.ServerStore.PutSecretKey(string base64, string name, bool overwrite)
Fixed

2021-02-28 14:44 UTC, morhilai commented on Documentation/4.0/Raven.Documentation.Pages/server/security/encryption/secret-key-management.markdown
> +3. [Advanced: Using the Admin Console](../../../server/security/encryption/secret-key-management#using-the-admin-js-console)
Fixed

2021-02-28 14:48 UTC, morhilai commented on Documentation/4.0/Raven.Documentation.Pages/server/security/encryption/secret-key-management.markdown
> +| **overwrite** | `string` | If this is false, an exception will be thrown. Be sure that this is what you want to do. |
Changed description to this:
>Whether to overwrite an existing key. If this is false and the database has a master key, an exception will be thrown. Be sure that this is what you want to do.
Is it ok?

2021-03-02 10:41 UTC, morhilai commented on Documentation/4.0/Raven.Documentation.Pages/server/security/encryption/secret-key-management.markdown
> +A master key can be modified with the script:
Fixed

2021-03-02 10:43 UTC, morhilai commented on Documentation/4.0/Raven.Documentation.Pages/server/security/encryption/secret-key-management.markdown
> +A master key can be modified with the script:
Fixed

2021-03-02 10:43 UTC, morhilai commented on Documentation/4.0/Raven.Documentation.Pages/server/security/encryption/secret-key-management.markdown
> +| **base64** | `string` | The new master key for the server store |
Fixed

2021-03-02 10:44 UTC, morhilai commented on Documentation/4.0/Raven.Documentation.Pages/server/security/encryption/secret-key-management.markdown
> +{PANEL/}
Fixed

2021-03-02 10:55 UTC, morhilai commented on Documentation/4.0/Raven.Documentation.Pages/server/security/encryption/secret-key-management.markdown
> +| **base64** | `string` | The new master key for the server store |
Fixed

2021-03-02 10:56 UTC, morhilai commented on Documentation/4.0/Raven.Documentation.Pages/server/security/encryption/secret-key-management.markdown
> +{PANEL/}
Added

2021-03-24 08:22 UTC, merged