R doc 1886 olap etl
ravendb/docs pull request #1337
Opened 2021-05-04 15:13 UTC by morhilai

2021-05-31 14:54 UTC, aviv86 requested changes

2021-05-31 14:54 UTC, aviv86 commented on Documentation/5.2/Raven.Documentation.Pages/server/ongoing-tasks/etl/olap.markdown
> +{NOTE/}
All the supported destinations (including Local) can have  [GetBackupConfigurationScript](https://github.com/ravendb/ravendb/blob/v5.1/src/Raven.Client/Documents/Operations/Backups/BackupSettings.cs#L10) property set (instead of all the rest) 

please mention that in a few words and add a link to docs (if exists..)

2021-05-31 14:54 UTC, aviv86 commented on Documentation/5.2/Raven.Documentation.Pages/server/ongoing-tasks/etl/olap.markdown
> +Same as the above query, but this time we're only taking the top 20 results
I think we can drop this example..

2021-05-31 14:54 UTC, aviv86 commented on Documentation/5.2/Raven.Documentation.Pages/server/ongoing-tasks/etl/olap.markdown
> +    `_lastModifiedTime` bigint
`_lastModifiedTime` can be of type `int` (we changed from ticks to milliseconds)

2021-06-01 09:25 UTC, morhilai commented on Documentation/5.2/Raven.Documentation.Pages/server/ongoing-tasks/etl/olap.markdown
> +The OLAP connection string can configure S3 storage, local storage, or both.
Fixed

2021-06-01 09:25 UTC, morhilai commented on Documentation/5.2/Raven.Documentation.Pages/server/ongoing-tasks/etl/olap.markdown
> +| `S3Settings` | `S3Settings` | Information about the S3 bucket and the AWS server in general. |
Fixed

2021-06-01 09:25 UTC, morhilai commented on Documentation/5.2/Raven.Documentation.Pages/server/ongoing-tasks/etl/olap.markdown
> +| `CustomServerUrl` | `string` | The custom URL to the S3 bucket, if you have one |
Fixed

2021-06-01 09:25 UTC, morhilai commented on Documentation/5.2/Raven.Documentation.Pages/server/ongoing-tasks/etl/olap.markdown
> +| `VaultName` | `string` | The name of your AWS Glacier vault |
Fixed

2021-06-01 09:55 UTC, morhilai commented on Documentation/5.2/Raven.Documentation.Pages/server/ongoing-tasks/etl/olap.markdown
> +    `_lastModifiedTime` bigint
Fixed

2021-06-01 09:56 UTC, morhilai commented on Documentation/5.2/Raven.Documentation.Pages/server/ongoing-tasks/etl/olap.markdown
> +Same as the above query, but this time we're only taking the top 20 results
Done

2021-06-01 10:01 UTC, morhilai commented on Documentation/5.2/Raven.Documentation.Pages/server/ongoing-tasks/etl/olap.markdown
> +#### `AmazonSettings`
Fixed

2021-06-01 10:04 UTC, morhilai commented on Documentation/5.2/Raven.Documentation.Pages/server/ongoing-tasks/etl/olap.markdown
> +the data is partitioned at the destination: data extracted from the same collection can be further divided
Fixed

2021-06-01 10:13 UTC, morhilai commented on Documentation/5.2/Raven.Documentation.Pages/server/ongoing-tasks/etl/olap.markdown
> +Same as the above query, but this time we're only taking the top 20 results
Done

2021-06-01 10:13 UTC, morhilai commented on Documentation/5.2/Raven.Documentation.Pages/server/ongoing-tasks/etl/olap.markdown
> +    `_lastModifiedTime` bigint
Fixed

2021-06-01 10:13 UTC, morhilai commented on Documentation/5.2/Raven.Documentation.Pages/server/ongoing-tasks/etl/olap.markdown
> +| `PartitionColumn` | `string` | A name for the column that indicates which partition a given row is in. Default: "_dt" |
Fixed

2021-06-01 10:20 UTC, morhilai commented on Documentation/5.2/Raven.Documentation.Pages/server/ongoing-tasks/etl/olap.markdown
> +The folder name consists of a customized 'tag' plus the date-time value `key`.
Fixed

2021-06-01 10:38 UTC, morhilai commented on Documentation/5.2/Raven.Documentation.Pages/server/ongoing-tasks/etl/olap.markdown
> +| `FolderPath` | `string` | Path to local folder. If not empty, backups will be held in this folder and not deleted. Otherwise, backups will be created in the TempDir of a database and deleted after
Fixed

2021-06-01 11:48 UTC, morhilai commented on Documentation/5.2/Raven.Documentation.Pages/server/ongoing-tasks/etl/olap.markdown
> +!!!$customPartitionValue
Done

2021-06-01 12:55 UTC, morhilai commented on Documentation/5.2/Raven.Documentation.Pages/server/ongoing-tasks/etl/olap.markdown
> +
Done

2021-06-01 12:56 UTC, morhilai commented on Documentation/5.2/Raven.Documentation.Pages/server/ongoing-tasks/etl/olap.markdown
> +    partitionBy('byMonth', ['month', 'August'], ['week', 'two'], 'Monday'),
Fixed

2021-06-01 12:56 UTC, morhilai commented on Documentation/5.2/Raven.Documentation.Pages/server/ongoing-tasks/etl/olap.markdown
> +{CODE-BLOCK: javascript}
Done

2021-06-01 12:59 UTC, morhilai commented on Documentation/5.2/Raven.Documentation.Pages/server/ongoing-tasks/etl/olap.markdown
> +The connection string can be created for either a remote S3 or a local folder.
Fixed (I removed the paragraph as it was no longer necessary)

2021-06-01 13:13 UTC, morhilai commented on Documentation/5.2/Raven.Documentation.Pages/server/ongoing-tasks/etl/olap.markdown
> +{NOTE/}
No docs for this exist... because no docs exist, it doesn't seem helpful to mention it without an explanation of how to use it. I have created an issue to document this both for OLAP and backups: https://issues.hibernatingrhinos.com/issue/RDoc-1936

2021-06-09 09:19 UTC, aviv86 commented on Documentation/5.2/Raven.Documentation.Pages/server/ongoing-tasks/etl/olap.markdown
> +
please mention that in case of multiple partitions, the `[name, $customPartitionValue]` tuple can appear in any position (first, last, somewhere in the middle...)

2021-06-09 10:35 UTC, morhilai commented on Documentation/5.2/Raven.Documentation.Pages/server/ongoing-tasks/etl/olap.markdown
> +| `RemoteFolderName` | `string` | Name of the S3 partition folder |
Done

2021-06-09 10:37 UTC, morhilai commented on Documentation/5.2/Raven.Documentation.Pages/server/ongoing-tasks/etl/olap.markdown
Fixed

2021-06-09 10:39 UTC, morhilai commented on Documentation/5.2/Raven.Documentation.Pages/server/ongoing-tasks/etl/olap.markdown
> +* **`partitionBy(key)`** - takes one `string` value as the partition name, uses the default virtual column
Fixed

2021-06-09 10:48 UTC, morhilai commented on Documentation/5.2/Raven.Documentation.Pages/server/ongoing-tasks/etl/olap.markdown
> +This just means that all child folder names have this format: `[virtual column name]=[partition name]`,
Done

2021-06-09 10:49 UTC, morhilai commented on Documentation/5.2/Raven.Documentation.Pages/server/ongoing-tasks/etl/olap.markdown
> +i.e. two strings separated by a `=`. You don't have to set the virtual column name - its default value is
Fixed

2021-06-09 10:52 UTC, morhilai commented on Documentation/5.2/Raven.Documentation.Pages/server/ongoing-tasks/etl/olap.markdown
> +
Done
You can also use `$customPartitionValue` as many times as you want, right?

2021-06-09 11:47 UTC, aviv86 approved these changes

2021-06-16 16:45 UTC, merged