RDoc-1907-TS-first-last-points Document the ability to select first/last entries in a time series
ravendb/docs pull request #1353
Opened 2021-06-17 13:29 UTC by morhilai

Document the ability to select first/last entries in a time series

2021-06-20 15:41 UTC, aviv86 requested changes

2021-06-20 15:41 UTC, aviv86 commented on Documentation/5.0/Raven.Documentation.Pages/document-extensions/timeseries/querying/choosing-query-range.markdown
> +* **Milliseconds**
`Milliseconds` is not supported
https://github.com/ravendb/ravendb/blob/v5.2/test/SlowTests/Client/TimeSeries/Query/TimeSeriesLinqQuery.cs#L2835

there's an open ticket to add support for this:
https://issues.hibernatingrhinos.com/issue/RavenDB-14988

2021-06-21 09:37 UTC, morhilai commented on Documentation/5.0/Raven.Documentation.Pages/document-extensions/timeseries/querying/choosing-query-range.markdown
> +* **Milliseconds**
Fixed

2021-06-22 13:34 UTC, aviv86 approved these changes

2021-06-28 14:40 UTC, merged