Rdoc-1983 incremental time series
ravendb/docs pull request #1383
Opened 2021-11-02 07:45 UTC by reebhub

2021-11-04 06:13 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/client-api/session/overview.markdown
> +The `IncrementalTimeSeriesFor` class gathers useful incremental time series
gathers => has / contains

2021-11-04 06:13 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/client-api/session/overview.markdown
> +      The name **must** begin with "inc:" to identify the time series as incremental.
=>

Create an instance of `IncrementalTimeSeriesFor` and pass it:

* An explicit document ID,
  -or-
  An entity tracked by the session, e.g. a document object returned from session.Query or from session.Load.
      
* The time series name.
   The name must begin with "INC:"  (can be either upper or lower case) to identify the time series as 
    incremental.

2021-11-04 06:13 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/client-api/session/overview.markdown
> +* Call a `IncrementalTimeSeriesFor` method
Call a => Call an

2021-11-04 07:55 UTC, shiranshalom commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/client-api/operations/get.markdown
> +* **Return Value**: **`TimeSeriesRangeResult<TimeSeriesEntry>`**
maybe we should present the new parameters receive from `GetTimeSeriesOperation`.

- TotalResults  - the actual number of values [exists on regular TS, but with a potential small difference].

- SkippedResults - helps to calculate next start.

- NodeValues - the nodes distribution per each entry.

2021-11-04 07:57 UTC, shiranshalom commented on Documentation/5.3/Samples/csharp/Raven.Documentation.Samples/DocumentExtensions/TimeSeries/IncrementalTimeSeriesTests.cs
> +                // Get time series HeartRates' time points data
remove comment? :)

2021-11-04 07:58 UTC, shiranshalom approved these changes

2021-11-04 10:47 UTC, Danielle9897 requested changes

2021-11-04 10:47 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/client-api/session/get.markdown
> +{PANEL/}
Fix this panel the same way as requested in the 'Session/Overview Article'

2021-11-04 10:47 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/client-api/session/delete.markdown
> +{PANEL/}
Fix this panel the same way as requested in the 'Session/Overview Article'

2021-11-04 10:47 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/client-api/operations/get.markdown
> +the values stored in entries by each node.
=>

Use GetTimeSeriesOperation to retrieve the distinct values stored per node for the requested entries.

2021-11-04 10:47 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/client-api/operations/get.markdown
> +    | `returnFullResults` | `bool` | If true, retrieve node values from entries |
1. 
@shiranshalom @reebhub 
what if this value is 'false' ?
what is returned then ?

2.
=> If true, retrieve the values stored per node

2021-11-04 10:47 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/client-api/operations/get.markdown
> +* Entries are returned into a `dictionary of `TimeSeriesRangeResult` classes.
Remove the extra  ```  ` ``` before the word dictionary !

2021-11-04 10:47 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/client-api/operations/get.markdown
> +  {CODE incremental_GetTimeSeriesOperation@DocumentExtensions\TimeSeries\IncrementalTimeSeriesTests.cs /}
in this example, it **must** be
`var entries`
and not
`var values`

2021-11-04 10:47 UTC, Danielle9897 commented on Documentation/5.3/Samples/csharp/Raven.Documentation.Samples/DocumentExtensions/TimeSeries/IncrementalTimeSeriesTests.cs
> +                var values = store.Operations
values => entries

2021-11-04 10:47 UTC, Danielle9897 commented on Documentation/5.3/Samples/csharp/Raven.Documentation.Samples/DocumentExtensions/TimeSeries/IncrementalTimeSeriesTests.cs
> +                values = store.Operations
values => entries

2021-11-04 10:47 UTC, Danielle9897 commented on Documentation/5.3/Samples/csharp/Raven.Documentation.Samples/DocumentExtensions/TimeSeries/IncrementalTimeSeriesTests.cs
> +                var nextStart = values.Entries.Length + values.SkippedResults;
values => entries

2021-11-04 10:47 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/client-api/operations/get.markdown
> +       The per-node values are counted by the `Get` operation, and returned in a `SkippedResults` value.
Above is wrong 

=>

The value you set in pageSize indicates the location of the first entry to retrieve.

More than one entry can exist for the same timestamp since when different nodes increment a value for the same timestamp, then the entries stored on those nodes will have the same timestamp, resulting in 'duplicate' entries
(although each has its own different tag).

The number of these duplicated entries is returned in the `SkippedResults`

2021-11-04 21:22 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/overview.markdown
> +  embedded in time series entries.
done

2021-11-04 21:23 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/overview.markdown
> +  the changes made in its value over time.
done

2021-11-04 21:36 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/time-series.markdown
> +2. Click to create a new time series, [see more below](../../../studio/database/document-extensions/time-series#create-new-time-series-by-creating-the-first-entry).
please don't number the comments where there are numbers in the text (unless the numbers refer to the numbers in the text).
done

2021-11-04 21:37 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/time-series.markdown
> +3. Hover to view comments when available.
nope

2021-11-04 21:38 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/time-series.markdown
> +* A. Displays the time series':
done

2021-11-04 21:40 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/time-series.markdown
> +![Time Series - Document View](images/time-series/document-time-series.png "Time Series - Document View")
done

2021-11-04 21:41 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/time-series.markdown
> +1. Displays time series entries' data, including -
done

2021-11-04 21:46 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/time-series.markdown
> +      or lower case characters, as you prefer).
series, not series entries. otherwise done.

2021-11-04 21:48 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/time-series.markdown
> +  handle time series values as counters, increasing and decreasing them at will.
done

2021-11-04 21:52 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/time-series.markdown
> +* Learn about incremental time series [here](../../../document-extensions/timeseries/incremental-time-series/overview).
done

2021-11-04 21:53 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/time-series.markdown
> +    * **Enable** to create an Incremental time series.
done

2021-11-04 21:53 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/time-series.markdown
> +      or lower case characters, as you prefer).
done

2021-11-04 21:56 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/time-series.markdown
> +    * **Disable** to show only the entry's Current Values.
done

2021-11-04 22:18 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/time-series.markdown
> +      The accumulation of all the numbers that cluster nodes have increased *Value #0** by.
"content" is very strange here. maybe you meant "count"? in any case - 

* **Total Value**  
  This is an accumulation of this value from all cluster nodes.

2021-11-04 22:26 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/time-series.markdown
> +      The value will be modified only when you click the **Save** button.
done

2021-11-04 22:28 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/time-series.markdown
> +    * **Enable** to show the current value **and** the number each node increases it by.
done

2021-11-04 22:28 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/time-series.markdown
> +      The accumulation of all the numbers that cluster nodes have increased *Value #0** by.
* **Total Value**  
      This is an accumulation of this value from all cluster nodes.

2021-11-04 22:34 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/time-series.markdown
> +      Enter a positive number to increase Value #0, or a negative number to decrease it.
done + minor changes

2021-11-04 22:35 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/time-series.markdown
> +      The value will be modified only when you click the **Save** button.
done

2021-11-04 22:37 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/time-series.markdown
> +      ![Node Value](images/time-series/edit-entry-value_increment-by.png "Node Value")
done

2021-11-04 22:38 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/time-series.markdown
> +        {NOTE/}
done

2021-11-04 22:40 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/time-series.markdown
> +      The number shown for each node is in itself an accumulation of all the numbers this node's clients have increased this value by.
done

2021-11-04 22:46 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/time-series.markdown
> +   Values you add here change the sum collected from your Studio's cluster node.
done i guess, hard to tell what you mean (the first sentence was removed previously and the second is needed)

2021-11-04 23:08 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/overview.markdown
> +  time series values concurrently without conflict.
this "content" concept doesn't compute. 

- The total value is simply the accumulation of that value stored per cluster node, for the same timestamp.

2021-11-04 23:11 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/overview.markdown
> +  to **use entry values as counters, while storing their modifications in an evolving time series**.
done

2021-11-04 23:15 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/overview.markdown
> +   {NOTE/}
done

2021-11-04 23:22 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/overview.markdown
> +  or get the value stored by each node.
done (content->contents)

2021-11-04 23:29 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/overview.markdown
> +   a single time series. Each time series entry contains data from all nodes.
nope

2021-11-04 23:40 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/overview.markdown
> +* This process is conflict-free, in both the clients' and in the nodes' level.
done

2021-11-05 00:08 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/overview.markdown
> +{PANEL/}
done

2021-11-05 00:27 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/overview.markdown
> +  entries may very well contain more data.
applied with some changes.

2021-11-05 00:36 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/client-api/session/overview.markdown
> +  method is available instead, for the creation and modification if incremental time series.
done

2021-11-05 00:38 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/client-api/session/overview.markdown
> +The `IncrementalTimeSeriesFor` class gathers useful incremental time series
the point is that it gathers them in one entry point

2021-11-05 00:41 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/client-api/session/overview.markdown
> +      The name **must** begin with "inc:" to identify the time series as incremental.
done

2021-11-05 00:45 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/client-api/session/overview.markdown
> +* Call a `IncrementalTimeSeriesFor` method
done

2021-11-05 02:09 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/client-api/operations/get.markdown
> +* **Return Value**: **`TimeSeriesRangeResult<TimeSeriesEntry>`**
done

2021-11-05 02:30 UTC, reebhub commented on Documentation/5.3/Samples/csharp/Raven.Documentation.Samples/DocumentExtensions/TimeSeries/IncrementalTimeSeriesTests.cs
> +                // Get time series HeartRates' time points data
done (o:

2021-11-05 02:35 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/client-api/session/increment.markdown
> +     Increment the current entry value by a number of your choice.
done

2021-11-05 02:41 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/client-api/session/increment.markdown
> +   * Increment an entry value at the provided timestamp.
done

2021-11-05 02:41 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/client-api/session/increment.markdown
> +   * Increment an entry value at the current time.
done

2021-11-05 02:42 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/client-api/session/increment.markdown
> +    | `value` | double | Entry's value |
done

2021-11-05 02:45 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/client-api/session/increment.markdown
> +    | `values` | IEnumerable<double> | Entry's values |
done

2021-11-05 02:51 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/client-api/session/get.markdown
> +{PANEL/}
done

2021-11-05 02:51 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/client-api/session/delete.markdown
> +{PANEL/}
done

2021-11-05 02:54 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/client-api/operations/get.markdown
> +the values stored in entries by each node.
done

2021-11-05 02:56 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/client-api/operations/get.markdown
> +    | `returnFullResults` | `bool` | If true, retrieve node values from entries |
done

2021-11-05 02:56 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/client-api/operations/get.markdown
> +* Entries are returned into a `dictionary of `TimeSeriesRangeResult` classes.
done

2021-11-05 03:02 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/client-api/operations/get.markdown
> +  {CODE incremental_GetTimeSeriesOperation@DocumentExtensions\TimeSeries\IncrementalTimeSeriesTests.cs /}
done

2021-11-05 03:03 UTC, reebhub commented on Documentation/5.3/Samples/csharp/Raven.Documentation.Samples/DocumentExtensions/TimeSeries/IncrementalTimeSeriesTests.cs
> +                var values = store.Operations
repeating comment

2021-11-05 03:04 UTC, reebhub commented on Documentation/5.3/Samples/csharp/Raven.Documentation.Samples/DocumentExtensions/TimeSeries/IncrementalTimeSeriesTests.cs
> +                values = store.Operations
repeating comment

2021-11-05 03:05 UTC, reebhub commented on Documentation/5.3/Samples/csharp/Raven.Documentation.Samples/DocumentExtensions/TimeSeries/IncrementalTimeSeriesTests.cs
> +                var nextStart = values.Entries.Length + values.SkippedResults;
repetitive

2021-11-05 03:07 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/client-api/operations/get.markdown
> +       The per-node values are counted by the `Get` operation, and returned in a `SkippedResults` value.
it's already fixed, in a way that i prefer.

2021-11-07 07:49 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/time-series.markdown
> +  embedded in time series entries.
The increase/decrease text is clearly explained in the second bullet, lets make this bullet shorter

=>
Incremental Time Series are time series whose values behave as counters.

2021-11-07 07:49 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/time-series.markdown
> +  for the same timestamp.
Since the hights value is only taken upon conflicts... let's provide just a general statement here
And let's add a link to the comparison table in the bullet bellow

=>
This is opposed to the regular-time-series where a value that is modified is intended to replace the existing value's content on all other nodes.

2021-11-07 07:49 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/time-series.markdown
> +* learn more about incremental-time-series [here](../../../document-extensions/timeseries/incremental-time-series/overview).
Change to + add link to the comparison panel in the server side articel
=>
Learn more in [Incremental Time Series -vs- Non-incremental Time Series](url)

2021-11-07 07:49 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/time-series.markdown
> +      or lower case characters, as you prefer).
pls add the brackets so that it will be clear that the colon is part of the prefix 
+ remove the 'as you prefer'

=>
Incremental time series names must start with `INC:` (can be either upper or lower case)

2021-11-07 07:49 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/time-series.markdown
> +    * **Total Value**
well, since the pr with the title change (**current value => total value**) has **not** been merged yet..
then better to be consistent with what we have now, so change this title back to '**Current Value**'
as that is what is shown in the image...

2021-11-07 07:49 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/time-series.markdown
> +    * **Enable** to view the value's contents distribution per cluster node.
pls remove bold on Enable

2021-11-07 07:49 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/time-series.markdown
> +   Values you add here change the sum collected from your Studio's cluster node.
pls remove this sentence
the one that starts with: `Values you add here change the sum....`
it is incorrect, it doesn't change the sum, it adds a new value

2021-11-07 07:49 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/overview.markdown
> +  An incremental time series entry can be **modified by multiple clients without conflict**.
conflict => conflicts  ? 
without any conflicts ?

2021-11-07 07:49 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/overview.markdown
> +  or get the value stored by each node.
let's avoid 'wall of text'
pls modify to be with bullets as suggested in the comment + make the text bold as in the comment

2021-11-07 09:12 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/time-series.markdown
> +  for the same timestamp.
done.
we're using "non-incremental", not "regular", because the term clarifies what we're talking about and because "regular" is somewhat suggestive to "boring".

2021-11-07 09:18 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/time-series.markdown
> +* learn more about incremental-time-series [here](../../../document-extensions/timeseries/incremental-time-series/overview).
done

2021-11-07 09:26 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/time-series.markdown
> +    * **Total Value**
* regarding `INC:`, that's why the thing is blue. adding brackets might suggest they are needed.
* total value - ok. though if it's going to be merged in another form it'll create a mistake.

2021-11-07 09:28 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/time-series.markdown
> +    * **Enable** to view the value's contents distribution per cluster node.
it's already removed. make sure you're not checking an older version of the document.

2021-11-07 09:30 UTC, Danielle9897 requested changes

2021-11-07 09:30 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/overview.markdown
> +  time series is. In Studio, incremental time series are even accessed through the
add a line break before 'In Studio..'

2021-11-07 09:30 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/overview.markdown
> +* The main structural difference is incremental time series' capacity to store multiple
switch order - this bullet should come before the previous one

2021-11-07 09:30 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/client-api/session/overview.markdown
> +The `IncrementalTimeSeriesFor` class gathers useful incremental time series
but in the sentence, you refer to the methods being gathered.. not to the values/entries
`... gathers useful incremental time series session API methods, ...`
the class doesn't gather methods, so pls change

2021-11-07 09:30 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/client-api/session/increment.markdown
> +    * If the time series doesn't exist, it will be created with this first entry.
pls apply comment

2021-11-07 09:30 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/client-api/operations/get.markdown
> +    | `returnFullResults` | `bool` | If true, retrieve the values stored per-node |
@shiranshalom @reebhub
what if this value is 'false' ?
what is returned then ?

2021-11-07 09:31 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/time-series.markdown
> +   Values you add here change the sum collected from your Studio's cluster node.
it's now "Add an additional value (up to 32 values).", you're checking an older version of the documentation.

2021-11-07 09:34 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/overview.markdown
> +  An incremental time series entry can be **modified by multiple clients without conflict**.
conflict

2021-11-07 09:35 UTC, shiranshalom commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/client-api/operations/get.markdown
> +    | `returnFullResults` | `bool` | If true, retrieve the values stored per-node |
`NodeValues = null` as in Counters

2021-11-07 09:49 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/overview.markdown
> +  the per-node values, or get the distinct values per-node.
don't know what comment you're referring to. added bullets.
the previous paragraph is a single argument, no need to divide it.

2021-11-07 09:50 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/client-api/session/increment.markdown
> +{PANEL/}
done

2021-11-07 09:52 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/client-api/session/increment.markdown
> +    * If the time series doesn't exist, it will be created with this first entry.
done

2021-11-07 09:58 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/overview.markdown
> +  * [Overview](../../../document-extensions/timeseries/incremental-time-series/overview#overview)
done

2021-11-07 10:03 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/overview.markdown
> +     that is composed of the value's contents per node.
it's hard to see what's bold and what isn't in comments you leave here, if you want texts to be bolded please refer to them specifically.

2021-11-07 10:04 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/overview.markdown
> +  time series is. In Studio, incremental time series are even accessed through the
done

2021-11-07 10:04 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/overview.markdown
> +* The main structural difference is incremental time series' capacity to store multiple
done

2021-11-07 10:15 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/client-api/operations/get.markdown
> +    | `returnFullResults` | `bool` | If true, retrieve the values stored per-node |
If true, retrieve the values stored per-node. <br> If false, return `null ` in `TimeSeriesEntry.NodeValues`.

2021-11-07 10:31 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/overview.markdown
> +  the per-node values, or get the distinct values per-node.
done

2021-11-07 10:36 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/overview.markdown
> +  * [Overview](../../../document-extensions/timeseries/incremental-time-series/overview#overview)
done

2021-11-07 10:43 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/timeseries/incremental-time-series/overview.markdown
> +     that is composed of the value's contents per node.
done

2021-11-07 12:32 UTC, Danielle9897 approved these changes

2021-11-08 11:23 UTC, merged