RDoc-1984 Concurrent Subscriptions documentation
ravendb/docs pull request #1389
Opened 2021-11-08 01:42 UTC by reebhub

2021-11-08 06:44 UTC, karmeli87 reviewed
Review only the common text (not the .dotnet, .java, etc)

2021-11-08 06:44 UTC, karmeli87 commented on Documentation/5.3/Raven.Documentation.Pages/client-api/data-subscriptions/advanced-topics/maintenance-operations.dotnet.markdown
> +{PANEL:DocumentSubscriptions class}
I think this should be at the top.

2021-11-08 06:44 UTC, karmeli87 commented on Documentation/5.3/Raven.Documentation.Pages/client-api/data-subscriptions/concurrent-subscriptions.markdown
> +* In this page:
Maybe worth adding `Single` vs `Concurrent` what each mode promise.

2021-11-08 06:44 UTC, karmeli87 commented on Documentation/5.3/Raven.Documentation.Pages/client-api/data-subscriptions/concurrent-subscriptions.markdown
> +   * [Defining a Concurrent Worket](../../client-api/data-subscriptions/concurrent-subscriptions#defining-concurrent-workers)
typo `Worket` -> `Worker`

2021-11-08 06:44 UTC, karmeli87 commented on Documentation/5.3/Raven.Documentation.Pages/client-api/data-subscriptions/concurrent-subscriptions.markdown
> +  than once: First by worker/s that disconnected unexpectedly,
`worker/s` ?

2021-11-08 06:44 UTC, karmeli87 commented on Documentation/5.3/Raven.Documentation.Pages/client-api/data-subscriptions/concurrent-subscriptions.markdown
> +  and then by workers they have been reassigned to.
correct, it might happened if the disconnected worker processed the documents but didn't acked them.

2021-11-08 06:44 UTC, karmeli87 commented on Documentation/5.3/Raven.Documentation.Pages/client-api/data-subscriptions/advanced-topics/maintenance-operations.dotnet.markdown
> +| **DropConnection(string name, string database)** | `void` | Drops existing subscription connection with worker. |
we now also have `DropSubscriptionWorker<T>` `DropSubscriptionWorkerAsync<T>`
it will drop a specific connection, while `DropConnection` will drop all connections.

2021-11-08 08:02 UTC, Danielle9897 requested changes

2021-11-08 10:09 UTC, lastav5 requested changes

2021-11-08 11:22 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/data-subscriptions/advanced-topics/maintenance-operations.dotnet.markdown
> +{PANEL:DocumentSubscriptions class}
done

2021-11-08 11:26 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/data-subscriptions/concurrent-subscriptions.markdown
> +* In this page:
sorry, that's a leftover remark, removed.
the single vs concurrent issue is handled in 
* data-subscriptions/what-are-data-subscriptions#working-with-multiple-clients
* and in consumption/how-to-consume-data-subscription#worker-interplay

2021-11-08 11:28 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/data-subscriptions/concurrent-subscriptions.markdown
> +   * [Defining a Concurrent Worket](../../client-api/data-subscriptions/concurrent-subscriptions#defining-concurrent-workers)
fixed

2021-11-08 11:30 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/data-subscriptions/concurrent-subscriptions.markdown
> +  than once: First by worker/s that disconnected unexpectedly,
yeah, because there may be a chain of failures.
but you're right, I'll simplify it.
"First by a worker that disconnected unexpectedly, and then by workers the documents have been reassigned to."

2021-11-08 11:31 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/data-subscriptions/concurrent-subscriptions.markdown
> +  and then by workers they have been reassigned to.
First by a worker that disconnected unexpectedly, without acknowledging the procession of its documents, and then by workers the documents have been reassigned to.

2021-11-08 12:27 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/tasks/ongoing-tasks/subscription-task.markdown
> +     are connected.
done

2021-11-08 12:29 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/tasks/ongoing-tasks/subscription-task.markdown
> +     are connected.
as with all comments here, it's hard to tell if the text is bolded or not

2021-11-08 12:31 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/tasks/ongoing-tasks/subscription-task.markdown
> +     to connect one by one, or Concurrent for concurrent workers.
done

2021-11-08 12:32 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/data-subscriptions/concurrent-subscriptions.markdown
> +  are able to connect a common subscription simultaneously.
done

2021-11-08 12:33 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/data-subscriptions/concurrent-subscriptions.markdown
> +  [what is the limit? the max number of connections, same as for non-concurrent subscriptions.
the whole sentence is a aleftover.. removed.. (o:

2021-11-08 12:36 UTC, reebhub commented on Documentation/5.3/Samples/csharp/Raven.Documentation.Samples/ClientApi/DataSubscriptions/ConcurrentSubscriptions.cs
> +                // Connect concurrently with "All Orders" subscription
done

2021-11-08 12:37 UTC, reebhub commented on Documentation/5.3/Samples/csharp/Raven.Documentation.Samples/ClientApi/DataSubscriptions/ConcurrentSubscriptions.cs
> +            // Connect concurrently with "All Orders" subscription
done

2021-11-08 12:39 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/data-subscriptions/concurrent-subscriptions.markdown
> +  to any available worker.
done

2021-11-08 12:42 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/data-subscriptions/concurrent-subscriptions.markdown
> +  before disconnecting.
done

2021-11-08 13:04 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/data-subscriptions/consumption/api-overview.dotnet.markdown
> +After receiving a subscription worker, the subscription worker is still not processing any documents. SubscriptionWorker's `Run` function allows you to start processing worker operations.
[generating](../../../client-api/data-subscriptions/consumption/api-overview#subscription-worker-generation)

2021-11-08 13:05 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/data-subscriptions/consumption/how-to-consume-data-subscription.dotnet.markdown
> +  If there is a existing connection, the incoming worker will throw a
done

2021-11-08 13:10 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/data-subscriptions/consumption/how-to-consume-data-subscription.dotnet.markdown
> +  If the client currently cannot open the subscription because it is used
worker
updated

2021-11-08 15:27 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/data-subscriptions/consumption/how-to-consume-data-subscription.dotnet.markdown
> +
added a new "Subscription Strategy" panel that explains it.

2021-11-08 15:28 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/data-subscriptions/creation/how-to-create-data-subscription.dotnet.markdown
> +Subscriptions are created by performing a request to the server with certain subscription creations parameters, see [Creation API summary](api-overview#create-and-createasync-overloads-summary).
done

2021-11-08 15:29 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/data-subscriptions/creation/how-to-create-data-subscription.dotnet.markdown
> +Upon subscription creation, the cluster will choose a preferred node that will run the subscription (unless client has stated a mentor node).
done

2021-11-08 15:32 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/data-subscriptions/creation/how-to-create-data-subscription.dotnet.markdown
> +will be the node that will the only node to process the subscription. There is an enterprise license level feature that support subscription (and any other ongoing task)
done

2021-11-08 15:44 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/data-subscriptions/what-are-data-subscriptions.dotnet.markdown
> +Data subscriptions are consumed by clients, called subscription workers. In any given moment, only one worker can be connected to a data subscription.
* Data subscriptions are consumed by clients, called subscription **workers**.  
* You can determine whether workers would be able to connect a subscription concurrently, or only one at a time.  
* A worker that connects a data subscription, receives a batch of documents and gets to process it.  
  Depending on the code that the client provided the worker with, processing can take from seconds to hours.  
  When all documents are processed, the worker informs the server of its progress and the server can send it the next batch.

2021-11-08 15:50 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/data-subscriptions/what-are-data-subscriptions.dotnet.markdown
> +When it's done, depending on the code that the client gave the worker, it can take from seconds to hours. It informs the server about the progress, and the server is ready to send the next batch.
see previous comment

2021-11-08 15:53 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/data-subscriptions/what-are-data-subscriptions.dotnet.markdown
> +
done

2021-11-08 16:04 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/data-subscriptions/what-are-data-subscriptions.dotnet.markdown
> +The TCP connection is also used as the "state" of the worker process and as long as it's alive, the server will not allow other clients to consume the subscription.
* The status of the TCP connection is also used to determine the "state" of the worker process.  
  If the subscription and its workers implement a 
  [One Worker Per Subscription](../../client-api/data-subscriptions/consumption/how-to-consume-data-subscription#worker-interplay) 
  strategy, as long as the connection is alive the server will not allow 
  other clients to consume the subscription. 
* The TCP connection is kept alive and monitored using "heartbeat" messages.  
  If the connection is found nonfunctional, the current batch progress will be restarted.

2021-11-08 16:07 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/data-subscriptions/advanced-topics/maintenance-operations.dotnet.markdown
> +| **SubscriptionName** | `string` | Subscription's name, and also it's unique identifier |
done

2021-11-08 16:10 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/data-subscriptions/advanced-topics/maintenance-operations.dotnet.markdown
> +| **ChangeVectorForNextBatchStartingPoint** | `string` | Change vector, starting from which the subscription will send documents. This value is updated manually, or automatically on batch acknowledgm
done

2021-11-08 16:11 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/data-subscriptions/advanced-topics/maintenance-operations.dotnet.markdown
> +| **GetSubscriptionWorker(string subscriptionName, string database)** | `SubscriptionWorker<dynamic>` | Generates a subscription worker, using default configurations, that processes documents in it's
done

2021-11-08 16:11 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/data-subscriptions/advanced-topics/maintenance-operations.dotnet.markdown
> +| **GetSubscriptionWorker(SubscriptionWorkerOptions options, string database)** | `SubscriptionWorker<dynamic>` | Generates a subscription worker, using default configurations, that processes documen
done

2021-11-08 16:14 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/data-subscriptions/concurrent-subscriptions.markdown
> +  are able to connect a common subscription simultaneously.
nah (o:

2021-11-08 16:24 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/data-subscriptions/concurrent-subscriptions.markdown
> +
1st comment: added a bullet at the top - 
* Documents will never be processed concurrently by multiple workers.  

2nd comment: added a new "Subscription Strategy" panel in consumption/how-to-consume-data-subscription.dotnet.markdown

2021-11-08 16:25 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/data-subscriptions/consumption/api-overview.dotnet.markdown
> +| **AfterAcknowledgment** | `AfterAcknowledgmentAction` (event) | Event that is risen after each the server acknowledges batch processing progress. |
done

2021-11-08 16:29 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/data-subscriptions/consumption/examples.dotnet.markdown
> +{PANEL:Subscription that ends when no documents left}
done

2021-11-08 16:41 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/data-subscriptions/advanced-topics/maintenance-operations.dotnet.markdown
> +| **DropConnection(string name, string database)** | `void` | Drops existing subscription connection with worker. |
| **DropConnection(string name, string database)** | `void` | Drops all existing subscription connections with workers. |
| **DropConnectionAsync(string name, string database)** | `Task` | Drops all existing subscription connections with workers. |
| **DropSubscriptionWorker<T>(SubscriptionWorker<T> worker, string database = null)** | `void` | Drops an existing subscription connection with a worker |

2021-11-09 06:28 UTC, lastav5 requested changes

2021-11-09 06:28 UTC, lastav5 commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/tasks/ongoing-tasks/subscription-task.markdown
> +     **Single**: mode is 'Single' if the workers' strategy allows them to connect one by one.
if the workers' strategy allows only one worker to be connected at a time

2021-11-09 07:34 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/tasks/ongoing-tasks/subscription-task.markdown
> +     **Single**: mode is 'Single' if the workers' strategy allows them to connect one by one.
done

2021-11-09 07:56 UTC, lastav5 approved these changes

2021-11-09 08:50 UTC, Danielle9897 requested changes

2021-11-09 08:50 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/client-api/data-subscriptions/consumption/how-to-consume-data-subscription.dotnet.markdown
> +{PANEL: Subscription Strategy}
Refactor title
=>
Determining which workers the subscription will serve

2021-11-09 08:50 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/client-api/data-subscriptions/what-are-data-subscriptions.dotnet.markdown
> +A subscription worker will retry processing documents from the last acknowledged and processed document (by tracking its Change Vector).
@lastav5 
Can this be clarified ?
From the above, it is implied that the worker tracks the Change Vector ?

2021-11-09 08:50 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/client-api/data-subscriptions/what-are-data-subscriptions.dotnet.markdown
> +Processing progress is persisted and therefore it can be paused and resumed from the last point it was stopped.
=>
The processing progress is persisted on the server and therefore the subscription task can be paused and resumed from the last point it was stopped.

2021-11-09 08:50 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/client-api/data-subscriptions/what-are-data-subscriptions.dotnet.markdown
> +  connect it simultaneously and divide the documents procession load between them to speed it up.
procession => processing

2021-11-09 08:50 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/client-api/data-subscriptions/what-are-data-subscriptions.dotnet.markdown
> +   * Batch procession is divided between the multiple workers.
procession => processing

2021-11-09 08:50 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/client-api/data-subscriptions/what-are-data-subscriptions.dotnet.markdown
> +Data subscriptions are accessible by a document store. Here's an example of an ad-hoc creation and usage of data subscriptions:
Here's an example of an ad-hoc creation and usage of data subscriptions:
=>
Here's an example of creating and using a data subscription:

2021-11-09 08:50 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/tasks/ongoing-tasks/subscription-task.markdown
> +* Data subscriptions are task that automatically send certain documents to a subscribed
1.
Data subscriptions are task that automatically send ...
=>
A data subscription is a task that automatically sends ...

2. make 'data subscription' bold

2021-11-09 08:50 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/tasks/ongoing-tasks/subscription-task.markdown
> +* This page explains how to create a subscription on the server side using the Studio.
=> subscription task

2021-11-09 08:50 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/tasks/ongoing-tasks/subscription-task.markdown
> +2. Limit the age of the documents that will be retrieved. Default: "the
retrieved => sent

(and in the below sentence as well)

2021-11-09 08:50 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/tasks/ongoing-tasks/subscription-task.markdown
> +     document change vector.
=>
Define the starting point from which to send the **first** batch:

* **Begining of Tim**e (default option) - all documents matching the RQL query will be sent, regardless of their creation time.
* **Latest document** - start from the first new document that will be created after the subscription is created.
* **Change vector** - specify a document change vector as the subscription starting point

2021-11-09 08:50 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/tasks/ongoing-tasks/subscription-task.markdown
> +specified query.
are retrieved => are matched 
or
which documents match the...

2021-11-09 08:50 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/tasks/ongoing-tasks/subscription-task.markdown
> +     responded that it has recieved a batch.
recieved => received

2021-11-09 08:50 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/tasks/ongoing-tasks/subscription-task.markdown
> +     document in the batch that will be sent next.
Not clear
=>

The change vector of the last document that was sent in the last batch
or
The change vector of the next document to be sent in the next batch

???

2021-11-09 08:57 UTC, lastav5 commented on Documentation/5.3/Raven.Documentation.Pages/client-api/data-subscriptions/consumption/api-overview.dotnet.markdown
> +It won't try to failover to another server. It might also fail if the subscription worker changes the node it communicates with.
There is a failover mechanism for when a node fails, yes. Then the entire subscription and its connections will move to another node

2021-11-09 09:07 UTC, lastav5 commented on Documentation/5.3/Raven.Documentation.Pages/client-api/data-subscriptions/what-are-data-subscriptions.dotnet.markdown
> +A subscription worker will retry processing documents from the last acknowledged and processed document (by tracking its Change Vector).
Not sure what "tracking its change vector" means here exactly. But overall, the server hands out batches according to the last batch that had been acked (But it gives priority to batches of documents that need to be resent)

2021-11-09 09:47 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/data-subscriptions/concurrent-subscriptions.markdown
> +* Documents will never be processed concurrently by multiple workers.
dropped

2021-11-09 09:47 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/data-subscriptions/concurrent-subscriptions.markdown
> +Subscription workers are defined similarly to other workers, except for their
done

2021-11-09 09:53 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/data-subscriptions/consumption/how-to-consume-data-subscription.dotnet.markdown
> +
done

2021-11-09 10:01 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/data-subscriptions/consumption/how-to-consume-data-subscription.dotnet.markdown
> +From this point on, the subscription worker will start processing batches. If for any reason, the processing is aborted, and the returned task (`subscriptionRuntimeTask`) will be finished with an exc
If processing is aborted for any reason, the returned task (`subscriptionRuntimeTask`) 
will be finished with an exception.

2021-11-09 10:06 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/data-subscriptions/consumption/how-to-consume-data-subscription.dotnet.markdown
> +   * The existing connection **does not** have a `TakeOver` strategy.
* `SubscriptionOpeningStrategy.TakeOver`  
  The server will allow an incoming connection to overthrow an existing one, 
  according to the existing connection strategy.  
   * If the existing connection **does not** have a `TakeOver` strategy:  
     The incoming connection will take over, causing the existing connection to throw a `SubscriptionInUseException`.  
   * If the existing connection **has** a `TakeOver` strategy:  
     The incoming connection will throw a `SubscriptionInUseException` exception.

2021-11-09 10:07 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/data-subscriptions/consumption/how-to-consume-data-subscription.dotnet.markdown
> +   * The existing connection **has** a `TakeOver` strategy.
see previous reply

2021-11-09 10:10 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/data-subscriptions/consumption/how-to-consume-data-subscription.dotnet.markdown
> +### Concurrent Subscription Strategy
done

2021-11-09 10:20 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/data-subscriptions/consumption/how-to-consume-data-subscription.dotnet.markdown
> +{PANEL: Subscription Strategy}
a subscription.
done.

2021-11-09 10:30 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/data-subscriptions/what-are-data-subscriptions.dotnet.markdown
> +Processing progress is persisted and therefore it can be paused and resumed from the last point it was stopped.
done

2021-11-09 10:32 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/data-subscriptions/what-are-data-subscriptions.dotnet.markdown
> +  connect it simultaneously and divide the documents procession load between them to speed it up.
done

2021-11-09 10:32 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/data-subscriptions/what-are-data-subscriptions.dotnet.markdown
> +   * Batch procession is divided between the multiple workers.
done

2021-11-09 10:46 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/data-subscriptions/what-are-data-subscriptions.dotnet.markdown
> +Data subscriptions are accessible by a document store. Here's an example of an ad-hoc creation and usage of data subscriptions:
done

2021-11-09 10:48 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/tasks/ongoing-tasks/subscription-task.markdown
> +* Data subscriptions are task that automatically send certain documents to a subscribed
done

2021-11-09 10:49 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/tasks/ongoing-tasks/subscription-task.markdown
> +* This page explains how to create a subscription on the server side using the Studio.
done

2021-11-09 11:14 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/tasks/ongoing-tasks/subscription-task.markdown
> +     document change vector.
done

2021-11-09 11:15 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/tasks/ongoing-tasks/subscription-task.markdown
> +2. Limit the age of the documents that will be retrieved. Default: "the
irrelevant, the text changed

2021-11-09 11:16 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/tasks/ongoing-tasks/subscription-task.markdown
> +specified query.
done

2021-11-09 11:17 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/tasks/ongoing-tasks/subscription-task.markdown
> +     responded that it has recieved a batch.
done

2021-11-09 11:27 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/tasks/ongoing-tasks/subscription-task.markdown
> +     document in the batch that will be sent next.
irrelevant to concurrent subscriptions (as most of these comments are).
if you want to make a change here please state it specifically or open a new issue.

2021-11-09 12:01 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/tasks/ongoing-tasks/subscription-task.markdown
> +     document in the batch that will be sent next.
took "the change vector of the last document that was sent in the last batch".

2021-11-09 14:18 UTC, Danielle9897 approved these changes

2021-11-09 14:20 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/client-api/data-subscriptions/consumption/api-overview.dotnet.markdown
> +It won't try to failover to another server. It might also fail if the subscription worker changes the node it communicates with.
Created issue for this:
https://issues.hibernatingrhinos.com/issue/RDoc-2009

2021-11-09 14:21 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/client-api/data-subscriptions/what-are-data-subscriptions.dotnet.markdown
> +A subscription worker will retry processing documents from the last acknowledged and processed document (by tracking its Change Vector).
Created issue for this:
https://issues.hibernatingrhinos.com/issue/RDoc-2010

2021-11-09 14:24 UTC, merged