RDoc-2004 code assistance
ravendb/docs pull request #1393
Opened 2021-11-12 13:02 UTC by reebhub

2021-11-12 18:04 UTC, ml054 commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/code-assistance.markdown
> +  or a [subscription task definition](../../studio/database/tasks/ongoing-tasks/subscription-task#subscription-task-definition),
subscription? Rather collection.

2021-11-12 18:07 UTC, ml054 requested changes

2021-11-12 18:07 UTC, ml054 commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/code-assistance.markdown
> +2. The list of **keywords** that can be used with the selected collection
keywords can be used with any query source: collection or index.

2021-11-12 18:07 UTC, ml054 commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/code-assistance.markdown
> +3. The list of **document fields** that can be queried
document/index fields - depends on query source

2021-11-12 18:07 UTC, ml054 commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/code-assistance.markdown
> +### When is Auto-Completion Not Available
I'd remove this chapter
- nothing to show off
- in future we want to add such feature
- you can invoke completion any time - it simply might not show results.

2021-11-12 18:07 UTC, ml054 commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/code-assistance.markdown
> +and errors are detected and highlighted.
technically we don't highlight errors - we show annotations/warning on left side (gutter)

2021-11-12 20:35 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/code-assistance.markdown
> +  or a [subscription task definition](../../studio/database/tasks/ongoing-tasks/subscription-task#subscription-task-definition),
is this clearer?

* The RQL auto-completion tool can be used in these views:  
   - The [Query View](../../studio/database/queries/query-view#query-view)  
   - The [Index View](../../studio/database/indexes/create-map-index#edit-index-view)  
   - The [Subscription Task View](../../studio/database/tasks/ongoing-tasks/subscription-task#subscription-task-definition)  
* To invoke auto-completion, click **CTRL+Space** while writing RQL.

2021-11-12 20:42 UTC, ml054 commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/code-assistance.markdown
> +  or a [subscription task definition](../../studio/database/tasks/ongoing-tasks/subscription-task#subscription-task-definition),
oh yes, you referred to places where this feature can be used. Then we can't use RQL on index view - there you want linq.

So list is: subscription, patch, query views.

2021-11-12 20:43 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/code-assistance.markdown
> +2. The list of **keywords** that can be used with the selected collection
you probably read it here? 
when you look at the actual document this list relates to number drops in the screenshots of a few queries.
#2 shows the list that auto-complete shows for a collection ("Companies").
do you still want me to change it?

2021-11-12 20:45 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/code-assistance.markdown
> +3. The list of **document fields** that can be queried
same here, it explains the list that pops up for "where".
do you still want me to change it?

2021-11-12 20:48 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/code-assistance.markdown
> +### When is Auto-Completion Not Available
removed

2021-11-12 20:56 UTC, ml054 commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/code-assistance.markdown
> +3. The list of **document fields** that can be queried
let's leave it - I'm reviewing w/o looking at images + text as a whole

2021-11-12 21:03 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/code-assistance.markdown
> +and errors are detected and highlighted.
* As you write your query, its syntax is continuously verified and errors are detected.  
* When an error is detected, an error indicator is displayed on the left side of the edit box.  
* Hovering over the error indicator shows the error details.

2021-11-12 21:23 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/code-assistance.markdown
> +  or a [subscription task definition](../../studio/database/tasks/ongoing-tasks/subscription-task#subscription-task-definition),
ah
very true
i replaced "patch view" with "index".
fixed everywhere (at the top, in the auto-completion section, and in the related articles)

2021-11-14 09:43 UTC, Danielle9897 requested changes

2021-11-14 09:43 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/code-assistance.markdown
> +  queries an enjoyable task.
Replace the above 2 bullets with:

=>

* All queries addressed to the RavenDB server use **[RQL](url)** (RavenDB's Query Language), which is a rich query language exposing the order of operations handled by the RavenDB server when serving a query.

* **RQL Code Assistance** is available when writing any query in the Studio.
The code auto-completion allows you to see the various paths your query can take, as data entities, functions, keywords, and operators are presented for you to select, speeding up the writing process and making the creation of intelligent queries an enjoyable task. 

* In addition, the query syntax is checked and potential errors are highlighted.

2021-11-14 09:43 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/code-assistance.markdown
> +* The RQL auto-completion tool can be used in these views:
=>
RQL code assistance is available in the following views

2021-11-14 09:43 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/code-assistance.markdown
> +   - The [Subscription Task View](../../studio/database/tasks/ongoing-tasks/subscription-task#subscription-task-definition)
remove the 'The' from all

2021-11-14 09:43 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/code-assistance.markdown
> +* Options relevant for the query section that your cursor is placed at will be listed.
=>
The relevant options for the current cursor location will be listed.

2021-11-14 09:43 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/code-assistance.markdown
> +create a JavaScript function).
pls list:

* from - to select a collection to query on
* from index - to select an index to query on
* declare function - to create a JavaScript function

2021-11-14 09:43 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/code-assistance.markdown
> +1. **The list of available options**
remove 'The'

2021-11-14 09:43 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/code-assistance.markdown
> +3. The **Option type**, which can be -
remove 'The'

2021-11-14 09:43 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/code-assistance.markdown
> +**As the query evolves**, the auto-completion tool will suggest new options.
=>
As the query evolves, new options that are are relevant to the current code are suggested

2021-11-14 09:43 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/code-assistance.markdown
> +{INFO: For the queries shown above, auto-completion presents: }
=>
For the collection query shown above, ...

2021-11-14 09:43 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/code-assistance.markdown
> +* When an error is detected, an error indicator is displayed on the left side of the edit box.
=>
When an error is detected, a warning sign is displayed on the left side of the editor

2021-11-14 09:43 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/code-assistance.markdown
> +* Hovering over the error indicator shows the error details.
=>
Hovering over the warning sign shows the error details.

2021-11-14 09:43 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/code-assistance.markdown
> +1. a **Syntax error**
`#1` is not needed
(it is not clear what was meant here)

2021-11-14 09:43 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/code-assistance.markdown
> +2. the **Error indicator**
remove 'the'

2021-11-14 09:43 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/code-assistance.markdown
> +   Hovering over the error indicator opens a pop-up that specifies the error details.
=>
Hover over the error indicator to see the error details.

2021-11-14 10:45 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/code-assistance.markdown
> +* The RQL auto-completion tool can be used in these views:
done

2021-11-14 10:45 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/code-assistance.markdown
> +   - The [Subscription Task View](../../studio/database/tasks/ongoing-tasks/subscription-task#subscription-task-definition)
done

2021-11-14 10:46 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/code-assistance.markdown
> +* Options relevant for the query section that your cursor is placed at will be listed.
done

2021-11-14 10:50 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/code-assistance.markdown
> +create a JavaScript function).
changed to a list

2021-11-14 10:52 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/code-assistance.markdown
> +1. **The list of available options**
done

2021-11-14 10:52 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/code-assistance.markdown
> +3. The **Option type**, which can be -
done

2021-11-14 11:04 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/code-assistance.markdown
> +**As the query evolves**, the auto-completion tool will suggest new options.
done

2021-11-14 11:05 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/code-assistance.markdown
> +{INFO: For the queries shown above, auto-completion presents: }
done

2021-11-14 11:06 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/code-assistance.markdown
> +* When an error is detected, an error indicator is displayed on the left side of the edit box.
done

2021-11-14 11:06 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/code-assistance.markdown
> +* Hovering over the error indicator shows the error details.
done

2021-11-14 11:09 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/code-assistance.markdown
> +1. a **Syntax error**
that's the actual error.

1. a **Syntax error** (this symbol cannot be used here)

2021-11-14 11:10 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/code-assistance.markdown
> +2. the **Error indicator**
**Warning Sign**

2021-11-14 11:11 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/code-assistance.markdown
> +   Hovering over the error indicator opens a pop-up that specifies the error details.
done

2021-11-14 11:45 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/code-assistance.markdown
> +  queries an enjoyable task.
* All queries addressed to RavenDB use the rich [RQL](../../indexes/querying/what-is-rql) language.  
* The query **structure** exposes the **order** by which RavenDB handles operations when serving a query.  
* RQL Code Assistance is available when writing any query in the Studio.  
  The code auto-completion allows you to see the various paths your query can take, as data entities, functions, keywords, and operators are presented for you to select, speeding up the writing process and making the creation of intelligent queries an enjoyable task.  
* In addition, the query syntax is checked and potential errors are highlighted.

2021-11-14 14:36 UTC, Danielle9897 requested changes

2021-11-14 14:36 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/code-assistance.markdown
> +  views.
1. All queries addressed to RavenDB => All queries addressed to the RavenDB server

2. can take, as data entities, => can take as data entities,

3. about the second bullet ..the query structure exposes... 
in spite of what was discussed, it is still not good like that,
because when saying 'ravenDB handles operations' ist is not clear if we mean the query operations or other operations

=>
The query structure exposes the order of the query operations handled by the RavenDB server when serving a query

2021-11-14 14:36 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/code-assistance.markdown
> +   Hover over the error indicator to see the error details.
since you changed the above to 'warning sign' then need to change here:
=> 
Hover over the warning sign to see the error details.

2021-11-14 16:18 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/code-assistance.markdown
> +  views.
done

2021-11-14 16:19 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/code-assistance.markdown
> +   Hover over the error indicator to see the error details.
done

2021-11-14 17:17 UTC, Danielle9897 requested changes

2021-11-14 17:17 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/code-assistance.markdown
> +* The **query structure** exposes the **order of the query operations**
pls remove all the bold parts from above sentence

2021-11-14 17:17 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/code-assistance.markdown
> +* RQL Code Assistance is available when writing any query in the Studio.
pls make **RQL Code Assistance** bold in the above sentence

2021-11-14 19:57 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/code-assistance.markdown
> +* RQL Code Assistance is available when writing any query in the Studio.
done

2021-11-14 21:06 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/code-assistance.markdown
> +* The **query structure** exposes the **order of the query operations**
no, they need to remain bold.

2021-11-15 07:02 UTC, ml054 approved these changes

2021-11-15 09:52 UTC, merged