RDoc-2001 Added connection string samples for Raven, Sql, and Olap.
ravendb/docs pull request #1406
Opened 2021-11-28 09:21 UTC by serezhub

2021-11-29 11:44 UTC, reebhub commented on Documentation/4.0/Raven.Documentation.Pages/client-api/operations/maintenance/etl/add-etl.dotnet.markdown
> +* [Example - Add Raven ETL](../../../../client-api/operations/maintenance/etl/add-etl#example---add-raven-etl)
reverse the order (here and in the contents)
a connection string is needed to create the task, so explaining how to create the connection string should come first.

2021-11-29 11:48 UTC, reebhub commented on Documentation/4.0/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/AddEtl.cs
> +                //send the connection string to connect
create the connection string

2021-11-29 11:51 UTC, reebhub commented on Documentation/4.0/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/AddEtl.cs
>                  #endregion
the connection string is defined but never created

2021-11-29 11:53 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/maintenance/etl/add-etl.dotnet.markdown
> +
see previous remark about reversing the order (connection string first, TL task second)

2021-11-29 11:57 UTC, reebhub commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/AddEtl.cs
> +
the connection string is defined but never created

2021-11-29 12:03 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/etl/add-etl.markdown
>  {CODE add_raven_etl@ClientApi\Operations\AddEtl.cs /}
* please use the format that is used here for the Elasticsearch connection string and task, for the other ETL types as well (Raven, SQL, OLAP).
* please add a contents here, as you did for the other versions.
* please apply comments given for previous versions.

2021-12-01 09:45 UTC, serezhub commented on Documentation/4.0/Raven.Documentation.Pages/client-api/operations/maintenance/etl/add-etl.dotnet.markdown
> +* [Example - Add Raven ETL](../../../../client-api/operations/maintenance/etl/add-etl#example---add-raven-etl)
Done.

2021-12-01 10:53 UTC, serezhub commented on Documentation/4.0/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/AddEtl.cs
> +                //send the connection string to connect
Done in each version

2021-12-01 11:32 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/maintenance/etl/add-etl.dotnet.markdown
> +
Done for all versions

2021-12-16 13:15 UTC, serezhub commented on Documentation/4.0/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/AddEtl.cs
>                  #endregion
done

2021-12-16 13:15 UTC, serezhub commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/AddEtl.cs
> +
done

2021-12-16 13:56 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/etl/add-etl.markdown
>  {CODE add_raven_etl@ClientApi\Operations\AddEtl.cs /}
done

2022-01-17 11:35 UTC, aviv86 requested changes

2022-01-17 11:35 UTC, aviv86 commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/AddEtl.cs
> +        }
redundant

2022-01-17 11:35 UTC, aviv86 commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/OlapConnectionString.cs
> +}
why is this needed? we have this in `Raven.Client.Documents.Operations.ETL.OLAP`

2022-01-17 11:35 UTC, aviv86 commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/AddEtl.cs
> +
this is wrong
all these properties are inside `S3Settings `
and we're missing other ones..
please apply same changes as discussed in [RDoc-2030](https://github.com/ravendb/docs/pull/1412#discussion_r777561580)

2022-01-17 11:35 UTC, aviv86 commented on Documentation/5.3/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/AddEtl.cs
> +
same here

2022-01-17 11:35 UTC, aviv86 commented on Documentation/5.3/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/AddEtl.cs
> +            (new PutConnectionStringOperation<OlapConnectionString>(myOlapConnectionString));
same (`myOlapConnectionString` => `connectionString`)

2022-01-17 11:35 UTC, aviv86 commented on Documentation/5.3/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/AddEtl.cs
> +                var resultRavenString = store.Maintenance.Send(new PutConnectionStringOperation<RavenConnectionString>(ravenConnectionString));
same (`ravenConnectionString` => `myOlapConnectionString` and `resultRavenString` => `resultOlapString`)

2022-01-17 13:13 UTC, serezhub commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/AddEtl.cs
> +                var resultRavenString = store.Maintenance.Send(new PutConnectionStringOperation<RavenConnectionString>(ravenConnectionString));
Made those changes and also changed `RavenConnectionString` to `OlapConnectionString`.  
It is still unhappy.

2022-01-17 13:17 UTC, serezhub commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/AddEtl.cs
> +                var resultRavenString = store.Maintenance.Send(new PutConnectionStringOperation<RavenConnectionString>(ravenConnectionString));
Also made the changes in 5.3, still not happy.

2022-01-17 13:20 UTC, serezhub commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/AddEtl.cs
> +                    (new PutConnectionStringOperation<OlapConnectionString>(myOlapConnectionString));
Used second option because it seems that otherwise we'd need to rename myOlapConnectionString in many places...

2022-01-17 13:21 UTC, serezhub commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/AddEtl.cs
> +        }
gone

2022-01-17 13:22 UTC, serezhub commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/OlapConnectionString.cs
> +}
I wish I knew...  What should I do?

2022-01-19 16:01 UTC, serezhub commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/AddEtl.cs
> +
done and pushed

2022-01-19 16:02 UTC, serezhub commented on Documentation/5.3/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/AddEtl.cs
> +
done

2022-01-19 16:02 UTC, serezhub commented on Documentation/5.3/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/AddEtl.cs
> +            (new PutConnectionStringOperation<OlapConnectionString>(myOlapConnectionString));
fixed

2022-01-20 12:26 UTC, aviv86 reviewed
Looks fine, but you have failing checks on `docs-parsing` and `missing-md` 
I noticed something about a missing image : 
```
System.InvalidOperationException: Could not compile 'D:\a\docs\docs\Documentation\4.1\Raven.Documentation.Pages\client-api\operations\maintenance\etl\add-etl.dotnet.markdown'. 
---> System.InvalidOperationException: Could not find image in 'D:\a\docs\docs\Documentation\4.1\Raven.Documentation.Pages\client-api\operations\maintenance\etl\images/export-server-certificate.png' 
for article 'client-api/operations/maintenance/etl/add-etl'.
```

please check

2022-01-23 09:32 UTC, serezhub commented
I've taken out the image and replaced it with a link to an article on the topic of passing certificates.  

The checks...I get these fails every time.  As far as I know, they're because our java and js files aren't finished yet.  I'll check with Reeb.

2022-01-24 13:53 UTC, reebhub commented on Documentation/4.0/Raven.Documentation.Pages/client-api/operations/maintenance/etl/add-etl.dotnet.markdown
> +
bullet the top options

2022-01-24 13:53 UTC, reebhub commented on Documentation/4.0/Raven.Documentation.Pages/client-api/operations/maintenance/etl/add-etl.dotnet.markdown
> +You can add ETL task by using **AddEtlOperation**.
an ETL task

2022-01-24 13:57 UTC, reebhub commented on Documentation/4.0/Raven.Documentation.Pages/client-api/operations/maintenance/etl/add-etl.dotnet.markdown
> +To manage them in the Studio read this article about [ETLs and how to add them via the GUI Studio](../../../../studio/database/tasks/ongoing-tasks/ravendb-etl-task).
* ..To learn how to..
* who are "them"?
* simplify & stick to the original article name.  "..read: [RavenDB ETL Task]()"

2022-01-24 14:14 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/etl/add-etl.markdown
> +
make the three top options bullets

2022-01-24 14:16 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/etl/add-etl.markdown
> +You can add ETL task by using **AddEtlOperation**.
an ETL task

2022-01-24 14:21 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/etl/add-etl.markdown
> +To manage them in the Studio read this article about [ETLs and how to add them via the GUI Studio](../../../../studio/database/tasks/ongoing-tasks/ravendb-etl-task).
* who are "them"?
* simplify and use the original article title, e.g. "To learn how to manage ETL tasks using Studio see: [RavenDB ETL Task]()"
* place the two "learn how to" bullets next to each other, either start or end with the "AddEtlOperation" bullet.

2022-01-24 14:25 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/etl/add-etl.markdown
> +To learn more about ETL (Extract, Transfer, Load) ongoing tasks, see this article on [ETL Basics](../../../../server/ongoing-tasks/etl/basics).
make the three top options bullets

2022-01-24 14:29 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/etl/add-etl.markdown
> +Add [Raven ETL](../../../../server/ongoing-tasks/etl/raven)
not sure what this line is supposed to be, in any case you can't repeat a title with exactly the same words only smaller.

2022-01-24 15:03 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/etl/add-etl.markdown
> +**Secure servers**
is this supposed to be a bullet? a note? 
the text is currently so messy it's hard to understand what the panel is about.

2022-01-24 15:05 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/etl/add-etl.markdown
> +  Be sure that the node definition in the connection string has the "s" in https:
probably better to make it a comment within the sample. in its current location it's completely out of context.

2022-01-24 15:18 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/etl/add-etl.markdown
> +
start with an explanation about what the panel is about.
make the two following issues (the certificates discussion and what happens after) bullets
make the following comment (about HTTPS) an inner comment inside the sample code, in its current location it's completely out of context.

2022-01-24 16:13 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/etl/add-etl.markdown
apply relevant comments to all panels.

2022-01-25 08:45 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/etl/add-etl.markdown
> +You can add ETL task by using **AddEtlOperation**.
Done.

2022-01-25 08:47 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/etl/add-etl.markdown
> +To manage them in the Studio read this article about [ETLs and how to add them via the GUI Studio](../../../../studio/database/tasks/ongoing-tasks/ravendb-etl-task).
Good point

2022-01-25 08:49 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/etl/add-etl.markdown
> +To learn more about ETL (Extract, Transfer, Load) ongoing tasks, see this article on [ETL Basics](../../../../server/ongoing-tasks/etl/basics).
done

2022-01-25 08:52 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/etl/add-etl.markdown
> +Add [Raven ETL](../../../../server/ongoing-tasks/etl/raven)
I was just following your example, like you instructed me to do.  I agree that using different words is more elegant

2022-01-25 09:30 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/etl/add-etl.markdown
> +Add [Raven ETL](../../../../server/ongoing-tasks/etl/raven)
I added a more descriptive intro to each section, including Elasticsearch.

2022-01-25 09:31 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/etl/add-etl.markdown
Added to the intro:
* ETL tasks are ongoing tasks that:
  1. Continuously extract selected data from your database.
  2. Apply a transform script on the data.
  3. Load the transformed data to a destination that you designate. 

As stated above, I gave a descriptive sentence introducing each sentence.

2022-01-25 10:34 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/etl/add-etl.markdown
> +
did all three

2022-01-25 10:37 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/etl/add-etl.markdown
> +### Connection String for Raven ETL
Again, I was following the Elasticsearch example.  
In the interest of keeping titles short and not creating section link problems from the table of contents and perhaps other articles, I've learned to change sub-headings only when absolutely necessary because it causes confusion.

2022-01-25 10:39 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/etl/add-etl.markdown
> +### Code Sample to Add Raven ETL
Because this is the first time that this article will have these connection string titles, it is still safe to change them.

2022-01-25 10:42 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/etl/add-etl.markdown
> +### Code Sample to Add Raven ETL
Actually, I'm wrong.  There is the elasticsearch connection string.  I used that as the base example.  It could cause problems in any article that references that, so I think it's best to leave this cosmetic point behind....

2022-01-25 10:42 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/etl/add-etl.markdown
done

2022-01-25 12:17 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/etl/add-etl.markdown
> +### Code Sample to Add Raven ETL
the connection string samples were added very lately and their titles can be changed with no broad interference, right? you can search the entire solution for references to titles you change and change these references in a few minutes, and the links aren't used yet outside this documentation.

2022-01-25 12:37 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/etl/add-etl.markdown
I added an intro sentence for each section.

2022-01-25 14:50 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/etl/add-etl.markdown
> +### Code Sample to Add Raven ETL
Ok. I've changed the titles, tables of contents, etc...

2022-01-25 14:51 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/etl/add-etl.markdown
> +### Connection String for Raven ETL
Because these sections of the article are new, they haven't been referenced yet, so I changed them without problems.

2022-01-25 15:04 UTC, reebhub approved these changes

2022-01-25 16:16 UTC, aviv86 approved these changes

2022-01-26 08:17 UTC, merged