RDoc 1980 Time Series Settings
ravendb/docs pull request #1411
Opened 2021-12-12 18:51 UTC by reebhub

2021-12-14 10:03 UTC, Danielle9897 commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +   {NOTE/}
1. 
Replace:
=>
Note: Any modifications made in this view will Not be saved until you click the Save button.

2. 
Make this note a 'yellow warning'

2021-12-14 10:05 UTC, Danielle9897 commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +   Click to cancel additions and changes to this configuration.
=> Click to cancel adding this configuration

2021-12-14 10:06 UTC, Danielle9897 commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +   Save your additions and changes to time series configurations.
=>
Save all modifications made in this view.

2021-12-14 10:16 UTC, Danielle9897 commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +   in the `Companies` collection.
=>
The `ByMinute` rollup policy aggregates data from the time series raw data in the Companies collection.

2021-12-14 10:18 UTC, Danielle9897 commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +   The `30Mins` rollup time series aggregates data from the `ByMinute` rollup time series.
=>
The `30Mins` rollup policy aggregates data from the rollup time series that was created by the `ByMinute` policy.

2021-12-14 10:21 UTC, Danielle9897 commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +   of the new rollup time series.
aggregated in => aggregated into
of => in

2021-12-14 10:21 UTC, Danielle9897 commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +   is aggregated in a single entry of the `30Mins` rollup time series.
aggregated in => aggregated into
of => in

2021-12-14 10:28 UTC, Danielle9897 commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +     time series of the selected collection.
=>
The first rollup policy aggregates the time series raw data.

2021-12-14 10:38 UTC, Danielle9897 commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +
Add a bullet about:
=>

* Each policy aggregation time must be greater than the aggregation time set for the previous policy

2021-12-14 17:16 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +
* The **Time Series Settings view** allows you to define and manage time series 
  configurations per collection. Configurations may include:  

    * [Named Values](../../../document-extensions/timeseries/client-api/named-time-series-values)  
      A customized name can be set per time series value.  
      API methods can access time series values by their names.  
    
    * [Rollup Policies](../../../document-extensions/timeseries/rollup-and-retention#what-are-rollups)  
      A rollup policy defines a time frame by which data from an origin time series 
      will be aggregated into a new **rollup time series**.  

    * [Retention Periods](../../../document-extensions/timeseries/rollup-and-retention)  
      A retention period defines how long time series entries are kept.  
      An entry that exceeds this period will be removed.

2021-12-14 17:20 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +         the server checks them (see **Policy Check Frequency** blow).
this is wrong.

2021-12-14 17:24 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +    {NOTE/}
this is meant to explain Policy Check Frequency, your text explain what the execution of a policy does. it may be needed (though i don't think so), but not here.

2021-12-14 17:27 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +   View and manage the time series configurations that were already defined (read more [below](../../../studio/database/settings/time-series-settings#defined-time-series-configurations).
this is an action item and is phrased as such. i see there's a missing parenthesis there, fixed it.

2021-12-14 17:39 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +   Click to save configuration changes and additions.
well it's either the image numbering look really strange or the Save is one before last and not the last item, which is a little less weird.
the phrasing is meant to address both the changes in the defined configurations and the additions in the edit window.

2021-12-14 17:42 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +    * Click a defined configuration **Edit** button to edit an existing configuration.
true, it's not really needed if someone continues reading, but i want it to already be clear in this point.

2021-12-14 21:53 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +   Time series configurations are defined **per collection** (Companies` in the above image).
fixed

2021-12-14 21:55 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +      The retention policy for collected raw data.
done

2021-12-14 22:40 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +       * **Rollup Time Series Name**
done

2021-12-14 22:40 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +         The name of a **rollup time series** that aggregates **time series raw data**.
changed to - 

{NOTE: }
The policy name will be included in the name of the rollup time series, e.g. `StockPrices@ByMinute`.  
NOTE/}

2021-12-14 22:42 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +         The name of a **rollup time series** that aggregates **time series raw data**.
removed

2021-12-14 22:50 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +         collection is aggregated into a new rollup time series named `ByMinute`.
ok (without the "any")

2021-12-14 23:04 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +         a single entry of the `ByMinute` rollup time series.
the word "aggregated" indicates that the data is rolled up, no need to call the entry a "rollup entry" in addition to the "aggregated" and its existence as a rollup series entry.
added the second sentence as:
{NOTE: }
An entry is added to the rollup series only when the defined aggregation time frame has ended.  
{NOTE/}

2021-12-14 23:08 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +         The retention period defined for the rollup time series.
the point is to explain that this retention is defined for the new time series, not for the origin time series.

2021-12-14 23:11 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +       * **Rollup Time Series Name**
done

2021-12-14 23:18 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +         a **rollup time series**.
done

2021-12-14 23:20 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +         data from the `ByMinute` rollup time series.
In this example, the policy name is: `30Mins`.  
Data from the rollup time series `<raw-timeseries-name>@ByMinute>`  will be aggregated into a new rollup time series named: `<raw-timeseries-name>@30Mins`

2021-12-14 23:29 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +         data from the `ByMinute` rollup time series.
In this example, every 30 minutes of data from the `ByMinute` 
rollup time series are aggregated into a single entry of the 
`30Mins` rollup time series.  
NOTE: }
An entry is added to the rollup time series only when the defined aggregation time frame has ended.  
NOTE/}

2021-12-14 23:30 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +         of the `30Mins` rollup time series.
In this example, every 30 minutes of data from the `ByMinute` rollup time series are aggregated into a single entry of the `30Mins` rollup time series.  
NOTE: }
An entry is added to the rollup time series only when the defined aggregation time frame has ended.  
NOTE/}

2021-12-14 23:37 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +         The retention period defined for the rollup time series.
see my previous reply to this suggestion

2021-12-14 23:40 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +4. **Enable Retention**
done

2021-12-14 23:42 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +   Toggle to create a retention policy.
Toggle to set a retention policy for raw time series entries.

2021-12-14 23:44 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +      Enable to create a retention policy for the **raw data** of time series of the selected collection.
Enable to set a retention time period for **raw data** of all time-series in the selected collection.

2021-12-14 23:46 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +      Enter retention time.
done

2021-12-14 23:47 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +      In the example above, time series entries older than 1 hour will be removed.
done

2021-12-14 23:47 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +      Enter Rollup Policy Name
done

2021-12-14 23:48 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +      Enter the aggregation period
done

2021-12-14 23:50 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +      into a single entry of the new rollup time series.
changed "image" to "example", no need for double "rollup".

2021-12-14 23:58 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +      {NOTE/}
moved the note.
the "per policy" suggestion makes the sentence much harder to understand, and "for the time series that the data is aggregated from" explains it very clearly.

2021-12-14 23:59 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +      Enable to define a retention policy for the new rollup time series.
see my previous response to this suggestion.

2021-12-15 00:02 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +7. **Confirm**
please update me when it's merged and i'll change this title and take the new image (until then the title needs to remain identical to the button caption)

2021-12-15 00:04 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +   Click **OK** to confirm your changes.
done

2021-12-15 00:07 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +   {NOTE/}
done

2021-12-15 00:10 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +   Click to cancel additions and changes to this configuration.
too obscure, the configuration may already be added (can be entered through the "edit" button too).

2021-12-15 00:11 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +   Save your additions and changes to time series configurations.
Save all the modifications made in this view.

2021-12-15 00:14 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +     time series of the selected collection.
i can't see how this is better.

2021-12-15 00:15 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +
done

2021-12-15 00:18 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +   in the `Companies` collection.
The `ByMinute` rollup policy aggregates data from raw time series data in the Companies collection.

2021-12-15 00:22 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +   of the new rollup time series.
changed "in" to "into", "of" remains.

2021-12-15 00:24 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +   The `30Mins` rollup time series aggregates data from the `ByMinute` rollup time series.
done

2021-12-15 00:25 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +   is aggregated in a single entry of the `30Mins` rollup time series.
Every 30 minutes of data from the `ByMinute` rollup time series, are aggregated into a single entry of the `30Mins` rollup time series.

2021-12-16 08:33 UTC, Danielle9897 requested changes

2021-12-16 08:33 UTC, Danielle9897 commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +   Click to cancel additions and changes to this configuration.
both 'additions' and 'changes' is redundant (unless you meant the adding of a new configuration)

can use => 
Click to cancel the settings made to this configuration
or simply: 
Click to cancel (it is really self-explanatory)

(that works for both an existing configuration and for a new configuration)

2021-12-16 08:33 UTC, Danielle9897 commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +   in the `Companies` collection.
you are using 'from' in point 3 below as well,
so =>
The `ByMinute` rollup policy aggregates data from the time series raw data.

2021-12-16 08:33 UTC, Danielle9897 commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +         a single entry of the `ByMinute` rollup time series.
better to use 'in'
=>
In this example, every 1 minute of raw data is aggregated into a single entry in the `ByMinute` rollup time series

2021-12-16 08:33 UTC, Danielle9897 commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +         `30Mins` rollup time series.
better to use 'in'
=>
In this example, every 30 minutes of data from the `ByMinute` rollup time series are aggregated into a single entry in the        `30Mins` rollup time series.  

or
In this example, every 30 minutes of the `ByMinute` rollup time series are aggregated into a single entry in the        `30Mins` rollup time series.

2021-12-16 08:33 UTC, Danielle9897 commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +      into a single entry of the new rollup time series.
use 'in'
=>
In the above example, every 10 minutes of raw time series data will be aggregated into a single entry in the new rollup time series.

2021-12-16 08:33 UTC, Danielle9897 commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +   a single entry of the new rollup time series.
in the new rollup...

2021-12-16 08:33 UTC, Danielle9897 commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +   are aggregated into a single entry of the `30Mins` rollup time series.
in the new rollup...

2021-12-16 10:38 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +
the "may" is needed because all the options are optional.

2021-12-16 12:44 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +    {NOTE/}
regarding the execution bullet:

* Enabled policies will be executed -  
  By the time frame set by each policy,  
  As the policy is checked by the server (see **Policy Check Frequency** blow).

2021-12-16 14:27 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +    {NOTE/}
regarding **Policy Check Frequency**:

3. **Policy Check Frequency**  
   Set the frequency by which the server checks Rollup and Retention policies.  
   {NOTE: }
   Set **Policy Check Frequency** to a frequency that allows your 
   most frequent policy to run.  
   {NOTE/}

2021-12-16 14:38 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +         a single entry of the `ByMinute` rollup time series.
sounds a bit off this "in" thing, plus not technically correct because the new entry is not in the series yet.

2021-12-16 14:46 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +         The retention period defined for the rollup time series.
The retention period defined for the rollup time series entries.

2021-12-16 14:46 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +         The retention period defined for the rollup time series.
The retention period defined for the rollup time series entries.

2021-12-16 14:47 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +      into a single entry of the new rollup time series.
see previous discussion

2021-12-16 14:53 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +      {NOTE/}
The **aggregation time** cannot exceed the **retention period** defined for the origin time series.

2021-12-16 14:55 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +   Click to cancel additions and changes to this configuration.
and the winner is.. 
**Click to cancel.**

2021-12-16 14:57 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +   in the `Companies` collection.
right
done

2021-12-16 15:03 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +         `30Mins` rollup time series.
see previous discussions

2021-12-16 15:03 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +   a single entry of the new rollup time series.
see previous discussions

2021-12-16 15:11 UTC, Danielle9897 commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +    {NOTE/}
pls keep it simple - just use:

in the above part about the enabled policies:
=>
```
Enabled policies will be executed as frequently as defined by the Policy Check Frequency (see below).
When a policy is executed:
   * Aggregated/Rollup entries will be created according to the policy's aggregation time
   * Entries will be removed according to the policy's retention period
```
   
in this `#3`:
=>
`Set the frequency by which the server checks and executes the Rollup and Retention policies.`

and no need for the note about ..set...to a frequency that allows your most frequent policy to run...
1. users will decide, maybe they have other considerations... 
2. the term 'your most frequent policy' is not good here

2021-12-16 19:01 UTC, Danielle9897 requested changes

2021-12-16 19:15 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +
the "may" isn't redundant because missing it implies that each configuration has all three settings (named values, rollups, retentions), this isn't the case..

2021-12-16 19:20 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +         a single entry of the `ByMinute` rollup time series.
done

2021-12-16 19:20 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +         `30Mins` rollup time series.
done

2021-12-16 19:21 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +   read more [here](../../../studio/database/settings/time-series-settings#rollup-policies-for-rollup-time-series).
done

2021-12-16 19:45 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +         {NOTE: When a policy is executed:}
done

2021-12-16 19:53 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +      Enable to define a retention policy for the new rollup time series.
done

2021-12-16 20:03 UTC, Danielle9897 approved these changes

2021-12-16 21:27 UTC, Danielle9897 approved these changes

2021-12-17 08:44 UTC, merged