RDoc-2030 - Added Olap and Elasticsearch connection strings to 5.2/.3
ravendb/docs pull request #1412
Opened 2021-12-14 12:44 UTC by serezhub

2022-01-03 16:00 UTC, aviv86 requested changes

2022-01-04 10:01 UTC, serezhub commented on Documentation/5.3/Samples/java/src/test/java/net/ravendb/ClientApi/Operations/Server/ClientCertificate.java
> +public class ClientCertificate {
It isn't in my set of files.  I don't know how that got into this commit.  I've never seen this.

2022-01-04 10:49 UTC, serezhub commented on Documentation/5.3/Samples/java/src/test/java/net/ravendb/ClientApi/Operations/Server/DeleteClientCertificate.java
> +public class DeleteClientCertificate {
I'm not familiar with this either.

2022-01-10 06:51 UTC, serezhub commented on Documentation/5.3/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/ConnectionStrings.cs
> +                AddEtl(store, configuration, connectionString);
Thanks

2022-01-10 06:58 UTC, serezhub commented on Documentation/5.3/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/ConnectionStrings.cs
> +
good catch

2022-01-10 07:04 UTC, serezhub commented on Documentation/5.3/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/ConnectionStrings.cs
> +                public string FolderPath { get; set; }
I'm not clear about what to do with that.  `FolderPath` doesn't need a get/set?
I see that it is a property of local settings

                    Name = (string)connectionStringName,
                    LocalSettings = new LocalSettings
                    {
                        FolderPath = path
                    }

With that...how did it get into the code tests for olap connection strings?  I don't understand these things enough to give an answer or to fix it properly.

2022-01-10 12:09 UTC, serezhub commented on Documentation/5.3/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/ConnectionStrings.cs
> +                public string FolderPath { get; set; }
right

2022-01-17 10:23 UTC, aviv86 commented on Documentation/5.3/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/ConnectionStrings.cs
> +                public string FolderPath { get; set; }
please remove these
we already have them listed below

2022-01-17 10:26 UTC, aviv86 commented on Documentation/5.3/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/ConnectionStrings.cs
> +                public string FolderPath { get; set; }
also, please move the comments next to the relevant setting, i.e. :
```
public string Name { get; set; }
public string LocalSettings { get; set; } // If on local machine
public S3Settings S3Settings { get; set; } // If on AWS Cloud
...

```

2022-01-17 10:26 UTC, aviv86 commented on Documentation/5.3/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/ConnectionStrings.cs
> +        }
redundant

2022-01-17 10:28 UTC, aviv86 commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/ConnectionStrings.cs
> +
please apply the same changes here as we discussed in `5.3/Smaples/.../ConnectionStrings.cs`

2022-01-17 10:29 UTC, aviv86 commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/ConnectionStrings.cs
> +
redundant

2022-01-17 10:44 UTC, aviv86 commented on Documentation/5.3/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/ConnectionStrings.cs
> +            }s
`s` ?

2022-01-17 11:16 UTC, arekpalinski commented on Documentation/5.3/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/ConnectionStrings.cs
> +            }s
This is a _compilation_ error. Please make sure that you rebuild the project once you modify the code examples

2022-01-17 12:45 UTC, serezhub commented on Documentation/5.3/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/ConnectionStrings.cs
> +                public string FolderPath { get; set; }
I removed the // If on local machine section.
In 5.3 the configurations were not only about AWS, but in 5.2 they were about AWS.  They were configurations for parameters that were set in a connection string for AWS.  We used AWS as an example, just so that they'd see that if they're working with Google or Azure, they'll need to set up the parameters for them...

2022-01-17 12:51 UTC, serezhub commented on Documentation/5.3/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/ConnectionStrings.cs
> +        }
removed

2022-01-17 12:53 UTC, serezhub commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/ConnectionStrings.cs
> +
Removed the local machine lines.
Remove the AWS, even though an example is given for AWS?

2022-01-17 12:54 UTC, serezhub commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/ConnectionStrings.cs
> +
gone

2022-01-17 12:55 UTC, serezhub commented on Documentation/5.3/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/ConnectionStrings.cs
> +            }s
Removed the s.
I'll try a rebuild when I finish and write how it went here.

2022-01-17 13:01 UTC, serezhub commented on Documentation/5.3/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/ConnectionStrings.cs
> +            }s
Everything worked except for the Type in the 5.2 Olap configuration...

2022-01-20 12:38 UTC, aviv86 reviewed
Looks fine, but `missing-md` chcek failed - it looks like you having missing java and js markdowns 
please chcek

2022-01-20 12:38 UTC, aviv86 commented on Documentation/5.3/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/ConnectionStrings.cs
> +                var connectionString = olapConnectionString;
redundant

2022-01-23 09:38 UTC, serezhub commented on Documentation/5.3/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/ConnectionStrings.cs
> +                var connectionString = olapConnectionString;
Fixed

2022-01-24 16:32 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/add-connection-string.dotnet.markdown
> +## Syntax
call it by the method name (PutConnectionStringOperation) so when we refer to this method in some other article we can link directly to this title.

2022-01-24 16:34 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/add-connection-string.dotnet.markdown
> +* You can add a connection string by using **PutConnectionStringOperation**.
* Add a connection string using the `PutConnectionStringOperation` method.
* (note that we normally use `blue text` when we refer to code, e.g. methods, parameters etc.)

2022-01-24 16:36 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/add-connection-string.dotnet.markdown
> +* This article explains how to define the properties needed to connect to an external database.
maybe "read this article to learn how to.."?

2022-01-24 16:56 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/add-connection-string.dotnet.markdown
> +---
delete the divider

2022-01-24 16:56 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/add-connection-string.dotnet.markdown
> +###Configurations
delete the title

2022-01-24 17:20 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/add-connection-string.dotnet.markdown
> +## Example - Add Sql Connection String
remove this title, and place it in the panel definition as is normally done.
do the same with all these panels.
remove the "example" from the name, and i don't understand why the "a" or "an" are missing from all these.
e.g. -  
{PANEL: Add an Sql Connection String}

2022-01-24 17:29 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/add-connection-string.dotnet.markdown
> +{CODE add_sql_connection_string@ClientApi\Operations\ConnectionStrings.cs /}
please rearrange the panel:

* add a bullet, name it after the name of the relevant connection string definition (that you removed from the now-desist "Configurations" panel), and add the definition under it.  
* add another bullet, call it "code sample", and place the code sample under it.  

e.g. -  

* `SqlConnectionString`  
   {CODE:csharp sql_connection_string@ClientApi\Operations\ConnectionStrings.cs /}  
* **Code Sample**  
   {CODE add_sql_connection_string@ClientApi\Operations\ConnectionStrings.cs /}  

please do this with all the panels, so each of them contains its connection string definition and code sample.

2022-01-24 17:31 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/add-connection-string.dotnet.markdown
> +**Secure servers**
please make this a note, and if possible in your opinion place the note at the bottom of the panel.

2022-01-24 17:36 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/add-connection-string.dotnet.markdown
> +Be sure that the node definition in the connection string has the "s" in https:
remove it from here and place it as a comment to the HTTPS line within the code sample

2022-01-24 17:40 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/add-connection-string.dotnet.markdown
> +{PANEL/}
this is the {PANEL/} of a {PANEL:} that was never declared, so the page just shows it as text.

2022-01-24 17:46 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/get-connection-string.dotnet.markdown
> +# Operations: How to Get Connection String
please apply the same structural changes described in the comments to add-connection-string.
let me know if you need me to clarify.

2022-01-25 11:37 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/add-connection-string.dotnet.markdown
> +## Syntax
Done.  I just hope it isn't already referenced somewhere...

2022-01-26 06:23 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/add-connection-string.dotnet.markdown
> +* You can add a connection string by using **PutConnectionStringOperation**.
done

2022-01-26 06:36 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/add-connection-string.dotnet.markdown
> +* This article explains how to define the properties needed to connect to an external database.
Changed 'explains' to 'demonstrates'.

2022-01-26 06:39 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/add-connection-string.dotnet.markdown
> +---
I don't see why, but it doesn't matter much.  The sections are also divided by panels

2022-01-26 06:40 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/add-connection-string.dotnet.markdown
> +###Configurations
Don't see why and I can't.  It's part of the table of contents.

2022-01-26 06:42 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/add-connection-string.dotnet.markdown
> +{PANEL: }
That makes sense.

2022-01-26 06:54 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/add-connection-string.dotnet.markdown
> +## Example - Add Sql Connection String
I disagree. This format is better because it allows us to control the size of the subheadings, which is important when a section is long and needs to have sub-sub headings.  The ## method looks almost identical to the panel title method, but it gives us more flexibility. Putting them in panel definitions is also harder to find in the markdown than ##.  Someone some time ago decided that using the panel title is the way, but it doesn't have to be, and probably shouldn't.  

For example, in [this time series article](https://ravendb.net/docs/article-page/5.3/csharp/document-extensions/timeseries/overview#overview) some of the sub-sub headings are bigger than the headings and for some reason the background is almost white, making the contrast weak between the text and the background.  This makes reading more strenuous, especially for people with certain vision impairments.  We should be careful about placing long notes or panels inside panels for this reason...

2022-01-26 07:48 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/add-connection-string.dotnet.markdown
> +{CODE add_sql_connection_string@ClientApi\Operations\ConnectionStrings.cs /}
I did this but used sub-headings instead of bullets.

2022-01-26 07:51 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/add-connection-string.dotnet.markdown
> +**Secure servers**
It's a good idea to add it as a note, but it isn't a special case.  Almost everyone uses secure servers.  I shouldn't put it at the bottom because then they'll get into code and forget to pass the certificates.

2022-01-26 08:00 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/add-connection-string.dotnet.markdown
> +This can be done easily in the RavenDB Studio -> Server Management -> Certificates view.
There is a link in the sentence above.

2022-01-26 08:01 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/add-connection-string.dotnet.markdown
> +Be sure that the node definition in the connection string has the "s" in https:
Done

2022-01-26 08:01 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/add-connection-string.dotnet.markdown
> +{PANEL/}
fixed

2022-01-26 08:11 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/get-connection-string.dotnet.markdown
> +# Operations: How to Get Connection String
Done

2022-01-26 08:14 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/add-connection-string.dotnet.markdown
> +## Syntax
please check it, and if there are references there from anywhere in this document or others, change them.
this request appeared in the previous connection strings issue as well, are you still missing some comments?
to change existing references search for the link to the existing title (ctrl-F -> **entire solution** -> "find all") the link (**client-api/operations/maintenance/connection-strings/add-connection-string#syntax**) and replace it with the new one.

2022-01-26 08:16 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/add-connection-string.dotnet.markdown
> +---
read on to understand why.

2022-01-26 08:16 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/add-connection-string.dotnet.markdown
> +###Configurations
read on to understand why.

2022-01-26 08:30 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/add-connection-string.dotnet.markdown
> +## Example - Add Sql Connection String
* this is a panel title (or it will be when you change it to one as requested), not a sub anything.
* there is no difference between a reference to a ## title and a panel title, and this format is not the one 
   we're normally using, it looks strange, and there is no reason for it.
* there is nearly no difference in length between "Add Sql Connection String" and "Add an Sql Connection 
   String", and the latter is in english.
* the difference between different panels is good enough, and separating different segments is what they exist 
  for. you can, if you want, include every connection string and task creation couple a panel of their own instead 
  of separating them to a connection string creation panel and a task creation panel, but not add an out-of-panel 
  title.

2022-01-26 08:34 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/add-connection-string.dotnet.markdown
> +{CODE add_sql_connection_string@ClientApi\Operations\ConnectionStrings.cs /}
the advantage in bullets is the indentation of the two segments beyond their titles so the reader can easily see that they belong to the same "story".

2022-01-26 08:38 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/add-connection-string.dotnet.markdown
> +**Secure servers**
it is "special" in the sense that it's an extension of the main issue, a comment on it.

2022-01-26 08:47 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/add-connection-string.dotnet.markdown
> +This can be done easily in the RavenDB Studio -> Server Management -> Certificates view.
the link is to the general article, it'd be nice if the "certificates view" was a link to the specific place in the article you're referring to, e.g. server/security/authentication/certificate-management#studio-certificates-management-view

2022-01-26 13:58 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/add-connection-string.dotnet.markdown
> +## Syntax
Done

2022-01-26 14:00 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/add-connection-string.dotnet.markdown
> +## Example - Add Sql Connection String
We discussed this in on Zoom.

2022-01-26 14:01 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/add-connection-string.dotnet.markdown
> +{CODE add_sql_connection_string@ClientApi\Operations\ConnectionStrings.cs /}
I see.

2022-01-26 14:05 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/add-connection-string.dotnet.markdown
> +**Secure servers**
ok

2022-01-26 14:05 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/add-connection-string.dotnet.markdown
> +This can be done easily in the RavenDB Studio -> Server Management -> Certificates view.
ok

2022-01-26 16:56 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/get-connection-string.dotnet.markdown
> +* You can get connection strings by using the [**GetConnectionStringsOperation** method](../../../../client-api/operations/maintenance/connection-strings/get-connection-string#getconnectionstringsope
[**GetConnectionStringsOperation** method](../../../../client-api/operations/maintenance/connection-strings/get-connection-string#getconnectionstringsoperation) 
-> 
[GetConnectionStringsOperation](../../../../client-api/operations/maintenance/connection-strings/get-connection-string#getconnectionstringsoperation) method

2022-01-26 17:03 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/get-connection-string.dotnet.markdown
> +* This article explains how to configure the properties for the `GetConnectionStringOperation` method
remove "This article explains how to configure the properties for the `GetConnectionStringOperation` method"

2022-01-26 17:09 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/get-connection-string.dotnet.markdown
> +
`* `To learn how to `**Create**` a connection string see: `[Add Connection String](../../../../client-api/operations/maintenance/connection-strings/add-connection-string)`.

2022-01-26 17:28 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/get-connection-string.dotnet.markdown
> +## GetConnectionStringsOperation
almost none of the contents references work, and the names of the examples are different from the names of the sections they refer to. did you run through your finalization procedure?
we said we'll minimize the changes here, but this is half done.

* use the conventional structure: separate this section from the top section by a separation line, and make it a panel.
* actually create three panels:  
   * first panel for GetConnectionStringsOperation  
   * a second panel for the class definitions (you can name it "definitions")  
   * a third panel for the two code samples.

2022-01-26 17:31 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/get-connection-string.dotnet.markdown
> +| Connection String Type | Return Value |  | Description |
either make the first column broader (add hyphens to the line under it) or change "Connection String Type" to "type" (to match the "type" it returns).

2022-01-26 17:37 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/get-connection-string.dotnet.markdown
> +
add short explanations.
A **Raven** connection string:
An **SQL** connection string:
An **OLAP** connection string:
An **Elasticsearch** connection string:
A **generic** connection string:

2022-01-26 17:39 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/get-connection-string.dotnet.markdown
> +#### Generic `ConnectionString`
remove the "Generic", it's a class definition' that's its name.
the line you add to precede it will explain it's generic.

2022-01-26 17:42 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/add-connection-string.dotnet.markdown
> +* You can add a connection string by using the [**PutConnectionStringOperation** method](../../../../client-api/operations/maintenance/connection-strings/add-connection-string#putconnectionstringoper
the bolded text doesn't look like a link.

change:
**PutConnectionStringOperation** method](../../../../client-api/operations/maintenance/connection-strings/add-connection-string#putconnectionstringoperation)

to:
[PutConnectionStringOperation](../../../../client-api/operations/maintenance/connection-strings/add-connection-string#putconnectionstringoperation) method

2022-01-26 17:45 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/add-connection-string.dotnet.markdown
> +* Standard properties (name, database location, password) are explained here.
remove this bullet. you don't really explain any of the properties, and if you did you'd have to mention what you don't explain as well.

2022-01-26 17:49 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/add-connection-string.dotnet.markdown
> + This can be done easily in the RavenDB Studio -> Server Management -> [Certificates view](../../../../server/security/authentication/certificate-management#enabling-communication-between-servers-imp
this link needs to take you to the certificate view, not the general explanation (that's already covered in the first link)

2022-01-26 17:50 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/add-connection-string.dotnet.markdown
> +{PANEL: Add a Sql Connection String}
an Sql

2022-01-26 17:54 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/add-connection-string.dotnet.markdown
> +To connect to a cloud instance, see the [Olap ETL article](../../../../server/ongoing-tasks/etl/olap#section-1).
"To learn how to connect a cloud instance.."
you don't connect when you go there, you just learn how to. look for similar errors, i caught a few without searching for them so you may find more when you do look for them.

2022-01-27 13:00 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/get-connection-string.dotnet.markdown
> +* You can get connection strings by using the [**GetConnectionStringsOperation** method](../../../../client-api/operations/maintenance/connection-strings/get-connection-string#getconnectionstringsope
Done.

2022-01-27 13:03 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/get-connection-string.dotnet.markdown
> +
Done

2022-01-27 13:12 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/get-connection-string.dotnet.markdown
> +## GetConnectionStringsOperation
I've had to change the titles so frequently that I lost track...
I like your idea for contents organization.  It's simple and it all works.

2022-01-27 13:18 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/get-connection-string.dotnet.markdown
> +| Connection String Type | Return Value |  | Description |
Widening it didn't work, so I changed it to type.  I assume they won't get it confused with int and string or even bool.  

I didn't know how to label it and preferred leaving it blank to mis-informing.  I asked Aviv.

2022-01-27 13:28 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/get-connection-string.dotnet.markdown
> +#### Generic `ConnectionString`
Done

2022-01-27 13:28 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/add-connection-string.dotnet.markdown
> +* You can add a connection string by using the [**PutConnectionStringOperation** method](../../../../client-api/operations/maintenance/connection-strings/add-connection-string#putconnectionstringoper
ok

2022-01-27 13:30 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/add-connection-string.dotnet.markdown
> +* Standard properties (name, database location, password) are explained here.
Done

2022-01-27 13:36 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/add-connection-string.dotnet.markdown
> + This can be done easily in the RavenDB Studio -> Server Management -> [Certificates view](../../../../server/security/authentication/certificate-management#enabling-communication-between-servers-imp
It does take us to the certificate view.  I didn't think that putting this link twice was necessary, but I was told to, so I did.  I'll take out the upper link.

2022-01-27 13:42 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/add-connection-string.dotnet.markdown
> +{PANEL: Add a Sql Connection String}
Because arguing about the correct pronunciation of sql is a waste of time, I'll change it.  Both pronunciations are correct - esquel and sequel .

2022-01-27 13:43 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/add-connection-string.dotnet.markdown
> +* You can add a connection string by using the [**PutConnectionStringOperation** method](../../../../client-api/operations/maintenance/connection-strings/add-connection-string#putconnectionstringoper
Done

2022-01-27 13:47 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/add-connection-string.dotnet.markdown
> +To connect to a cloud instance, see the [Olap ETL article](../../../../server/ongoing-tasks/etl/olap#section-1).
ok

2022-01-30 12:36 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/add-connection-string.dotnet.markdown
> + This can be done easily in the RavenDB Studio -> Server Management -> [Certificates view](../../../../server/security/authentication/certificate-management#enabling-communication-between-servers-imp
the upper link is needed too, just to a different place. one is to the view, the other for the specific section.

2022-01-30 14:40 UTC, reebhub approved these changes

2022-01-30 14:51 UTC, aviv86 approved these changes

2022-01-31 16:49 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/operations/maintenance/connection-strings/add-connection-string.dotnet.markdown
> + This can be done easily in the RavenDB Studio -> Server Management -> [Certificates view](../../../../server/security/authentication/certificate-management#enabling-communication-between-servers-imp
ok

2022-02-11 15:05 UTC, merged