RDoc-1917 certificate-management -
ravendb/docs pull request #1413
Opened 2021-12-20 13:40 UTC by serezhub

Edited images. Clarified and improved the readability of texts.

2021-12-23 09:28 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +
from the links i checked, "Studio Certificate Management View" and "Export Cluster Certificates" don't work. 
Verify that all the links in your PR work.

2021-12-23 10:04 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +2. Select **Certificates**.
you can find a better format here: studio/database/settings/time-series-settings
where it says: 

1. **Time Series Settings View**  
    Select **Settings** > **Time Series** to open the Time Series Settings View.

2021-12-23 10:11 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +3. To enable servers to communicate, **generate** or **import** client certificates and **export** server certificate with these buttons.
that's extremely hard to understand. 
try to use the same form for all actions, all through this PR and your other pages:  **do X to achieve Y.**
with these two buttons for example, separate them (either using the same frame but as two different bullets, or in some other way) and instruct the reader what to do with each option. For the one titled "Client Certificate", the contents will be "Click to Generate or Import client certificates".

2021-12-23 11:12 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +{PANEL:The RavenDB Security Authorization Approach}
please revert the title to how it was. it may be linked to, and it's more accurate.

2021-12-23 11:14 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +allowed than RavenDB.  This is why access levels of RavenDB databases in each cluster are highly customizable by [cluster admins](../../../server/security/authorization/security-clearance-and-permiss
i fail to find anything in this new paragraph that isn't already explained in the existing text below.

2021-12-23 11:16 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +### Authorization
please remove the subtitle (btw subtitles should be in a different style than their mother titles, e.g. if the previous is ### this one should probably be ####, or a bold text)

2021-12-23 11:57 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +### Full Access to Database
separate from the part above (---)

2021-12-23 11:57 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +### Partial Access to Database
separate from the part above (---)

2021-12-23 12:00 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +#### *-Using ETL for selective, one-way data transfer-*
strange subtitles format, would probably look better as bolded text in a bullet list (and the text under each title will also be indented this way so it'll look less blockish).

2021-12-23 13:48 UTC, reebhub requested changes

2021-12-23 13:48 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +![Figure 2. Status of Registered Certificates](images/registered.png "Status of Registered Certificates")
how do you get to this page? please explain it here and wherever else is required (there are currently several other images here that show views without explaining how to get to them)

2021-12-23 13:48 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/studio/server/certificates/server-management-certificates-view.markdown
> +
please use the same format we normally use, with a note for the top page part. just open any other page with a contents for an example.

2021-12-23 13:48 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/studio/server/certificates/server-management-certificates-view.markdown
> +---
there is a lot to be fixed in this view, but please go through the fixes suggested for certificate-management.markdown first, after fixing the server article implement in this article everything you learned there you need to fix, recommit and ask for a review again.

2021-12-29 08:15 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +
Good catch.  Done.

2021-12-29 08:27 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +{PANEL:The RavenDB Security Authorization Approach}
Good point.  I checked it in Visual Studio and Google.  This is the only article that links to this title.  

The reason I changed it is because the title is misleading.  This section describes only one aspect of the RavenDB security approach - authorization and permissions via client certificate configurations.  This section doesn't discuss authentication, encryption, etc...So, I thought it's important to make sure that people know that authorization isn't the only security feature.

2021-12-29 08:58 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +3. To enable servers to communicate, **generate** or **import** client certificates and **export** server certificate with these buttons.
Good point.  I'm glad another person looked at this because I wouldn't have noticed that it wasn't clear to others.  I'll separate button instructions from now on, also when they have related functions.

2021-12-29 09:03 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +allowed than RavenDB.  This is why access levels of RavenDB databases in each cluster are highly customizable by [cluster admins](../../../server/security/authorization/security-clearance-and-permiss
No, I didn't duplicate it.  I cut/pasted it to the top.  It is easier to understand the details of anything once the big-picture summary has been stated.  That is why every article in the world has an intro.  Thus, I moved the summary to the top, added a sentence, and broke this long block of text into clear sections.

2021-12-29 09:05 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +### Authorization
It's not needed, but it separates the intro paragraph from the rest of the 'essay'.  
I'm leaving it because this helps with readability.

2021-12-29 09:23 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +### Full Access to Database
Done

2021-12-29 09:24 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +### Partial Access to Database
Done

2021-12-29 09:31 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +#### *-Using ETL for selective, one-way data transfer-*
I tried your idea, but it didn't work because only the first paragraph indented.  Bullet lists are made to be lists, not sub-headings.  
I took out the dashes - and left the #### size and italics to differentiate it from the rest of the text and from the parent subheading.  It looks professional and doesn't veer from any standards.

2021-12-29 09:45 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +In this manner, you can choose exactly what is exposed, including redacting personal information, hiding details, etc. Because the ETL process is unidirectional,
The current text was respected and I didn't take any info out.  I needn't make any changes here. I simply reorganized it to help it make more sense to the reader.  There was only one paragraph about read-only and I left it there verbatim, adding links in the list above to make clarification easier.  

In the original document, the second paragraph is about ETL, not read-only certificates, so I moved it up to the subheading area about ETLs.  That makes that section much more clear and prevents confusion about why ETLs are discussed when we're talking about User Access Levels.  

I am adding a summary statement that helps the reader transition to the next section.

2021-12-29 11:24 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +In the Studio Certificates Management view, we can see a list of registered client certificates and their status.
Done.

2021-12-29 11:27 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +you can grant different access levels by using different client certificates, each with its own set of permissions.
Good point.  I did this using line spacing instead of list format.  

I summarized the 'essay' above to make sure that people understand the logic if they didn't read the essay.

2021-12-29 11:45 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +1. Name
I thought that the titles were self-explanatory, but I bolded each title and gave a brief description below.

2021-12-29 11:50 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +3. Allowed databases and access level for each database
I added the link to security clearance levels, but 'thickening the explanations' would just add text to explanations that are already very clear.

2021-12-29 11:54 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
>  This information is used by RavenDB internally and is not stored in the certificate itself.
Done

2021-12-29 12:02 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +![Figure 2. Status of Registered Certificates](images/registered.png "Status of Registered Certificates")
I explained it in the intro to the 'List of Registered Certificates' section before the image.

In all of the documentation, after we show the whole screen view and how to get there, when we show steps or options within that view, we don't show the image with the whole screen because:

1. Readers have already gotten to the 'parent' view with the introductory image, and are focused on the instructions that follow in each option.
2. Sometimes showing the whole scene makes it hard to see important details, especially when the GUI opens a new window, when there are a lot of options, or when it's a long process.

2021-12-29 12:05 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/studio/server/certificates/server-management-certificates-view.markdown
> +
I assume you're referring to the "---" that shouldn't be there.  Yeah.  I already fixed that earlier today.  It was there from the article I copied to make this one.  Also, because I added another sentence to the intro, I added bullet points.

2021-12-30 08:19 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/studio/server/certificates/server-management-certificates-view.markdown
> +---
Done.

2022-01-02 10:34 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +
the note is very fluffy, combining background, suggestions and persuasion we're the good guys.
these preface notes are meant simply to state, very concisely, what the main points of an article are.

please make it so. any background explanations and suggestive notes can be placed in a new panel (make it the first panel) that you can name "Certificate Management" after the article to clarify it contains general explanations.

2022-01-02 10:36 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +  Each client certificate can be configured to specify which databases it can access and its authorization clearance level.
the second sentence ("Each client..") is very unclear. try to avoid using "it" in general, in the current sentence it's unclear what "it" refers to.

2022-01-02 10:40 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +* You can read about the logic and rationale behind RavenDB's client certificates in [The RavenDB Security Authorization Approach](../../../server/security/authentication/certificate-management#the-r
less familiarity will probably help. more like "Read more about.. here:.."

2022-01-02 10:46 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +* RavenDB provides an intuitive certificates management GUI in the Studio which is the focus of this article.
add a link to the Studio article that discusses it.
remove the "which is the focus of this article". the whole purpose of the note's short points is to clarify what the focus of the article is.

2022-01-02 10:47 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +* All of the operations which are described below are also available in the client API.
leave here only the first sentence. move the details to the new background panel (or someplace else?)

2022-01-02 10:56 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
>  # Authentication: Certificate Management
it's hard to review your markdowns when the sentences go beyond the boundary of the screen. in general, please wrap your lines so reviewers would be able to simply go down the text.

2022-01-02 10:58 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +  - There are CLI-based means to [generate](../../../server/security/authentication/client-certificate-usage#example-i---using-the-ravendb-cli) and [configure client certificates in Windows](../../..
it's hard to connect the introducing sentence ("All of the operations..") to the three items following it. 
in the new background panel, please phrase the sub-bullets as facts related to the client API (or remove them from this list of client-API-related items).

2022-01-02 11:00 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +
if you follow the comments given so far, it will also shorten your preface note (which is currently extremely cluttered).

2022-01-02 11:07 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +3. **Client certificate**
what is the connection between the title (client certificates) and the bullets under it?
- add the required action ("click to select:" or whatever the action is)
- list each sub-option as a title and its contents

2022-01-02 11:08 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +4. **Server certificates**
same here

2022-01-02 11:09 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +5. Status of current server certificate. You can click [Renew now](../../../server/security/authentication/certificate-renewal-and-rotation) here.
"You can click Renew now here" to gain what? phrase as action item, explain what clicking it is for.

2022-01-02 11:13 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +Client certificates are managed by RavenDB directly and not through any PKI infrastructure. If you want to remove
explain/link - what is PKI?

2022-01-02 11:19 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +* [Cluster Admin](../../../server/security/authorization/security-clearance-and-permissions#cluster-admin)  Full administrative access to cluster and databases within.
break the lines between titles and contents

2022-01-02 11:44 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +Exposing some part of the data or exposing read-only access is something that is commonly needed.
"is something that is commonly needed" is a little awkward. replace with "often needed" or "a practice that is commonly needed" or something else that sounds better,

2022-01-02 11:48 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +The way that the HR system looks at those operations is very different. Perhaps the HR manager needs a client certificate with read/write permission to edit documents on the HR database,
is there any way to make this wall of text less wally? line breaks, links, bold text, whatever - in it's current shape it is somewhat uninviting.

2022-01-02 11:52 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +In that case, set up an [ETL](../../../server/ongoing-tasks/etl/basics) process from the source data to the destination.
"granting it access" - avoid using "it", find a way to tell explicitly what/who the access is granted to.

2022-01-02 11:54 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +by [generating a separate certificate](../../../server/security/authentication/certificate-management#generate-client-certificate) for that purpose and granting it access to a _different_ database.
"generating a separate certificate" - unclear what the "separate" means here

2022-01-02 12:02 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +You can also do this by giving a client certificate a [User](../../../server/security/authorization/security-clearance-and-permissions#user) security clearance.
here and in various other places, you speak about certificates as if they are the entities that permissions are given to, while in fact they are the means by which permissions are given. please go through your text, find references to certificates, and make sure this point is clear.

2022-01-02 12:24 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +![Figure 1. Studio Certificates Management View](images/studio-certificates-overview.png "Studio Certificates Management View")
give 3 & 4 separate frames (when you edit the image you can move the "client certificate" button a little to the left to make room)

2022-01-02 12:30 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
>  The Read-Only access level allows reading data and performing queries on a particular database, but
this block should probably be added to the "read-only" bullet, as its contents. and maybe divided a little differently to make it a little less blockish, like maybe a line break before "Indexes cannot.." and before "Learn more about..".

2022-01-02 12:36 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +![Figure 2. Status of Registered Certificates](images/registered.png "Status of Registered Certificates")
looks good with the new image, just change the frames color to blue (your explanations are info)

2022-01-02 12:39 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +![Figure 3. Generate Client Certificate](images/generate.png "Generate Client Certificate")
how do you get here?

2022-01-02 12:52 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +   * If you choose *User* security clearance, you can give access to specific databases on the server and configure [User](../../../server/security/authorization/security-clearance-and-permissions#us
would probably look better without the bulltet (just as the contents of #3)

2022-01-02 12:56 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +1. Name
go through texts for action item drops (in this image, the next one, and wherever else is needed) and make sure they are phrased as action item instructions.
e.g. - 
1. **Name**  
    Enter Client Certificate Name

2022-01-02 13:06 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +2. Select **Certificates**.
Done

2022-01-02 13:10 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +![Figure 2. Status of Registered Certificates](images/registered.png "Status of Registered Certificates")
Done

2022-01-02 13:23 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +
Done

2022-01-02 13:32 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +  Each client certificate can be configured to specify which databases it can access and its authorization clearance level.
Odd...There's only one subject in this sentence 'Each client certificate'.  'It' is confusing when talking about two different things.  I can change 'it' to 'the certificate', though that is repetitive.

2022-01-02 13:37 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +* You can read about the logic and rationale behind RavenDB's client certificates in [The RavenDB Security Authorization Approach](../../../server/security/authentication/certificate-management#the-r
Done

2022-01-02 13:39 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +* RavenDB provides an intuitive certificates management GUI in the Studio which is the focus of this article.
OK...that was a transition to the next bullet point (where you can learn about Command Line means of configuring client certs).  It isn't necessary, so I took it out.

2022-01-02 13:40 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +* All of the operations which are described below are also available in the client API.
I moved them both to the new panel before starting with the studio view, for those who prefer CLI.

2022-01-02 13:40 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
>  # Authentication: Certificate Management
ok

2022-01-02 13:48 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +  - There are CLI-based means to [generate](../../../server/security/authentication/client-certificate-usage#example-i---using-the-ravendb-cli) and [configure client certificates in Windows](../../..
I changed the intro from "API" to "CLI".

2022-01-02 13:56 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +3. **Client certificate**
Done

2022-01-02 13:56 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +4. **Server certificates**
done

2022-01-02 14:07 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +5. Status of current server certificate. You can click [Renew now](../../../server/security/authentication/certificate-renewal-and-rotation) here.
Done

2022-01-02 14:14 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +Client certificates are managed by RavenDB directly and not through any PKI infrastructure. If you want to remove
Linked.

2022-01-03 06:57 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +* [Cluster Admin](../../../server/security/authorization/security-clearance-and-permissions#cluster-admin)  Full administrative access to cluster and databases within.
done

2022-01-03 07:10 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +Exposing some part of the data or exposing read-only access is something that is commonly needed.
Good point.  I rewrote it.
"To protect data, developers often need to expose only portions of the database or to provide read-only access."

2022-01-03 07:25 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +The way that the HR system looks at those operations is very different. Perhaps the HR manager needs a client certificate with read/write permission to edit documents on the HR database,
I broke up the paragraphs and added bold intros to two of them.

2022-01-03 07:38 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +In that case, set up an [ETL](../../../server/ongoing-tasks/etl/basics) process from the source data to the destination.
"It" refers to the certificate which is given access to a specific database.  Each certificate is configured with access to specified databases when "User" authorization levels are chosen.

2022-01-03 07:42 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +by [generating a separate certificate](../../../server/security/authentication/certificate-management#generate-client-certificate) for that purpose and granting it access to a _different_ database.
It's good that a second person is reviewing this.  I also found this sentence now, but because by the time I started editing, I already understood this essay, my mind glossed over the awkwardness.  

I clarified 'generate a separate client certificate' and I changed "different database" to "a dedicated, exposed database".

2022-01-03 09:03 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +You can also do this by giving a client certificate a [User](../../../server/security/authorization/security-clearance-and-permissions#user) security clearance.
I clarified it at the intro and in most of the text it is clear that the certificates are configured to give varying levels of access.

2022-01-03 09:20 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +![Figure 1. Studio Certificates Management View](images/studio-certificates-overview.png "Studio Certificates Management View")
Done

2022-01-03 09:21 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
>  The Read-Only access level allows reading data and performing queries on a particular database, but
Good point.  I changed the paragraph to a bullet list.

2022-01-03 10:54 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +![Figure 3. Generate Client Certificate](images/generate.png "Generate Client Certificate")
Good point.  Done.

2022-01-03 12:27 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +   * If you choose *User* security clearance, you can give access to specific databases on the server and configure [User](../../../server/security/authorization/security-clearance-and-permissions#us
Fixed

2022-01-03 12:44 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +1. Name
Done

2022-01-04 13:30 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authentication/certificate-management.markdown
> +6. Status of current client certificates active in this server. You can remove or [edit client certificates](../../../server/security/authentication/certificate-management#edit-certificate),
line break before "You can remove or.."

2022-01-05 14:50 UTC, reebhub approved these changes

2022-01-11 11:35 UTC, merged