Including revisions
ravendb/docs pull request #1437
Opened 2022-02-07 06:43 UTC by reebhub

2022-02-13 16:02 UTC, omerlewitz requested changes

2022-02-13 18:21 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/session/revisions/including.markdown
> +- [Including Revisions With `session.Load`](../../../client-api/session/revisions/including#including-revisions-with-session.load)
done

2022-02-13 18:21 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/session/revisions/including.markdown
> +- [Including Revisions With `session.Query`](../../../client-api/session/revisions/including#including-revisions-with-session.query)
done

2022-02-13 18:27 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/session/revisions/including.markdown
> +* To include **a Group of revisions** by their change vectors:
you mean "change vector"? it's basically capitalized in main titles and links and uncapitalized everywhere else. that's fine.

2022-02-13 18:50 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/session/revisions/including.markdown
> +   - [By Date](../../../client-api/session/revisions/including#raw-query-include-revisions-by-date)
changed to "time" or "creation time" wherever needed

2022-02-13 18:50 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/session/revisions/including.markdown
> +To include a **single revision** by its **creation date**, pass `IncludeRevisions` the date.
"date" changed to "time" or "creation time" wherever needed

2022-02-14 13:08 UTC, omerlewitz approved these changes

2022-02-14 13:56 UTC, ayende commented on Documentation/5.2/Raven.Documentation.Pages/client-api/how-to/handle-document-relationships.dotnet.markdown
> +# Client API: How to Handle Document Relationships
Why is this here? Does this relates to the include revisions PR?

2022-02-14 13:56 UTC, ayende commented on Documentation/5.2/Raven.Documentation.Pages/client-api/session/revisions/including.markdown
> +* If no revisions exist, an empty `IncludeRevisions` object will be returned.
No, we'll remember that no such revision exists and skip going to the server when you ask for it, returning `null`

2022-02-15 09:11 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/how-to/handle-document-relationships.dotnet.markdown
> +# Client API: How to Handle Document Relationships
yes, there's an "Includes" section in it that references the different kinds of includes, added revisions to the list

2022-02-15 09:14 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/session/revisions/including.markdown
> +* If no revisions exist, an empty `IncludeRevisions` object will be returned.
done

2022-02-15 19:15 UTC, closed without merging

2022-02-15 19:16 UTC, ppekrol commented
New PR: https://github.com/ravendb/docs/pull/1447