RDoc-2097-Apply database configuration settings - new doc
ravendb/docs pull request #1450
Opened 2022-02-17 09:33 UTC by serezhub

2022-02-17 10:53 UTC, maciejaszyk requested changes

2022-02-17 10:53 UTC, maciejaszyk commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/configuration/database-settings-operation.markdown
> +  only take effect when a database is loading or enabled.  See [code sample](../../../../client-api/operations/maintenance/configuration/database-settings-operation#toggledatabasesstateoperation) bel
`only take effect when a database is loading or enabled.`

Configuration is loaded only on startup and it is persisted in memory. A reboot is required for the changes to take effect.

2022-02-17 10:53 UTC, maciejaszyk commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/configuration/database-settings-operation.markdown
> +| `PutDatabaseSettingsOperation` | `string` | `store.Database, settings` | Saves new database settings |
Type -> `void`

arguments:
`Database name`, `Dictionary<string, string>`

2022-02-17 10:53 UTC, maciejaszyk commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/configuration/database-settings-operation.markdown
> +| `ToggleDatabasesStateOperation` | `bool` | `store.Database, disable: true` | Disables database |
Type: 
![image](https://user-images.githubusercontent.com/86351904/154460213-85653aae-4eed-4418-a8dc-572ab7f847b7.png)


Arguments: `database name`, `state of database(bool)`

2022-02-17 10:53 UTC, maciejaszyk commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/configuration/database-settings-operation.markdown
> +| `ToggleDatabasesStateOperation` | `bool` | `store.Database, disable: false` | Enables (reloads) database to apply saved settings |
delete

2022-02-17 10:53 UTC, maciejaszyk commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/configuration/database-settings-operation.markdown
> +| `GetDatabaseSettingsOperation` | `string` | `store.Database`, `Assert.NotNull(settings)` | Shows newly configured settings |
Type `DatabaseSettings` 
![image](https://user-images.githubusercontent.com/86351904/154460576-e69ecadd-48d3-4f34-999a-b0503d095ddf.png)


Args: same as `Put`

2022-02-17 10:53 UTC, maciejaszyk commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/configuration/database-settings-operation.markdown
> +| `ToggleDatabasesStateOperation` | `bool` | `store.Database, disable: true` | Disables database |
`Disables database` -> `enable/disable database`

2022-02-17 10:53 UTC, maciejaszyk commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/configuration/database-settings-operation.markdown
> +* `ToggleDatabasesStateOperation` disables/enables database to apply new settings because changes
`disables/enables database` this is true
`to apply new settings because changes....` -> it could be used to...

2022-02-17 17:15 UTC, serezhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/configuration/database-settings-operation.markdown
> +  only take effect when a database is loading or enabled.  See [code sample](../../../../client-api/operations/maintenance/configuration/database-settings-operation#toggledatabasesstateoperation) bel
Done

2022-02-17 17:16 UTC, serezhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/configuration/database-settings-operation.markdown
> +| `PutDatabaseSettingsOperation` | `string` | `store.Database, settings` | Saves new database settings |
I refactored the whole syntax area according to our Slack conversation.

2022-02-17 17:17 UTC, serezhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/configuration/database-settings-operation.markdown
> +| `ToggleDatabasesStateOperation` | `bool` | `store.Database, disable: false` | Enables (reloads) database to apply saved settings |
I included it in the refactored syntax area.  It seems important to be clear that we need both `true` and `false`, in case users don't read the intro section.

2022-02-17 17:18 UTC, serezhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/configuration/database-settings-operation.markdown
> +| `GetDatabaseSettingsOperation` | `string` | `store.Database`, `Assert.NotNull(settings)` | Shows newly configured settings |
Done

2022-02-17 17:19 UTC, serezhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/configuration/database-settings-operation.markdown
> +* `ToggleDatabasesStateOperation` disables/enables database to apply new settings because changes
Done

2022-02-21 08:51 UTC, serezhub commented on Documentation/5.1/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/ClientConfig.cs
> +            */
That was already there.  This sample file feeds code to all of the API/operations/maintenance/configuration docs, including the PutClientConfigurtion doc.

2022-02-21 08:52 UTC, serezhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/configuration/database-settings-operation.markdown
> + | `PutDatabaseConfigurationSettingsCommand` | Saves settings (must still disable -> enable to apply new configurations) |
Done

2022-02-21 10:35 UTC, maciejaszyk commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/configuration/database-settings-operation.markdown
> + | Return Type | Description |
delete  `PutDatabaseConfigurationSettingsCommand` . This is internal class invisible for users.

2022-02-21 10:35 UTC, maciejaszyk commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/configuration/database-settings-operation.markdown
> + | `DisableDatabaseToggleResult` | `true` disables database. Then enable it to reboot quickly |
``true` disables database. Then enable it to reboot quickly`  This class contains information on what happened on the server.

2022-02-21 10:35 UTC, maciejaszyk commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/configuration/database-settings-operation.markdown
> + | `settings` | View new database configuration settings |
``settings`` -> `DatabaseSettings`

2022-02-21 10:35 UTC, maciejaszyk commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/configuration/database-settings-operation.markdown
> + | `DisableDatabaseToggleResult` | `true` disables database. Then enable it to reboot quickly |
So make the desc more generic.
![image](https://user-images.githubusercontent.com/86351904/154937226-bfb526c5-75fd-4307-bbf1-6270e4b8f7ed.png)

2022-02-21 10:35 UTC, maciejaszyk commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/configuration/database-settings-operation.markdown
> +| `Dictionary<string, string> configurationSettings` | `string` | Pass configuration settings. |
`| `Dictionary<string, string> configurationSettings` | `string` | Pass configuration settings. |`

to

`|  `Configuration Settings` | `Dictionary<string, string>` | Pass configuration settings. |`

2022-02-21 10:35 UTC, maciejaszyk commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/configuration/database-settings-operation.markdown
> + | `DisableDatabaseToggleResult` | `true` disables database. Then enable it to reboot quickly |
So you can write "result of operation" etc I think

2022-02-21 10:42 UTC, serezhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/configuration/database-settings-operation.markdown
> + | Return Type | Description |
Done

2022-02-21 10:44 UTC, serezhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/configuration/database-settings-operation.markdown
> + | `DisableDatabaseToggleResult` | `true` disables database. Then enable it to reboot quickly |
Done

2022-02-21 10:45 UTC, serezhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/configuration/database-settings-operation.markdown
> + | `settings` | View new database configuration settings |
OK.  I saw both in the tests and src code.  
I changed it to DatabaseSettings

2022-02-21 10:47 UTC, serezhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/configuration/database-settings-operation.markdown
> +| `Dictionary<string, string> configurationSettings` | `string` | Pass configuration settings. |
Done

2022-02-21 11:56 UTC, maciejaszyk approved these changes

2022-02-24 12:27 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/configuration/database-settings-operation.markdown
> +  * The next line should give the argument `false` to enable the database, thus applying the changes that were saved.
move these explanations about `ToggleDatabasesStateOperation` to its panel, here it should be listed with a bried description like the other options.

2022-02-24 12:29 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/configuration/database-settings-operation.markdown
> +
close the last two bullets in an info box

2022-02-24 12:32 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/configuration/database-settings-operation.markdown
> +
change the structure.
create three panels, each called after its option.
in the contents include only references to the three panels.
include two parts in each panel: syntax, and sample.

2022-02-24 12:55 UTC, serezhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/configuration/database-settings-operation.markdown
> +  * The next line should give the argument `false` to enable the database, thus applying the changes that were saved.
Done

2022-02-24 13:03 UTC, serezhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/configuration/database-settings-operation.markdown
> +
If you're referring to the following, I just removed them.  They're repeated in the sample code area. 
* The first line should give the argument `true` so that the database is disabled.  
  * The next line should give the argument `false` to enable the database, thus applying the changes that were saved.

2022-02-24 13:04 UTC, serezhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/configuration/database-settings-operation.markdown
> +
If you're referring to the following, I just removed them.  They're repeated in the sample code area. 
* The first line should give the argument `true` so that the database is disabled.  
  * The next line should give the argument `false` to enable the database, thus applying the changes that were saved.

2022-02-24 13:56 UTC, serezhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/configuration/database-settings-operation.markdown
> +
Done.  
BTW, the explanation sentences about each option were already in both the intro and at the beginning of each code sample.

2022-02-27 11:13 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/configuration/database-settings-operation.markdown
> +
i'm referring to the bullets i'm commenting on, "Database settings can.." and "After editing & saving..".

2022-02-27 11:39 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/configuration/database-settings-operation.markdown
> +This provides a dictionary of newly configured settings.
This applies..

2022-02-27 11:54 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/configuration/database-settings-operation.markdown
> +The following sample shows how to apply new database configurations with `ToggleDatabasesStateOperation`.
The following sample uses `ToggleDatabasesStateOperation` to toggle the database **off** and **on** again, to apply a new database configuration.

2022-02-27 11:59 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/configuration/database-settings-operation.markdown
> +  * The next line should give the argument `false` to enable the database, thus applying the changes that were saved.
remove these two lines ("The first.." and "The next line.."). they speak of a first line and a second line that aren't the first or the second, and in general aren't needed.

2022-02-27 12:01 UTC, reebhub commented on Documentation/5.1/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/ClientConfig.cs
> +                        // The following two lines are needed to disable/enable the database so that the changes take effect
// The following two lines are needed to disable/enable the database so that the changes take effect -->
// Toggle the database OFF

2022-02-27 12:03 UTC, reebhub commented on Documentation/5.1/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/ClientConfig.cs
> +                        store.Maintenance.Server.Send(new ToggleDatabasesStateOperation(store.Database, disable: false));
precede the second call to `ToggleDatabasesStateOperation` with a comment:
// Enable the database

2022-02-27 12:07 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/configuration/database-settings-operation.markdown
> +This provides a dictionary of newly configured settings.
what do you mean by "provides"? provides the user? provides the database?
probably should be something like "use `GetDatabaseSettingsOperation` to get the current database configuration"

2022-02-27 12:59 UTC, serezhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/configuration/database-settings-operation.markdown
> +
Done

2022-02-27 16:31 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/configuration/database-settings-operation.markdown
> +Get a dictionary only of newly configured settings.
--> Use `GetDatabaseSettingsOperation` to retrieve the newly configured database settings.

2022-02-27 21:56 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/configuration/database-settings-operation.markdown
> +{CODE signature-PutConfigurationSettings@ClientApi\Operations\ClientConfig.cs /}
you are explaining the syntax of PutDatabaseSettingsOperation but are showing the definition of "PutConfigurationSettings", a method that is defined and used by one of our tests.
you need to provide the signature of PutDatabaseSettingsOperation here, NOT PutConfigurationSettings. it is:
PutDatabaseSettingsOperation(string databaseName, Dictionary<string, string> configurationSettings)

then the parameters you explain below make sense.

2022-02-27 22:04 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/configuration/database-settings-operation.markdown
> +
the contents of your "Parameters" columns needs to be the parameter name.
use the names from the signature i added above:
* databaseName
* configurationSettings

2022-02-27 22:13 UTC, reebhub commented on Documentation/5.1/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/ClientConfig.cs
> +                    static void PutConfigurationSettings(DocumentStore store, Dictionary<string, string> settings)
you are explaining the syntax of PutDatabaseSettingsOperation but are showing the definition of "PutConfigurationSettings", a method that is defined and used by one of our tests and isn't relevant for users.
you need to provide the signature of PutDatabaseSettingsOperation here, NOT PutConfigurationSettings. it is:
PutDatabaseSettingsOperation(string databaseName, Dictionary<string, string> configurationSettings)

then the parameters you currently explain in the markdown below this signature make sense.

2022-02-27 22:16 UTC, reebhub commented on Documentation/5.1/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/ClientConfig.cs
> +                    store.Maintenance.Server.Send(new ToggleDatabasesStateOperation(store.Database, disable: true));
this is not a signature, it is a line that uses the method.
the signature is:
ToggleDatabasesStateOperation(string databaseName, bool disable)

2022-02-27 22:17 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/configuration/database-settings-operation.markdown
> +
you need to provide the parameter NAMES in the parameters column. they are:
* databaseName
* disable

2022-02-27 22:19 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/configuration/database-settings-operation.markdown
> +
the signature is wrong. added a comment with the right signature to the cs file.

2022-02-27 22:21 UTC, reebhub commented on Documentation/5.1/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/ClientConfig.cs
> +                        store.Maintenance.Server.Send(new ToggleDatabasesStateOperation(store.Database, disable: true));
replace this with:
`var result = store.Maintenance.Server.Send(new ToggleDatabasesStateOperation(store.Database, true));`

2022-02-27 22:23 UTC, reebhub commented on Documentation/5.1/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/ClientConfig.cs
> +                        store.Maintenance.Server.Send(new ToggleDatabasesStateOperation(store.Database, disable: false));
replace this with:
`store.Maintenance.Server.Send(new ToggleDatabasesStateOperation(store.Database, false));`

2022-02-27 22:28 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/configuration/database-settings-operation.markdown
> +{CODE signature-GetDatabaseSettingsOperation@ClientApi\Operations\ClientConfig.cs /}
this is not the method's signature. see comment for cs file.

2022-02-27 22:30 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/configuration/database-settings-operation.markdown
> +| Database name | `string` | Select database to view its new settings. |
* change the parameter name to: `databaseName`

2022-02-27 22:30 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/configuration/database-settings-operation.markdown
> + | `DatabaseSettings` | View new database configuration settings |
add below the table the definition for `DatabaseSettings`

2022-02-27 22:39 UTC, reebhub commented on Documentation/5.1/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/ClientConfig.cs
> +                    var settings = store.Maintenance.Send(new GetDatabaseSettingsOperation(store.Database));
this is not the method's signature. the signature is: 
`public GetDatabaseSettingsOperation(string databaseName)`

2022-02-27 22:48 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/configuration/database-settings-operation.markdown
> +{CODE signature-PutConfigurationSettings@ClientApi\Operations\ClientConfig.cs /}
* add a title: 
  ---
  Syntax
* this is not the method signature. added the signature in a comment to the cs file.

2022-02-27 22:51 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/configuration/database-settings-operation.markdown
> +The following sample shows how to use `PutDatabaseSettingsOperation` in the context of a generic database configuration.
* add a title: 
  ```
   ---
  Sample
```

* "The following sample shows how to use `PutDatabaseSettingsOperation` in the context of a generic database configuration." -->
  The following sample shows how to use `PutDatabaseSettingsOperation` to set the database configuration.

2022-02-27 22:53 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/configuration/database-settings-operation.markdown
> +{CODE signature-PutConfigurationSettings@ClientApi\Operations\ClientConfig.cs /}
this is not the method's signature. added the right signature in a comment to the cs file.

2022-02-27 22:54 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/configuration/database-settings-operation.markdown
> +The following sample shows how to use `PutDatabaseSettingsOperation` in the context of a generic database configuration.
"The following sample shows how to use `PutDatabaseSettingsOperation` in the context of a generic database configuration." -->
The following sample shows how to use `PutDatabaseSettingsOperation` to set the database configuration.

2022-02-27 22:56 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/configuration/database-settings-operation.markdown
> +
add titles: 
```
---
Syntax
---
Sample
```

2022-02-27 22:57 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/configuration/database-settings-operation.markdown
> +Get a dictionary only of newly configured settings.
add titles: 
```
---
Syntax
---
Sample
```

2022-03-01 11:51 UTC, reebhub approved these changes

2022-03-01 13:16 UTC, merged