RDoc-2101-AddOrPatch-
ravendb/docs pull request #1460
Opened 2022-03-08 12:51 UTC by serezhub

Moved the markdown from 5.0 to 5.1, where the p…Moved the markdown from 5.0 to 5.1, where the patch feature is new

2022-03-10 20:40 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/patching/single-document.dotnet.markdown
> +For example, they can be used in a loop that is activated whenever a user looks at a product on a site
please remove this addition (the paragraph from "For example" to "IO usage").

2022-03-10 20:41 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/patching/single-document.dotnet.markdown
> +We can assume that there are many viewed items, so using a patch reduces the amount of trips to the server.
please remove this addition (the paragraph from "For example" to "IO usage").

2022-03-10 20:56 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/patching/single-document.dotnet.markdown
> +`Session.Advanced.AddOrPatch`
please conform to the structure of all other examples.
either add the name of the used method to them all or remove it from here.

2022-03-10 21:15 UTC, reebhub commented on Documentation/5.1/Samples/csharp/Raven.Documentation.Samples/Blog.cs
> +﻿using System;
why is this file included in this PR?

2022-03-10 21:15 UTC, reebhub commented on Documentation/5.1/Samples/csharp/Raven.Documentation.Samples/Blog.cs
> +﻿using System;
why is this file included in this PR?

2022-03-10 21:16 UTC, reebhub commented on Documentation/5.1/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/Patches/PatchRequests.cs
> +                    session.Delete(id);
why is deleting the session included in the region we show?

2022-03-10 21:18 UTC, reebhub commented on Documentation/5.1/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/Patches/PatchRequests.cs
> +                    #endregion
why is deleting the session (and saving the session again) included in the region?

2022-03-10 21:36 UTC, reebhub commented on Documentation/5.1/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/Patches/PatchRequests.cs
> +                    session.Advanced.AddOrPatch<Order, DateTime>(
i don't see Order defined anywhere (no Order class defined locally or included), did you actually run this patch?

2022-03-10 21:40 UTC, reebhub commented on Documentation/5.1/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/Patches/PatchRequests.cs
> +                    id,
you didn't add the method signature or parameters, but you can at least comment here and explain what is what (what is the ID, what is patched)

2022-03-10 21:43 UTC, reebhub commented on Documentation/5.1/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/Patches/PatchRequests.cs
> +                    x => x.RequireAt, new DateTime(2022, 9, 12));
comment, explain, what is this?

2022-03-10 22:02 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/patching/single-document.dotnet.markdown
> +{CODE Add_Or_Patch_Sample@ClientApi\Operations\PatchRequests.cs /}
add a **Session-syntax-untyped** sample (how to perform this operation using `session.Advanced.Defer`) and an **Operations-syntax** sample (how to perform it using `store.Operations.Send`), in the same three-tabs structure as in most other samples.

2022-03-14 08:11 UTC, serezhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/patching/single-document.dotnet.markdown
> +We can assume that there are many viewed items, so using a patch reduces the amount of trips to the server.
Done

2022-03-14 08:41 UTC, serezhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/patching/single-document.dotnet.markdown
> +`Session.Advanced.AddOrPatch`
removed.  it's the second line of the sample

2022-03-14 08:43 UTC, serezhub commented on Documentation/5.1/Samples/csharp/Raven.Documentation.Samples/Blog.cs
> +﻿using System;
Some of the samples have fields that need to be defined in blog.cs.  It needed to be moved up from the older version or else it throws.

2022-03-14 08:44 UTC, serezhub commented on Documentation/5.1/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/Patches/PatchRequests.cs
> +                    #endregion
It was in the slow test.
@omerlewitz - Should we remove this line from the sample?

2022-03-14 10:30 UTC, serezhub commented on Documentation/5.1/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/Patches/PatchRequests.cs
> +                    x => x.RequireAt, new DateTime(2022, 9, 12));
None of the examples in this article include the signature/parameters table.
If we want consistency in this article, it means that I'd need to do that for 15 different patches.  
That's a super-deep dive!  
I'll happily do it, but do you think it's worth it?

2022-03-14 14:48 UTC, serezhub commented on Documentation/5.1/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/Patches/PatchRequests.cs
> +                    #endregion
I took the last two lines out.

2022-03-15 06:08 UTC, serezhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/patching/single-document.dotnet.markdown
> +`Session.Advanced.AddOrPatch`
Removed the last two lines.

2022-03-15 06:09 UTC, serezhub commented on Documentation/5.1/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/Patches/PatchRequests.cs
> +                    #endregion
Removed the last two lines.

2022-03-15 06:20 UTC, serezhub commented on Documentation/5.1/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/Patches/PatchRequests.cs
> +                    session.Advanced.AddOrPatch<Order, DateTime>(
None of the other examples have class definitions.  
The class is defined in northwind.cs, which the docs use to insert northwind variables as examples.  None of the definitions have #region statements (though there is one around the whole document for some reason).  

Omer said that it was obvious that this is a class definition for the variables.

2022-03-15 06:21 UTC, serezhub commented on Documentation/5.1/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/Patches/PatchRequests.cs
> +                    x => x.RequireAt, new DateTime(2022, 9, 12));
None of the other examples have signatures and descriptions individually.  Instead, the signatures are defined above.

2022-03-15 06:22 UTC, serezhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/patching/single-document.dotnet.markdown
> +{CODE Add_Or_Patch_Sample@ClientApi\Operations\PatchRequests.cs /}
Omer checked with Grisha who said that we shouldn't have an untyped example in this case.

2022-03-17 07:12 UTC, serezhub commented on Documentation/5.1/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/Patches/PatchRequests.cs
> +                    session.Advanced.AddOrPatch<Order, DateTime>(
All of the examples here pull their definitions from Northwind.cs and none of them show the definition.  Omer says that the definition is obvious and unnecessary.  If we want to, we can add a whole section that defines the class components that are used on this page.  I wonder if it makes sense to define them for each example (it would make this article crazy-long).  
I'm fine with doing either if you'd like, I just wonder if it would make it better for the users.

2022-03-17 07:13 UTC, serezhub commented on Documentation/5.1/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/Patches/PatchRequests.cs
> +                    x => x.RequireAt, new DateTime(2022, 9, 12));
The signatures and descriptions for all of the examples are in the syntax section above.

2022-03-17 07:14 UTC, serezhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/patching/single-document.dotnet.markdown
> +{CODE Add_Or_Patch_Sample@ClientApi\Operations\PatchRequests.cs /}
Omer checked with Grisha who said that there is no untyped version...that we should leave it as-is.

2022-03-20 09:15 UTC, omerlewitz requested changes

2022-03-20 09:15 UTC, omerlewitz commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/patching/single-document.dotnet.markdown
> +
We need to add another sample adding to an existing array -https://github.com/ravendb/ravendb/blob/73ea69110cf9a6922abd9183c5e61ce0117bfa52/test/SlowTests/Core/Session/AddOrPatch.cs#L77

2022-03-20 09:15 UTC, omerlewitz commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/patching/single-document.dotnet.markdown
> +
What about `AddOrIncrement` ? 
https://github.com/ravendb/ravendb/blob/73ea69110cf9a6922abd9183c5e61ce0117bfa52/test/SlowTests/Core/Session/AddOrPatch.cs#L178

2022-03-20 09:15 UTC, omerlewitz commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/patching/single-document.dotnet.markdown
> +
The signatures of the methods should be added
https://github.com/ravendb/ravendb/blob/73ea69110cf9a6922abd9183c5e61ce0117bfa52/src/Raven.Client/Documents/Session/IAdvancedSessionOperations.Patch.cs#L38

2022-03-24 11:29 UTC, reebhub commented on Documentation/5.1/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/Patches/PatchRequests.cs
> +                    session.Advanced.AddOrPatch<Order, DateTime>(
doesn't matter as long as the sample works and doesn't rely on things that the user isn't aware of and wouldn't be able to reproduce

2022-03-24 11:31 UTC, reebhub commented on Documentation/5.1/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/Patches/PatchRequests.cs
> +                    x => x.RequireAt, new DateTime(2022, 9, 12));
"since you don't show the method signature or explain its parameters in the article" doesn't imply you should, but explains why adding comments is important.

2022-03-28 14:05 UTC, serezhub commented on Documentation/5.1/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/Patches/PatchRequests.cs
> +                    session.Advanced.AddOrPatch<Order, DateTime>(
ok

2022-03-29 06:57 UTC, omerlewitz approved these changes

2022-03-29 08:52 UTC, serezhub commented on Documentation/5.1/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/Patches/PatchRequests.cs
> +                    x => x.RequireAt, new DateTime(2022, 9, 12));
done

2022-03-29 08:52 UTC, serezhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/patching/single-document.dotnet.markdown
> +
done

2022-03-29 08:52 UTC, serezhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/patching/single-document.dotnet.markdown
> +
done

2022-03-29 08:52 UTC, serezhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/patching/single-document.dotnet.markdown
> +
done

2022-03-29 09:12 UTC, omerlewitz approved these changes

2022-03-29 10:07 UTC, reebhub requested changes

2022-03-29 10:07 UTC, reebhub commented on Documentation/5.1/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/Patches/PatchRequests.cs
> +                    // Lambda describing the path to the field and value to be added.
just "the path to the edited property, and the value to be added"

2022-03-29 10:07 UTC, reebhub commented on Documentation/5.1/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/Patches/PatchRequests.cs
> +                // Save session changes to complete the patch.
remove the comment

2022-03-29 10:07 UTC, reebhub commented on Documentation/5.1/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/Patches/PatchRequests.cs
> +            #endregion
end the region earlier, after SaveChanges

2022-03-29 10:07 UTC, reebhub commented on Documentation/5.1/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/Patches/PatchRequests.cs
> +            {   // Add new values to an existing array in users/1-A
basically the same changes requested for "Add_Or_Increment_Sample"

2022-03-29 10:07 UTC, reebhub commented on Documentation/5.1/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/Patches/PatchRequests.cs
> +                     #region Add_Or_Patch_Sample
requested a few changes for "Add_Or_Increment_Sample", some can be implemented here too

2022-03-29 10:30 UTC, serezhub commented on Documentation/5.1/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/Patches/PatchRequests.cs
> +                // Call method and specify <entity type, field type>, then (document ID.
done

2022-03-29 10:40 UTC, serezhub commented on Documentation/5.1/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/Patches/PatchRequests.cs
> +            {   // Increment LoginCount in users/1-A by 1
done

2022-03-29 10:41 UTC, serezhub commented on Documentation/5.1/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/Patches/PatchRequests.cs
> +                        FirstName = "Hibernating",
done

2022-03-29 10:41 UTC, serezhub commented on Documentation/5.1/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/Patches/PatchRequests.cs
> +                        LastName = "Rhinos",
done

2022-03-29 10:41 UTC, serezhub commented on Documentation/5.1/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/Patches/PatchRequests.cs
> +                    // Lambda describing the path to the field and value to be added.
done

2022-03-29 10:41 UTC, serezhub commented on Documentation/5.1/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/Patches/PatchRequests.cs
> +                // Save session changes to complete the patch.
done

2022-03-29 10:41 UTC, serezhub commented on Documentation/5.1/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/Patches/PatchRequests.cs
> +            #endregion
done

2022-03-29 10:41 UTC, serezhub commented on Documentation/5.1/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/Patches/PatchRequests.cs
> +                     #region Add_Or_Patch_Sample
done for all 3 samples

2022-03-30 09:58 UTC, serezhub commented on Documentation/5.1/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/Patches/PatchRequests.cs
> +            {   // Add new values to an existing array in users/1-A
done

2022-04-01 10:14 UTC, reebhub approved these changes

2022-04-03 09:44 UTC, merged