RDoc-2037-Added links for each section, lines between QAs, license re…
ravendb/docs pull request #1479
Opened 2022-04-11 13:21 UTC by serezhub

…newal QA

2022-04-24 13:38 UTC, garayx approved these changes

2022-04-24 13:38 UTC, garayx commented on Documentation/5.1/Raven.Documentation.Pages/server/security/common-errors-and-faq.markdown
> +If you are getting the following error you must update the RavenDB server. This bug is fixed as of build 4.0.3-patch-40033.
I guess we can drop this line, there should be no users that are using RavenDB with version older that 4.2

2022-04-24 13:38 UTC, garayx commented on Documentation/5.1/Raven.Documentation.Pages/server/security/common-errors-and-faq.markdown
> +* [After installing with Let's Encrypt, can I change the DNS records?](../../server/security/common-errors-and-faq#after-installing-with-lets-encrypt-can-i-change-the-dns-records)
some of those are not related to Setup Wizard Issues

2022-04-25 06:45 UTC, serezhub commented on Documentation/5.1/Raven.Documentation.Pages/server/security/common-errors-and-faq.markdown
> +* [After installing with Let's Encrypt, can I change the DNS records?](../../server/security/common-errors-and-faq#after-installing-with-lets-encrypt-can-i-change-the-dns-records)
Which ones? These all seem to be about setting up security.  
Do you mean that they're also relevant to manual setup and not Wizard?  
If this is what you meant, I can change the link name to "Security Setup Issues", but it would mean changing the link in a few other docs that link here as well.  I just want to be sure that this is what you mean first.

2022-04-25 06:48 UTC, serezhub commented on Documentation/5.1/Raven.Documentation.Pages/server/security/common-errors-and-faq.markdown
> +If you are getting the following error you must update the RavenDB server. This bug is fixed as of build 4.0.3-patch-40033.
Good point.  I took it out because this is a 5.1+ doc.

2022-05-01 07:13 UTC, garayx commented on Documentation/5.1/Raven.Documentation.Pages/server/security/common-errors-and-faq.markdown
> +* [After installing with Let's Encrypt, can I change the DNS records?](../../server/security/common-errors-and-faq#after-installing-with-lets-encrypt-can-i-change-the-dns-records)
1. `After installing with Let's Encrypt, can I change the DNS records?`
2. `Can I change the (private) IP address RavenDB binds to?`
3. `The Let's Encrypt certificate is about to expire but doesn't renew automatically`
4. `What should I do when my license expires?`


Those are not related to **Setup Wizard Issues** (both wizard/manual setup)

2022-05-01 07:19 UTC, garayx commented
Please add a link to this page to Setup Examples articles, [Running in a Docker Container](https://ravendb.net/docs/article-page/5.3/csharp/start/installation/running-in-docker-container) article.

2022-05-01 10:39 UTC, serezhub commented on Documentation/5.1/Raven.Documentation.Pages/server/security/common-errors-and-faq.markdown
> +* [After installing with Let's Encrypt, can I change the DNS records?](../../server/security/common-errors-and-faq#after-installing-with-lets-encrypt-can-i-change-the-dns-records)
Done

2022-05-10 11:56 UTC, reebhub requested changes

2022-05-10 11:56 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/server/security/common-errors-and-faq.markdown
> +In this page, we review some of the common security configuration errors and explain how to handle them.
* apply the regular structure (top note, make the current first line an introduction bullet and start it with "this article discusses" or something similar to avoid duplicity, add an "in this page" bullet for the table of contents, etc.)
* make sure the main issues are addressed in the related articles section

2022-05-10 11:56 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/server/security/common-errors-and-faq.markdown
> +* **Setup.Mode" must be "LetsEncrypt**
half `**` half `"`, doesn't look right.
don't know if Grammarly checks these things, make sure you run it in any case (both with the VS text and with the text generated by the browser)

2022-05-11 08:38 UTC, serezhub commented on Documentation/5.1/Raven.Documentation.Pages/server/security/common-errors-and-faq.markdown
> +In this page, we review some of the common security configuration errors and explain how to handle them.
Done

2022-05-11 08:49 UTC, serezhub commented on Documentation/5.1/Raven.Documentation.Pages/server/security/common-errors-and-faq.markdown
> +* **Setup.Mode" must be "LetsEncrypt**
done

2022-05-11 11:04 UTC, reebhub approved these changes

2022-05-12 10:57 UTC, merged