RDoc-2174-Unit Tests - explained initialization and updated sample comments
ravendb/docs pull request #1488
Opened 2022-04-25 11:47 UTC by serezhub

Especially related to ConfigureServer( )

2022-05-06 13:08 UTC, arekpalinski approved these changes

2022-05-10 08:25 UTC, reebhub commented on Documentation/4.2/Raven.Documentation.Pages/start/test-driver.dotnet.markdown
>  TestDriver uses an [Embedded](../server/embedded) package with the same set of [prerequisites](../server/embedded#prerequisites) to run the Server.
the same set of prerequisites as what?

2022-05-10 09:42 UTC, reebhub requested changes

2022-05-10 09:42 UTC, reebhub commented on Documentation/4.2/Raven.Documentation.Pages/start/test-driver.dotnet.markdown
> +You can use it with `TestServerOptions` to change the path to the Raven server binaries, specify data storage path, security, adjust .NET framework versions, etc.
the "security," floats there in a universe of its own

2022-05-10 09:42 UTC, reebhub commented on Documentation/4.2/Raven.Documentation.Pages/start/test-driver.dotnet.markdown
get everything inside the note out of it, make it two bullets (`condigureServer`.. and If it..)
remove the ">" and make the quote blue text

2022-05-10 09:42 UTC, reebhub commented on Documentation/4.2/Raven.Documentation.Pages/start/test-driver.dotnet.markdown
>  {INFO /}
"See the complete list of.." see it where?

2022-05-10 09:42 UTC, reebhub commented on Documentation/4.2/Samples/csharp/Raven.Documentation.Samples/Start/RavenDBTestDriver.cs
> +                FrameworkVersion = "3.1.15+", // Look for newest version on machine including 3.1.15 and any newer patches, but not major new releases (default is .NET version at time of server relea
* place all the notes here above the code lines they refer to
* break the notes to shorter lines so the reader doesn't have to scroll the scree
* add line breaks between the code lines (make it three pairs, each pair a note and beneath it the code it relates to)

2022-05-10 09:42 UTC, reebhub commented on Documentation/4.2/Raven.Documentation.Pages/start/test-driver.dotnet.markdown
>  #### .NET FrameworkVersion
why is .NET FrameworkVersion discussed so thoroughly here, and simply by copying the very text it links to in the end?
move the "TestServerOptions" info box here, and place two bullets in it: the first with the current `TestServerOptions` explanation, and the second with just a clear reference to where `.NET FrameworkVersion` is already explained.

2022-05-10 09:42 UTC, reebhub commented on Documentation/4.2/Raven.Documentation.Pages/start/test-driver.dotnet.markdown
> +
a previous comment referred to a similar pre-sample text, please implement it here as well,

2022-05-10 13:04 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/start/test-driver.dotnet.markdown
> +In this section, we will explain how to use [RavenDB.TestDriver](https://www.nuget.org/packages/RavenDB.TestDriver/) in order to write unit tests for working with RavenDB.
done

2022-05-10 13:04 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/start/test-driver.dotnet.markdown
>  TestDriver uses an [Embedded](../server/embedded) package with the same set of [prerequisites](../server/embedded#prerequisites) to run the Server.
done

2022-05-10 13:05 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/start/test-driver.dotnet.markdown
> +We'll be using [xunit](https://www.nuget.org/packages/xunit/) for the test framework in the below example.
done

2022-05-10 13:05 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/start/test-driver.dotnet.markdown
> +> Note that the test itself is meant to show different capabilities of the test driver and is not meant to be the most efficient.
done

2022-05-10 13:05 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/start/test-driver.dotnet.markdown
> +In the test, we get an IDocumentStore to our test database. Deploy an index and insert two documents into it.
done

2022-05-10 13:05 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/start/test-driver.dotnet.markdown
> +We then wait for the indexing to complete and launch the Studio so we can verify that the documents
done

2022-05-10 13:05 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/start/test-driver.dotnet.markdown
> +You can use it with `TestServerOptions` to change the path to the Raven server binaries, specify data storage path, security, adjust .NET framework versions, etc.
done

2022-05-10 13:05 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/start/test-driver.dotnet.markdown
done

2022-05-10 13:05 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/start/test-driver.dotnet.markdown
>  #### .NET FrameworkVersion
done

2022-05-10 13:06 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/start/test-driver.dotnet.markdown
> +
done

2022-05-10 13:08 UTC, serezhub commented on Documentation/4.2/Samples/csharp/Raven.Documentation.Samples/Start/RavenDBTestDriver.cs
> +                FrameworkVersion = "3.1.15+", // Look for newest version on machine including 3.1.15 and any newer patches, but not major new releases (default is .NET version at time of server relea
done.

2022-05-10 13:56 UTC, reebhub commented on Documentation/4.2/Raven.Documentation.Pages/start/test-driver.dotnet.markdown
> +In this section, we explain how to use [RavenDB.TestDriver](https://www.nuget.org/packages/RavenDB.TestDriver/) to write RavenDB unit tests.
* make it a bullet
* add line break at the end

2022-05-10 14:09 UTC, reebhub commented on Documentation/4.2/Raven.Documentation.Pages/start/test-driver.dotnet.markdown
indent the note, it's not with its bullet

2022-05-10 14:19 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/start/test-driver.dotnet.markdown
> +TestDriver uses an [Embedded](../server/embedded) package with the same set of [prerequisites](../server/embedded#prerequisites) as embedded servers to run the Server.
done

2022-05-10 14:25 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/start/test-driver.dotnet.markdown
> +In this section, we explain how to use [RavenDB.TestDriver](https://www.nuget.org/packages/RavenDB.TestDriver/) to write RavenDB unit tests.
done

2022-05-11 07:51 UTC, merged