RDoc-2128_Revisions
ravendb/docs pull request #1490
Opened 2022-04-28 03:53 UTC by reebhub

2022-04-28 06:11 UTC, karmeli87 commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/revert-revisions.markdown
> +  created for documents.
Not sure I follow this statement

2022-04-28 06:11 UTC, karmeli87 commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/revert-revisions.markdown
> +**Revert Revisions** is used to revert all the documents in the database
I would emphasis here `all the documents``

2022-04-28 06:11 UTC, karmeli87 commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/revert-revisions.markdown
> +     a new revision for the document that replicates the historical
the word `replicates` confused me for few moments :)

2022-04-28 06:11 UTC, karmeli87 commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/revert-revisions.markdown
> +   Documents will ve reverted to a revision that was created for them
typo `ve` -> `be`

2022-04-28 06:11 UTC, karmeli87 commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/revisions-and-other-features.dotnet.markdown
> +   * [Revisions and Data Subscriptions](../../document-extensions/revisions/revisions-and-other-features#revisions-and-data-subscriptions)
This is absolutely superb ! :)

2022-04-28 06:11 UTC, karmeli87 commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/revisions-and-other-features.dotnet.markdown
> +* A revision will **not** be created upon modifications to counter values.
Would put that as a first sentence

2022-04-28 06:11 UTC, karmeli87 commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/revert-revisions.markdown
> +## Related Articles
Missing section to mention Reverting of Coutners/Time-Series/Attachments
- for counters we can revert to the actual value at that time-point
- for time-series is tricky need to check what is the actual behavior
- for attachment we revert to the state of that point in time

2022-04-28 06:11 UTC, karmeli87 commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/revert-revisions.markdown
> +## Related Articles
probably put that section in `Revisions: Revisions and Other Features`

2022-04-28 09:56 UTC, reebhub commented on Documentation/4.0/Raven.Documentation.Pages/server/clustering/replication/replication.markdown
> +Replication consistency can be achieved using
ok, thx
i'll return it with a better explanation (if it took you a few read to understand it probably needs rephrasing)

2022-04-28 09:57 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/client-api/operations/configure-revisions.dotnet.markdown
> +    | **MinimumRevisionAgeToKeep** | [TimeSpan](https://docs.microsoft.com/en-us/dotnet/api/system.timespan) | Limit the Age of revisions kept per document. <br> `null` = no age limit | `null` |
are you sure? i sat with Aviv to check this and it seems like it behaves differently

2022-04-28 10:01 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/client-api/operations/conflict-revisions-configuration.markdown
> +* RavenDB can create revisions for document conflicts
yes we have an example in the Studio page with images of the kept revisions
here: studio/database/settings/document-revisions#editing-the-conflicting-document-defaults

2022-04-28 10:04 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/overview.markdown
> +field of more than 128 bytes is compressed.
i'll mention it.
can you make sure this text is true? i took it from an old document but have no way knowing how accurate it is

2022-04-28 10:06 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/revert-revisions.markdown
> +  created for documents.
i'll add an example
it means that if i created 100 revisions i'll be able to return to a closer date to what i want than if i created 5

2022-04-28 10:06 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/revert-revisions.markdown
> +     a new revision for the document that replicates the historical
i'll change it to "copy"

2022-04-28 10:08 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/revisions-and-other-features.dotnet.markdown
> +   * [Revisions and Data Subscriptions](../../document-extensions/revisions/revisions-and-other-features#revisions-and-data-subscriptions)
yay (o:

2022-04-28 10:22 UTC, karmeli87 commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/client-api/operations/configure-revisions.dotnet.markdown
> +    | **MinimumRevisionAgeToKeep** | [TimeSpan](https://docs.microsoft.com/en-us/dotnet/api/system.timespan) | Limit the Age of revisions kept per document. <br> `null` = no age limit | `null` |
Not sure here :-) If you checked that then all good

2022-04-30 13:05 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/client-api/operations/configure-revisions.dotnet.markdown
> +    | **MaximumRevisionsToDeleteUponDocumentUpdate** | `long` | The maximum number of revisions to delete upon document update. <br> `null` = no limit | `null` |
i found two tests that set this value explicitly to 100, and Studio suggests a value of 100 when a configuration is created using it (`"enter max revisions to delete (suggested: 100)`"), but i couldn't find where the default is set. 
can you please make sure there's such a default before i document it?

2022-04-30 23:14 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/client-api/operations/conflict-revisions-configuration.markdown
> +* RavenDB can create revisions for document conflicts
regarding RavenDB applying a conflict configuration by default, i added this bullet:

* RavenDB applies a conflict revisions configuration by default.
  You will only need to run the operation yourself if you want to disable the feature or change its characteristics (e.g. to modify the number of conflict revisions kept per document).

regarding the default value: i added a comment about it in the Studio article (`studio/database/settings/document-revisions#editing-the-conflicting-document-defaults`) since it's the only place there seems to be a default. 
i didn't find (maybe i'm just missing it) a default for the creation of a configuration via API (using either `ConfigureRevisionsOperation` or `ConfigureRevisionsForConflictsOperation`)

2022-05-01 00:30 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/client-api/operations/conflict-revisions-configuration.markdown
> +
added it in a new "Storage Considerations" section.

2022-05-01 00:55 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/overview.markdown
> +By default, the Revisions feature is **Disabled** for all collections: no revisions
thanks, done

2022-05-01 01:02 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/revert-revisions.markdown
> +**Revert Revisions** is used to revert all the documents in the database
done

2022-05-01 01:05 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/revert-revisions.markdown
> +   Documents will ve reverted to a revision that was created for them
fixed

2022-05-01 01:10 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/revisions-and-other-features.dotnet.markdown
> +* A revision will **not** be created upon modifications to counter values.
done

2022-05-01 14:53 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/client-api/operations/configure-revisions.dotnet.markdown
> +    | **MaximumRevisionsToDeleteUponDocumentUpdate** | `long` | The maximum number of revisions to delete upon document update. <br> `null` = no limit | `null` |
(resolved in a later discussion: defaults are not set for `RevisionsCollectionConfiguration` properties by either `ConfigureRevisionsOperation` or `ConfigureRevisionsForConflictsOperation`, except for `MinimumRevisionAgeToKeep` that is set by Studio when it creates a conflict revisions configuration)

2022-05-01 16:40 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/revert-revisions.markdown
> +## Related Articles
done (added a "reverted data" bit to the counters, time series, and attachments sections of the "revisions and other features" page)

2022-05-02 21:26 UTC, reebhub commented on Documentation/4.0/Raven.Documentation.Pages/server/clustering/replication/replication.markdown
> +Replication consistency can be achieved using
done

2022-05-04 20:25 UTC, Danielle9897 requested changes

2022-05-04 20:25 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/settings/document-revisions.markdown
> +        and time it accordingly.
remove comma:

purging, that
=>
purging that

2022-05-04 20:25 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/settings/document-revisions.markdown
> +  are defined for, explain the process, and allow you to proceed or cancel the operation.
=>
Clicking 'Enforce Configuration' will first pup-up the below confirmation dialog.
The dialog will list the collections that configurations are defined for, explain the process, and allow you to proceed or cancel the operation.

2022-05-04 20:25 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/settings/document-revisions.markdown
> +     configuration that applies to them.
...according to the default settings or to the collection-specific... 
=>
...according to the default settings or the collection-specific...

2022-05-04 23:34 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/revisions.markdown
> +  other uses.
done

2022-05-04 23:41 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/revisions.markdown
> +     that holds the revisions of deleted documents.
unlike most Studio pages, that describe a single view, this article describes two views. these bullets are meant to clarify this.
i changed the first line to: 

* The Studio views that this article describes are -

2022-05-04 23:49 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/revisions.markdown
> +revisions to the live document version.
"The document's" is wrong because it's right for every document, hence "a".
the second sentence emphasizes the creation of a new revision, which is done in rare occasions. this is mostly not what revisions are about. plus its written in passive terms and doesn't flow, and "live document version" is clearer than "the current document".  let's leave this as is.

2022-05-04 23:51 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/revisions.markdown
> +1. [document view](../../../studio/database/documents/document-view) > **Revisions tab**
done

2022-05-04 23:52 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/revisions.markdown
> +   Revisions are listed in the Revisions tab by their creation time signatures.
done

2022-05-04 23:54 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/revisions.markdown
> +   Click to create a new revision for this document.
done

2022-05-04 23:58 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/revisions.markdown
> +   Click to compare this revision with the current live version of this document.
"the current live version of this document" is easier to understand, and nicer to read (o:

2022-05-05 00:06 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/revisions.markdown
> +* **Click a revision time signature** to inspect the revision's contents.
"inspect" is better. the word explains why you should look at a revision, the place it takes you to allows more than viewing (you can also compare it with other revisions), and mainly it's the same term used later on in the "Revision Inspection" section (which is where this click takes you).

2022-05-05 00:16 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/revisions.markdown
> +![Revision Inspection](images/revisions/revision-inspection.png "Revision Inspection")
1. explained above why inspection is better
2. i don't understand where the arrow should be and what it is for.
    the top image explains that clicking a revision brings you here, the sentence below it says "click to inspect", and this image is named "Revision Inspection", plus the red label speaks for itself. more than this is just too much.

2022-05-05 00:23 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/revisions.markdown
> +   Click to create a document that replicates the revision's contents.
done (replicates  -> copies)

2022-05-05 00:24 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/revisions.markdown
> +  * [Revision Inspection](../../../studio/database/document-extensions/revisions#revision-inspection)
nope

2022-05-05 00:24 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/revisions.markdown
> +{PANEL: Revision Inspection}
nah

2022-05-05 00:27 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/revisions.markdown
> +3. **Revision Inspection Box**
nay (maybe "view" is better than "box" though, not sure.. left it as is, let's discuss "box" vs "view", or maybe some other term i didn't think of)

2022-05-05 00:30 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/revisions.markdown
> +
but this is just what the existing sentence says isn't it?

2022-05-05 00:35 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/revisions.markdown
> +a new revision for the document and move all its revisions to the revisions bin.
this is really unclear, and also inaccurate. the revisions aren't accessed from the deleted revision, it's simply the revision whose signature marks them.
changed it to:

Deleting a document that the Revisions feature is enabled for will:  

* Create a new revision for the document to mark its deletion.  
* Move all the document's revisions, including the deletion revision, 
  to the revisions bin.

2022-05-05 00:39 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/revisions.markdown
> +   Each item listed in the Revisions Bin view references all the revisions created for a deleted document.
this doesn't work

2022-05-05 00:42 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/revisions.markdown
> +3. **Selection Boxes**
done

2022-05-05 00:45 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/revisions.markdown
> +2. **Delete**
it actually works nicely as number 3.
easy to follow visually, and then you speak about deleting selected items right after explaining how to select them.

2022-05-05 00:52 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/revisions.markdown
> +5. **Deletion Revision Change Vector**
done

2022-05-05 00:53 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/revisions.markdown
> +   Change vector of the revision that was created for the document when it was deleted.
unclear.
added "the", though.
The change vector of the revision that was created for the document when it was deleted.

2022-05-05 00:54 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/revisions.markdown
> +6. **Deletion Date**
done

2022-05-05 00:56 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/revisions.markdown
> +them to the new document.
done

2022-05-05 00:57 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/revisions.markdown
> +the new one was created.
"deleted-revision" is a bad name because it implies that the revision itself is deleted, plus then you have to repeat "delete" twice. left it as is.

2022-05-05 01:54 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/revisions.markdown
> +       and cloned just like the revisions of a live document.
-->
"This is the ID of the document that was deleted.  
Click it to inspect the revisions created for this document (aka "orphaned revisions" because their parent document has 
been deleted)."

i added a "deletion revision" balloon to the current image, pointing at the deletion revision.

i think another panel will just clutter the explanation for no good reason, i don't see why the deletion revision should be emphasized that much? the only real info provided by clicking it is the deletion date, that is already available both in the revisions bin main view and in every change vector.

2022-05-08 08:04 UTC, Danielle9897 requested changes

2022-05-08 08:04 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/client-api/operations/conflict-revisions-configuration.markdown
> +     of revisions, no revisions will be created for conflicting documents.
are you sure about this?
we said that if a **collection-specific-configuration** (if defined) overrides the default conflict-config
(the regular default doesn't override the conflict one - as I remember)

2022-05-08 08:19 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/revisions.markdown
> +revisions to the live document version.
* The studio uses 'see the **current** document' on the button 
* here you use '**live**-document'
* and many places you use '**parent**-document'

maybe better to unify

2022-05-08 08:24 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/revisions.markdown
> +* **Click a revision time signature** to inspect the revision's contents.
yes and no

* you click the time signature to **view the revision**
* you can do revision-comparison **also from the parent document** by clicking the icon next to the revision timestamp -  so the 'inspection' is not only from the revision view

2022-05-08 08:30 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/revisions.markdown
> +![Revision Inspection](images/revisions/revision-inspection.png "Revision Inspection")
it is important to have such arrow/indication because (from experience) it can go unnoticed, as when you have a large monitor and it is all the way on the **far right side** (as opposed to the image here),
and - also - to differentiate (later) from a '**`deleted revision`**' label

and this is a `Revision View `
maybe you can relate the term 'inspection' to when you do the comparison - side by side 
but this is the view where you see the revision

2022-05-08 08:35 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/revisions.markdown
> +3. **Revision Inspection Box**
this is the revision content.
what is not clear ?
(this also relates to what we say above that this `content` is copied when you do clone)

2022-05-08 09:44 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/revisions.markdown
> +
I am just suggesting adding this sentence to the opening paragraph

2022-05-08 09:52 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/revisions.markdown
> +a new revision for the document and move all its revisions to the revisions bin.
pls just change:
deletion revision => `deleted-revision`

since that is also the (red) label we use in Studio

2022-05-08 09:56 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/revisions.markdown
> +   Each item listed in the Revisions Bin view references all the revisions created for a deleted document.
'marks' is not good - it doesn't mark the revisions created
if anything - then better to return the word `'references`' that was before.

2022-05-08 10:02 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/revisions.markdown
> +       and cloned just like the revisions of a live document.
ok
but change deletion-revision to ``deleted-revision``
to be in sync w/ Stuido

2022-05-08 10:06 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/revisions.markdown
> +the new one was created.
but this name (deleted-revision) is the name the UI shows this revision by - see images
ok - how about:
let's change from deleted-revision to `delete-revision`
and I'll change in Studio as well

2022-05-08 11:11 UTC, Danielle9897 requested changes

2022-05-08 11:11 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/revisions-and-other-features.dotnet.markdown
> +  [time series](../../document-extensions/timeseries/overview) values.
to time series values => to existing time series values

2022-05-08 16:47 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/revisions.markdown
> +revisions to the live document version.
"live document" seems more to the point here than "parent document" because it places the two entities we compare on the same level, as if the parent document were just another revision. in most other occasions "parent document" is indeed better,

2022-05-08 17:24 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/revisions.markdown
> +* **Click a revision time signature** to inspect the revision's contents.
"inspection" clarifies the role of this view, that includes more than just viewing, distinguishes it from other areas, and is closer to the spirit of what a trail of revisions is used for.
the document view can't be called "inspection area" because documents can be edited there, not just viewed/inspected.

2022-05-08 17:44 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/revisions.markdown
> +![Revision Inspection](images/revisions/revision-inspection.png "Revision Inspection")
added an explanation about the "revision" label

2022-05-08 17:54 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/revisions.markdown
> +3. **Revision Inspection Box**
* The revision's content, displayed in read-only mode.  
* box --> area

2022-05-08 18:12 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/revisions.markdown
> +a new revision for the document and move all its revisions to the revisions bin.
done, here and in the following image

2022-05-08 18:14 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/revisions.markdown
> +   Each item listed in the Revisions Bin view references all the revisions created for a deleted document.
--> indicates

2022-05-08 18:16 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/revisions.markdown
> +   Each item listed in the Revisions Bin view references all the revisions created for a deleted document.
done

2022-05-08 18:18 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/revisions.markdown
> +       and cloned just like the revisions of a live document.
done

2022-05-08 18:26 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/document-extensions/revisions.markdown
> +the new one was created.
done

2022-05-08 18:41 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/settings/document-revisions.markdown
> +  Revisions configuration.
not really. it's the one configuration that applies to the whole database.. one configuration to rule them all (o:

2022-05-08 18:43 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/settings/document-revisions.markdown
> +  Revisions configuration.
--> the Revisions configuration

2022-05-08 18:43 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/settings/document-revisions.markdown
> +  Revisions configuration.
tried, it doesn't work well

2022-05-08 18:45 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/settings/document-revisions.markdown
> +  [here](../../../document-extensions/revisions/overview#revisions-configuration).
done

2022-05-08 18:47 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/settings/document-revisions.markdown
> +      at the specified point in time or to the nearest revision preceding this time.
done

2022-05-08 18:51 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/settings/document-revisions.markdown
> +   server resources. Please read carefully the section dedicated to it.
done

2022-05-08 18:56 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/settings/document-revisions.markdown
> +   will override them for the collection it is defined for.
done

2022-05-08 19:00 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/settings/document-revisions.markdown
> +The Revisions configuration can be comprised of default settings that apply to all
--> The Revisions configuration can include default settings that apply to all document collections, and/or configurations..

2022-05-08 19:02 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/settings/document-revisions.markdown
> +and enabled, the Revisions feature will remain disabled for all document collections.
done

2022-05-08 19:05 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/settings/document-revisions.markdown
> +  they are defined for.
done

2022-05-08 19:07 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/settings/document-revisions.markdown
> +
fixed

2022-05-08 19:18 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/settings/document-revisions.markdown
> +  interested in tracking document conflicts using revisions you can disable it.
done

2022-05-08 19:29 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/settings/document-revisions.markdown
> +   ![Limit By Number](images/revisions/define-default-settings_limit-by-number.png "Limit By Number")
done

2022-05-08 19:36 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/settings/document-revisions.markdown
> +   their parent document is modified.
--> If this limit is set and the number of revisions exceeds it, revisions will be purged (starting from the oldest revision) when their parent document is modified.

2022-05-08 19:40 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/settings/document-revisions.markdown
> +   ![Limit By Age](images/revisions/define-default-settings_limit-by-age.png "Limit By Age")
done

2022-05-08 19:43 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/settings/document-revisions.markdown
> +   Enable to set a Revisions age limit.
done

2022-05-08 19:44 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/settings/document-revisions.markdown
> +   when their parent document is modified.
done

2022-05-08 19:45 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/settings/document-revisions.markdown
> +      setting as well (read about it above).
done

2022-05-08 19:47 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/settings/document-revisions.markdown
> +5. Click **OK** to modify or create the default settings, or **Cancel**.
done

2022-05-08 19:48 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/settings/document-revisions.markdown
> +   to apply the new settings.
done

2022-05-08 19:51 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/settings/document-revisions.markdown
> +   the only difference is in the scope of both configurations.
why? it refers to the explanation, not the settings.

2022-05-08 19:51 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/settings/document-revisions.markdown
> +4. Click **OK** to modify or create the configuration, or **Cancel**.
done

2022-05-08 19:57 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/settings/document-revisions.markdown
> +     3. when the conflict is resolved by replacing the local document with the replicated one
changed it to the past tense, can't argue with the past (o:

In this case, **three** revisions were created:  
     1. when the replicated document arrived and entered a conflict state  
     2. when the local document entered a conflict state on the arrival of the replicated document  
     3. when the conflict was resolved by replacing the local document with the replicated one

2022-05-08 19:59 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/settings/document-revisions.markdown
> +     its collection-specific configurations.**
should remain "its" - the collection-specific configurations belong to the Revisions configuration

2022-05-08 20:04 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/settings/document-revisions.markdown
> +        and time it accordingly.
done

2022-05-08 20:07 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/settings/document-revisions.markdown
> +  are defined for, explain the process, and allow you to proceed or cancel the operation.
-->
* Clicking 'Enforce Configuration' will present a confirmation dialog that will list the collections that configurations are defined for, explain the process, and allow you to proceed or cancel the operation.

2022-05-08 20:11 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/settings/document-revisions.markdown
> +     configuration that applies to them.
done

2022-05-08 20:13 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/overview.markdown
> +  all and/or specific collections.
done

2022-05-08 20:17 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/overview.markdown
> +There is one Revisions configuration per database, stored in the database record.
there can be only one Revisions configuration per database, collection-specific configurations are a part of it.
(but i changed "one" to "a single")

2022-05-08 20:42 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/overview.markdown
> +     * [Revisions Configuration Properties](../../document-extensions/revisions/overview#revisions-configuration-properties)
done

2022-05-08 20:42 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/overview.markdown
> +#### Revisions Configuration Properties
done

2022-05-08 20:44 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/overview.markdown
> +  about the available configuration properties.
done

2022-05-08 20:45 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/overview.markdown
> +Default and collection-specific configurations are executed:
done

2022-05-08 20:45 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/overview.markdown
> +1. **When documents are Created, Modified, or Deleted**.
done

2022-05-08 20:46 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/overview.markdown
> +2. **When [Enforce Configuration](../../studio/database/settings/document-revisions#enforce-configuration) is applied**.
done

2022-05-08 20:46 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/overview.markdown
> +  When a document is created, modified, or deleted the configuration (either
done

2022-05-08 20:47 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/overview.markdown
> +   * Revisions will optionally be purged by limits set in the configuration.
done

2022-05-08 20:47 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/overview.markdown
> +    purging, that Enforcing Configuration will purge all at once.
done

2022-05-08 20:53 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/overview.markdown
> +  modification), or when the document is deleted.
seems like it's clear after all.. yes, that's how it works.
there is no revision for the document's contents before it was modified.
its first revision contains its contents after the modification.

2022-05-08 20:54 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/overview.markdown
> +     (Click the _See the current document_ button to return to the live document version.)
done

2022-05-08 21:12 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/overview.markdown
> +      Clicking the removed document's ID will show its revisions.
seems wrong.
all the revisions are moved to the revisions bin, not just the delete revision.
and the revisions are opened through the removed document's ID, not through the delete revision.
it's true that the delete-revision's change vector is listed, but that's just because it's the latest revision.
I'm leaving this more or less as it is, just adding the "delete-revision" reference.

5. **Delete the document**.  
   Though you removed the document, its **audit trail** is **not lost**.  
   all of its revisions remain, including a new revision (called **Delete-Revision**) indicating that the document was deleted.  

      To see the "orphaned" revisions (whose parent document was deleted) open the Studio `Documents > Revisions Bin` section.  
      Clicking the removed document's ID will show its revisions.

2022-05-08 21:30 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/overview.markdown
> +      ![Revisions Bin](images\revisions_revisions-bin.png "Revisions Bin")
i don't think that's how it works

2022-05-08 21:35 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/overview.markdown
> +   new one was created.
done (with "delete-revision")

2022-05-08 21:57 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/overview.markdown
> +  regular documents.
seems like we'll have to write it first..

2022-05-08 22:01 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/overview.markdown
> +     field of more than 128 bytes is compressed.
individual fields are compressed as they are compressed in regular documents: any text field of more than 128 bytes is compressed.

2022-05-08 22:05 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/overview.markdown
> +* A revision will be created even if the document was not modified.
* A revision **will** be created even if the Revisions feature is disabled for the document's collection.  
* A revision **will** be created even if the document was not modified.  
* A revision **will not** be created if the latest revision already contains the document's contents.

2022-05-08 22:13 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/revert-revisions.markdown
> +  a stored backup.
is understanding a document in its historical context related to comparing it with its current version?
if you revert the database to its state a year ago and open a document, you see it in its historical context.

2022-05-08 22:15 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/revert-revisions.markdown
> +  be reverted by this process.
done

2022-05-08 22:18 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/revert-revisions.markdown
> +* Documents created **after** the specified point in time will be **deleted**.
you mean, if the document was created with the ID of a document whose revisions are in the revisions bin?

2022-05-08 22:22 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/revert-revisions.markdown
> +     time, may be reverted to a revision newer than the specified time.
changed it to - 
.. Such documents, that were created **before** the specified point in time but all their revisions may have been created **after** that time, may be reverted ..

2022-05-08 22:32 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/revert-revisions.markdown
> +     a new revision for the document that copieschanged to "copies" the historical
hmm

To revert a document to one of its revisions, RavenDB will create a new revision for the document that copies the historical revision, effectively replacing the live version of the document.

2022-05-08 22:33 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/revert-revisions.markdown
> +   Make sure that a [Revisions configuratio](../../document-extensions/revisions/overview#revisions-configuration)
seems like i was exercising my French here

2022-05-08 22:35 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/client-api/session/loading.dotnet.markdown
> +| **pageSize** | int | The metadata for how many revisions to retrieve per page |
fixed

2022-05-08 22:42 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/client-api/session/including.markdown
> +any of its included revisions will retrieve them from memory rather than from the server.
When it is known prior to the retrieval of a document that its revisions may be needed, the revisions can be **Included** with the document when the document is loaded, and stored locally.  

[Loading](../../../../document-extensions/revisions/client-api/session/loading) a revision that was included with the document will retrieve it from memory rather than require an additional trip to the server.

2022-05-08 22:43 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/client-api/operations/configure-revisions.dotnet.markdown
> +* A Revisions configuration is comprised of Default settings and/or Collection-specific configurations.
A Revisions configuration includes Default settings and/or Collection-specific configurations.

2022-05-08 22:47 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/client-api/operations/conflict-revisions-configuration.markdown
> +     of revisions, no revisions will be created for conflicting documents.
i tried it..
i disabled the default settings, and conflict revisions were not created.

2022-05-08 22:49 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/revisions-and-other-features.dotnet.markdown
> +  [counter](../../document-extensions/counters/overview) values.
done

2022-05-08 22:50 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/revisions-and-other-features.dotnet.markdown
> +  [time series](../../document-extensions/timeseries/overview) values.
done

2022-05-09 07:36 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/overview.markdown
> +      ![Revisions Bin](images\revisions_revisions-bin.png "Revisions Bin")
Orphaned Revisions => Click to see all orphaned revisions

2022-05-09 07:43 UTC, Danielle9897 commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/settings/document-revisions.markdown
> +     its collection-specific configurations.**
yes - the collection-specific configurations belong to the Revisions configuration - but here you are referring to the 
Revisions configuration's **default settings**

2022-05-09 08:23 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/studio/database/settings/document-revisions.markdown
> +     its collection-specific configurations.**
both the default settings and the collection-specific configurations are `RevisionsCollectionConfiguration` objects that belong to a single `RevisionsConfiguration` object which is the "Revisions configuration" we're talking about, hence "its settings".

2022-05-09 08:41 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/revisions/overview.markdown
> +      ![Revisions Bin](images\revisions_revisions-bin.png "Revisions Bin")
done

2022-05-09 10:48 UTC, Danielle9897 approved these changes

2022-05-10 13:18 UTC, merged