RDoc-2161-Created How to use DateOnly and TimeOnly article
ravendb/docs pull request #1491
Opened 2022-05-01 13:19 UTC by serezhub

2022-05-11 13:13 UTC, maciejaszyk commented on Documentation/5.3/Raven.Documentation.Pages/client-api/how-to/using-timeonly-and-dateonly.markdown
> +The index orders the strings according to the first digits, then the second, and so on.
This is the same algorithm used in radix sorting :)

2022-05-11 13:40 UTC, maciejaszyk commented on Documentation/5.3/Raven.Documentation.Pages/client-api/how-to/using-timeonly-and-dateonly.markdown
> +* RavenDB has introduced the ability to convert `DateTime` or strings written in date/time formats to .NET's
Not exactly. Microsoft in .NET6 introduced them and now RavenDB allows users to store and query on them in the same manner as DateTime.

2022-05-11 13:40 UTC, maciejaszyk commented on Documentation/5.3/Raven.Documentation.Pages/client-api/how-to/using-timeonly-and-dateonly.markdown
> +The index must be declared as DateOnly or TimeOnly.
Not the index, but a field inside the Index.
In this manner, we are sure that a user is giving a `DateOnly` or `TimeOnly` object (otherwise the compiler will throw an error). If not, there is also a possibility to call `AsDateOnly` or `AsTimeOnly` to give us information about `DateOnly` \ `TimeOnly`

2022-05-11 13:40 UTC, maciejaszyk commented on Documentation/5.3/Raven.Documentation.Pages/client-api/how-to/using-timeonly-and-dateonly.markdown
> +Once the data has been converted inside the index, you can query on the converted data to find DateOnly or TimeOnly information.
Even if they are not converted you still can query on them. Main reason to create static index are the Ticks

2022-05-11 13:40 UTC, maciejaszyk commented on Documentation/5.3/Raven.Documentation.Pages/client-api/how-to/using-timeonly-and-dateonly.markdown
> +An auto-index will not convert DateOnly or TimeOnly into ticks, but will be able to convert data to strings.
It's not converting. Just treating data from documents as a normal string.

2022-05-12 04:33 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/how-to/using-timeonly-and-dateonly.markdown
> +The index orders the strings according to the first digits, then the second, and so on.
Noted

2022-05-12 04:39 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/how-to/using-timeonly-and-dateonly.markdown
> +* RavenDB has introduced the ability to convert `DateTime` or strings written in date/time formats to .NET's
done

2022-05-12 05:04 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/how-to/using-timeonly-and-dateonly.markdown
> +The index must be declared as DateOnly or TimeOnly.
Changed it to
`The index must have a field that declares the type as DateOnly or TimeOnly. `

2022-05-12 05:26 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/how-to/using-timeonly-and-dateonly.markdown
> +An auto-index will not convert DateOnly or TimeOnly into ticks, but will be able to convert data to strings.
Done.
This is the whole improved paragraph on that...
```
An auto-index will not convert DateOnly or TimeOnly into ticks, but will be data as strings.  
You can also compare strings, though comparing ticks is usually much faster and a static index needs to be used to do so.  
The index orders the strings according to the first digits, then the second, and so on (Radix Sorting).  
```

2022-05-12 06:58 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/how-to/using-timeonly-and-dateonly.markdown
> +Once the data has been converted inside the index, you can query on the converted data to find DateOnly or TimeOnly information.
1. Doesn't it save processing time/energy if the types are already converted?
2. How do they query on DateOnly if their data is DateTime? 
      a. In [this StackOverflow chain](https://stackoverflow.com/questions/22506930/how-to-query-datetime-field- 
          using-only-date-in-microsoft-sql-server) on that question there are like 20 answers and many of them look 
          too complex
3.  We don't have much documentation on querying ticks.  I found [this chain that discusses using ticks] 
    (https://groups.google.com/g/ravendb/c/rwMzQ96-zL4) in the google group, but there is no generic formula.  If 
    using ticks is much more efficient, it should be a part of every documentation article on querying (especially if it 
    has to do with querying date/time types)
        a. How would you advise a customer to query with ticks if their data is in DateTime?  I imagine that the first 
            step is to convert them in the index, but I may be wrong.

2022-05-16 06:48 UTC, maciejaszyk commented on Documentation/5.3/Raven.Documentation.Pages/client-api/how-to/using-timeonly-and-dateonly.markdown
> +* RavenDB has introduced the ability to convert `DateTime` or strings written in date/time formats to .NET's
Where?

2022-05-16 06:48 UTC, maciejaszyk commented on Documentation/5.3/Raven.Documentation.Pages/client-api/how-to/using-timeonly-and-dateonly.markdown
> +* It is also possible to covert via patch or query, but it is [far more efficient](../../client-api/how-to/using-timeonly-and-dateonly#convert-and-use-date/timeonly-without-affecting-your-existing-da
It's not possible. You can modify data through the patch to get a compatible format but honestly, it's not a good idea. I think this part should be deleted.

2022-05-16 06:48 UTC, maciejaszyk commented on Documentation/5.3/Raven.Documentation.Pages/client-api/how-to/using-timeonly-and-dateonly.markdown
> +It is possible to covert via patch or query, but it is far more efficient to do so in a [static index](../../indexes/map-indexes).
Same, you can transform through the patch, but not query. Projections are not converting anything for Querying/Indexing.

2022-05-16 06:48 UTC, maciejaszyk commented on Documentation/5.3/Raven.Documentation.Pages/client-api/how-to/using-timeonly-and-dateonly.markdown
> +     Also, queries will need to process all of your data every time.
? what do you mean

2022-05-16 06:48 UTC, maciejaszyk commented on Documentation/5.3/Raven.Documentation.Pages/client-api/how-to/using-timeonly-and-dateonly.markdown
> +         each time with a query.
At this point, I think an explanation about how Indexes works are not necessary.

2022-05-16 06:48 UTC, maciejaszyk commented on Documentation/5.3/Raven.Documentation.Pages/client-api/how-to/using-timeonly-and-dateonly.markdown
> +Strings can be ordered according to the first digits, then the second, and so on (Radix Sorting).
not necessary.

2022-05-16 06:48 UTC, maciejaszyk commented on Documentation/5.3/Raven.Documentation.Pages/client-api/how-to/using-timeonly-and-dateonly.markdown
> +Because the query is on a static index, you can rapidly query on ticks if you choose.
We are prioritizing ticks over strings in queries. So if the user created ticks (or it has happened automatically), the user cannot decide how we do the query internally.

2022-05-16 06:48 UTC, maciejaszyk commented on Documentation/5.3/Raven.Documentation.Pages/client-api/how-to/using-timeonly-and-dateonly.markdown
> +conversions repetetively in queries.
Don't get it.

2022-05-16 06:48 UTC, maciejaszyk commented on Documentation/5.3/Raven.Documentation.Pages/client-api/how-to/using-timeonly-and-dateonly.markdown
> +The following generic sample is a map index where `AsDateOnly` converts the string `item.StringDateOnlyField` into `DateTime`.
`DateOnly` ;)

2022-05-16 06:48 UTC, maciejaszyk commented on Documentation/5.3/Raven.Documentation.Pages/client-api/how-to/using-timeonly-and-dateonly.markdown
> +The conversion automatically makes the DateTime type available as ticks.
DateTime data always is saved with ticks. Doing `AsDateOnly` we are trimming the Time part.

2022-05-16 13:45 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/how-to/using-timeonly-and-dateonly.markdown
> +* RavenDB has introduced the ability to convert `DateTime` or strings written in date/time formats to .NET's
I changed it to `You can now convert DateTime or strings written in date/time formats to .NET's DateOnly or TimeOnly types...`

2022-05-16 13:49 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/how-to/using-timeonly-and-dateonly.markdown
> +* It is also possible to covert via patch or query, but it is [far more efficient](../../client-api/how-to/using-timeonly-and-dateonly#convert-and-use-date/timeonly-without-affecting-your-existing-da
Removed

2022-05-16 13:51 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/how-to/using-timeonly-and-dateonly.markdown
> +It is possible to covert via patch or query, but it is far more efficient to do so in a [static index](../../indexes/map-indexes).
Removed.

2022-05-16 13:52 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/how-to/using-timeonly-and-dateonly.markdown
> +     Also, queries will need to process all of your data every time.
That is what I thought we discussed on Zoom.  I removed this section because even if it was right, we don't need to tell users what not to do...only what to do.

2022-05-16 13:56 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/how-to/using-timeonly-and-dateonly.markdown
> +         each time with a query.
It seems important because it explains the reasoning for using the index to create a converted copy of the data.  Most articles that I've read about converting `DateTime` to `DateOnly` discuss using .NET's `FromDateTime` method.  We offer a different method that is used in the index.  

It's a very brief summary, with a link to learn more.

2022-05-16 13:58 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/how-to/using-timeonly-and-dateonly.markdown
> +The following generic sample is a map index where `AsDateOnly` converts the string `item.StringDateOnlyField` into `DateTime`.
Good catch. thanks!

2022-05-16 14:04 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/how-to/using-timeonly-and-dateonly.markdown
> +conversions repetetively in queries.
I previously thought that indexing is a better alternative to using queries, which [seems to be a common way](https://stackoverflow.com/questions/22506930/how-to-query-datetime-field-using-only-date-in-microsoft-sql-server).

Clearly the way we're presenting is much better for many reasons, but if using a query is common practice, isn't it a good idea to explain why we use indexes instead?

2022-05-17 13:20 UTC, serezhub reviewed
Does it make sense to use this?  It isn't in the #region, and we needed to get `waitforindexing(store)` to work.

2022-05-17 13:45 UTC, maciejaszyk commented on Documentation/5.3/Raven.Documentation.Pages/client-api/how-to/using-timeonly-and-dateonly.markdown
>  #### Converting Strings with minimal cost
Maybe we will concatenate strings & DateTime conversion examples into one example? They are very similar.

2022-05-17 13:48 UTC, maciejaszyk commented on Documentation/5.3/Raven.Documentation.Pages/client-api/how-to/using-timeonly-and-dateonly.markdown
> +Once the data has been converted inside the index, you can query on the converted data to find DateOnly or TimeOnly information.
```How do they query on DateOnly if their data is DateTime?
a. In [this StackOverflow chain](https://stackoverflow.com/questions/22506930/how-to-query-datetime-field-
using-only-date-in-microsoft-sql-server) on that question there are like 20 answers and many of them look
too complex```

You cannot compare them directly from C# code, for example ;) BUT you can use RQL. Your DateTime will be converted into Ticks (as usual).

2022-05-17 13:53 UTC, maciejaszyk commented on Documentation/5.3/Raven.Documentation.Pages/client-api/how-to/using-timeonly-and-dateonly.markdown
> +         each time with a query.
Internally, we are doing `FromDateTime` ;) 
https://github.com/ravendb/ravendb/blob/016785f4d3d96485af3e972f64ba3eaff05a7e7e/src/Raven.Server/Documents/Indexes/Static/StaticIndexBase.cs#L462

2022-05-17 13:56 UTC, maciejaszyk commented on Documentation/5.3/Raven.Documentation.Pages/client-api/how-to/using-timeonly-and-dateonly.markdown
> +         each time with a query.
We are calling our own converters when the user has stored data as strings already.

2022-05-17 14:00 UTC, maciejaszyk commented on Documentation/5.3/Raven.Documentation.Pages/client-api/how-to/using-timeonly-and-dateonly.markdown
> +Strings can be ordered according to the first digits, then the second, and so on (Radix Sorting).
My mistake, sorry.

2022-05-17 14:07 UTC, maciejaszyk commented on Documentation/5.3/Raven.Documentation.Pages/client-api/how-to/using-timeonly-and-dateonly.markdown
> +conversions repetetively in queries.
This is T-SQL (SQL) and RavenDB is NoSQL. RavenDB requires an index (exploration query is the exception).

2022-05-17 14:33 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/how-to/using-timeonly-and-dateonly.markdown
>  #### Converting Strings with minimal cost
Does it make sense to combine them into one code sample?  
They use different variables and they reference different indexes.  
Also, the user won't have both strings and DateTime, so if the sample is combined, will that throw an error?

2022-05-19 09:26 UTC, maciejaszyk commented on Documentation/5.3/Raven.Documentation.Pages/client-api/how-to/using-timeonly-and-dateonly.markdown
> +      each time you query and it doesn't affect your existing data.
As I said before, we are always creating an index for search. I think you can delete this part. @arekpalinski what do you think?

2022-05-19 09:26 UTC, maciejaszyk commented on Documentation/5.3/Raven.Documentation.Pages/client-api/how-to/using-timeonly-and-dateonly.markdown
> +An auto-index will not convert DateOnly or TimeOnly into ticks, but will be able to convert data to strings.
` but will be data as strings. ` -> `but will index data as strings` maybe?

+
`Strings can be ordered according to the first digits, then the second, and so on (Radix Sorting).  `

I'm not sure if we want to add that :)

2022-05-19 09:37 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/how-to/using-timeonly-and-dateonly.markdown
> +         each time with a query.
I see

2022-05-19 09:41 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/how-to/using-timeonly-and-dateonly.markdown
> +conversions repetetively in queries.
I took out the part about queries

2022-05-19 09:43 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/how-to/using-timeonly-and-dateonly.markdown
> +      each time you query and it doesn't affect your existing data.
I took out the last sentence about queries.

2022-05-19 10:38 UTC, maciejaszyk commented on Documentation/5.3/Raven.Documentation.Pages/client-api/how-to/using-timeonly-and-dateonly.markdown
> +         each time with a query.
Yes

2022-05-19 11:01 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/how-to/using-timeonly-and-dateonly.markdown
> +Once the data has been converted inside the index, you can query on the converted data to find DateOnly or TimeOnly information.
Changed to `Now you can use ticks to query on the converted data in the index.  `

But, now if the point is about using ticks, does the following query use ticks?
```
    public void QuerySampleForIndexWithDateTimeAndDateOnly()
        {
                using (var store = new DocumentStore())
                {
                    using var session = store.OpenSession();
                    #region TimeOnly_between15-17
                    var after = new TimeOnly(15, 00);
                    var before = new TimeOnly(17, 00);
                    var result = session
                    .Query<DateAndTimeOnly>()
                    .Where(i => i.TimeOnly > after && i.TimeOnly < before)
                    .ToList();
                    #endregion
                }
        }
```

2022-05-19 11:03 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/how-to/using-timeonly-and-dateonly.markdown
> +Strings can be ordered according to the first digits, then the second, and so on (Radix Sorting).
I took out the sentence about radix

2022-05-19 13:15 UTC, maciejaszyk approved these changes

2022-05-19 13:16 UTC, maciejaszyk commented
LGTM

2022-05-24 22:38 UTC, reebhub requested changes

2022-05-24 22:38 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/how-to/using-timeonly-and-dateonly.markdown
> +In RavenDB, we offer conversion of types in static indexes with the methods [AsDateOnly or AsTimeOnly](../../client-api/how-to/using-timeonly-and-dateonly#use--or--in-a-static-index-to-convert-string
RavenDB offers..

2022-05-24 22:38 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/how-to/using-timeonly-and-dateonly.markdown
> +  including calculations and converstions to DateOnly/TimeOnly values, which can be used as ticks,
* fix "converstions" (& run it through Grammarly)
* the line is cut in the wrong place

2022-05-24 22:38 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/how-to/using-timeonly-and-dateonly.markdown
> +{INFO: Ticks}
you don't explain what ticks are anywhere, including in the box called "ticks"

2022-05-26 06:31 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/how-to/using-timeonly-and-dateonly.markdown
> +In RavenDB, we offer conversion of types in static indexes with the methods [AsDateOnly or AsTimeOnly](../../client-api/how-to/using-timeonly-and-dateonly#use--or--in-a-static-index-to-convert-string
done

2022-05-26 06:31 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/how-to/using-timeonly-and-dateonly.markdown
> +  including calculations and converstions to DateOnly/TimeOnly values, which can be used as ticks,
done

2022-05-26 06:31 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/how-to/using-timeonly-and-dateonly.markdown
> +{INFO: Ticks}
done

2022-05-26 13:28 UTC, reebhub approved these changes

2022-05-26 14:00 UTC, maciejaszyk commented on Documentation/5.3/Raven.Documentation.Pages/client-api/how-to/using-timeonly-and-dateonly.markdown
> +so the variables must be wrapped in AsDateDonly() or AsTimeOnly() explicitly.
Why did you paste it 3 times?

2022-05-26 14:26 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/client-api/how-to/using-timeonly-and-dateonly.markdown
> +so the variables must be wrapped in AsDateDonly() or AsTimeOnly() explicitly.
There are three different sections with code samples.  It would be out of context in the intro section because it's about the code syntax, so I needed to put the note in each section.

2022-05-26 14:27 UTC, serezhub commented on Documentation/5.3/Samples/csharp/Raven.Documentation.Samples/ClientApi/HowTo/UseTimeOnlyAndDateOnly.cs
> +                               // so they need to be called explicitly.
done

2022-06-03 08:30 UTC, merged