RDoc-2160-Added admin-only config to define JS static index, updated …
ravendb/docs pull request #1492
Opened 2022-05-03 08:41 UTC by serezhub

…docs about JS indexing permissions with new config option

2022-05-09 08:53 UTC, arekpalinski commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authorization/security-clearance-and-permissions.markdown
> +  * [JavaScript static indexes](../../../indexes/javascript-indexes) are permitted by default with Read Only User certificates.
Why mentioning specifically static JS indexes here? Everything is already covered above in "Defining [static indexes]" - a user with read only cert cannot create _any_ static indexes and that's it. `Indexing.Static.RequireAdminToDeployJavaScriptIndexes` is not relevant in context of read-only certs

2022-05-09 09:11 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authorization/security-clearance-and-permissions.markdown
> +  * [JavaScript static indexes](../../../indexes/javascript-indexes) are permitted by default with Read Only User certificates.
Done.  I moved that comment to the read/write section.

2022-05-09 09:15 UTC, arekpalinski approved these changes

2022-05-10 10:46 UTC, reebhub requested changes

2022-05-11 06:29 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/indexes/javaScript-indexes.dotnet.markdown
> +JavaScript indexes can be defined by a user with lower permissions than the C# indexes (User/Read-Write certificates can also define JS indexes).
Changed it to: 
```
JavaScript indexes can be defined with a User/Read-Write certificate, whereas C# static indexes require User/Admin certificate or higher.  
To configure defining a static index as Admin only in JavaScript as well, set [Inde...
```

2022-05-11 06:44 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/indexes/javaScript-indexes.dotnet.markdown
> +To configure defining a static index as Admin only in JavaScript as well, set [Indexing.Static.RequireAdminToDeployJavaScriptIndexes](../server/configuration/indexing-configuration#indexing.static.re
Changed it to 
```
To prevent the creation of nonessential, resource taxing indexes, you can configure JavaScript index creation with **Admin only privileges** by setting...
```

2022-05-11 06:45 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/indexes/javaScript-indexes.dotnet.markdown
> +
done

2022-05-11 06:48 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authorization/security-clearance-and-permissions.markdown
> +
Done

2022-05-11 06:49 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authorization/security-clearance-and-permissions.markdown
> +    configure [Indexing.Static.RequireAdminToDeployJavaScriptIndexes](../../../server/configuration/indexing-configuration#indexing.static.requireadmintodeployjavascriptindexes)
done

2022-05-11 06:58 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authorization/security-clearance-and-permissions.markdown
> +The `ReadOnly` access level **allows** clients to:
done

2022-05-11 10:52 UTC, reebhub requested changes

2022-05-11 10:52 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/indexes/javaScript-indexes.dotnet.markdown
> +* This feature was created for users who want to create a static index and prefer JavaScript over C#.
bullet doesn't work

2022-05-11 10:52 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/indexes/javaScript-indexes.dotnet.markdown
> +  To prevent the creation of nonessential, resource taxing indexes, you can configure JavaScript index creation with **Admin only privileges** by setting
* unclear what indexes you refer to as "nonessential" & "resource taxing", and therefore unclear what you're saying in general and specifically what the config option is for. are you trying to say it's to permit only certified users to create JS indexes? and are they resource taxing in relation to c#?
* give this its own bullet

2022-05-11 10:52 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/indexes/javaScript-indexes.dotnet.markdown
> +* All other capabilities and features are the same as C# indexes.
* capabilities and features of what?
* as C# indexes --> as in C# indexes

2022-05-11 10:52 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/indexes/javaScript-indexes.dotnet.markdown
> +from AbstractJavaScriptIndexCreationTask.
AbstractJavaScriptIndexCreationTask --> `AbstractJavaScriptIndexCreationTask`
same with other objects / code entities

2022-05-11 10:52 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/indexes/javaScript-indexes.dotnet.markdown
> +(Read more about [AbstractIndexCreationTask here](../indexes/creating-and-deploying#Using-AbstractIndexCreationTask).)
just make the first appearance of AbstractIndexCreationTask a link, no need to say it explicitly in parenthesis

2022-05-11 10:52 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authorization/security-clearance-and-permissions.markdown
>     * Auto-indexes are built as a normal result of queries.
* as a normal result of queries -->  as normal query results
* place it in an info box, not a bullet
* i don't understand it, an example is needed

2022-05-11 10:56 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/indexes/javaScript-indexes.dotnet.markdown
> +* This feature was created for users who want to create a static index and prefer JavaScript over C#.
done

2022-05-11 11:47 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/indexes/javaScript-indexes.dotnet.markdown
> +  To prevent the creation of nonessential, resource taxing indexes, you can configure JavaScript index creation with **Admin only privileges** by setting
done

2022-05-11 11:49 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/indexes/javaScript-indexes.dotnet.markdown
> +* All other capabilities and features are the same as C# indexes.
done

2022-05-11 11:50 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/indexes/javaScript-indexes.dotnet.markdown
> +from AbstractJavaScriptIndexCreationTask.
done

2022-05-11 11:54 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/indexes/javaScript-indexes.dotnet.markdown
> +(Read more about [AbstractIndexCreationTask here](../indexes/creating-and-deploying#Using-AbstractIndexCreationTask).)
done

2022-05-11 12:13 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/server/security/authorization/security-clearance-and-permissions.markdown
>     * Auto-indexes are built as a normal result of queries.
I changed it to 
`[Auto-indexes] are built if there is no existing index that satisfies a query.`
If they don't understand, the link is there to prevent over-explaining.

2022-05-24 21:55 UTC, reebhub approved these changes

2022-05-25 12:19 UTC, merged