RDoc-2163-Option to PreventETL from deleting filtered documents - …
ravendb/docs pull request #1496
Opened 2022-05-09 09:58 UTC by serezhub

…moved doc from 5.1 to 5.3
Ignore the first commit

2022-05-13 12:46 UTC, arekpalinski commented on Documentation/5.3/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
> +function deleteDocumentsOf<CollectionName>Behavior(docId, deleted) {
Maybe let's show both signatures:

`function deleteDocumentsOf<CollectionName>Behavior(docId)`

and 

`function deleteDocumentsOf<CollectionName>Behavior(docId, deleted)`

?

2022-05-13 12:46 UTC, arekpalinski commented on Documentation/5.3/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
> +| **deleted** | `bool` | Optional and therefore doesn't affect existing code. If you don't include the `deleted` parameter, RavenDB will execute the function without checking if the document was dele
I think we are missing explicit explanation that we're doing deletes also when we sent an update of a document. And this parameter allows to distinguish between those two cases.

The original motivation for that was that we had an issue that we were propagating the deletion of a document which was already sent to the destination, then it was updated and it filtered by the condition in the script.

2022-05-13 12:46 UTC, arekpalinski commented on Documentation/5.3/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
> +function deleteDocumentsBehavior(docId, collection, deleted) {
Same as above. Let's show both signatures

2022-05-15 05:07 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
> +function deleteDocumentsOf<CollectionName>Behavior(docId, deleted) {
Done

2022-05-15 07:32 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
> +function deleteDocumentsBehavior(docId, collection, deleted) {
Done

2022-05-16 14:23 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
> +| **deleted** | `bool` | Optional and therefore doesn't affect existing code. If you don't include the `deleted` parameter, RavenDB will execute the function without checking if the document was dele
Now I explained it in the intro to this section.

2022-05-16 14:23 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
> +function deleteDocumentsBehavior(docId, collection, deleted) {
done

2022-05-16 14:24 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
> +function deleteDocumentsOf<CollectionName>Behavior(docId, deleted) {
done

2022-05-18 06:21 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
> +| **deleted** | `bool` | Optional and therefore doesn't affect existing code. If you don't include the `deleted` parameter, RavenDB will execute the function without checking if the document was dele
I just want to be clear about the motivation for this project.  
A doc in the destination with a different collection gets deleted by default every time the source is updated or deleted.  
We want to 
1. Enable people to save the outdated/older versions instead of deleting them if they want to.
2. Make sure that they understand the logic of the ID changing with each ETL update when the collection is different.
3. Let them choose whether they want to delete the older version when the source is deleted, and to choose if they want to delete it when the source is simply updated, but not deleted...which is why we added the parameter `deleted` that checks if the source doc was deleted.
4. Am I missing anything?

2022-05-18 06:59 UTC, arekpalinski commented on Documentation/5.3/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
> +* ETL is triggered any time a document is updated or deleted in a collection where ETL is set.
It's triggered also on _put_ of a document

2022-05-18 07:01 UTC, arekpalinski commented on Documentation/5.3/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
> +  that checks if the document was deleted or updated in the source database.
I wouldn't say that the signature itself "checks" that. A user can do the check based on the parameter provided to the method.

2022-05-18 07:03 UTC, arekpalinski commented on Documentation/5.3/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
> +  If it was deleted in the source and the `return` is set to `true`,
"return` is set to `true`," ?? I'm not sure what you meant here but that is not correct for sure

2022-05-18 07:07 UTC, arekpalinski commented on Documentation/5.3/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
> +* If the `return` is set to `false`, or if the document was not deleted,
"OR if the document was not deleted," - this is not how it works, there is no "OR". We provide the values of parameters to the behavior function and _a user_ decides if it should be deleted or not. He does it by returning `true / false`.

2022-05-18 07:07 UTC, arekpalinski commented on Documentation/5.3/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
> +Alternately, the following signature will not check if the document was indeed deleted.
Again, the signature doesn't check itself. The user can do the check

2022-05-18 07:09 UTC, arekpalinski commented on Documentation/5.3/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
> +The following signature will use the `deleted` parameter to check whether a document was deleted in the source database.
Same here - the signature doesn't "use" the parameter. The user can use it to make a decision and decide what to return from the deletion behavior function

2022-05-18 07:27 UTC, arekpalinski commented on Documentation/5.3/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
> +| **deleted** | `bool` | Optional and therefore doesn't affect existing code. If you don't include the `deleted` parameter, RavenDB will execute the function without checking if the document was dele
This is okay

2022-05-18 08:43 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
> +* ETL is triggered any time a document is updated or deleted in a collection where ETL is set.
added `created, updated...`

2022-05-18 18:30 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
> +  that checks if the document was deleted or updated in the source database.
I moved the description into the code sample comments to make it easier to understand. 
```
function deleteDocumentsOf<CollectionName>Behavior(docId, deleted) {
    // If any document in the specified source collection is modified but is not deleted,  
    // then the ETL will not send a delete command to the destination.  
    if (deleted == false) 
    return [false]; 
    // If the source document was deleted, the destination will also be deleted and there will be no replacement.
    else return true;
```

2022-05-18 18:32 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
> +  If it was deleted in the source and the `return` is set to `true`,
The comments are above the code lines now, which is cleaner than explaining them in a paragraph before the sample.

2022-05-18 18:33 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
> +* If the `return` is set to `false`, or if the document was not deleted,
done.

2022-05-18 18:33 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
> +Alternately, the following signature will not check if the document was indeed deleted.
changed it

2022-05-18 18:35 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
> +The following signature will use the `deleted` parameter to check whether a document was deleted in the source database.
Changed this whole section to: 
```
* This means that if `return` is `true` and  
  if a source document was updated, but not deleted,  
  it will be deleted in the destination before the updated document with a new ID is loaded to replace the previous one.  
   * If the source document was deleted, the destination will also be deleted and there will be no replacement.
* If `return` is `false`, a 'historical' set of the document will accumulate in the destination collection every time 
  the source document is updated.  
  The number at the end of the ID will automatically increment with every new version. 
   * If the document was deleted from the source, the set of old versions of the document will remain in the destination 
     because the delete behavior returns `false`.
```

2022-05-19 09:16 UTC, arekpalinski commented on Documentation/5.3/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
> +        In this case, I am looking at two versions of a document in the collection "profile" which is in a database in node "B"
Why lowercased? Typically the collection names starts with big letter. If user defined `loadToProfile()` then the collection name will be `Profile` just the doc it will be lowercased

2022-05-19 09:18 UTC, arekpalinski commented on Documentation/5.3/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
>      return [false];
Minor - formatting issue

```
if (deleted == false) 
    return [false]; 
```

instead of 
```
if (deleted == false) 
return [false]; 
```

2022-05-19 09:22 UTC, arekpalinski commented on Documentation/5.3/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
> +* This means that if `return` is `true` and
Instead of saying "if `return` is `true`" I'd rather rephrase it to "if the method returns `true`". It's more natural since `return` is a keyword in programming languages and we don't set the value to `return` - it's not a variable. We just return the value from the function

2022-05-19 09:23 UTC, arekpalinski commented on Documentation/5.3/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
> +    return false;
Formatting 

```
if (deleted == false) 
    return false; 
```

2022-05-19 09:50 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
> +        In this case, I am looking at two versions of a document in the collection "profile" which is in a database in node "B"
I see..the doc ID is a filename, so all of the letters are lowercase.
Done

2022-05-19 09:52 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
>      return [false];
Good catch.  I thought I took out the [ ]...  I took it out now.

2022-05-19 09:54 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
> +* This means that if `return` is `true` and
I see.  Done

2022-05-19 09:56 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
> +    return false;
Done

2022-05-23 08:55 UTC, arekpalinski approved these changes

2022-05-25 13:05 UTC, reebhub requested changes

2022-05-25 14:45 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
> +{PANEL: Deletions}
Done.  
I changed it to 
```Upon source document modifications, ETL is set by default to delete and replace the destination documents.  

If you want to control the way deletions are handled in the destination database, 
you can change the default settings with the configurable functions described in this section.

* [Why documents are deleted by default]...
```

2022-05-25 14:49 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
> +     1. Document `employees/1-A` is processed by ETL and put into the `People` and `Sales` collections with IDs:
Done

2022-05-25 14:51 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
> +Deletions can be controlled by defining deletion behavior functions in the ETL script.
Odd. That's not how it looks on my end...
![image](https://user-images.githubusercontent.com/91824041/170291691-873d0e4a-4889-4ba2-9d2b-ac81a192ad0a.png)

2022-05-26 13:08 UTC, reebhub requested changes

2022-05-26 13:08 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
> +## ETL script with deletion behavior defined
start with "Deletions: .." / "Deletions Example: .."

2022-05-26 13:28 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
> +  * For example:
done

2022-05-26 13:29 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
> +## ETL script with deletion behavior defined
done

2022-05-29 06:10 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
> +* [Why documents are deleted by default](../../../server/ongoing-tasks/etl/raven#why-documents-are-deleted-by-default-in-the-destination-database)
They all work again.

2022-06-02 21:47 UTC, reebhub approved these changes

2022-06-03 08:29 UTC, merged