RDoc-2175-Which backups contain Change Vector
ravendb/docs pull request #1498
Opened 2022-05-22 11:50 UTC by serezhub

2022-05-29 12:33 UTC, garayx commented on Documentation/4.2/Raven.Documentation.Pages/client-api/operations/maintenance/backup/backup.markdown
> +   * Re-indexes the data from backed up definitions.
should be
Re-indexes the data from _restored_ definitions.  
 ?

2022-05-29 12:54 UTC, garayx commented on Documentation/4.2/Raven.Documentation.Pages/client-api/operations/maintenance/backup/backup.markdown
> +  Snapshot-backups are available for **Enterprise subscribers**.
duplication of full database already means that journals (and tasks) are duplicated, we should mention it duplicates the files structure itself. lets change to something like this:

```suggestion
* A Snapshot is a compressed binary duplication of the full database data structure. Which include the data file, and the journals of all storages at a given point-in-time. therefore it includes fully built indexes, it also includes ongoing tasks.  
See [file structure](../../../../server/storage/directory-structure#storage--directory-structure) for more info.
 
  Snapshot-backups are available for **Enterprise subscribers**.  
```

2022-05-29 12:54 UTC, garayx commented on Documentation/4.2/Raven.Documentation.Pages/client-api/operations/maintenance/backup/backup.markdown
> +* Snapshot cannot backup data incrementally.
there is a incremental option in snapshot backups

2022-05-29 12:59 UTC, garayx commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/backup/backup.markdown
>  ####Logical-Backup
why do we update this for 5.1? 5.1 is end of life.

2022-05-29 13:01 UTC, garayx commented on Documentation/5.1/Raven.Documentation.Pages/server/ongoing-tasks/backup-overview.markdown
> +   * Cannot do [incremental backups](../../server/ongoing-tasks/backup-overview#backup-scope:-full-or-incremental)
there are incremental backups

2022-05-29 13:02 UTC, garayx commented on Documentation/5.1/Raven.Documentation.Pages/server/ongoing-tasks/backup-overview.markdown
> +| Change Vector data | Snapshots save Change Vector data. Restoring from a Logical Backup causes Change Vector data to restart.|
change vectors are on database level not cluster

2022-05-29 13:08 UTC, garayx commented on Documentation/5.1/Raven.Documentation.Pages/server/ongoing-tasks/backup-overview.markdown
> +| Ongoing Tasks configuration | 4.0 Snapshots only, 4.2 Logical-backups & Snapshots |
```suggestion
| Ongoing Tasks configuration | Logical-backups & Snapshots |
```

2022-05-29 13:11 UTC, garayx commented on Documentation/5.1/Raven.Documentation.Pages/server/ongoing-tasks/backup-overview.markdown
>  | Subscriptions |
subscription are saved in cluster.

I think we are missing times series

2022-05-30 06:34 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/client-api/operations/maintenance/backup/backup.markdown
> +   * Re-indexes the data from backed up definitions.
I can change that.
The important thing here is that people know that it has a lot of work to do because the index data wasn't backed up, just the definitions.

2022-05-30 06:39 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/client-api/operations/maintenance/backup/backup.markdown
> +  Snapshot-backups are available for **Enterprise subscribers**.
done

2022-05-30 06:45 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/client-api/operations/maintenance/backup/backup.markdown
> +* Snapshot cannot backup data incrementally.
I just tested it. You're right.  That means that I need to change the studio article on it too.

2022-05-30 08:30 UTC, serezhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/backup/backup.markdown
>  ####Logical-Backup
To prevent inconsistencies and inaccuracies.  It seems strange to update 4.2 and 5.2, but not 5.1

2022-05-30 08:46 UTC, serezhub commented on Documentation/5.1/Raven.Documentation.Pages/server/ongoing-tasks/backup-overview.markdown
> +| Change Vector data | Snapshots save Change Vector data. Restoring from a Logical Backup causes Change Vector data to restart.|
done.  I'm surprised.  The change vector shows a number for each node. 
![image](https://user-images.githubusercontent.com/91824041/170954354-a32ca0a1-bccf-4efc-b52a-c375231f00f1.png)

2022-05-30 08:55 UTC, serezhub commented on Documentation/5.1/Raven.Documentation.Pages/server/ongoing-tasks/backup-overview.markdown
> +| Ongoing Tasks configuration | 4.0 Snapshots only, 4.2 Logical-backups & Snapshots |
done

2022-05-30 08:58 UTC, serezhub commented on Documentation/5.1/Raven.Documentation.Pages/server/ongoing-tasks/backup-overview.markdown
>  | Subscriptions |
done

2022-06-03 00:30 UTC, reebhub requested changes

2022-06-03 00:30 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/server/ongoing-tasks/backup-overview.markdown
> +
* replace the "notes" column with two columns titled "logical backup" and "snapshot backup".
  if possible, link the column titles to where logical and snapshot backups are explained.
* in each row, explain if the entity is stored or not by each backup type.
* in the change vectors row, link the two references to the section in `change-vector.markdown` whose text is referred to in the comment above that starts with "the first sentence looks as if it continues" (or just embed the relevant text in each )

2022-06-03 00:30 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/server/ongoing-tasks/backup-overview.markdown
* replace the "notes" column with two columns titled "logical backup" and "snapshot backup".
* in each row, explain if the entity is stored or not in each backup type.

2022-06-06 08:18 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/client-api/operations/maintenance/backup/backup.markdown
> +     so during restoration the indexes must use the definitions to scan and process the dataset.
done
`During restoration, the dataset is scanned and indexed according to the definitions.`

2022-06-06 08:19 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/client-api/operations/maintenance/backup/backup.markdown
> +  frequently saving any changes made since the previous backup.
done

2022-06-06 08:23 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/client-api/operations/maintenance/backup/backup.markdown
> +  This includes the data file and the journals of all storages at a given point-in-time.
* I removed storages.  It backs up a database and it's tasks.  That is covered in the first sentence.
* The reference to journals is in the next line.

2022-06-06 08:24 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/client-api/operations/maintenance/backup/backup.markdown
> +* A Snapshot is a compressed binary duplication of the full database data structure.
done

2022-06-06 08:25 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/client-api/operations/maintenance/backup/backup.markdown
> +* Snapshot-backups are available for **Enterprise subscribers**.
done

2022-06-06 08:30 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/server/clustering/replication/change-vector.markdown
But I did...
```
{NOTE/}

---

{PANEL: Backup Types}
```
```
{PANEL/}

{PANEL: Backup Scope}
```
```
{PANEL/}

{PANEL: Backup to Local and Remote Destinations}
```
and so on

2022-06-06 08:31 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/client-api/operations/maintenance/backup/backup.markdown
> +
done.
This is what I have now
```
* If Incremental Snapshot backups are used: 
   * The first backup will be a full Snapshot, but the incremental backups, 
     like Logical backup types, will not update indexes or [change vectors](../../../../server/clustering/replication/change-vector).   
   * Document data will be up-to-date, but restoring from an 
     Incremental Snapshot will still require some re-indexing and the change vectors will also be affected. 
```

2022-06-06 09:03 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/server/clustering/replication/change-vector.markdown
> +
I did everything but the restart bit...
I researched it and the only way I found to say this without a convoluted explanation is 
```
  Restoring a database from a logical backup will restart the documents' change vector ETags(../../../server/clustering/replication/change-vector#what-are-change-vectors-constructed-from).
  i.e. If the last change vector ETag was 8456, when restoring the database, the ETag will be 1.  
```

2022-06-06 09:11 UTC, serezhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/backup/backup.markdown
done

2022-06-06 09:12 UTC, serezhub commented on Documentation/5.1/Raven.Documentation.Pages/server/ongoing-tasks/backup-overview.markdown
> +   * **Freezing data in chosen points-in-time** to revert to, (e.g. if a mistake was made in a patch or an upgrade).
done

2022-06-06 09:13 UTC, serezhub commented on Documentation/5.1/Raven.Documentation.Pages/server/ongoing-tasks/backup-overview.markdown
> +     that runs in the background.
done

2022-06-06 09:15 UTC, serezhub commented on Documentation/5.1/Raven.Documentation.Pages/server/ongoing-tasks/backup-overview.markdown
> +* Backup can be configured with [Client API](../../client-api/operations/maintenance/backup/backup) or in the [Studio](../../studio/database/tasks/backup-task).
done

2022-06-06 10:48 UTC, serezhub commented on Documentation/5.1/Raven.Documentation.Pages/server/ongoing-tasks/backup-overview.markdown
> +
Done.  Because I linked to Change Vectors, I also created links to all of the additional data (ongoing tasks, subscriptions, etc...)

2022-06-06 10:50 UTC, serezhub commented on Documentation/5.1/Raven.Documentation.Pages/server/ongoing-tasks/backup-overview.markdown
done

2022-06-06 10:52 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/studio/database/tasks/backup-task.markdown
> +* To see what data different backup types save, see the [backup overview article](../../../server/ongoing-tasks/backup-overview).
done

2022-06-06 10:58 UTC, serezhub commented on Documentation/5.1/Raven.Documentation.Pages/server/ongoing-tasks/backup-overview.markdown
> +   * Cannot do [incremental backups](../../server/ongoing-tasks/backup-overview#backup-scope:-full-or-incremental)
done

2022-06-08 11:32 UTC, garayx commented on Documentation/4.2/Raven.Documentation.Pages/client-api/operations/maintenance/backup/backup.markdown
> +     like Logical backup types, will not update indexes or [change vectors](../../../../server/clustering/replication/change-vector).
```suggestion
     like Logical backup types will be backed-up in JSON files therefor will not update indexes or [change vectors](../../../../server/clustering/replication/change-vector).   
```

2022-06-08 11:33 UTC, garayx commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/backup/backup.markdown
> +     like Logical backup types, will not update indexes or [change vectors](../../../../server/clustering/replication/change-vector).
same as above comment

2022-06-08 11:36 UTC, garayx commented on Documentation/5.1/Raven.Documentation.Pages/server/ongoing-tasks/backup-overview.markdown
> +* You can create and configure backup tasks using the [Client API](../../client-api/operations/maintenance/backup/backup) or [Studio](../../studio/database/tasks/backup-task).
```suggestion
* You can create and configure backup tasks using the [Client API](../../client-api/operations/maintenance/backup/backup) or using the Tasks/Backups page in [Studio](../../studio/database/tasks/backup-task).
```

2022-06-08 11:37 UTC, garayx commented on Documentation/5.1/Raven.Documentation.Pages/server/ongoing-tasks/backup-overview.markdown
> +   * During a database restore, indexes must re-scan the dataset according to their saved definitions.
Actually this is happens after restore, restore only restores the index definitions, so when index definition is added the dataset start to be indexed.

2022-06-08 11:40 UTC, garayx commented on Documentation/5.1/Raven.Documentation.Pages/server/ongoing-tasks/backup-overview.markdown
> +| Database-level data | [Logical Backup](../../server/ongoing-tasks/backup-overview#logical-backup) | [Snapshot](../../server/ongoing-tasks/backup-overview#snapshot) |
can you post a screen shot of this table?

2022-06-08 11:50 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/client-api/operations/maintenance/backup/backup.markdown
> +     like Logical backup types, will not update indexes or [change vectors](../../../../server/clustering/replication/change-vector).
Done

2022-06-08 11:51 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/server/clustering/replication/change-vector.markdown
> +
Done

2022-06-08 11:51 UTC, serezhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/backup/backup.markdown
> +     like Logical backup types, will not update indexes or [change vectors](../../../../server/clustering/replication/change-vector).
Done

2022-06-08 11:52 UTC, serezhub commented on Documentation/5.1/Raven.Documentation.Pages/server/ongoing-tasks/backup-overview.markdown
> +   * **Freezing data in chosen points-in-time** to revert to retain access to it in various stages of its existence/development.
Done

2022-06-08 11:53 UTC, serezhub commented on Documentation/5.1/Raven.Documentation.Pages/server/ongoing-tasks/backup-overview.markdown
> +     Backup is therefore provided not as a one-time operation, but as an  [ongoing task](../../studio/database/tasks/ongoing-tasks/general-info)
Good eyes!

2022-06-08 11:57 UTC, serezhub commented on Documentation/5.1/Raven.Documentation.Pages/server/ongoing-tasks/backup-overview.markdown
> +* You can create and configure backup tasks using the [Client API](../../client-api/operations/maintenance/backup/backup) or [Studio](../../studio/database/tasks/backup-task).
Done 
`or 
  in [Studio](../../studio/database/tasks/backup-task) navigate from **Tasks** -> **Backups** -> **Create a Periodic Backup**.`

2022-06-08 11:59 UTC, serezhub commented on Documentation/5.1/Raven.Documentation.Pages/server/ongoing-tasks/backup-overview.markdown
> +   * During a database restore, indexes must re-scan the dataset according to their saved definitions.
Done
`After a database restore, indexes must re-scan the dataset according to the backed up definitions.`

2022-06-08 12:03 UTC, serezhub commented on Documentation/5.1/Raven.Documentation.Pages/server/ongoing-tasks/backup-overview.markdown
> +| Database-level data | [Logical Backup](../../server/ongoing-tasks/backup-overview#logical-backup) | [Snapshot](../../server/ongoing-tasks/backup-overview#snapshot) |
You must have seen an older commit.  This is what's current.  Red=links.
![image](https://user-images.githubusercontent.com/91824041/172611576-b9360d1d-32b6-4ede-b8e4-f4a303e41b9b.png)

2022-06-12 06:51 UTC, reebhub requested changes

2022-06-12 06:51 UTC, reebhub commented on Documentation/4.2/Raven.Documentation.Pages/client-api/operations/maintenance/backup/backup.markdown
> +
still messy (most of it can go to the incremental backups section it actually belongs to), and you simply ignored at least one comment (about explaining the mysterious "change vectors will also be affected").

* "If Incremental Snapshot backups are used: " --> "If Incremental backups are created for a snapshot: "
* replace the following two bullets with:
   "The first backup will be a full Snapshot. 
   The following incremental backups will be kept in [JSON format](../../../../client-api/operations/maintenance/backup/backup#incremental-backup)."
(The link is to the incremental-backups section below.)
* Add any additional information regarding incremental backups to the "Incremental-Backup" section below.
   E.g.  
     * An incremental backup keeps index definitions (not full indexes).
       When the backup is restored, the dataset is re-indexed by the index definitions. 
     * An incremental backup doesn't keep [change vectors](../../../../server/clustering/replication/change-vector).

2022-06-12 06:51 UTC, reebhub commented on Documentation/4.2/Raven.Documentation.Pages/server/clustering/replication/change-vector.markdown
i don't know where you're taking these texts from, they are definitely not included in your `RDoc-2175-Specify-Backup-Contents` PR's 4.2 `change-vector.markdown` file.

2022-06-12 06:51 UTC, reebhub commented on Documentation/4.2/Raven.Documentation.Pages/server/clustering/replication/change-vector.markdown
> +
"[Logical backups](../../../client-api/operations/maintenance/backup/backup#logical-backup) do not save change vector data. Restoring a database from a logical backup will renew the document change vector's frequently [incrementing ETag](../../../server/clustering/replication/change-vector#what-are-change-vectors-constructed-from)
  to it's original value."

break the line before "Restoring a database"
run Grammarly or something like it to catch "it's original value" and similar mistakes

2022-06-12 09:55 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/client-api/operations/maintenance/backup/backup.markdown
> +
done

2022-06-12 10:18 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/server/clustering/replication/change-vector.markdown
I thought we were discussing the API backups file.  I'll make the panels in the change-vector file.
Done.

2022-06-12 10:19 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/server/ongoing-tasks/backup-overview.markdown
> +   * After a database restore, indexes must re-scan the dataset according to the backed up definitions.
can't relate to indexes as if they were active entities.
"After a database restore, indexes must re-scan the dataset according to.." --> 
"After a database restore, the dataset is re-indexed by the backed up index definitions."

2022-06-12 10:20 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/server/clustering/replication/change-vector.markdown
> +
done

2022-06-12 10:23 UTC, serezhub commented on Documentation/5.1/Raven.Documentation.Pages/server/ongoing-tasks/backup-overview.markdown
> +   * After a database restore, indexes must re-scan the dataset according to the backed up definitions.
Then the definitions are treated as active entities, but the important thing is that it's clear and easy to understand.  
done

2022-06-12 11:08 UTC, reebhub requested changes

2022-06-12 11:08 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/backup/backup.markdown
> +
change to:

* **An incremental-backup file is always in JSON format**.  
  It is so even when the full-backup it is associated with is a binary snapshot.  
* **An incremental backup stores index definitions (not full indexes)**.  
    After the backup is restored, the dataset is re-indexed according to the index definitions.
    {NOTE: }
     This initial re-indexing can be time-consuming on large datasets.
    {NOTE/}
* **An incremental backup doesn't store [change vectors](../../../../server/clustering/replication/change-vector)**.

2022-06-12 11:08 UTC, reebhub commented on Documentation/4.2/Raven.Documentation.Pages/server/clustering/replication/change-vector.markdown
`Concurrency Control & Change Vectors` is not in any panel, can't tell if it belongs to the panel above it or owns the sections below it. please check & fix.

2022-06-12 11:12 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/server/clustering/replication/change-vector.markdown
You're right.  I missed that one.

2022-06-12 11:12 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/server/clustering/replication/change-vector.markdown
done

2022-06-12 11:14 UTC, serezhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/backup/backup.markdown
> +* If Incremental backups are created for a snapshot::
Yes, that is more clear. done

2022-06-12 11:18 UTC, serezhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/backup/backup.markdown
> +     The following incremental backups will be kept in [JSON format](../../../../client-api/operations/maintenance/backup/backup#incremental-backup). Therefore they will not update indexes or [change
done.  the incremental section clearly says that change vectors are not saved in incremental backups.  I hope it's enough.

2022-06-12 11:19 UTC, serezhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/backup/backup.markdown
> +   * Document data will be up-to-date, but restoring from an
True.

2022-06-12 11:26 UTC, serezhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/backup/backup.markdown
> +
I changed the sub-bullet to a {note] and turned the first bit into a bullet.
About the change vectors bit...in previous reviews you wrote that change vectors need a brief explanation.  So I did that, and now you want me to take the explanation out.  I think it's enough to have a link, which is what I had before because if change vectors are important to them, they should learn about them more in-depth.

2022-06-12 11:35 UTC, serezhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/backup/backup.markdown
> +     The following incremental backups will be kept in [JSON format](../../../../client-api/operations/maintenance/backup/backup#incremental-backup). Therefore they will not update indexes or [change
No.  I re-read it and in it's context of snapshot, it's important to clarify that index and change vector updates are not stored.  
The [incremental backups](http://localhost:54391/article/5.0/csharp/client-api/operations/maintenance/backup/backup#incremental-backup) will be kept in [JSON format](http://localhost:54391/article/5.0/csharp/client-api/operations/maintenance/backup/backup#incremental-backup) but will not include updated index or change vector data.

2022-06-12 12:22 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/backup/backup.markdown
> +
seems like you need to re-read the original correspondence.

2022-06-12 12:25 UTC, reebhub approved these changes

2022-06-12 12:55 UTC, reebhub commented on Documentation/5.1/Raven.Documentation.Pages/client-api/operations/maintenance/backup/backup.markdown
> +     The following incremental backups will be kept in [JSON format](../../../../client-api/operations/maintenance/backup/backup#incremental-backup). Therefore they will not update indexes or [change
remove "but will not include updated index or change vector data..".
if you want to say something about the backup contents find a way to say it in a bullet of its own. this bullet is occupied for this one fact: the incremental backups will be kept in JSON format.

2022-07-18 09:49 UTC, merged