RDoc-2184-Added Configurations section to Cloud Overview article
ravendb/docs pull request #1511
Opened 2022-06-02 11:13 UTC by serezhub

2022-06-15 06:29 UTC, gregolsky commented on Documentation/4.2/Raven.Documentation.Pages/cloud/cloud-overview.markdown
> +#### Setting Cloud Configuration via Studio
It's about overriding indexing configuration on a per index basis - we could just put a relevant link to studio docs here and add a writeup that IF somebody needs to override the default RavenDB Cloud server configuration then here's how they can do it. Also the term "Cloud Configuration" is inaccurate and I'm not sure what it means.

cc @arekpalinski

2022-06-15 07:05 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/cloud/cloud-overview.markdown
> +#### Setting Cloud Configuration via Studio
By "Cloud Configuration", it refers to config settings that are unique to the cloud, as it says in line 289.  I can change it to "Cloud-Specific Configuration Settings" if that makes more sense.

The reason why we decided to put this in the cloud docs is that, in this case, the default config is different in the cloud.  I can put it in studio docs, but I would have to make it very clear that this is only relevant to the cloud.

If you were to look for instructions on a configuration that is relevant for the cloud, would you look in the studio or cloud docs?  Should there be a clear separation?  
I don't mind moving it over to studio and having a section for cloud configs that are different from on-premise.  I just want to make sure that it makes the most sense.  
  @reebhub any thoughts?

2022-06-15 08:39 UTC, gregolsky commented on Documentation/4.2/Raven.Documentation.Pages/cloud/cloud-overview.markdown
> +If, for example, you want to index with smaller batches,
`Indexing.MapBatchSize` value is an integer. Not an equation. This equation is just here to show how we calculate the default value for cloud instances.

2022-06-15 08:40 UTC, gregolsky commented on Documentation/4.2/Raven.Documentation.Pages/cloud/cloud-overview.markdown
> +If, for example, you want to index with smaller batches,
I'd expect this https://github.com/ravendb/docs/pull/1511/files#diff-def5150a6cb52d80f032b387ef1167734b35c2a6253a932367904c33395a2fe7R293 here

2022-06-15 13:02 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/cloud/cloud-overview.markdown
> +If, for example, you want to index with smaller batches,
I didn't see any suggested changes.  I wrote equation in the example of how to override the default.  The default doesn't consist of an equation that gives us an integer?  
Should developers just write an int like `3000`?

2022-06-15 13:56 UTC, gregolsky commented on Documentation/4.2/Raven.Documentation.Pages/cloud/cloud-overview.markdown
> +If, for example, you want to index with smaller batches,
yes

2022-06-16 09:00 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/cloud/cloud-overview.markdown
> +If, for example, you want to index with smaller batches,
done

#### Overriding the Default Setting

Type: `int`  
MinValue: `128`  
Configuration Key: Indexing.MapBatchSize  
Value: Set number of documents per batch.  
Change [indexing configurations in Studio](../studio/database/indexes/create-map-index#configuration)

2022-07-11 12:21 UTC, reebhub requested changes

2022-07-12 06:24 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/cloud/cloud-overview.markdown
> +RavenDB sets default configurations to be the safest and most efficient in most cases.
done

2022-07-12 08:00 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/cloud/cloud-overview.markdown
> +If you want to change configurations for cloud instances, they must be set in Studio.
Added the following sentence.  
> Open the Studio GUI for each node by clicking on the URL associated with them.  

I created a Youtrack Issue [RDoc-2230](https://issues.hibernatingrhinos.com/issue/RDoc-2230/Should-we-document-how-to-access-the-cloud-studio-gui) about this.

2022-07-12 08:04 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/cloud/cloud-overview.markdown
> +
Changed it to
> Whenever cloud configuration defaults differ from RavenDB on-premise defaults, the cloud configurations will be discussed in this section.

2022-07-12 08:10 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/cloud/cloud-overview.markdown
> +  * [Cloud-Specific Configuration Settings](../cloud/cloud-overview#cloud-specific-configuration-settings)
There is no section for cloud settings.  It is new to this project.  
As stated above, whenever cloud configuration defaults differ from RavenDB on-premise defaults, the cloud configurations will be discussed in this section.

That is why it is important to be clear that these are cloud-specific configurations.  It is also why I linked to the on-premise configurations that that cloud inherits, but you asked me to remove that sentence.

I can change it to "Cloud Instance Settings", but really, except for this indexing setting, all of the settings inherit from the on-premise server and API configs.

2022-07-12 12:25 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/cloud/cloud-overview.markdown
> +{PANEL: Cloud-Specific Configuration Settings}
See response above https://github.com/ravendb/docs/pull/1511#discussion_r918676684

2022-07-12 12:46 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/cloud/cloud-overview.markdown
> +* [IOPS number](../cloud/cloud-instances#a-production-cloud-cluster) (IOPS - Input/Output Operations Per Second - can be adjusted according to your needs.)
done

2022-07-12 12:49 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/cloud/cloud-overview.markdown
> +  !["Find IOPS Number"](images\configuration-see-iops.png "Find IOPS Number")
done.  I didn't know about spacing the image from other lines

2022-07-12 13:23 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/cloud/cloud-overview.markdown
> +
I can't use the server/configuration... link because that specifies the on-premise default config.  I put the link there to make it easy for them to see where they can change the configuration.  
The point of this section is to show configs that are specific to the cloud.  

Normally the configs here will look like the server/configuration articles do (to the point). 
Greg explained to me that it's important for them to understand the IOPS formula when they're choosing a new MapBatchSize.  That is why we wrote that whole explanation.   
Having said that, I wrote a section that is relevant for cloud:

[Overriding the Default Setting](http://localhost:54391/article/5.0/csharp/cloud/cloud-settings#overriding-the-default-setting)
Change [cloud configurations in Studio](http://localhost:54391/article/5.0/csharp/studio/database/indexes/create-map-index#configuration).
Type: int
MinValue: 128
Configuration Key: Indexing.MapBatchSize
Value: Set your desired maximum number of documents per batch.

2022-07-12 13:27 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/cloud/cloud-overview.markdown
> +#### Default RavenDB Cloud-Specific Max Batch Size Configuration
> Cloud Indexing Batch Size

2022-07-12 13:38 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/cloud/cloud-overview.markdown
> +
done
> Indexing is done in batches to make it possible to adjust the number of documents that the index processes at a time.
Adjusting the map indexing batch size can be done to prevent exhausting system resources.
If an index processes a collection in a few batches, it will continue each new batch where the previous batch stopped.

2023-06-05 12:16 UTC, closed without merging