RDoc-2183-AlternativeToCmpxchg - Added section about cluster boundaries
ravendb/docs pull request #1515
Opened 2022-06-13 10:22 UTC by serezhub

The link to external replication will work when the new edits to that doc will be merged. [RDoc-2178](https://issues.hibernatingrhinos.com/issue/RDoc-2178) 

Also, I included the note about atomic guards before both code samples, in case a reader skips the first one.

2022-08-25 11:30 UTC, reebhub requested changes

2022-08-25 11:30 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +     or if you need every node to be able to read/write on the same database.
something strange happened to this sentence.
should probably end after "is crucial" and leave the rest to another bullet.
speaking of which, the rest is unclear: "if you need every node to be able to read/write on the same database" - i don't understand what you're trying to say here.

2022-08-25 11:30 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +To [prevent consistency conflicts between clusters and model an efficient global system](https://ayende.com/blog/196769-B/data-ownership-in-a-distributed-system),
these extremely long link captions interfere with the reading and make both the reader and you think this is a riddle and the solution is elsewhere instead of finding/providing the solution here. please remove / focus the link caption, or find another place for it ("for further reading: xxx", or simply in the related articles section).

2022-08-25 11:30 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +One way to ensure consistency between clusters is if [documents created in each cluster are owned and operated only by that cluster](../../../server/ongoing-tasks/external-replication#maintaining-con
here too, there's a mile long link that creates expectations and eventually leads to an article about external replication without explaining the connection between the link title and the article the reader lands in.

2022-08-25 11:30 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +You can replicate or ETL to another cluster for record-keeping or data analysis.
not clear what "you" means, how exporting a doc to another cluster helps in record keeping or in data analysis, and why it can't be achieved in the docs' origin cluster (?)

2022-08-25 11:30 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
>  | ------------- | ---- |
this table probably relates to an object, right? can we show this object or refer to it so the whole section won't be hanging like this? readers that ask themselves in this stage how to create a key should be able to immediately ding an answer or a clear reference to one.

2022-08-25 12:19 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +  * Cluster-wide transactions present a [performance cost](../../../client-api/operations/compare-exchange/overview#performance-cost-of-cluster-wide-sessions)
The first part is about Atomic Guards while the second part is about the performance cost of cluster-wide transactions.  They're deeply connected, but not the same point, so I separated them but kept them together by using a sub-bullet.

2022-08-25 12:21 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +  Thus, because they are associated with documents, compare-exchange items are not replicated externally to other clusters.
done

* Compare-exchange items are [not replicated externally](../../../client-api/operations/compare-exchange/overview#why-compare-exchange-items-are-not-replicated-to-external-clusters) to other clusters.

2022-08-25 12:39 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +     or if you need every node to be able to read/write on the same database.
done

* **Cluster-wide sessions** have ACID guarantees for conflict-free transactions.
   * Because of the performance cost of raft consensus checks, we recommend using cluster-wide sessions  
     for transactions where immediate consistency is crucial.  
   * You can also set the session transaction mode to cluster-wide if you need every node to be able to read and write on the same database, 
     instead of the primary node handling all reads and writes in node-local sessions.

2022-08-25 12:58 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +To [prevent consistency conflicts between clusters and model an efficient global system](https://ayende.com/blog/196769-B/data-ownership-in-a-distributed-system),
I shortened this link, but...

I've researched this in the past and while I agree that links shouldn't be too long, all of the authorities on the topic agree that links should be like a title that summarizes the content that they are linking to.  

To avoid duplication, we don't want to explain everything here when it's explained well elsewhere. It's not a riddle with the solution elsewhere, but the reader needs a clear link that lets them know where they're going.  The sentence that the link is a part of should be a summary of where they can go if they want to learn more.   

Meaningful link phrases are very useful for people when scanning a page, like subheadings.  They don't add noise, they add meaningful landmarks.  

Also, search engines scan links and titles of documents/images/etc... "Click here" is devout of meaning...it doesn't tell the search engine bots what the article is about, while meaningful links strengthen search engine optimization.

If you don't believe me, read from [Microsoft on making links](https://docs.microsoft.com/en-us/contribute/how-to-write-links) or from [Brandeis University on hyperlink best practices](https://www.brandeis.edu/cms-guide/best-practices/links-navigation.html).

2022-08-25 13:00 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +One way to ensure consistency between clusters is if [documents created in each cluster are owned and operated only by that cluster](../../../server/ongoing-tasks/external-replication#maintaining-con
I shortened it to [to ensure consistency between clusters](.)

2022-08-25 13:21 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +You can replicate or ETL to another cluster for record-keeping or data analysis.
I took out the whole paragraph from 150 to 153 because 

- the warning above summarizes the problem well, 
- Oren's article gives an in-depth explanation about why document ownership should be at the cluster level, 
- and the link to external replication shows how to ensure ID uniqueness in a global system.

2022-08-25 13:39 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
>  | ------------- | ---- |
added the signature - `public PutCompareExchangeValueOperation(string key, T value, long index)`

2022-08-31 09:07 UTC, haludi commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +  * The compare-exchange item is distributed to all nodes in a [cluster-wide transaction](../../../server/clustering/cluster-transactions)
Only modifying through the session will use cluster-wide transactions.
I think it will be more accurate to say:
The compare-exchange item is distributed to all nodes through the raft algorithm so that a consistent, unique key is guaranteed cluster-wide.

2022-09-01 12:09 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +  * The compare-exchange item is distributed to all nodes in a [cluster-wide transaction](../../../server/clustering/cluster-transactions)
Done.  Included link.

2022-09-02 05:34 UTC, haludi approved these changes

2022-09-08 13:56 UTC, Danielle9897 requested changes

2022-09-08 13:56 UTC, Danielle9897 commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/Server/CompareExchange.cs
> +            public class CompanyReference
Better to rename class name to PhoneReference
(it will reside in 'phones' collection)

2022-09-08 13:56 UTC, Danielle9897 commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/Server/CompareExchange.cs
> +                // A new document in the "Companies" collection with automatic HiLo ID
=>
A company document class that must be created with a unique 'Phone' field

2022-09-08 13:56 UTC, Danielle9897 commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/Server/CompareExchange.cs
> +                    // Check if a reference document exists where the ID is a unique value such as an email or phone
Replace comment with :
=>
// Check whether the new company phone is already in use by another company
// Do so by checking if there exists a reference document that has the new phone in its ID

2022-09-08 13:56 UTC, Danielle9897 commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/Server/CompareExchange.cs
> +                    var existing = session.Load<CompanyReference>("phones/" + newCompany.Phone);
rename:
existing => phoneDocument

2022-09-08 13:56 UTC, Danielle9897 commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/Server/CompareExchange.cs
> +                        var msg = $"The phone '{newCompany.Phone}' already exists in company ID: {existing.CompanyId}";
The phone.. => The new phone...

2022-09-08 13:56 UTC, Danielle9897 commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/Server/CompareExchange.cs
> +                    // If this unique value doesn't already exist, store the new entity
=>
If the new phone doesn't already exist then store the new company

2022-09-08 13:56 UTC, Danielle9897 commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/Server/CompareExchange.cs
> +                    // Create a reference document where the ID is a unique value for future checks
=>
Store a new reference document with the new phone value in its ID for future checks.

2022-09-08 13:56 UTC, Danielle9897 commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/Server/CompareExchange.cs
> +        {
Add comment:
=>
The reference document class

2022-09-11 05:40 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +* Compare-exchange items are [not replicated externally](../../../client-api/operations/compare-exchange/overview#why-compare-exchange-items-are-not-replicated-to-external-clusters) to other clusters
done

2022-09-11 05:42 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> + * [Why Compare-Exchange Items are Not Replicated to External Clusters](../../../client-api/operations/compare-exchange/overview#why-compare-exchange-items-are-not-replicated-to-external-clusters)
done

2022-09-11 05:44 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +    so that a consistent, unique key is guaranteed cluster-wide.
done

2022-09-11 05:44 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +    If other sessions load the document before the version changed, they will not be able to modify it.
done

2022-09-11 05:48 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +{PANEL: Example III - Ensuring Unique Values with Reference Documents}
done

2022-09-11 05:52 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +**The rule of thumb for documents created by another cluster - you can look, but don't touch.**
done

2022-09-11 06:08 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +{NOTE/}
removed everything but:
> * Compare Exchange can be used to reserve a shared resource **inside a single cluster**.

2022-09-11 06:10 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +{NOTE/}
I disagree.  The lack of this note was why this issue was created.

2022-09-11 06:21 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +
Done
> The following example shows how to use compare exchange to create documents 
with unique values. The scope is within the database group on a single cluster.
To establish uniqueness without using compare exchange see [example III](../../../client-api/operations/compare-exchange/overview#example-iii---ensuring-unique-values-with-reference-documents).

2022-09-11 06:37 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +These documents will then be externally replicated between clusters.
done 

Unique values can also be ensured without using compare exchange.

The below example shows how to achieve that by using **reference documents**.
The reference documents' IDs will contain the unique values instead of the compare exchange items.

Using reference documents is especially useful when [External Replication](../../../server/ongoing-tasks/external-replication) 
is defined between 2 databases that need to be synced with unique values. 
The reference documents will replicate to the destination database, 
as opposed to compare exchange items, which are not externally replicated.

2022-09-11 06:39 UTC, serezhub commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/Server/CompareExchange.cs
> +            public class CompanyReference
`UniqueValueReference`

2022-09-11 06:40 UTC, serezhub commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/Server/CompareExchange.cs
> +                // A new document in the "Companies" collection with automatic HiLo ID
done

2022-09-11 06:43 UTC, serezhub commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/Server/CompareExchange.cs
> +                    // Check if a reference document exists where the ID is a unique value such as an email or phone
done

2022-09-11 06:46 UTC, serezhub commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/Server/CompareExchange.cs
> +                    var existing = session.Load<CompanyReference>("phones/" + newCompany.Phone);
`phoneReferenceDocument`

2022-09-11 06:47 UTC, serezhub commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/Server/CompareExchange.cs
> +                        var msg = $"The phone '{newCompany.Phone}' already exists in company ID: {existing.CompanyId}";
done

2022-09-11 07:51 UTC, serezhub commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/Server/CompareExchange.cs
> +                    // If this unique value doesn't already exist, store the new entity
done

2022-09-11 07:51 UTC, serezhub commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/Server/CompareExchange.cs
> +                    // Create a reference document where the ID is a unique value for future checks
done

2022-09-11 07:52 UTC, serezhub commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/Server/CompareExchange.cs
> +        {
I felt that it needed a brief summary for those who go straight to the code sample...
         // When you create documents that must not duplicate another record
        // you can create reference documents with a unique value such as phone or email as the IDs.
        // Then you can check if that value is already part of another document.

2022-09-11 09:35 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +#### When to Use Cluster-Wide Sessions or Node-Local Sessions
This is a dedicated bullet in the 'in page area'
make it a separate panel as done for the other bullets

2022-09-11 09:35 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
>  {PANEL/}
Replace this whole panel's content with:
=>

* Each cluster defines its policies and configurations, including conflict resolution.
Read [Consistency in a Globally Distributed System](...) to learn more about why global database modeling is 
more efficient this way.

* Creating a compare-exchange is a cluster-wide transaction and as such requires nodes' consensus.
Externally replicating such data is problematic as the target database may reside within a cluster that is in an 
unstable state where decisions cannot be made. In such a state writing the compare-exchange on the target 
side will not be persisted,

* Conflicts between documents that occur between 2 databases are solved with the help of the documents 
Change-Vector. Compare-exchange conflicts cannot be handled properly as they do not have a similar 
mechanism to resolve conflicts.

* To ensure unique values between 2 databases without using compare-exchange see [Example III]

2022-09-11 09:35 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +{NOTE/}
1'st bullet - The ATomic guard bullet is not relevant to this example and is confusing here
2'nd bullet - info is repeated below, no need to duplicate just in the following sentences
remove the note

2022-09-11 09:35 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +{NOTE/}
remove the bullet about atomic guards

2022-09-11 09:35 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +The reference documents' IDs will contain the unique values instead of the compare exchange items.
missing line break line

2022-09-11 09:35 UTC, Danielle9897 commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/Server/CompareExchange.cs
> +                        var msg = $"The phone '{newCompany.Phone}' already exists in company ID: {existing.CompanyId}";
just rename phoneReferenceDocument to phoneDocument

2022-09-11 09:37 UTC, Danielle9897 requested changes

2022-09-11 09:37 UTC, Danielle9897 commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/Server/CompareExchange.cs
> +            public class CompanyReference
rename class CompanyReference to `PhoneReference`

2022-09-12 11:53 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +{NOTE/}
done

2022-09-12 12:01 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +{NOTE/}
done

2022-09-12 12:03 UTC, serezhub commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/Server/CompareExchange.cs
> +            public class CompanyReference
done

2022-09-12 12:07 UTC, serezhub commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/Server/CompareExchange.cs
> +                    var existing = session.Load<CompanyReference>("phones/" + newCompany.Phone);
I wanted to make it clear that this var is a loaded reference document, so I shortened it to `phoneRefDocument` .
Now people don't need to scroll sideways to see the whole line.

2022-09-12 12:07 UTC, serezhub commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/Server/CompareExchange.cs
> +                        var msg = $"The phone '{newCompany.Phone}' already exists in company ID: {existing.CompanyId}";
I wanted to make it clear that this var is a loaded reference document, so I shortened it to phoneRefDocument .
Now people don't need to scroll sideways to see the whole line.

2022-09-12 12:10 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +#### When to Use Cluster-Wide Sessions or Node-Local Sessions
DONE

2022-09-12 12:35 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +The reference documents' IDs will contain the unique values instead of the compare exchange items.
done

2022-09-12 12:40 UTC, Danielle9897 requested changes

2022-09-12 14:12 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
>  {PANEL/}
Done:

{PANEL: Why Compare-Exchange Items are Not Replicated to External Databases }

* Each cluster defines its policies and configurations, and should ideally have sole responsibility for managing its own documents.  
  Read [Consistency in a Globally Distributed System](https://ayende.com/blog/196769-B/data-ownership-in-a-distributed-system) 
  to learn more about why global database modeling is more efficient this way.
   
* When creating a compare-exchange item in a cluster-wide transaction, a Raft consensus is required from the nodes in the database group.
  Externally replicating such data is problematic as the target database may reside within a cluster that is in an
  unstable state where Raft decisions cannot be made. In such a state, the compare-exchange item will not be persisted in the target database.

* Conflicts between documents that occur between two databases are solved with the help of the documents
  Change-Vector. Compare-exchange conflicts cannot be handled properly as they do not have a similar
  mechanism to resolve conflicts.

* To ensure unique values between 2 databases without using compare-exchange, see [Example III](../../../client-api/operations/compare-exchange/overview#example-iii---ensuring-unique-values-without-using-compare-exchange).

{PANEL/}

2022-09-12 14:30 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +    so that a consistent, unique key is guaranteed to all nodes in the cluster that are in the same database-group.
done

2022-09-13 06:28 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +* A non-session-specific compare-exchange [operation](../../../client-api/operations/what-are-operations) (described below)
done: 

* Using the [Session Method](../../../client-api/session/cluster-transaction):  
  If the session fails, the compare-exchange pair creation also fails.  
  None of the nodes in the group will have the new compare-exchange pair.

* Using the [Document Store operation](../../../client-api/operations/compare-exchange/put-compare-exchange-value):    
  If the operation fails, the compare-exchange pair is not created.

* Using the [Document Store operation within a session context](../../../client-api/operations/compare-exchange/overview#example-i---email-address-reservation):  
  If the session fails, the compare-exchange operation can still succeed  
  because store operations do not rely on the success of the session.  
  You will need to delete the compare-exchange pair explicitly.

2022-09-13 06:37 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
>  Provide the following when saving a **key**:
done. I checked if they're linked to from anywhere else in the documentation and they aren't

2022-09-18 12:44 UTC, Danielle9897 requested changes

2022-09-18 12:44 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
>  * **Compare-exchange** items are cluster-wide key/value pairs where the key is a unique identifier.
Add bullet:

Compare-exchange operations require cluster consensus to ensure consistency across all nodes.
Once a consensus is reached, the compare-exchange items are distributed through the Raft algorithm to all nodes in the database group

2022-09-18 12:44 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +{PANEL: Compare Exchange Persistence in Various Failure Scenarios}
Remove this panel
Info is now integrated in the latest comments I made

2022-09-18 12:44 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
>    (see [API Compare-exchange examples](../../../client-api/operations/compare-exchange/overview#example-i---email-address-reservation)).
give the current name article uses:

 API Compare-exchange examples => Example 1

2022-09-18 12:44 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
>    * If you create a compare-exchange key/value pair, you can decide what actions to implement when the Raft index increments.
key/value pair => item

2022-09-18 12:44 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +#### Performance cost of cluster-wide sessions
This note will be summarized + provide link to the new article (RDoc-2271)

i.e.=>
Cluster-wide transactions are more expensive than single-node transactions.
Learn more in [wide vs single....]()

2022-09-18 12:44 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +{PANEL: When to Use Cluster-Wide Sessions or Node-Local Sessions}
As discussed - remove this panel completely.
See [Rdoc-2271](https://issues.hibernatingrhinos.com/issue/RDoc-2271/Cluster-Wide-Session-vs-SingleLocal-Node-Session)

2022-09-18 12:44 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +* When creating a compare-exchange item in a cluster-wide transaction, a Raft consensus is required from the nodes in the database group.
When creating a compare-exchange item in a cluster-wide transaction,
=>
 When creating a compare-exchange item in

2022-09-18 12:44 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +  for similar functionality that can be externally replicated.
=>
To ensure unique values between 2 databases without using compare-exchange items see [Example III]

2022-09-18 12:44 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
>  * You can use compare-exchange items in various situations to protect or reserve a resource.
protect or reserve a resource.  
=>
reserve a unique resource.

2022-09-18 12:44 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +Compare-exchange items are not externally replicated to other clusters.
to other clusters.  => to other databases.

2022-09-18 12:44 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +In the following example, we use compare-exchange to reserve a shared resource **inside a single cluster**.
Remove the 'inside a single cluster'
Maybe use the same words as in Example I

2022-09-18 12:44 UTC, Danielle9897 commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/Server/CompareExchange.cs
> +        // Then you can check if that value is already part of another document.
=>
// When you need documents that must contain a unique value such as a phone, email, etc.,
// you can create reference documents that will have that unique value in their IDs.
// To know if a value already exists, all you need to do is check whether a reference document with such ID exists.

2022-09-18 12:44 UTC, Danielle9897 commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/Server/CompareExchange.cs
> +        class UniquePhoneReference
add a comment above this line:
=>
The reference document class

2022-09-18 12:44 UTC, Danielle9897 commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/Server/CompareExchange.cs
> +                    // If the new phone number doesn't already exist, store the new entity
add line break before this line

2022-09-19 13:37 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +    They prioritize consistency over performance to ensure ACIDity across the cluster.
Done

2022-09-19 13:37 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +Compare Exchange items are key/value pairs that allow you to perform cluster-wide interlocked distributed operations.
done

2022-09-19 13:37 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +* [Atomic Guards](../../../client-api/operations/compare-exchange/atomic-guards)
done

2022-09-19 13:37 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +  This can be done within or outside a session.
done

2022-09-19 13:37 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +  the Raft algorithm to all nodes in the database group in a cluster-wide transaction.
done

2022-09-19 13:37 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +  Compare-exchange items are created one at a time in Studio, on one node at a time.  They are then replicated automatically to all nodes in the cluster's database group.
done

2022-09-21 06:20 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
>  * **Compare-exchange** items are cluster-wide key/value pairs where the key is a unique identifier.
done

2022-09-21 06:28 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
>    (see [API Compare-exchange examples](../../../client-api/operations/compare-exchange/overview#example-i---email-address-reservation)).
* You can use compare-exchange items in various situations to protect or reserve a resource.  
   * [Example I - Email Address Reservation](../../../client-api/operations/compare-exchange/overview#example-i---email-address-reservation)  
   * [Example II - Reserve a Shared Resource](../../../client-api/operations/compare-exchange/overview#example-ii---reserve-a-shared-resource)  
* You can also create the same functionality as compare-exchange but be able to replicate it to other databases or clusters with the following approach.
   * [Example III - Ensuring Unique Values without Using Compare Exchange](../../../client-api/operations/compare-exchange/overview#example-iii---ensuring-unique-values-without-using-compare-exchange)

2022-09-21 06:35 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
>    * If you create a compare-exchange key/value pair, you can decide what actions to implement when the Raft index increments.
done

2022-09-21 06:39 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +#### Performance cost of cluster-wide sessions
Made a comment in RDoc-2271 to remove this section from the current article when the new one is published.

2022-09-21 06:41 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +{PANEL: When to Use Cluster-Wide Sessions or Node-Local Sessions}
Also in the [Rdoc-2271](https://issues.hibernatingrhinos.com/issue/RDoc-2271/Cluster-Wide-Session-vs-SingleLocal-Node-Session) comments

2022-09-21 06:42 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +* When creating a compare-exchange item in a cluster-wide transaction, a Raft consensus is required from the nodes in the database group.
done, without the "in"

2022-09-21 06:46 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +  for similar functionality that can be externally replicated.
done, but I don't think it is a good move because the DESCRIPTIVE red link would have made it easy to see this alternative without reading the whole thing.  Now that the link isn't descriptive, it's buried.

2022-09-21 06:53 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
>  * You can use compare-exchange items in various situations to protect or reserve a resource.
done

2022-09-21 06:55 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +Compare-exchange items are not externally replicated to other clusters.
done

2022-09-21 06:56 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +In the following example, we use compare-exchange to reserve a shared resource **inside a single cluster**.
doen

2022-09-21 06:59 UTC, serezhub commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/Server/CompareExchange.cs
> +        // Then you can check if that value is already part of another document.
done

2022-09-21 06:59 UTC, serezhub commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/Server/CompareExchange.cs
> +        class UniquePhoneReference
done

2022-09-21 07:00 UTC, serezhub commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/Server/CompareExchange.cs
> +                    // If the new phone number doesn't already exist, store the new entity
done

2022-10-02 18:46 UTC, Danielle9897 requested changes

2022-10-02 18:46 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
>    To ensure [atomicity](https://en.wikipedia.org/wiki/ACID#Atomicity), if even one session transaction fails, the entire [session will roll back](../../../client-api/session/what-is-a-session-and-how
a session === a transaction
so better to write something like:


if even one session transaction fails
=>
if even one operation within a session fails

2022-10-02 18:46 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +#### Performance cost of cluster-wide sessions
Remove this note completely from here.
We don't want to merge text that was not reviewed in its relevant context.
We will prioritize RDoc-2271.

2022-10-02 18:46 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +{PANEL: When to Use Cluster-Wide Sessions or Node-Local Sessions}
Remove this panel completely from here.
We don't want to merge text that was not reviewed in its relevant context.
We will prioritize RDoc-2271.

2022-10-02 18:46 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +  for similar functionality that can be externally replicated.
Keep it short:

=>
To ensure unique values between 2 databases without using compare-exchange items see [Example III]

2022-10-02 18:46 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +The scope is within the database group on a single cluster.
The scope is within the database group on a single cluster 
=>
The scope is within the database group

2022-10-02 18:46 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +* This compare-exchange item was [created as an operation](../../../client-api/operations/compare-exchange/overview#transaction-scope-for-compare-exchange-operations)
link is wrong

2022-10-02 18:46 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +  rather than with a [cluster-wide session](../../../client-api/session/cluster-transaction).
link to relevant section

2022-10-02 18:46 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +  Thus, if `session.SaveChanges` fails, then the email reservation is _not_ rolled back automatically. It is your responsibility to do so.
pls break line before 'It is your...'

2022-10-02 18:46 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +* The compare-exchange value that was saved can be accessed from `RQL` in a query:
=>
The compare-exchange value that was saved can be accessed in a query using  `CmpXchg`:

2022-10-02 18:46 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +    {CODE-TAB:csharp:Sync query_cmpxchg@Server\CompareExchange.cs /}
1. Sync is not a relevant title
2. Make 2 separate tabs, one for the Query with Linq and one for the Document query, 
as done in many other places.

2022-10-02 18:46 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +The scope is within the database group on a single cluster.
The scope is within the database group on a single cluster
=>
The scope is within the database group

2022-10-02 18:46 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +To establish uniqueness without using compare-exchange see [example III](../../../client-api/operations/compare-exchange/overview#example-iii---ensuring-unique-values-without-using-compare-exchange).
example III => Example III

2022-10-02 18:46 UTC, Danielle9897 commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/Server/CompareExchange.cs
> +        // When you need documents that must contain a unique value such as a phone or email,
add etc.

2022-10-02 18:46 UTC, Danielle9897 commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/Server/CompareExchange.cs
> +        // all you need to do is check whether a reference document with such ID exists.
use the shorter version that was written in my previous comment:
=>
// To know if a value already exists, all you need to do is check whether a reference document with such ID exists.

2022-10-03 09:27 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +   Learn more in [Cluster-wide sessions vs Single-node sessions](../../../client-api/operations/compare-exchange/overview#when-to-use-cluster-wide-sessions-or-node-local-sessions)
done

2022-10-03 09:29 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +     If the compare-exchange operation fails, the item is not created on any of the nodes.
But that is only true if it's not the document store operation...if it is a cluster-wide session.  Here we're talking about the operation, not the session.

2022-10-03 09:36 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +  You can manage a compare-exchange item from inside a [Cluster-Wide session](../../../client-api/session/cluster-transaction).
This isn't just about creating, but also about managing...also, then they wouldn't see the key intro about `TransactionMode = TransactionMode.ClusterWide`

2022-10-03 09:37 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +  You can manage a compare-exchange item as an [operation on the document store](../../../client-api/operations/compare-exchange/put-compare-exchange-value).
done here and in line 63

2022-10-03 09:57 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +    The Raft index increments as a result of a change in the compare-exchange value or metadata.
I didn't find any way to get the index value, other than to look at it in the studio.  
Also, it only changes when the compare-exchange value changes, not if the document changes.  

So, I changed it to 
* If you create a compare-exchange item, you can decide what actions to implement when the compare-exchange [value changes](../client-api/operations/compare-exchange/put-compare-exchange-value#example-ii---update-an-existing-key).  

If this isn't what you meant, please write exactly what you'd like me to change this line to.

2022-10-03 10:02 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
>    To ensure [atomicity](https://en.wikipedia.org/wiki/ACID#Atomicity), if even one session transaction fails, the entire [session will roll back](../../../client-api/session/what-is-a-session-and-how
Operation isn't good because that word is reserved for document store operations.

if even one action within a session fails

2022-10-03 10:08 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +The scope is within the database group on a single cluster.
That would be confusing.  It's important that people know that they're only relevant to one cluster.  
I can think that if I have a database replicated to various clusters, the database group is in more than one cluster.

2022-10-03 10:09 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +* This compare-exchange item was [created as an operation](../../../client-api/operations/compare-exchange/overview#transaction-scope-for-compare-exchange-operations)
(../../../client-api/operations/compare-exchange/overview#how-to-create-and-manage-compare-exchange-items)

2022-10-03 10:11 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +  rather than with a [cluster-wide session](../../../client-api/session/cluster-transaction).
again, this would cause people to miss the key step of writing `TransactionMode = TransactionMode.ClusterWide`

2022-10-03 10:12 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +  Thus, if `session.SaveChanges` fails, then the email reservation is _not_ rolled back automatically. It is your responsibility to do so.
done

2022-10-03 10:12 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +* The compare-exchange value that was saved can be accessed from `RQL` in a query:
done

2022-10-03 10:19 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +    {CODE-TAB:csharp:Sync query_cmpxchg@Server\CompareExchange.cs /}
done..changed to Query-LINQ

2022-10-03 10:20 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +The scope is within the database group on a single cluster.
that would be confusing...see above

2022-10-03 10:21 UTC, serezhub commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/Server/CompareExchange.cs
> +        // When you need documents that must contain a unique value such as a phone or email,
done

2022-10-03 10:24 UTC, serezhub commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/Server/CompareExchange.cs
> +        // all you need to do is check whether a reference document with such ID exists.
Short isn't good if it doesn't explain that you explicitly create reference documents every time you create a document that has a value that must be unique.  One more sentence adds a lot more clarity to this example.

2022-10-06 12:39 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +#### Performance cost of cluster-wide sessions
pls apply comment

2022-10-18 14:09 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +   Cluster-wide transactions prioritize consistency over performance -
done

2022-10-18 14:12 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +     You will need to delete the compare-exchange item explicitly if you don't want it to persist.
I changed it word for word except for the last sentence where I added a few words to clarify...
> You will need to delete the compare-exchange item explicitly upon session failure if you don't want it to persist.

2022-10-18 14:18 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +  * **Metadata**
* **Metadata** - Like document metadata, it is written in JSON format where the key is prefixed with the `@` character.

2022-10-18 14:20 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +* If you create a compare-exchange item, you can decide what actions to implement when the compare-exchange [value changes](../client-api/operations/compare-exchange/put-compare-exchange-value#exampl
done, happily

2022-10-18 14:34 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +* This compare-exchange item was [created as an operation](../../../client-api/operations/compare-exchange/overview#how-to-create-and-manage-compare-exchange-items)
done

2022-10-18 14:35 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/compare-exchange/overview.dotnet.markdown
> +* The compare-exchange value that was saved can be accessed in a query using CmpXchg:
done

2022-10-18 14:35 UTC, serezhub commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/Server/CompareExchange.cs
> +        // When you create documents that must contain a unique value such as a phone or email, etc,
done

2022-10-19 13:09 UTC, Danielle9897 approved these changes

2022-10-19 13:10 UTC, Danielle9897 approved these changes

2022-10-19 13:12 UTC, Danielle9897 approved these changes

2022-10-19 13:15 UTC, Danielle9897 approved these changes

2022-10-19 13:33 UTC, Danielle9897 approved these changes

2022-10-19 13:40 UTC, Danielle9897 commented
There are many 'approvals' here above - as I pushed the button quite a few times
since GitHub was very unresponsive on my end today

2022-10-21 07:10 UTC, merged