RDoc-2135-Put-Command-5.0+ changed line 39 in sample file
ravendb/docs pull request #1519
Opened 2022-06-20 06:58 UTC by serezhub

I only changed one line - line 39 in the sample file

2022-06-26 15:27 UTC, reebhub requested changes

2022-06-26 15:27 UTC, reebhub commented on Documentation/5.0/Samples/csharp/Raven.Documentation.Samples/ClientApi/Commands/Documents/Put.cs
> +                var blittableDoc = session.Advanced.JsonConverter.ToBlittable(doc, docInfo);
* you updated the sample without updating the method's prototype and explanations about it
* please check in which version the new method replaced the old one, go through the documentation and make sure we document only the correct method.

2022-06-26 15:27 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/client-api/commands/documents/put.dotnet.markdown
> +| **document** | BlittableJsonReaderObject | The document to store. You may use `session.Advanced.EntityToBlittable.ConvertEntityToBlittable` to convert your entity to a `BlittableJsonReaderObject` |
you updated the method usage in the sample but left the old explanations here. (and in other copies of the article, e.g. in version 5.2)

2022-06-26 17:11 UTC, serezhub commented on Documentation/5.0/Samples/csharp/Raven.Documentation.Samples/ClientApi/Commands/Documents/Put.cs
> +                var blittableDoc = session.Advanced.JsonConverter.ToBlittable(doc, docInfo);
Added //comments to explain the sample.

We're supposed to change it in 5.0 plus.  I copied this into 5.0 and checked that it bubbles up to 6.0.

2022-06-26 17:13 UTC, serezhub commented on Documentation/5.0/Raven.Documentation.Pages/client-api/commands/documents/put.dotnet.markdown
> +| **document** | BlittableJsonReaderObject | The document to store. You may use `session.Advanced.EntityToBlittable.ConvertEntityToBlittable` to convert your entity to a `BlittableJsonReaderObject` |
I see.  Good catch. Done

2022-06-26 23:05 UTC, reebhub commented on Documentation/5.0/Samples/csharp/Raven.Documentation.Samples/ClientApi/Commands/Documents/Put.cs
> +                var blittableDoc = session.Advanced.JsonConverter.ToBlittable(doc, docInfo);
not sure what you changed, the 5.2 explanation remained the same.
please go through the versions as many times as you need and finish it properly.

2022-06-27 08:46 UTC, serezhub commented on Documentation/5.0/Samples/csharp/Raven.Documentation.Samples/ClientApi/Commands/Documents/Put.cs
> +                var blittableDoc = session.Advanced.JsonConverter.ToBlittable(doc, docInfo);
Done.

2022-07-18 06:30 UTC, reebhub approved these changes

2022-07-18 09:48 UTC, merged