RDoc-2177-Doc-Extensions-Overview - 5.0-6.0
ravendb/docs pull request #1520
Opened 2022-06-20 13:55 UTC by serezhub

2022-06-26 18:11 UTC, reebhub requested changes

2022-06-26 18:11 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/document-extensions/overview-extensions.markdown
> +#### Seeing which types of extensions are added to sets of documents
Document Extensions Flags

2022-06-26 18:11 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/document-extensions/overview-extensions.markdown
> +#### Managing extensions in specific documents
Document Extensions View

2022-06-26 18:11 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/overview-extensions.markdown
> +![Managing Document Extensions in Studio](images/extensions-managing-single-doc.png "Managing Document Extensions in Studio")
* frame each extension icon, not just the time series
* provide minimal caption for each (time series settings, counters settings, etc.)
* remove the lower frames and drops

2022-06-27 07:05 UTC, serezhub commented on Documentation/5.0/Raven.Documentation.Pages/document-extensions/overview-extensions.markdown
> +* Document extensions are data or attachments that are associated with documents.
Done. 
* Document extensions are stored separately from their parent documents and are referenced in the parent documents' meta-data.  
  Separate storage ensures that most modifications of an extension don't change the parent document,  
  thus reducing trips to the server and activation of tasks such as ETL that are triggered by document changes.  
   * Actions such as creating or deleting an extension do change the parent documents' meta-data.

2022-06-27 07:32 UTC, serezhub commented on Documentation/5.0/Raven.Documentation.Pages/document-extensions/overview-extensions.markdown
> +
Done
{PANEL: The Document Extensions}

* [Counters](../document-extensions/counters/overview)  
  RavenDB's distributed counters are numeric data variables that can be added to documents and used
  for various counting tasks.

* [Attachments](../document-extensions/attachments/what-are-attachments)  
  Attachments are images, PDF files, videos, and other types of binary streams that are associated with parent documents.  

* [Time Series](../document-extensions/timeseries/overview)  
  Time series are vectors of data that collect values over time, store the values consecutively across the cluster, 
  and manage the collected data with high efficiency and performance.

* [Revisions](../document-extensions/revisions/overview)  
  Document Revisions are snapshots of documents and their extensions that can be created to give access to a document's history.  

{PANEL/}

2022-06-27 07:32 UTC, serezhub commented on Documentation/5.0/Raven.Documentation.Pages/document-extensions/overview-extensions.markdown
> +
done

2022-06-27 07:45 UTC, serezhub commented on Documentation/5.0/Raven.Documentation.Pages/document-extensions/overview-extensions.markdown
> +3. **Extensions**
done

2022-06-27 07:46 UTC, serezhub commented on Documentation/5.0/Raven.Documentation.Pages/document-extensions/overview-extensions.markdown
> +#### Seeing which types of extensions are added to sets of documents
done

2022-06-27 07:49 UTC, serezhub commented on Documentation/5.0/Raven.Documentation.Pages/document-extensions/overview-extensions.markdown
> +#### Managing extensions in specific documents
done

2022-06-27 08:15 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/document-extensions/overview-extensions.markdown
> +![Managing Document Extensions in Studio](images/extensions-managing-single-doc.png "Managing Document Extensions in Studio")
done

2022-07-19 10:29 UTC, serezhub commented on Documentation/5.0/Raven.Documentation.Pages/document-extensions/overview-extensions.markdown
> +
I minimized the bullet and made it easier to understand by separating the two thihngs:

* Document extensions are stored separately to make sure that modifying an extension value (e.g. a counter 
  or a time series entry) will not modify its parent document.

* Creating or deleting an extension changes the parent documents' meta-data. 
  This document change triggers trips to the server as well as tasks such as indexing, ETL, and External Replication.

2022-08-14 21:22 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/document-extensions/overview-extensions.markdown
> +* Document extensions are data or attachments that are associated with documents.
"stored separately to make sure that.." --> "stored separately so.."
"the parent documents'" --> "the parent document's"
"triggers trips to the server as well as tasks such as indexing, ETL, and External Replication." --> "may trigger indexing, ETL tasks, and various other operations."

2022-08-14 21:42 UTC, reebhub commented on Documentation/5.0/Raven.Documentation.Pages/document-extensions/overview-extensions.markdown
> +
i understand your urge to write the attachments description in a way that resembles that of the other extensions, but the current description doesn't work well (because you use non existing terms to describe something that didn't happen yet - the docs aren't parents before the attachments are made and the files aren't attachments before they are attached to documents).

2022-08-15 11:44 UTC, serezhub commented on Documentation/5.0/Raven.Documentation.Pages/document-extensions/overview-extensions.markdown
> +* Document extensions are data or attachments that are associated with documents.
done

2022-08-15 11:51 UTC, serezhub commented on Documentation/5.0/Raven.Documentation.Pages/document-extensions/overview-extensions.markdown
> +
I used the wording of the attachments overview article 
> Attachments are binary streams (videos, images, PDF, etc.) that can be bound to an existing document.

2022-08-21 08:57 UTC, reebhub approved these changes

2022-08-23 08:46 UTC, merged