RDoc-2105-Add-Link-Querying-Distinct also clarified and updated forma…
ravendb/docs pull request #1533
Opened 2022-07-05 11:21 UTC by serezhub

…tting

2022-07-20 06:41 UTC, grisha-kotler approved these changes

2022-07-31 22:00 UTC, reebhub requested changes

2022-08-01 09:44 UTC, serezhub commented on Documentation/4.0/Raven.Documentation.Pages/indexes/querying/distinct.dotnet.markdown
> +The same result might be achieved by creating a [Map-Reduce](../../indexes/map-reduce-indexes) index that aggregates data by the field where you want a distinct value.
map-reduce is only relevant for Distinct().Count().  
I also added a link to Oren's article on the topic, which Grisha approved.

I clarified that map-reduce is an alternative to distinct.count by changing the intro to this paragraph to this: 
> You can also ensure that queries do not count duplicate items by creating a [Map-Reduce]

2022-08-25 12:31 UTC, reebhub commented on Documentation/4.0/Raven.Documentation.Pages/indexes/querying/distinct.java.markdown
* please remove the "info" clause
* the title can be ## or you can leave it ### and add a --- yourself

2022-08-25 12:37 UTC, reebhub commented on Documentation/4.0/Raven.Documentation.Pages/indexes/querying/distinct.dotnet.markdown
> +#### Map-Reduce Index Sample:
this is currently under the "Performance Cost and an Alternative Approach" section, does it belong here?

2022-08-25 13:53 UTC, serezhub commented on Documentation/4.0/Raven.Documentation.Pages/indexes/querying/distinct.java.markdown
done

2022-08-25 13:55 UTC, serezhub commented on Documentation/4.0/Raven.Documentation.Pages/indexes/querying/distinct.dotnet.markdown
> +#### Map-Reduce Index Sample:
Yes.  I asked Oren if the distinct.count alternative is about map-reduce indexing exclusively.  He said that map-reduce is **the** alternative to distinct.count, so the map-reduce example indeed belongs in this section.

2022-09-18 19:28 UTC, Danielle9897 requested changes

2022-09-18 19:28 UTC, Danielle9897 commented on Documentation/4.0/Raven.Documentation.Pages/indexes/querying/distinct.dotnet.markdown
>  {CODE:csharp distinct_3_1@Indexes\Querying\Distinct.cs /}
Code example should be similar to:
[https://demo.ravendb.net/demos/csharp/static-indexes/map-reduce-index](https://demo.ravendb.net/demos/csharp/static-indexes/map-reduce-index)

The `IndexEntry` class should have both the Country & the CountryCount
This way the aggregated count value is calculated by the index and is always up-to-date,
which is the point here...

Also, modify the query part accordingly.

2022-09-21 09:19 UTC, serezhub commented on Documentation/4.0/Raven.Documentation.Pages/indexes/querying/distinct.dotnet.markdown
>  The `Distinct` method allows you to remove duplicates from the result. Items are compared based on the fields listed in the `select` section of the query.
done

2022-09-21 09:33 UTC, serezhub commented on Documentation/4.0/Raven.Documentation.Pages/indexes/querying/distinct.dotnet.markdown
> +   * [Sample Query with Distinct Method](../../indexes/querying/distinct#sample-query-with-the-distinct-method)
done

2022-09-21 09:33 UTC, serezhub commented on Documentation/4.0/Raven.Documentation.Pages/indexes/querying/distinct.dotnet.markdown
> +   * [Paging with the Distinct Method](../../indexes/querying/distinct#paging-with-the-distinct-method)
done

2022-09-21 09:40 UTC, serezhub commented on Documentation/4.0/Raven.Documentation.Pages/indexes/querying/distinct.dotnet.markdown
> +   * [Count](../../indexes/querying/distinct#count)
done.

2022-09-21 09:40 UTC, serezhub commented on Documentation/4.0/Raven.Documentation.Pages/indexes/querying/distinct.dotnet.markdown
> +   * [Performance Cost and an Alternative Approach](../../indexes/querying/distinct#performance-cost-and-an-alternative-approach)
done

2022-09-21 10:02 UTC, serezhub commented on Documentation/4.0/Raven.Documentation.Pages/indexes/querying/distinct.dotnet.markdown
> +A special approach must be used when calling the `distinct()` method while paging.
done

2022-09-28 07:43 UTC, serezhub commented on Documentation/4.0/Raven.Documentation.Pages/indexes/querying/distinct.dotnet.markdown
> +RavenDB supports using the `Distinct()` operation in combination with the `Count()` operation.
done

2022-09-28 08:53 UTC, serezhub commented on Documentation/4.0/Raven.Documentation.Pages/indexes/querying/distinct.dotnet.markdown
>  {CODE-TABS/}
1. In RQL I only got as far as `from "Orders" select distinct ShipTo.Country`.  As soon as I added the count word, I got an error.  
2. done

2022-09-28 09:00 UTC, serezhub commented on Documentation/4.0/Raven.Documentation.Pages/indexes/querying/distinct.dotnet.markdown
> +## Performance Cost and an Alternative Approach
We don't have an article about Count
It is used in the [projection](https://ravendb.net/docs/article-page/5.4/Csharp/indexes/querying/projections#example-vii---projection-with-a-count-predicate) example, it's in a while() condition in 3 [Paging](https://ravendb.net/docs/article-page/5.4/Csharp/indexes/querying/paging#paging-through-tampered-results) examples, and in the [filtering](https://ravendb.net/docs/article-page/5.4/Csharp/indexes/querying/filtering#where---nested-property) article.

2022-09-28 09:11 UTC, serezhub commented on Documentation/4.0/Raven.Documentation.Pages/indexes/querying/distinct.dotnet.markdown
> +Learn how to use the alternative approach efficiently in the article [Implementing a count(distinct) query in RavenDB](https://ravendb.net/articles/implementing-a-countdistinct-query-in-ravendb).
done

2022-09-28 09:13 UTC, serezhub commented on Documentation/4.0/Raven.Documentation.Pages/indexes/querying/distinct.dotnet.markdown
> +Please keep in mind that `Distinct()` might not be efficient for large sets of data due to the need to scan all of the index results in order to find all the unique values.
done

2022-09-28 09:28 UTC, serezhub commented on Documentation/4.0/Raven.Documentation.Pages/indexes/querying/distinct.dotnet.markdown
> +Queries process all of the data assigned to them each time they are activated.
done

2022-10-02 15:13 UTC, Danielle9897 requested changes

2022-10-02 15:13 UTC, Danielle9897 commented on Documentation/4.0/Raven.Documentation.Pages/indexes/querying/distinct.dotnet.markdown
> +See [Implementing a count(distinct) query in RavenDB](https://ravendb.net/articles/implementing-a-countdistinct-query-in-ravendb).
=>
See article [xxx]() for such an example.

2022-10-02 15:13 UTC, Danielle9897 commented on Documentation/4.0/Raven.Documentation.Pages/indexes/querying/distinct.dotnet.markdown
> +  Queries, on the other hand, process all of the data assigned to them each time they are activated.
Remove the above sentence about "Queries, on the other hand...."

2022-10-02 15:13 UTC, Danielle9897 commented on Documentation/4.0/Samples/csharp/Raven.Documentation.Samples/Indexes/Querying/Distinct.cs
> +                    // The query calls the map-reduce index defined above
=>
Query the map-reduce index defined above

2022-10-18 13:19 UTC, serezhub commented on Documentation/4.0/Raven.Documentation.Pages/indexes/querying/distinct.dotnet.markdown
>  {CODE:csharp distinct_3_1@Indexes\Querying\Distinct.cs /}
done

2022-10-18 13:41 UTC, serezhub commented on Documentation/4.0/Raven.Documentation.Pages/indexes/querying/distinct.dotnet.markdown
> +The `Distinct` method allows you to remove duplicates from the result.
done

2022-10-18 13:42 UTC, serezhub commented on Documentation/4.0/Raven.Documentation.Pages/indexes/querying/distinct.dotnet.markdown
> +Similar to ToList(), Count() executes the query on the server-side.
done

2022-10-18 13:52 UTC, serezhub commented on Documentation/4.0/Raven.Documentation.Pages/indexes/querying/distinct.dotnet.markdown
> +## Performance Cost And Alternative Approaches
done

2022-10-18 13:53 UTC, serezhub commented on Documentation/4.0/Raven.Documentation.Pages/indexes/querying/distinct.dotnet.markdown
> +See [Implementing a count(distinct) query in RavenDB](https://ravendb.net/articles/implementing-a-countdistinct-query-in-ravendb).
done

2022-10-18 13:55 UTC, serezhub commented on Documentation/4.0/Samples/csharp/Raven.Documentation.Samples/Indexes/Querying/Distinct.cs
> +                    // The query calls the map-reduce index defined above
done

2022-10-19 09:33 UTC, Danielle9897 requested changes

2022-10-19 09:33 UTC, Danielle9897 commented on Documentation/4.0/Samples/csharp/Raven.Documentation.Samples/Indexes/Querying/Distinct.cs
> +                    // The query calls the map-reduce index defined above
=>
Query the map-reduce index defined above

2022-10-19 10:33 UTC, Danielle9897 approved these changes

2022-10-20 06:16 UTC, serezhub commented on Documentation/4.0/Samples/csharp/Raven.Documentation.Samples/Indexes/Querying/Distinct.cs
> +                    // The query calls the map-reduce index defined above
done

2022-10-21 07:09 UTC, merged