RDoc-2019-Filter-Non-Existing-Field
ravendb/docs pull request #1534
Opened 2022-07-07 07:05 UTC by serezhub

For some reason, it didn't give me the choice but to re-align the docs.json files.  I tried using undo, but it didn't help this time.

2022-07-17 23:14 UTC, reebhub requested changes

2022-07-17 23:14 UTC, reebhub commented on Documentation/4.1/Raven.Documentation.Pages/client-api/session/querying/how-to-filter-by-non-existing-field.dotnet.markdown
> +from "collection name"
you combine the explanations about a method's parameters and a sample that uses this method in the same block and use a table to explain the parameters passed in the sample. this is very strange.
- provide a method signature and explain its params in the table
- provide a workable sample that can actually work with the sample data, this semi-query with semi-parameters isn't the immediate solutions readers would like to get.

2022-07-17 23:14 UTC, reebhub commented on Documentation/4.1/Raven.Documentation.Pages/client-api/session/querying/how-to-filter-by-non-existing-field.dotnet.markdown
> +   Click to see Studio indexing tools.
if the reader doesn't know Studio this page is too little
and if the reader knows Studio this is too much
please minimize the explanations to what's relevant to the issue at hand (the query itself and its results) and send the reader to additional explanations about the query view in the dedicated Studio page.

2022-07-19 09:07 UTC, serezhub commented on Documentation/4.1/Raven.Documentation.Pages/client-api/session/querying/how-to-filter-by-non-existing-field.dotnet.markdown
> +from "collection name"
Done

2022-07-19 09:35 UTC, serezhub commented on Documentation/4.1/Raven.Documentation.Pages/client-api/session/querying/how-to-filter-by-non-existing-field.dotnet.markdown
> +   Click to see Studio indexing tools.
In Slack we decided to leave it as is.

2022-07-31 22:23 UTC, reebhub commented on Documentation/4.1/Raven.Documentation.Pages/client-api/session/querying/how-to-filter-by-non-existing-field.dotnet.markdown
> +from "collection name"
that's not a signature but it's probably clear enough.
i don't think you need all the explanations around `fieldName` and `fieldName2`, they are the only `fieldName` and `fieldName2` around.

2022-07-31 22:24 UTC, reebhub commented on Documentation/4.1/Raven.Documentation.Pages/client-api/session/querying/how-to-filter-by-non-existing-field.dotnet.markdown
> +   Click to see Studio indexing tools.
ok

2022-08-01 10:21 UTC, serezhub commented on Documentation/4.1/Raven.Documentation.Pages/client-api/session/querying/how-to-filter-by-non-existing-field.dotnet.markdown
> +from "collection name"
I explained them to make it clear that one of them is a field that exists universally and the other is a field that is missing in some docs. I changed the parameter names to simply  `fieldName` and `fieldName2 (after .Not)`

2022-08-04 18:05 UTC, Danielle9897 requested changes

2022-08-04 18:05 UTC, Danielle9897 commented on Documentation/4.1/Raven.Documentation.Pages/client-api/session/querying/how-to-filter-by-non-existing-field.dotnet.markdown
> +   (The field "Freight" was explicitly removed from these Northwind documents for this example.)
pls add a line break before this line, so it will start at a new line

2022-08-04 18:05 UTC, Danielle9897 commented on Documentation/4.1/Raven.Documentation.Pages/client-api/session/querying/how-to-filter-by-non-existing-field.dotnet.markdown
> +   You can click it to see the Studio indexing tools available for this index.
The dropdown options are not so much about tools, so write something simple such as:

=>
Click it to see the available Studio options for this index.

2022-08-07 05:27 UTC, serezhub commented on Documentation/4.1/Raven.Documentation.Pages/client-api/session/querying/how-to-filter-by-non-existing-field.dotnet.markdown
> +The index definition must also index a field that exists in every document (such as `Id`) so that it will include every document in the collection.
done

2022-08-07 05:28 UTC, serezhub commented on Documentation/4.1/Raven.Documentation.Pages/client-api/session/querying/how-to-filter-by-non-existing-field.dotnet.markdown
> +This way, the index includes all of the documents in the collection,
done

2022-08-07 05:37 UTC, serezhub commented on Documentation/4.1/Raven.Documentation.Pages/client-api/session/querying/how-to-filter-by-non-existing-field.dotnet.markdown
> +SYNTAX
1. Done.
2. I asked Reeb because although this makes sense, it goes against our normal docs flow.

2022-08-07 05:40 UTC, serezhub commented on Documentation/4.1/Raven.Documentation.Pages/client-api/session/querying/how-to-filter-by-non-existing-field.dotnet.markdown
> +| **T** | string | The type of object that you want to search. |
It's an object in the collection.  It's one Order in Orders. 
I clarified it with...
> An object in a collection (singular of the collection name - e.g. Order from the collection Orders).

2022-08-07 06:17 UTC, serezhub commented on Documentation/4.1/Raven.Documentation.Pages/client-api/session/querying/how-to-filter-by-non-existing-field.dotnet.markdown
> +QUERY SAMPLE CODE
I ran out of hashtags.  I already used ### and ####, so I needed a way to differentiate the title from the text for easy scanning.

2022-08-07 06:34 UTC, serezhub commented on Documentation/4.1/Samples/csharp/Raven.Documentation.Samples/ClientApi/Session/Querying/HowToFilterByField.cs
> +                            // Create a list of documents in `results` from Order
done

2022-08-07 06:34 UTC, serezhub commented on Documentation/4.1/Samples/csharp/Raven.Documentation.Samples/ClientApi/Session/Querying/HowToFilterByField.cs
> +                                // Call the static index
done

2022-08-07 06:35 UTC, serezhub commented on Documentation/4.1/Samples/csharp/Raven.Documentation.Samples/ClientApi/Session/Querying/HowToFilterByField.cs
> +                                // Make sure that the index has finished before listing the results
>Verify that the index is not stale (optional)

2022-08-07 06:36 UTC, serezhub commented on Documentation/4.1/Samples/csharp/Raven.Documentation.Samples/ClientApi/Session/Querying/HowToFilterByField.cs
> +                            // `results` will contain the list of incomplete documents.
done

2022-08-07 06:37 UTC, serezhub commented on Documentation/4.1/Raven.Documentation.Pages/client-api/session/querying/how-to-filter-by-non-existing-field.dotnet.markdown
> +| **T** | string | The type of object that you want to search. |
Done

2022-08-07 07:43 UTC, serezhub commented on Documentation/4.1/Raven.Documentation.Pages/client-api/session/querying/how-to-filter-by-non-existing-field.dotnet.markdown
> +It then lists the documents that do not have the specified field.
done. Good catch

2022-08-07 07:52 UTC, serezhub commented on Documentation/4.1/Raven.Documentation.Pages/client-api/session/querying/how-to-filter-by-non-existing-field.dotnet.markdown
> +Another option is to query the collection, which creates an auto-index to satisfy the query.
>Another option is to query the collection for the missing field.  
This will either create a new auto-index or add the new field to an existing auto-index if it indexes the same collection.

2022-08-07 08:02 UTC, serezhub commented on Documentation/4.1/Raven.Documentation.Pages/client-api/session/querying/how-to-filter-by-non-existing-field.dotnet.markdown
> +Then we use the keywords `not exists()` and specify the field that does not exist in some of the documents.
> See the example and query syntax descriptions below:

2022-08-07 08:03 UTC, serezhub commented on Documentation/4.1/Raven.Documentation.Pages/client-api/session/querying/how-to-filter-by-non-existing-field.dotnet.markdown
> +{PANEL: How to use Studio to filter by non-existing field}
done

2022-08-07 08:07 UTC, serezhub commented on Documentation/4.1/Raven.Documentation.Pages/client-api/session/querying/how-to-filter-by-non-existing-field.dotnet.markdown
> +   Click to see Studio indexing tools.
>Click to see the indexing menu items.

2022-08-07 08:08 UTC, serezhub commented on Documentation/4.1/Raven.Documentation.Pages/client-api/session/querying/how-to-filter-by-non-existing-field.dotnet.markdown
> +   Select to open the Studio query interface.
done

2022-08-07 08:09 UTC, serezhub commented on Documentation/4.1/Raven.Documentation.Pages/client-api/session/querying/how-to-filter-by-non-existing-field.dotnet.markdown
> +3. **Code text editor**
done

2022-08-07 08:11 UTC, serezhub commented on Documentation/4.1/Raven.Documentation.Pages/client-api/session/querying/how-to-filter-by-non-existing-field.dotnet.markdown
> +4. **Run Code**
done

2022-08-07 08:11 UTC, serezhub commented on Documentation/4.1/Raven.Documentation.Pages/client-api/session/querying/how-to-filter-by-non-existing-field.dotnet.markdown
> +   (The field "Freight" was explicitly removed from these Northwind documents for this example.)
done

2022-08-07 08:12 UTC, serezhub commented on Documentation/4.1/Raven.Documentation.Pages/client-api/session/querying/how-to-filter-by-non-existing-field.dotnet.markdown
> +   You can click it to see the Studio indexing tools available for this index.
done

2022-08-25 09:49 UTC, reebhub commented on Documentation/4.1/Raven.Documentation.Pages/client-api/session/querying/how-to-filter-by-non-existing-field.dotnet.markdown
> +{PANEL: How to use Studio to filter by non-existing field}
users currently have to look at the image and understand what you mean in it, and then type the sample themselves.
- please add a preface that explains what you're showing.
- please add the sample in text format.

you can combine the two in something like "you can use Studio to find missing fields using a query such as.." + the sample in text format, and the screenshot below that.

2022-08-25 10:31 UTC, serezhub commented on Documentation/4.1/Raven.Documentation.Pages/client-api/session/querying/how-to-filter-by-non-existing-field.dotnet.markdown
> +{PANEL: How to use Studio to filter by non-existing field}
done

{PANEL: Use Studio to filter by non-existing field}

You can also use Studio to find missing fields with an RQL query such as:  

```
from "Orders"  
where exists("Company") and not exists("Freight")
```

Like the [LINQ syntax examples above](../../../client-api/session/querying/how-to-filter-by-non-existing-field#query-a-static-index), 
we must first call a field that exists in every document in the collection 
and then the field that does not exist in some of them.

2022-08-25 14:26 UTC, Danielle9897 requested changes

2022-08-25 14:26 UTC, Danielle9897 commented on Documentation/4.1/Raven.Documentation.Pages/client-api/session/querying/how-to-filter-by-non-existing-field.dotnet.markdown
> +Query the index `Orders_ByFreight` and filter documents where `freight` does not exist.
The RQL example shows a dynamic query, it only queries the collection.
Should query the index.

2022-08-25 14:26 UTC, Danielle9897 commented on Documentation/4.1/Samples/csharp/Raven.Documentation.Samples/ClientApi/Session/Querying/HowToFilterByField.cs
> +                        .WhereExists("missing field")
missing field => fieldName

(since that is how the param is addressed in the parameters table..., and to be consistent w/ previous syntax...)

or... better yet:

change in both places/syntaxes to be: **`missingFieldName`**

2022-08-25 14:26 UTC, Danielle9897 commented on Documentation/4.1/Raven.Documentation.Pages/client-api/session/querying/how-to-filter-by-non-existing-field.dotnet.markdown
> +Like the [LINQ syntax examples above](../../../client-api/session/querying/how-to-filter-by-non-existing-field#query-a-static-index),
=> Like the RQL syntax... 
(In studio we write only RQL in the query view)

2022-08-25 14:26 UTC, Danielle9897 commented on Documentation/4.1/Raven.Documentation.Pages/client-api/session/querying/how-to-filter-by-non-existing-field.dotnet.markdown
> +LINQ SYNTAX:
I have read the whole page and the reading flow is confusing like this
Need to move the **Syntax part** (and the param table) below the **Sample Query** part

1. Note: that is also how it is done in the auto-index panel 
2. Whatever the convention is - when really reading this article and learning from it - understanding is much better if you see that sample first.

2022-08-25 14:26 UTC, Danielle9897 commented on Documentation/4.1/Raven.Documentation.Pages/client-api/session/querying/how-to-filter-by-non-existing-field.dotnet.markdown
> +   Click to see the indexing menu items.
Why 'indexing' ?
The menu item title is 'Indexes'
=> Click to see the Indexes menu items

('indexing' is usually used as the verb when the index is working, it is 'indexing')

2022-08-28 06:08 UTC, serezhub commented on Documentation/4.1/Raven.Documentation.Pages/indexes/querying/filtering.dotnet.markdown
> +* [RQL](../../indexes/querying/what-is-rql)) - Raven Query Language
done

2022-08-28 06:09 UTC, serezhub commented on Documentation/4.1/Raven.Documentation.Pages/indexes/querying/filtering.dotnet.markdown
> +To find all documents in a collection that don't have a specified field, see [How to Filter by Non-Existing Field](../../client-api/session/querying/how-to-filter-by-non-existing-field)
done

2022-08-28 06:13 UTC, serezhub commented on Documentation/4.1/Raven.Documentation.Pages/indexes/querying/filtering.dotnet.markdown
> +and there aren't any other fields involved then such a query, it is called a "collection query".
done

2022-08-28 06:13 UTC, serezhub commented on Documentation/4.1/Raven.Documentation.Pages/indexes/querying/filtering.dotnet.markdown
> +It means that querying by ID doesn't use an auto-index and has no extra cost. In terms of efficiency, it is the same as
done

2022-08-28 06:33 UTC, serezhub commented on Documentation/4.1/Raven.Documentation.Pages/client-api/session/querying/how-to-filter-by-non-existing-field.dotnet.markdown
> +Query the index `Orders_ByFreight` and filter documents where `freight` does not exist.
wow...good catch!
> from index "Orders/ByFreight"

2022-08-28 06:36 UTC, serezhub commented on Documentation/4.1/Samples/csharp/Raven.Documentation.Samples/ClientApi/Session/Querying/HowToFilterByField.cs
> +                        .WhereExists("missing field")
changed sample and table params to missingFieldName

2022-08-28 07:36 UTC, serezhub commented on Documentation/4.1/Raven.Documentation.Pages/client-api/session/querying/how-to-filter-by-non-existing-field.dotnet.markdown
> +Like the [LINQ syntax examples above](../../../client-api/session/querying/how-to-filter-by-non-existing-field#query-a-static-index),
Introduced the sentence with 
> In Studio we always use [RQL](../../../indexes/querying/what-is-rql) syntax.

2022-08-28 08:21 UTC, serezhub commented on Documentation/4.1/Raven.Documentation.Pages/client-api/session/querying/how-to-filter-by-non-existing-field.dotnet.markdown
> +LINQ SYNTAX:
done

2022-08-28 08:22 UTC, serezhub commented on Documentation/4.1/Raven.Documentation.Pages/client-api/session/querying/how-to-filter-by-non-existing-field.dotnet.markdown
> +   Click to see the indexing menu items.
done

2022-08-28 10:43 UTC, Danielle9897 requested changes

2022-08-28 10:43 UTC, Danielle9897 commented on Documentation/4.1/Samples/csharp/Raven.Documentation.Samples/ClientApi/Session/Querying/HowToFilterByField.cs
> +                        .WhereExists("missingFieldName")
This example has the 'missingFieldName' within quotes
But the previous one that shows in the article is without quotes
Need to unify

2022-08-28 10:43 UTC, Danielle9897 commented on Documentation/4.1/Raven.Documentation.Pages/client-api/session/querying/how-to-filter-by-non-existing-field.dotnet.markdown
> +| **fieldName** | string | The field that is missing in some of the documents. |
The above table has 'missingFieldName'
Need to unify

2022-08-28 11:25 UTC, serezhub commented on Documentation/4.1/Samples/csharp/Raven.Documentation.Samples/ClientApi/Session/Querying/HowToFilterByField.cs
> +                        .WhereExists("missingFieldName")
done

2022-08-28 11:28 UTC, serezhub commented on Documentation/4.1/Raven.Documentation.Pages/client-api/session/querying/how-to-filter-by-non-existing-field.dotnet.markdown
> +| **fieldName** | string | The field that is missing in some of the documents. |
I unified the signatures with the tables and used "quotes" in both signatures (I tried using <>, but that created an error because we can only do that in markdown files).

2022-08-29 05:24 UTC, Danielle9897 approved these changes

2022-09-18 12:56 UTC, Danielle9897 commented
@ppekrol can be merged from my point of view

2022-09-19 07:13 UTC, merged