RDoc-2184-2-Batch-Limit-Cloud-Indexing
ravendb/docs pull request #1538
Opened 2022-07-21 07:07 UTC by serezhub

Note: This is the second PR because the first one had problems generating all versions.

2022-07-31 10:38 UTC, reebhub requested changes

2022-07-31 10:38 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/cloud/cloud-settings.markdown
> +Indexing is done in batches which makes it possible to adjust the number of documents that an index processes at a time.
i guess you mean that we have a certain number of docs to index and we do it in batches of docs.
e.g. we have 1000 docs to index and we process them in batches of 100 docs, eventually creating 3 new indexes and modifying 2.
if so, please state it clearly. otherwise it's also possible that you mean we have 1000 indexes to create and we create them in batches of 100.
if some of the existing phrasing remains, please fix "..batches which.." to "..batches, which.."

2022-07-31 10:38 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/cloud/cloud-settings.markdown
> +Adjusting the `Indexing.MapBatchSize` configuration can be done to prevent exhausting system resources.
* configuration --> configuration setting
* `X can be done to Y` implies that Y is the subject of the change. the reader might need to go through the sentence at least twice to understand what you mean. please rephrase ("adjusting" --> "adjust", remove "can be done")

2022-07-31 10:38 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/cloud/cloud-settings.markdown
> +If an index processes a collection in a few batches, it will continue each new batch where the previous batch stopped.
"it will continue" --> "it will continue processing"

2022-07-31 10:38 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/cloud/cloud-settings.markdown
> +
seems like you're using four indentation levels where you need none

2022-07-31 10:38 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/cloud/cloud-settings.markdown
> +* RavenDB sets batch sizes with the following formula:
you're explaining here RavenDB's **automatic** settings, right? that the uses can change. please clarify it.

2022-07-31 10:38 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/studio/database/Indexes/create-map-index.markdown
> +!["Setting Configuration via Studio"](images\configuration-setting-new-config.png "Setting Configuration via Studio")
your image label doesn't show and the image is not resizable (in this case because there are spaces after the line end. please go over all your images and make sure they are presented properly)

2022-07-31 10:38 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/studio/database/Indexes/create-map-index.markdown
> +   * **Click Save** at the top of the interface when finished.
you probably updated this image so you can link to it from your explanation about setting batch size, but forgot to actually link to it.

2022-07-31 14:24 UTC, serezhub commented on Documentation/4.1/Raven.Documentation.Pages/studio/database/Indexes/create-map-index.markdown
> +3. Options available for an already saved index:
fixed now.  I do my best to update all versions with any relevant changes.

2022-07-31 14:35 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/cloud/cloud-overview.markdown
> +[Login]( https://cloud.ravendb.net/user/login)
done

2022-07-31 14:49 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/cloud/cloud-settings.markdown
> +Indexing is done in batches which makes it possible to adjust the number of documents that an index processes at a time.
Thanks for letting me know that it wasn't clear.  I gave an example to clarify.  
> * e.g. An index that processes 1,000,000 documents might exhaust memory and other system resources 
  if the index is set to process them all at once.  
  Instead, the index can be set to process the documents in batches of 10,000.

2022-07-31 14:52 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/cloud/cloud-settings.markdown
> +Adjusting the `Indexing.MapBatchSize` configuration can be done to prevent exhausting system resources.
good point.  done

2022-07-31 14:52 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/cloud/cloud-settings.markdown
> +If an index processes a collection in a few batches, it will continue each new batch where the previous batch stopped.
done

2022-07-31 14:58 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/cloud/cloud-settings.markdown
> +
I now used three instead of five levels.  One to help the title stand out for easy scanning. The others are in the example to show that the two parameters are part of the `max()` method.

2022-07-31 15:00 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/cloud/cloud-settings.markdown
> +* RavenDB sets batch sizes with the following formula:
done.  "RavenDB Cloud sets batch sizes with the following default formula:"

2022-08-01 06:07 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/studio/database/Indexes/create-map-index.markdown
> +!["Setting Configuration via Studio"](images\configuration-setting-new-config.png "Setting Configuration via Studio")
done

2022-08-01 06:10 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/studio/database/Indexes/create-map-index.markdown
> +   * **Click Save** at the top of the interface when finished.
I did.  I updated the image so that I can link from the cloud settings article.  The link is there in the section about setting cloud config via studio.

2022-08-14 20:40 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/cloud/cloud-settings.markdown
> +* Indexing is done in batches to make it possible to adjust the number of documents that an index processes at a time.
* seems like you tried to edit the line and duplicated it (here and in at least one other version).
* the phrasing here is still awkward and somewhat misleading, as if many documents are processed 
  simultaneously (they aren't) by the index (while it's the indexes that are being created). 
  if i understand correctly you are simply trying to say that documents are indexed in 
  batches, so RavenDB will get free time and resources in-between batches to do other stuff.
  take a look at the `Rolling Index Deployment` page if you want, i think it explains clearly 
  similar things (in a different context).

2022-08-14 20:56 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/cloud/cloud-settings.markdown
> +
the title can be separated from the preceding text with a line
and you can get rid of the first bullet ("RavenDB Cloud....") and of the first bullet in the note ("max())..")

2022-08-15 09:21 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/cloud/cloud-settings.markdown
> +
Done.  That works.

2022-08-21 09:40 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/cloud/cloud-overview.markdown
> +[Login]( https://cloud.ravendb.net/user/login)
not done though

2022-08-21 09:49 UTC, reebhub approved these changes

2022-08-23 08:46 UTC, merged