RDoc-2178-2-Replication Clarifications
ravendb/docs pull request #1539
Opened 2022-07-21 09:21 UTC by serezhub

2022-08-01 01:10 UTC, reebhub requested changes

2022-08-01 01:10 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/server/ongoing-tasks/hub-sink-replication.markdown
> +* Learn more about **Hub/Sink replication** [in the Overview article](../../studio/database/tasks/ongoing-tasks/hub-sink-replication/overview).
please return it to the way it was.
it's the overview article of a completely different section.

2022-08-01 01:10 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/server/ongoing-tasks/hub-sink-replication.markdown
> +   * e.g. (NYC/Customers/12345), (LDN/Customers/12345)
what is the extra bullet & indentation for?

2022-08-01 01:10 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/server/ongoing-tasks/external-replication.markdown
> +   * e.g. (NYC-nodes A,B,C), (LDN-nodes D,E,F)
just place the e.g. in the next line

* i'm a line
  e.g. i'm the lin'es e.g.
* i'm another line

2022-08-01 01:10 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/server/ongoing-tasks/external-replication.markdown
> +   * e.g. (NYC/Customers/12345), (LDN/Customers/12345)
same here

2022-08-01 01:10 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/server/ongoing-tasks/hub-sink-replication.markdown
> +   * e.g. (NYC/Customers/12345), (LDN/Customers/12345)
here too

2022-08-24 07:14 UTC, serezhub commented on Documentation/4.0/Raven.Documentation.Pages/server/clustering/replication/replication.markdown
> +* The rest of this article will focus on **within-cluster replication** in a single cluster.
done

* This article discusses replication between databases **within the same cluster**.

* Read more about **replication to other clusters here**:
   * [External Replication](../../../server/ongoing-tasks/external-replication)
   * [Hub/Sink Replication](../../../server/ongoing-tasks/hub-sink-replication)

2022-08-24 08:04 UTC, serezhub commented on Documentation/4.0/Raven.Documentation.Pages/server/clustering/replication/replication.markdown
> +in which you determine how many replicas will exist and will keep each other updated via replication.
done

2022-08-24 08:28 UTC, serezhub commented on Documentation/4.0/Raven.Documentation.Pages/server/clustering/replication/replication.markdown
> +   * You can configure the [ReadBalanceBehavior](../../../client-api/configuration/load-balance-and-failover#conventions-load-balance--failover).
done

#### To distribute work across nodes
* To [maintain consistency](../../../server/clustering/replication/replication#maintaining-consistency-between-nodes) 
  a [primary node](../../../client-api/session/configuration/use-session-context-for-load-balancing) 
  is responsible for writes and reads as a default setting.  
   * You can configure the [ReadBalanceBehavior](../../../client-api/configuration/load-balance-and-failover#conventions-load-balance--failover), 
     which determines to which nodes the client will send read requests. 
   * You can also set session-specific behavior for writes with [UseSessionContext](../../../client-api/session/configuration/use-session-context-for-load-balancing#loadbalancebehavior-usage), 
     which allows you to set read and write request behavior.  
      * **Changing the write request behavior can cause frequent conflicts** whenever two nodes write on the same document concurrently.  
* Distribution of work offers guaranteed consistency **when each node is responsible for a different database** 
  while updating the other nodes in a database group for failover purposes.  
  * e.g. There won't be conflicts if only node A writes on the "Customers" database, while only node B writes on the "Invoices" database.

2022-08-24 08:32 UTC, serezhub commented on Documentation/4.0/Raven.Documentation.Pages/server/clustering/replication/replication.markdown
> +* Distribution of work offers guaranteed consistency **when each node is responsible for a different database**,
It isn't a recommendation.  It explains the default and its rationale. 
Then it leads the reader to options that allow them to change the behavior but warns that changing the writes behavior can lead to frequent conflicts.

2022-08-24 09:47 UTC, serezhub commented on Documentation/4.0/Raven.Documentation.Pages/server/clustering/replication/replication.markdown
> +When it comes back online, it will automatically be updated by the responsible node with any changes made while it was down.
done 

If the offline node comes back online, it will automatically be updated by the responsible node with any changes made while it was down.  
If not, another node will be selected by the Cluster Observer to permanently fulfill its assigned tasks as long as [Dynamic Database Distribution is toggled on](../../../client-api/operations/server-wide/toggle-dynamic-database-distribution).

2022-08-24 12:25 UTC, serezhub commented on Documentation/4.0/Raven.Documentation.Pages/server/clustering/replication/replication.markdown
> +When a node goes down, the other nodes take over normal data updates.
done

When a node goes down, the [Cluster Oberver](../../../server/clustering/distribution/cluster-observer)
selects another node to fulfill all of the tasks which were assigned to the node that went down. 
This includes reads, writes and ongoing tasks.  

When back online, the node will be updated by the Responsible Node with any changes made to the data while it was down. 
The now online node will update its indexes with any changes in the data.  
Any ongoing tasks (ETL, Replication, Backup) for which it was explicitly set as the preferred node 
will be returned to the now-online node.

2022-08-24 12:39 UTC, serezhub commented on Documentation/4.0/Raven.Documentation.Pages/server/clustering/replication/replication.markdown
> +These changes will then trigger the tasks that the now-refreshed node is responsible for,
done

2022-08-24 12:39 UTC, serezhub commented on Documentation/4.0/Raven.Documentation.Pages/server/clustering/replication/replication.markdown
> +We highly recommend setting each production database in a [group of 3, 5, or more odd-numbered nodes on separate machines](https://ravendb.net/learn/inside-ravendb-book/reader/4.0/6-ravendb-clusters#
done

2022-08-24 12:40 UTC, serezhub commented on Documentation/4.0/Raven.Documentation.Pages/server/clustering/replication/replication.markdown
> +The replication process sends data over a TCP connection by the modification order, from the oldest to the newest.
done

The replication process sends data over a TCP connection in the order in which the documents were modified, from the oldest to the newest.

2022-08-24 12:41 UTC, serezhub commented on Documentation/4.0/Raven.Documentation.Pages/server/clustering/replication/replication.markdown
> +Every database has an [ETag](../../../glossary/etag), which is incremented on _every_ modification in the database's storage.
done

2022-08-24 13:08 UTC, serezhub commented on Documentation/4.0/Raven.Documentation.Pages/server/clustering/replication/replication.markdown
> +Each replication process has a _source_, _destination_, and a last confirmed `ETag` which is the cursor to where the replication process is.
Does this clarify it? 

Every document has an [ETag](../../../glossary/etag), 
which is local to each node and is incremented on _every_ document modification.  
An ETag is the local-node portion of the cluster's [Change Vector](../../../server/clustering/replication/change-vector).   

Each replication process has a _source_, a _destination_, and a last confirmed `Change Vector` which is used by the cluster for [concurrency control](../../../server/clustering/replication/change-vector#concurrency-control-at-the-cluster).   

The data is sent in batches. When the _destination_ node confirms getting the data, each document's last accepted `ETag` 
is then incremented and the next batch of data is sent.  
When the documents' local ETags are modified, the Change Vectors are modified accordingly.

2022-08-24 13:20 UTC, serezhub commented on Documentation/4.0/Raven.Documentation.Pages/server/clustering/replication/replication.markdown
> +* Using [Write Assurance](../../../client-api/session/saving-changes#waiting-for-replication---write-assurance)
done

2022-08-24 13:20 UTC, serezhub commented on Documentation/4.0/Raven.Documentation.Pages/server/clustering/replication/replication.markdown
> +* Use [cluster-wide sessions](../../../server/clustering/cluster-transactions)
done

2022-08-24 13:24 UTC, serezhub commented on Documentation/4.0/Raven.Documentation.Pages/server/clustering/replication/replication.markdown
> +   * Let's see how the replication of revisions helps data consistency.
done

2022-08-24 13:24 UTC, serezhub commented on Documentation/4.0/Raven.Documentation.Pages/server/clustering/replication/replication.markdown
> +   * Let's see how the replication of revisions helps data consistency.
done

2022-08-24 15:02 UTC, serezhub commented on Documentation/4.0/Raven.Documentation.Pages/server/ongoing-tasks/external-replication.markdown
> +  Replication between different clusters or between two databases in the same cluster is called **External Replication**.
done

2022-08-24 15:05 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/server/ongoing-tasks/hub-sink-replication.markdown
> +* Learn more about **Hub/Sink replication** [in the Overview article](../../studio/database/tasks/ongoing-tasks/hub-sink-replication/overview).
done

2022-08-24 15:08 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/server/ongoing-tasks/external-replication.markdown
> +   * e.g. (NYC-nodes A,B,C), (LDN-nodes D,E,F)
done

2022-08-24 15:08 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/server/ongoing-tasks/external-replication.markdown
> +   * e.g. (NYC/Customers/12345), (LDN/Customers/12345)
done

2022-08-28 11:02 UTC, reebhub commented on Documentation/4.0/Raven.Documentation.Pages/server/clustering/replication/replication.markdown
> +* The rest of this article will focus on **within-cluster replication** in a single cluster.
you second link is missing

2022-08-28 11:05 UTC, reebhub commented on Documentation/4.0/Raven.Documentation.Pages/server/clustering/replication/replication.markdown
> +   * You can configure the [ReadBalanceBehavior](../../../client-api/configuration/load-balance-and-failover#conventions-load-balance--failover).
"Changing the default write.." - make a note in the same bullet, not a new bullet

2022-08-28 11:07 UTC, reebhub commented on Documentation/4.0/Raven.Documentation.Pages/server/clustering/replication/replication.markdown
> +   * You can configure the [ReadBalanceBehavior](../../../client-api/configuration/load-balance-and-failover#conventions-load-balance--failover).
"e.g. There won't be conflicts if.." - doesn't need a bullet

2022-08-28 11:09 UTC, reebhub commented on Documentation/4.0/Raven.Documentation.Pages/server/clustering/replication/replication.markdown
> +When it comes back online, it will automatically be updated by the responsible node with any changes made while it was down.
nice

2022-08-28 11:12 UTC, reebhub commented on Documentation/4.0/Raven.Documentation.Pages/server/clustering/replication/replication.markdown
> +Each replication process has a _source_, _destination_, and a last confirmed `ETag` which is the cursor to where the replication process is.
yes

2022-08-28 11:34 UTC, reebhub commented on Documentation/4.0/Raven.Documentation.Pages/server/ongoing-tasks/external-replication.markdown
> +  Replication between different clusters or between two databases in the same cluster is called **External Replication**.
are the differences in this subject (and others?) between different versions of this article intentional?

2022-08-28 12:38 UTC, serezhub commented on Documentation/4.0/Raven.Documentation.Pages/server/clustering/replication/replication.markdown
> +   * You can configure the [ReadBalanceBehavior](../../../client-api/configuration/load-balance-and-failover#conventions-load-balance--failover).
done

2022-08-28 12:43 UTC, serezhub commented on Documentation/4.0/Raven.Documentation.Pages/server/ongoing-tasks/external-replication.markdown
> +  Replication between different clusters or between two databases in the same cluster is called **External Replication**.
Yes because Hub/sink didn't come until later and the docs section about passing certs is only from 5.2, so in docs before 5.2, I just explained passing certs in a sentence or two without images, etc...

2022-08-28 12:44 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/server/ongoing-tasks/hub-sink-replication.markdown
> +   * e.g. (NYC/Customers/12345), (LDN/Customers/12345)
removed sub-bullet

2022-08-29 12:16 UTC, serezhub commented on Documentation/4.0/Raven.Documentation.Pages/server/clustering/replication/replication.markdown
> +* The rest of this article will focus on **within-cluster replication** in a single cluster.
fixed.

2022-09-14 13:30 UTC, Danielle9897 requested changes

2022-09-15 14:25 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/server/ongoing-tasks/external-replication.markdown
> +{PANEL/}
I opened an issue for this:
https://issues.hibernatingrhinos.com/issue/RDoc-2263/Multi-Cluster-Documentation

2022-09-15 19:18 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/server/ongoing-tasks/external-replication.markdown
> +    {INFO/}
I opened a separate issue for this article:
https://issues.hibernatingrhinos.com/issue/RDoc-2270/External-Replication-Fix-Refactor

2022-09-18 12:23 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/server/clustering/replication/replication.markdown
> +
done

2022-09-18 12:25 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/server/clustering/replication/replication.markdown
> +* To [maintain consistency](../../../server/clustering/replication/replication#maintaining-consistency-between-nodes)
I did that in 
#### Single-Writer

By default to prevent conflicts, all of the clients will 'talk' (send read/write requests) to...

2022-09-18 12:56 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/server/clustering/replication/replication.markdown
> +#### When nodes are down
Replication is ultimately one of the elements for high-availability, so we should summarize and make it clear in the replication article that if node goes down, the cluster observer temporarily replaces it with an available node.  

{PANEL: Maintaining High Availability If Nodes Go Down}

When a node goes down, the [Cluster Oberver](../../../server/clustering/distribution/cluster-observer)
selects another node to fulfill all of the tasks which were assigned to the node that went down. 
This includes reads, writes, and ongoing tasks such ETL, Backup, and/or External Replication.  

The section on  [Dynamic Database Distribution](../../../server/clustering/distribution/distributed-database#dynamic-database-distribution) 
explains the different steps and default timing for handling nodes that go down.

{PANEL/}

2022-09-18 13:10 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/server/ongoing-tasks/external-replication.markdown
> +{PANEL/}
1. "Consistency boundaries" may need to be changed to something like "preventing between-cluster conflicts".
2. This section does not tell people not to allow the other side to modify the same document after external replication.  It tells them how they can do that if they want to, by having unique IDs.  
3. The part about GUID or email are relevant to not have conflicting IDs (or values if I connect this email section to the CmpXchg example about using a unique field as an id. 
4. This info is not the same for all types of replication.  For example, I don't know why, but Oren told me that ensuring that the node-tags are different in each cluster won't work for Hub/Sink, which is why it's different in that article.

2022-09-19 06:10 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/server/ongoing-tasks/external-replication.markdown
> +{PANEL/}
This is what I have now.
If we create a section of documents about multi-cluster/globalized systems best practices, we can move it there and link to it, but for now, external and hub/sink replication are the best places.  

I'm leaving it for now in Hub/Sink and external replication articles because it can take months until the multi-cluster article happens.  
I put a comment to remove these sections in the youtrack issue about it (RDoc-2263).

{PANEL: Preventing Conflicts Between Clusters}

[Consistency boundaries](https://ayende.com/blog/196769-B/data-ownership-in-a-distributed-system)
between clusters are crucial to preserve data integrity and model an efficient global system.  

One way to prevent conflicts is to ensure that only one server modifies a document.  

#### To ensure that two clusters don't write on the same document  

Following are a few ways to provide unique ID's across all of your clusters.  

Some of these approaches also make the source cluster clear in the ID so that you can set up logic 
that prevents multiple servers from modifying the same document.

You can ensure document ID uniqueness by:

* Ensuring that the node-tags are all unique.  
  e.g. (NYC-nodes A,B,C), (LDN-nodes D,E,F)  
* Including the cluster names in the [identifiers](../../client-api/document-identifiers/working-with-document-identifiers).  
  e.g. (NYC/Customers/12345), (LDN/Customers/12345)  
* Using a Globally Unique Identifier ([GUID](../../server/kb/document-identifier-generation#guid)).  
* [Using a unique field](../../../client-api/operations/compare-exchange/overview#example-iii---ensuring-unique-values-without-using-compare-exchange) 
  (such as an email address) in the ID as a global way to prevent duplication.  

{PANEL/}

2022-11-03 14:28 UTC, Danielle9897 commented
@serezhub 
As discussed, pls close this PR.

The new PR, with only the replication article, is here:
https://github.com/ravendb/docs/pull/1563

Any changes needed to be done for the external-replication article will be handled in issue:
https://issues.hibernatingrhinos.com/issue/RDoc-2270/External-Replication-Fix-Refactor

2022-11-06 09:17 UTC, serezhub commented
The new PR, with only the replication article, is here:
https://github.com/ravendb/docs/pull/1563

2022-11-06 09:17 UTC, closed without merging