RDoc-1989-2-RavenETL-Pass-Certs
ravendb/docs pull request #1540
Opened 2022-07-21 13:08 UTC by serezhub

2022-07-27 10:37 UTC, reebhub requested changes

2022-07-27 10:37 UTC, reebhub commented on Documentation/4.1/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
> +You can add the `@expires` tag to the metadata when storing the marker document,
link `@expires` to `server/extensions/expiration#setting-the-document-expiration-time`.

2022-07-27 10:37 UTC, reebhub commented on Documentation/4.1/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
>  * Function `loadAttachment()` returns `null` if a document doesn't have an attachment with a given name. Passing such reference to `addAttachment()` will be no-op and no error will be thrown.
when no bullet is needed (like here, when there's only one option) please don't use a bullet.

2022-07-27 10:37 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/studio/database/tasks/ongoing-tasks/ravendb-etl-task.markdown
> +    then the task will not be active, so data will not be ETL'ed.
look at `server/ongoing-tasks/external-replication#offline-behavior` for a proper phrasing (that doesn't use "ETL'ed").

2022-07-27 10:37 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/studio/database/tasks/ongoing-tasks/ravendb-etl-task.markdown
> +    * If you need to modify the ETL'ed data in the destination, you should create a companion document on the destination database instead of modifying the ETL'ed data directly.
find a substitute for ETL'ed (loaded, transferred..)

2022-07-27 10:37 UTC, reebhub commented on Documentation/5.3/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
> +  if you are running secure servers.
a secure server

2022-07-27 14:02 UTC, serezhub commented on Documentation/4.1/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
> +{NOTE: }
Done

2022-07-27 14:02 UTC, serezhub commented on Documentation/4.1/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
>  * Function `loadAttachment()` returns `null` if a document doesn't have an attachment with a given name. Passing such reference to `addAttachment()` will be no-op and no error will be thrown.
done

2022-07-27 14:04 UTC, serezhub commented on Documentation/4.1/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
> +* To indicate that a counter should also be sent, the behavior function needs to be defined in the script which decides if the counter should be sent if it's modified
done

2022-07-27 14:12 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/studio/database/tasks/ongoing-tasks/ravendb-etl-task.markdown
> +    * If you need to modify the ETL'ed data in the destination, you should create a companion document on the destination database instead of modifying the ETL'ed data directly.
done

2022-07-27 14:14 UTC, serezhub commented on Documentation/5.3/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
> +  if you are running secure servers.
done, though we are talking about two servers - source and destination.

2022-07-28 11:55 UTC, reebhub commented on Documentation/4.1/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
> +* To indicate that a counter should also be sent, the behavior function needs to be defined in the script which decides if the counter should be sent if it's modified
not done
please search this term through the article and link it to proper context where needed (you use the same term for counters, time series and deletions, make sure the links are correct)

2022-07-28 12:11 UTC, reebhub commented on Documentation/4.1/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
you changed the page for version 5.1, didn't change it for version 6.0 (and i don't know what other versions), and your changes have very little to do with what you were asked to change.
- you removed the deletions submenu and much of the text, including for instance a discussion of duplications that are now simply not covered and a discussion of IDs that is now smeared in the section's preface without ever stating what's discussed. Please restructure and make sure no needed material was eliminated.

2022-07-31 08:55 UTC, serezhub commented on Documentation/4.1/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
> +* For the destination cluster to trust the source, you must:
done

2022-07-31 09:01 UTC, serezhub commented on Documentation/4.1/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
>  {CODE-BLOCK:javascript}
done

2022-07-31 09:22 UTC, serezhub commented on Documentation/4.1/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
> +* To indicate that a counter should also be sent, the behavior function needs to be defined in the script which decides if the counter should be sent if it's modified
Done in all versions.  I added a list of links when there are multiple behavior functions - to make it easier for the user to navigate.

2022-07-31 09:30 UTC, serezhub commented on Documentation/4.1/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
I don't see bullets in the Revisions section.

2022-07-31 12:41 UTC, serezhub commented on Documentation/4.1/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
There are a few points here to respond to...

1. I removed the submenu and lots of the text in each version before 5.3 because these `deleted` check is only relevant for 5.3 and in a previous commit, I copied the 5.3 section into 5.1 and 4.1 on accident.  It shouldn't be there until 5.3. 
2. You're right, I now separated the syntax section from the example section. 
3. Deletes is a complicated aspect of ETL because there are various variables at play.  e.g. If the source/destination collection name is the same...behavior 1.  If the collection names are different...behavior 2.   I didn't 'smear' the explanation out of nowhere.  It needs to be there, but now it also has a link to the explanation from the samples where it is necessary to understand.  The explanation also has a clear title which explains what's discussed. "Identifiers change when destination collections are different"
4. I now got rid of the complex descriptions after the samples because the comments in the context of the samples do the job more clearly.

2022-07-31 12:52 UTC, serezhub commented on Documentation/4.1/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
I realized that this section has been outdated since I wrote detailed comments in the code samples.  Comments are easier to understand because they're in their context.  So, I got rid of these confusing sections.

2022-07-31 12:52 UTC, serezhub commented on Documentation/4.1/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
> +There is also a generic function to control deletion on different collections.
separated syntax and example

2022-07-31 12:55 UTC, serezhub commented on Documentation/4.1/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
> +By the time an ETL process runs a delete behavior function, a document is already deleted.
done

2022-07-31 14:03 UTC, serezhub commented on Documentation/4.1/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
> +In the below example, if `LocalOnlyDeletions/{docId}` exists then we skip this deletion during ETL.
done

2022-07-31 14:04 UTC, serezhub commented on Documentation/4.1/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
> +You can add the `@expires` tag to the metadata when storing the marker document,
done

2022-08-14 18:49 UTC, reebhub commented on Documentation/4.1/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
>  {CODE-BLOCK:javascript}
not done, actually, i don't understand what your answer relates to.
please see the attached image
![align](https://user-images.githubusercontent.com/43774704/184550809-b312387f-e085-4eb5-98b9-a8d31582f00a.png)
.

2022-08-14 19:06 UTC, reebhub commented on Documentation/4.1/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
> +In the below example, if `LocalOnlyDeletions/{docId}` exists then we skip this deletion during ETL.
you flattened it (removed the unneeded first bullet) for version 4.1 but missed at least version 5.3

2022-08-15 08:43 UTC, serezhub commented on Documentation/4.1/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
>  {CODE-BLOCK:javascript}
Now I understand. Done in every section of every version.

2022-08-15 08:48 UTC, serezhub commented on Documentation/4.1/Raven.Documentation.Pages/server/ongoing-tasks/etl/raven.markdown
> +In the below example, if `LocalOnlyDeletions/{docId}` exists then we skip this deletion during ETL.
done

2022-08-18 10:58 UTC, arekpalinski approved these changes

2022-08-22 07:31 UTC, reebhub approved these changes

2022-08-23 08:47 UTC, merged