RDoc-1491- Edited, clarified and added link to article with sample fo…
ravendb/docs pull request #1541
Opened 2022-08-03 11:09 UTC by serezhub

…r creating HiLo and other types of IDs

2022-08-15 16:09 UTC, Danielle9897 requested changes

2022-08-15 16:09 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/client-api/document-identifiers/hilo-algorithm.dotnet.markdown
> +It provides the next unique number without the node tag.
Replace both above paragraphs with:
=>
The following example shows how to get the next HiLo ID number from the client.
This ID is then used to create and store a new document.
The ID provided is the next unique number without the node tag and the collection.
Calling `GenerateNextIdForAsync` ensures minimal calls to the server, as the ID is generated from the reserved range of numbers on the client.

2022-08-15 16:09 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/client-api/document-identifiers/hilo-algorithm.dotnet.markdown
> +or a cluster-wide Identities generator.
Remove the 'or a cluster-wide Identities generator'
since reading the next line says: 'you may also consider using...... '
do you see ?

2022-08-15 16:09 UTC, Danielle9897 commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/ClientApi/DocumentIdentifiers/HiloAlgorithm.cs
> +                // The following uses the overload GenerateNextIdFor(string database, string collectionName);
simplify comment: (in all 3 comments)

The following uses the overload... => Using overload xxx...

2022-08-17 05:50 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/document-identifiers/hilo-algorithm.dotnet.markdown
> +| **type** | `Type` | The collection entity type. It is usually the singular of the collection name. <br/> For example, collection = "Orders", then entity = "Order". |
done

2022-08-17 05:51 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/document-identifiers/hilo-algorithm.dotnet.markdown
> +When the document store is disposed, the client sends to the server the last value it used to create an identifier and the max value he got from the server.
I changed "he" to "it" in the whole section

2022-08-17 05:56 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/document-identifiers/hilo-algorithm.dotnet.markdown
> +After execution of the code above, the `Max` value of the Hilo document in the server will be 1. That's because the client used only one identifier from the range he got before we disposed the store.
done

2022-08-17 05:56 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/document-identifiers/hilo-algorithm.dotnet.markdown
> +The next time that a client asks for a range of numbers from the server for this collection he will get (in our example) the range 2 - 33.
I removed every occurrence of 'he' from the document.

2022-08-17 05:58 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/document-identifiers/hilo-algorithm.dotnet.markdown
> +(`store.Dispose()` is used in this example to demonstrate what happens when a range is released.
done

2022-08-17 06:20 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/document-identifiers/hilo-algorithm.dotnet.markdown
> +To further ensure that no two nodes generate a document with the same ID, a node-tag is added to the number and collection.
done

2022-08-17 06:22 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/document-identifiers/hilo-algorithm.dotnet.markdown
> +To ensure that multiple clients can generate the identifiers simultaneously, they need some mechanism to avoid duplicates. It is ensured with `Raven/HiLo/collection` documents, stored in a database,
done

2022-08-17 06:24 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/document-identifiers/hilo-algorithm.dotnet.markdown
> +This separator can be changed to any other character except | in the
done, also for `/`

2022-08-17 06:53 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/document-identifiers/hilo-algorithm.dotnet.markdown
> +automatically creates unique IDs, you can also generate HiLo IDs manually.
done

```
To use RavenDB's automatic HiLo ID generation, a session needs to store a new document with id = null. 
RavenDB's automatic HiLo ID generator includes the collection name, unique number, and node tag to ensure that
the ID is unique across the cluster.  

However, you can use the HiLo algorithm and create documents with your own ID that is based on the next HiLo ID number
provided by the client.

The manual generator does not guarantee unique IDs across a cluster because there is no node-tag attached.  
```

2022-08-17 06:58 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/document-identifiers/hilo-algorithm.dotnet.markdown
> +the ID is unique across the cluster.
See the comment above to see how this has been refactored.  
I think that it's worth it to put the part about them being responsible for unique IDs in a warning box because having duplicate document IDs is very problematic.

2022-08-17 07:07 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/document-identifiers/hilo-algorithm.dotnet.markdown
> +{WARNING/}
Changed We to RavenDB.
I think that the flow of this section is best like this.  
1. Title - creating manual ID
2. No need, our auto id works well, but
you can create them manually anyway.
3. Why manual IDs do not guarantee unique IDs and the warning with a link to the article with different types of unique ID generators.
4. Code sample.

2022-08-17 07:46 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/document-identifiers/hilo-algorithm.dotnet.markdown
> +It provides the next unique number without the node tag.
done
Changed the last sentence to 
> Calling `GenerateNextIdForAsync` ensures minimal calls to the server, as the ID is generated by the client from the reserved range of numbers.

2022-08-17 07:47 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/document-identifiers/hilo-algorithm.dotnet.markdown
> +or a cluster-wide Identities generator.
Good catch.  Done.

2022-08-17 07:48 UTC, serezhub commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/ClientApi/DocumentIdentifiers/HiloAlgorithm.cs
> +                // The following uses the overload GenerateNextIdFor(string database, string collectionName);
done

2023-06-05 11:11 UTC, Danielle9897 commented
Closing this PR 
This PR was replaced with this one:
https://github.com/ravendb/docs/pull/1545

2023-06-05 11:11 UTC, closed without merging