RDoc-2049-Updated image and created example to demonstrate how to set
ravendb/docs pull request #1543
Opened 2022-08-11 13:24 UTC by serezhub

2022-08-25 15:28 UTC, Danielle9897 commented
@serezhub
I see the studio issue this was fixed in is **5.2**
Why the files in this PR are for **5.0** ?

2022-08-25 18:08 UTC, Danielle9897 requested changes

2022-08-28 11:37 UTC, serezhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +the previously aggregated data.
done

2022-08-28 11:41 UTC, serezhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +so that you can delete the previous data after it has been summarized.
done

2022-08-28 12:06 UTC, serezhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +  * [Rationale for Configuring Time Series](../../../studio/database/settings/time-series-settings#rationale-for-configuring-time-series)
done

2022-08-28 12:07 UTC, serezhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +[See Heart Clinic Example.](../../../studio/database/settings/time-series-settings#heart-clinic-example)
done

> ... It must be kept at least until it is aggregated/summarized in the rollup policy, 
but can be set to be available for a period after the rollup, as seen in the example below.

2022-08-28 12:07 UTC, serezhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +Here are the different levels of resolution that they want to see:
done

2022-08-28 14:44 UTC, Danielle9897 commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +but can be set to be available for a period after the rollup, as seen in the example below.
for a period
=> 
for some time period

2022-08-28 15:28 UTC, serezhub commented on Documentation/5.0/Raven.Documentation.Pages/studio/database/settings/time-series-settings.markdown
> +but can be set to be available for a period after the rollup, as seen in the example below.
done 

> but can be set to be available for any time period after the rollup

2022-08-29 05:20 UTC, Danielle9897 commented
* This PR is approved in the new PR:
https://github.com/ravendb/docs/pull/1553

* @serezhub you can close this PR

2022-08-29 07:44 UTC, closed without merging