RDoc-1491-2 HiLo-ID-Generation - Edited for clarity - In 5.2 I added …
ravendb/docs pull request #1545
Opened 2022-08-17 09:02 UTC by serezhub

…a section about manual ID generation

Due to a git push error I got, I re-cloned and copy/pasted the project into a clean project.
To see github comments until now, see the old PR at https://github.com/ravendb/docs/pull/1541

2022-08-22 14:52 UTC, Danielle9897 requested changes

2022-08-22 14:52 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/client-api/document-identifiers/hilo-algorithm.dotnet.markdown
> +  by not specifying an `Id` value when creating a new document,
It is created by not specifying an `Id` value when creating a new document
=>
These IDs are generated when creating a new document without specifying an 'Id' value.

2022-08-22 14:52 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/client-api/document-identifiers/hilo-algorithm.dotnet.markdown
> +{INFO/}
This info is important - but it is hidden...
Maybe add a link to it in the 'in this page'

2022-08-22 14:52 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/client-api/document-identifiers/hilo-algorithm.dotnet.markdown
> +[RavenDB can only guarantee unique IDs when using RavenDB's ID generators.](../../client-api/document-identifiers/working-with-document-identifiers)
Don't make the whole sentence 'red'...
Place the link only on 'RavenDB's ID generators'

2022-08-22 14:52 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/client-api/document-identifiers/hilo-algorithm.dotnet.markdown
> +The ID provided is the next unique number without the node tag and the collection.
Reverse sentences order:

first:
The ID provided is the next...

second:
This ID is then used to create...

2022-08-23 05:36 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/document-identifiers/hilo-algorithm.dotnet.markdown
> +  by not specifying an `Id` value when creating a new document,
done

2022-08-23 05:40 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/document-identifiers/hilo-algorithm.dotnet.markdown
> +{INFO/}
done.

2022-08-23 05:42 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/document-identifiers/hilo-algorithm.dotnet.markdown
> +[RavenDB can only guarantee unique IDs when using RavenDB's ID generators.](../../client-api/document-identifiers/working-with-document-identifiers)
done

2022-08-23 05:43 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/document-identifiers/hilo-algorithm.dotnet.markdown
> +The ID provided is the next unique number without the node tag and the collection.
done

2022-08-23 06:34 UTC, Danielle9897 approved these changes

2022-09-12 21:02 UTC, merged