RDoc-1929-Compact-One-Node-clarified about ForNode() in intro and com…
ravendb/docs pull request #1546
Opened 2022-08-18 09:57 UTC by serezhub

…ments

2022-08-21 18:08 UTC, Danielle9897 requested changes

2022-08-21 18:08 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/server-wide/compact-database.markdown
>  | **Indexes** | string[] | List of index names to compact |
Regarding the `DatabaseName` param (first one in the table):

Is it mandatory ?
What happens if user does not provide it ? Probably will take the default db defined in the store
Better to mention/explain/specify that....

2022-08-22 08:49 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/server-wide/compact-database.markdown
> +   * [Example III - Compact a database that is external to the store](../../../client-api/operations/server-wide/compact-database#example-iii)
done.

2022-08-22 08:50 UTC, serezhub commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/Server/Compact.cs
> +                // Specify indexes to compact.
done. the title is `Example I - Compact specific indexes`

2022-08-22 08:55 UTC, serezhub commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/Server/Compact.cs
> +                    .Send(new CompactDatabaseOperation(settings));
I disagree in this case.  If someone is compacting, they obviously want to compact all of their nodes.  Thus, IMO the examples should make specifying the node to compact a default so that they don't miss this step.

2022-08-22 09:00 UTC, Danielle9897 commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/Server/Compact.cs
> +                    .Send(new CompactDatabaseOperation(settings));
either way - need to explain what happens when ForNode is Not used

2022-08-22 09:01 UTC, serezhub commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/Server/Compact.cs
> +                // Use 'ForNode("node tag")' to specify on which node to compact.
done.  I left the space to make it obvious that you're not supposed to write <nodeTag>

2022-08-22 09:03 UTC, serezhub commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/Server/Compact.cs
> +                // Compact entire database: documents + all indexes.
done

2022-08-22 09:07 UTC, serezhub commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/Server/Compact.cs
> +                // get all index names.
done

2022-08-22 09:08 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/server-wide/compact-database.markdown
>  | **Indexes** | string[] | List of index names to compact |
We looked at the class and it showed that all of the params are mandatory.  

```
    public class CompactSettings
    {
        public string DatabaseName { get; set; }

        public bool Documents { get; set; }

        public string[] Indexes { get; set; }

        public DynamicJsonValue ToJson()
        {
            return new DynamicJsonValue
            {
                ["DatabaseName"] = DatabaseName,
                ["Documents"] = Documents,
                ["Indexes"] = Indexes
            };
        }
    }
```

2022-08-22 09:12 UTC, ml054 commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/server-wide/compact-database.markdown
>  | **Indexes** | string[] | List of index names to compact |
https://github.com/ravendb/ravendb/blob/d0922ad9c9268b9e39325bf8eba5c23ae57c4f2e/src/Raven.Server/Web/System/AdminDatabasesHandler.cs#L1066

2022-08-22 09:12 UTC, ml054 commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/server-wide/compact-database.markdown
>  | **Indexes** | string[] | List of index names to compact |
db is mandatory
you need to specify documents and/or indexes

2022-08-22 09:19 UTC, Danielle9897 commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/Server/Compact.cs
> +                    .Send(new CompactDatabaseOperation(settings));
It is not obvious that a user wants to compact all nodes.
The point is to explain what happens when ForNode is not used and what happens when it is used.

2022-08-22 12:59 UTC, serezhub commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/Server/Compact.cs
> +                    .Send(new CompactDatabaseOperation(settings));
I clarified it in the comments, as we discussed on Skype.

2022-08-22 12:59 UTC, serezhub commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/Server/Compact.cs
> +                    .Send(new CompactDatabaseOperation(settings));
I clarified it in the comments, as we discussed on Skype.

2022-08-22 13:04 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/server-wide/compact-database.markdown
>  | **Indexes** | string[] | List of index names to compact |
Thanks. I added the following in the syntax area.

`DatabaseName` is a mandatory parameter.  
You must also specify `Documents` and/or `Indexes`.

2022-08-22 13:50 UTC, Danielle9897 requested changes

2022-08-22 13:50 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/server-wide/compact-database.markdown
> +  Use the `CompactDatabaseOperation` to select the collections and compact them.
No collections are selected/specified
So refactor to just:
=>
Use the `CompactDatabaseOperation`.

2022-08-22 13:50 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/server-wide/compact-database.markdown
> +  To compact on more than one node, the command must be sent to each node by specifying `ForNode("node tag")`.
`"node tag"` => `<nodeTag>`

2022-08-22 13:50 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/server-wide/compact-database.markdown
> +Documents are set to be compacted in this example.
=>
The following example shows how to compact only specific indexes. Documents are also set to be compacted.

2022-08-22 13:50 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/server-wide/compact-database.markdown
> +The following example shows how compact all of the indexes and documents in the database.
how compact => how to compact..

2022-08-22 13:50 UTC, Danielle9897 commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/Server/Compact.cs
> +                // get all index names in the database.
got => Get

2022-08-22 13:50 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/server-wide/compact-database.markdown
> +on all collections that are configured for compression.
Add:
=>
All existing documents will be compressed.

2022-08-23 05:14 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/server-wide/compact-database.markdown
> +  Use the `CompactDatabaseOperation` to select the collections and compact them.
Right..done

2022-08-23 05:14 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/server-wide/compact-database.markdown
> +  To compact on more than one node, the command must be sent to each node by specifying `ForNode("node tag")`.
done

2022-08-23 05:15 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/server-wide/compact-database.markdown
> +Documents are set to be compacted in this example.
done

2022-08-23 05:15 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/server-wide/compact-database.markdown
> +The following example shows how compact all of the indexes and documents in the database.
done

2022-08-23 05:16 UTC, serezhub commented on Documentation/5.2/Samples/csharp/Raven.Documentation.Samples/ClientApi/Operations/Server/Compact.cs
> +                // get all index names in the database.
done

2022-08-23 05:18 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/client-api/operations/server-wide/compact-database.markdown
> +on all collections that are configured for compression.
done 
Compaction triggers [documents compression](../../../server/storage/documents-compression) 
on all existing documents in the collections that are configured for compression.

2022-08-23 06:13 UTC, Danielle9897 approved these changes

2022-09-12 21:02 UTC, merged