RDoc-1677-Cluster-Configs-Should-Be-Identical
ravendb/docs pull request #1547
Opened 2022-08-22 10:41 UTC by serezhub

2022-08-23 07:10 UTC, karmeli87 commented on Documentation/4.0/Raven.Documentation.Pages/server/clustering/cluster-best-practice-and-configuration.markdown
> +For ACID guarantees, a majority of the nodes must agree on every transaction, so having an odd number of nodes makes achieving the majority easier.
this is not true for single node transactions, only for cluster-wide ones.

2022-08-23 09:01 UTC, serezhub commented on Documentation/4.0/Raven.Documentation.Pages/server/clustering/cluster-best-practice-and-configuration.markdown
> +For ACID guarantees, a majority of the nodes must agree on every transaction, so having an odd number of nodes makes achieving the majority easier.
done

2022-09-12 08:51 UTC, Danielle9897 requested changes

2022-09-12 08:51 UTC, Danielle9897 commented on Documentation/4.0/Raven.Documentation.Pages/server/clustering/cluster-best-practice-and-configuration.markdown
> +{PANEL/}
Panel is not clear:

* better to be specific about that, this is related to nodes within the **same** cluster,
  so that reader does not think this is mandatory between 2 diff clusters.
  
 * What kind/type of cluster-configuration options are being referred here ?

2022-09-12 08:51 UTC, Danielle9897 commented on Documentation/4.0/Raven.Documentation.Pages/server/clustering/cluster-best-practice-and-configuration.markdown
> +{PANEL/}
Organize info to make it easy to spot differences, as follows: (note my changes inside)
=>

We recommend setting up clusters with an odd number of nodes equal to or greater than 3.

**A single node cluster:**
Will not have failover automatically to another node if it goes down.
This means that the node is not highly available.

**A two nodes cluster:**
Also not recommended, since the cluster must have a consensus among the majority of nodes to operate.
In this case, if one of the nodes is down or partitioned, no raft command will be committed, although any database on the surviving node will still be responsive to the user.


**Odd number of 3 nodes and up:**
For ACID guarantees, a majority of the nodes must agree on every [cluster-wide transaction](http://localhost:54391/docs/article-page/6.0/csharp/server/clustering/cluster-transactions), 
so having an odd number of nodes makes achieving the majority easier.

2022-09-12 08:51 UTC, Danielle9897 commented on Documentation/4.0/Raven.Documentation.Pages/server/configuration/cluster-configuration.markdown
> +Each node in a cluster must have the same configuration.
Why add this here (and I see you also added it in a few other places) ?
Isn't that relevant for all options on this page ?

Either:
* The top note enough 

Or:
* if top note is only relevant to some specific configurations, then it must be stated in the note.

2022-09-12 08:51 UTC, Danielle9897 commented on Documentation/4.0/Raven.Documentation.Pages/server/configuration/cluster-configuration.markdown
> +Tcp connection receive buffer size in bytes.
Tcp => TCP
(here and in any other place)

2022-09-12 08:51 UTC, Danielle9897 commented on Documentation/4.1/Raven.Documentation.Pages/server/clustering/distribution/distributed-database.markdown
> +
Remove the note from this panel.
The panel is about a node going to rehab & coming back from rehab.

2022-09-13 08:46 UTC, serezhub commented on Documentation/4.0/Raven.Documentation.Pages/server/configuration/cluster-configuration.markdown
> +Tcp connection receive buffer size in bytes.
I changed it in the descriptions, but not in the configuration names.

2022-09-13 08:52 UTC, serezhub commented on Documentation/4.1/Raven.Documentation.Pages/server/clustering/distribution/distributed-database.markdown
> +
done

2022-09-13 11:33 UTC, serezhub commented on Documentation/4.0/Raven.Documentation.Pages/server/clustering/cluster-best-practice-and-configuration.markdown
> +A _single node_ server will not have the ability to automatically failover to another node in the cluster if it goes down.
done

2022-09-13 11:33 UTC, serezhub commented on Documentation/4.0/Raven.Documentation.Pages/server/clustering/cluster-best-practice-and-configuration.markdown
>  A _two_ nodes cluster is also not recommended, since the cluster must have a majority of nodes to operate,
done

2022-09-13 11:33 UTC, serezhub commented on Documentation/4.0/Raven.Documentation.Pages/server/clustering/cluster-best-practice-and-configuration.markdown
> +If you must set cluster configurations differently in separate nodes, we recommend first testing it
done

2022-09-13 11:34 UTC, serezhub commented on Documentation/4.0/Raven.Documentation.Pages/server/clustering/cluster-best-practice-and-configuration.markdown
> +{PANEL/}
done.  clarified title and put link to cluster configurations article

### Nodes in a cluster usually must have identical cluster configurations

Configuration mismatches tend to cause interaction problems between nodes.

If you must set different [cluster configurations](../../server/configuration/cluster-configuration) in separate nodes,  
**test the configuration** in a development environment to see that each node interacts properly with the others.

2022-09-13 11:39 UTC, serezhub commented on Documentation/4.0/Raven.Documentation.Pages/server/configuration/cluster-configuration.markdown
> +Each node in a cluster must have the same configuration.
Removed the individual warnings so that they test any non-identical configurations.

2022-09-14 07:26 UTC, Danielle9897 requested changes

2022-09-14 07:26 UTC, Danielle9897 commented on Documentation/4.0/Raven.Documentation.Pages/server/clustering/cluster-best-practice-and-configuration.markdown
> +although any _database_ on the surviving node will still be responsive to the user.
The way the sentence is currently structured, when you say 'in this case' it is not clear what is referenced by 'this case':
the 2-node structure or the majority ...

=>
Also not recommended, since the cluster must have a consensus among the majority of nodes to operate.
Having only 2 nodes, if one of the nodes is down or partitioned, no raft command will be committed, although any database on the surviving node will still be responsive to the user.

(no need for italics on 'database')

2022-09-14 07:26 UTC, Danielle9897 commented on Documentation/4.0/Raven.Documentation.Pages/server/clustering/cluster-best-practice-and-configuration.markdown
> +   * [Nodes in a cluster usually must have identical cluster configurations](../../server/clustering/cluster-best-practice-and-configuration#nodes-in-a-cluster-usually-must-have-identical-cluster-con
Don't describe it as a 'must'
we *know that some must... and we even use the term 'usually' 
'usually' contradicts 'must' here

title should just be the general subject:
=> Cluster configurations among the cluster's nodes

or, event better, since this is a best practice recommendation:
=> Avoid different cluster configurations among the cluster's nodes

I like the second option with avoid....

2022-09-14 07:26 UTC, Danielle9897 commented on Documentation/4.0/Raven.Documentation.Pages/server/configuration/cluster-configuration.markdown
> +
Apply the comment about the title here as well

2022-09-14 10:28 UTC, serezhub commented on Documentation/4.0/Raven.Documentation.Pages/server/clustering/cluster-best-practice-and-configuration.markdown
> +although any _database_ on the surviving node will still be responsive to the user.
done

2022-09-14 10:37 UTC, serezhub commented on Documentation/4.0/Raven.Documentation.Pages/server/clustering/cluster-best-practice-and-configuration.markdown
> +   * [Nodes in a cluster usually must have identical cluster configurations](../../server/clustering/cluster-best-practice-and-configuration#nodes-in-a-cluster-usually-must-have-identical-cluster-con
I used the avoid one

2022-09-14 10:40 UTC, serezhub commented on Documentation/4.0/Raven.Documentation.Pages/server/configuration/cluster-configuration.markdown
> +
If you set different [cluster configurations](http://localhost:54391/article/5.0/csharp/server/configuration/cluster-configuration) in separate nodes,
test the configuration in a development environment to see if each node interacts properly with the others.

2022-09-14 14:13 UTC, Danielle9897 requested changes

2022-09-14 14:13 UTC, Danielle9897 commented on Documentation/4.0/Raven.Documentation.Pages/server/configuration/cluster-configuration.markdown
> +{NOTE: Nodes in a cluster usually must have identical cluster configurations.}
Fix title as done in the other place

2022-09-14 14:13 UTC, Danielle9897 commented on Documentation/4.0/Raven.Documentation.Pages/server/clustering/cluster-best-practice-and-configuration.markdown
> +**test the configuration** in a development environment to see if each node interacts properly with the others.
Use the same text you have in the other place:
=>
If you must set cluster configurations differently in separate nodes,
we recommend first testing it in a development environment to see that each node interacts properly with the others.

2022-09-14 14:13 UTC, Danielle9897 commented on Documentation/4.0/Raven.Documentation.Pages/server/clustering/cluster-best-practice-and-configuration.markdown
> +although any database on the surviving node will still be responsive to the user.
Needs to be modified a bit (as I now know more), 
because the word 'committed' is not good as it is in this text
because even if one node is down, the other one will still execute/commit raft commands it already got from before... 
so:

=>

Also not recommended since the cluster must have a consensus among the majority of nodes to operate.
With a two-node cluster, if one of the nodes is down or partitioned, the other node is not considered a 'majority'
and thus no [Raft]() command will be created, although any database on the surviving node will still be responsive to the user.

2022-09-15 10:08 UTC, serezhub commented on Documentation/4.0/Raven.Documentation.Pages/server/configuration/cluster-configuration.markdown
> +{NOTE: Nodes in a cluster usually must have identical cluster configurations.}
done

2022-09-15 10:10 UTC, serezhub commented on Documentation/4.0/Raven.Documentation.Pages/server/clustering/cluster-best-practice-and-configuration.markdown
> +**test the configuration** in a development environment to see if each node interacts properly with the others.
done

2022-09-15 10:12 UTC, serezhub commented on Documentation/4.0/Raven.Documentation.Pages/server/clustering/cluster-best-practice-and-configuration.markdown
> +although any database on the surviving node will still be responsive to the user.
done

2022-09-15 11:27 UTC, Danielle9897 commented on Documentation/4.0/Raven.Documentation.Pages/server/clustering/cluster-best-practice-and-configuration.markdown
> +**test the configuration** in a development environment to see if each node interacts properly with the others.
in BOTH places use the original as was in the comment:

```
If you must set cluster configurations differently in separate nodes,
we recommend first testing it in a development environment to see that each node interacts properly with the others.
```

2022-09-15 11:53 UTC, Danielle9897 approved these changes

2022-09-15 11:55 UTC, Danielle9897 commented
@ppekrol @reebhub 
PR can be merged from my point of view

2022-10-18 07:58 UTC, merged