RDoc-1948-Common-Analyzers-Usage -
ravendb/docs pull request #1552
Opened 2022-08-23 16:50 UTC by serezhub

clarified how the analyzers affect email and web addresses, passwords, etc..

2022-08-28 12:17 UTC, serezhub commented
@grisha-kotler Can you please check if the changes made answer your request in [RDoc-1948](https://issues.hibernatingrhinos.com/issue/RDoc-1948/Document-analyzers-rules)?

2022-09-07 15:15 UTC, grisha-kotler approved these changes

2022-09-11 19:16 UTC, Danielle9897 requested changes

2022-09-11 19:16 UTC, Danielle9897 commented on Documentation/4.2/Raven.Documentation.Pages/indexes/using-analyzers.dotnet.markdown
> +{PANEL: RavenDB's Default Analyzers}
**Move** this panel (RavenDB's Default Analyzers)
to be just right above panel 'Manipulating Field Indexing Behavior'

Reading about the options here is confusing
The panel needs to be close to where it is further explained.

2022-09-11 19:16 UTC, Danielle9897 commented on Documentation/4.2/Raven.Documentation.Pages/indexes/using-analyzers.dotnet.markdown
> +{PANEL: RavenDB's Default Analyzers}
Also, the inner contents of this paragraph require some changes
Call me to discuss this further, as this PR does not show all the latest content.

2022-10-02 11:04 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/indexes/using-analyzers.dotnet.markdown
> +    Useful in situations like IDs and codes where you do not want to separate into multiple tokens.
done

2022-10-02 11:06 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/indexes/using-analyzers.dotnet.markdown
> +* **KeywordAnalyzer** will perform no tokenization, and will consider the whole text a stream as one token:
done

2022-10-02 11:10 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/indexes/using-analyzers.dotnet.markdown
> +    Only separates with whitespaces
done

2022-10-02 11:10 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/indexes/using-analyzers.dotnet.markdown
> +    This analyzer preserves upper/lower cases in text, which means that searches will be case-sensitive.
done

2022-10-02 11:11 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/indexes/using-analyzers.dotnet.markdown
> +    This analyzer preserves upper/lower cases in text for case-sensitive searches.
done

2022-10-02 11:11 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/indexes/using-analyzers.dotnet.markdown
> +    Email and web addresses, phone numbers, and other such forms of ID are kept whole
done

2022-10-02 11:11 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/indexes/using-analyzers.dotnet.markdown
> +    Separates with white spaces
done

2022-10-02 11:13 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/indexes/using-analyzers.dotnet.markdown
> +    Removes numbers and symbols, then separates tokens with these.
> Removes numbers and symbols and separates tokens with them.

2022-10-02 11:14 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/indexes/using-analyzers.dotnet.markdown
> +    Removes common "stop" words
done

2022-10-02 11:14 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/indexes/using-analyzers.dotnet.markdown
> +    Separates with white spaces
done

2022-10-02 11:16 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/indexes/using-analyzers.dotnet.markdown
> +    Numbers with hyphen/dash are not separated at the hyphen.
done

2022-10-02 11:17 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/indexes/using-analyzers.dotnet.markdown
> +Lucene offers several Analyzers out of the box, and new ones can be [created](../indexes/using-analyzers#creating-custom-analyzers).
done

2022-10-02 11:17 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/indexes/using-analyzers.dotnet.markdown
> +The examples below will use this sample text:
done

2022-10-02 11:18 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/indexes/using-analyzers.dotnet.markdown
> -The indexing of a single document starts from creating Lucene's **Document** according an index definition. Lucene processes it by breaking it into **fields** and splitting all the text
done

2022-10-02 11:22 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/indexes/using-analyzers.dotnet.markdown
done

2022-10-02 11:36 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/indexes/using-analyzers.dotnet.markdown
>  {INFO The analyzer you are referencing to has to be available to the RavenDB server instance. When using analyzers that do not come with the default Lucene.NET distribution, you need to drop all the
Changed to "Customized analyzers availability"

The current text you see is in the 5.2 version, where this section is different from the 5.1 and 4.2 versions.  This aspect was updated in 5.2 and might only be relevant for 5.2+.  [Here ](https://issues.hibernatingrhinos.com/issue/RDoc-1896/Document-Custom-Analyzers )is the issue where it was changed.  It is marked for 5.2

2022-10-02 12:22 UTC, serezhub commented on Documentation/4.2/Raven.Documentation.Pages/indexes/using-analyzers.dotnet.markdown
> +{PANEL: RavenDB's Default Analyzers}
I moved the RavenDB's Default Analyzers panel above the Manipulating Field Indexing Behavior section and changed the table of contents accordingly.

I copied the info from this section and Manipulating Field Indexing Behavior from 5.2 and moved these improved explanations into 4.2 and 5.1.

2022-10-02 14:36 UTC, Danielle9897 requested changes

2022-10-02 14:36 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/indexes/using-analyzers.dotnet.markdown
> +    Removes numbers and symbols, then separates tokens with these.
with these => with them

2022-10-02 14:36 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/indexes/using-analyzers.dotnet.markdown
>  methods of [creating custom analyzers](../indexes/using-analyzers#creating-custom-analyzers).
* pls line break before 'see the diff...'
* there are a few other places in the article that can use a line break. 
pls go over and see where it can be helpful.

2022-10-02 14:36 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/indexes/using-analyzers.dotnet.markdown
>  By default, each indexed field is analyzed using the '`LowerCaseKeywordAnalyzer`' which indexes a field as a single, lowercased term.
* remove the `'` (just make blue)
'`LowerCaseKeywordAnalyzer`' => `LowerCaseKeywordAnalyzer`

* StandardAnalyzer (a few lines below) also needs blue (but w/o `'`)

2022-10-03 06:04 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/indexes/using-analyzers.dotnet.markdown
> +    Preserves upper/lower cases in text for case-sensitive searches.
done

2022-10-03 06:05 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/indexes/using-analyzers.dotnet.markdown
> +{INFO: Customized Analyzer Availability}
singular sounds better to me

2022-10-03 08:10 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/indexes/using-analyzers.dotnet.markdown
>    in a process called *tokenization*. Those tokens will be stored in the index, and later will be searched upon.
These tokens/terms will be kept in the index, and later can be searched upon.

2022-10-03 08:11 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/indexes/using-analyzers.dotnet.markdown
> +    Removes common "stop words".
done.

2022-10-03 08:14 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/indexes/using-analyzers.dotnet.markdown
> +    Removes numbers and symbols, then separates tokens with these.
done

2022-10-03 08:51 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/indexes/using-analyzers.dotnet.markdown
>  methods of [creating custom analyzers](../indexes/using-analyzers#creating-custom-analyzers).
done

2022-10-03 08:53 UTC, serezhub commented on Documentation/5.2/Raven.Documentation.Pages/indexes/using-analyzers.dotnet.markdown
>  By default, each indexed field is analyzed using the '`LowerCaseKeywordAnalyzer`' which indexes a field as a single, lowercased term.
done

2022-10-06 05:23 UTC, Danielle9897 approved these changes

2022-10-07 08:46 UTC, merged