RDoc-2317 [Node.js] Client API > Session > How to > Defer operations
ravendb/docs pull request #1570
Opened 2022-11-28 12:28 UTC by Danielle9897

**Related issue:**
https://issues.hibernatingrhinos.com/issue/RDoc-2317/Node.js-Client-API-Session-How-to-Defer-operations

@ml054 
For Node.js - the files to be reviewed are:

```
Documentation/5.2/Raven.Documentation.Pages/client-api/session/how-to/defer-operations.js.markdown
Documentation/5.2/Samples/nodejs/ClientApi/Session/HowTo/defer.js
```

**Note:**
Java files in this PR are Not to be reviewed.
Only copied (with minor changes) to 5.2 since we have no file bubbling.

2022-11-28 20:17 UTC, ml054 commented on Documentation/5.2/Raven.Documentation.Pages/client-api/session/how-to/defer-operations.js.markdown
> +- DeleteCommandData]
?

2022-11-28 20:17 UTC, ml054 commented on Documentation/5.2/Raven.Documentation.Pages/client-api/session/how-to/defer-operations.js.markdown
> +- PatchCommandData]
?

2022-11-28 20:19 UTC, ml054 requested changes
Just fix ] (2 times) and we have it.

2022-11-29 06:07 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/client-api/session/how-to/defer-operations.js.markdown
> +- PatchCommandData]
done - thanks for catching this copy-paste error

2022-11-29 06:25 UTC, ml054 approved these changes

2022-12-02 11:28 UTC, merged