RDoc-2165 Licensing documentation
ravendb/docs pull request #1595
Opened 2023-01-22 16:09 UTC by Danielle9897

2023-01-30 12:18 UTC, garayx requested changes

2023-01-30 12:18 UTC, garayx commented on Documentation/5.2/Raven.Documentation.Pages/start/licensing/force-update.markdown
> +   This will update your current license immediately.
requires internet connection to api.ravendb.net

2023-01-30 12:18 UTC, garayx commented on Documentation/5.2/Raven.Documentation.Pages/start/licensing/licensing-overview.markdown
> +  To renew your license see [renew license](../../start/licensing/renew-license).
maybe its worth to mention that renewed license will have new json file

2023-01-30 12:18 UTC, garayx commented on Documentation/5.2/Raven.Documentation.Pages/start/licensing/licensing-overview.markdown
> +{PANEL: License types}
we can add new panel with Support Types here as well and rename the article to "Licensing & Support Overview"

2023-01-30 12:18 UTC, garayx commented on Documentation/5.2/Raven.Documentation.Pages/start/licensing/renew-license.markdown
> +* Copy the new license key from the mail and set it in either of the following ways:
this is about replace of the license, no?

2023-01-30 12:18 UTC, garayx commented on Documentation/5.2/Raven.Documentation.Pages/start/licensing/replace-license.markdown
> +* If you have set up with the [Setup Wizard](../../start/installation/setup-wizard) and used a Let's Encrypt certificate,
this is about renewal of license, no?

2023-01-30 12:18 UTC, garayx commented on Documentation/5.2/Raven.Documentation.Pages/start/licensing/replace-license.markdown
> +* Otherwise, changing your license ID will cause a mismatch between the new license ID
this mostly applies to community

2023-01-31 09:35 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/server/configuration/license-configuration.markdown
> +Either a full path, or a relative path to the Server directory.
Fixed to:

```
Path to the license.json file.
Either the full path to the license file,
or a relative path to the license file from the Server directory. 
```

2023-01-31 10:24 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/server/configuration/license-configuration.markdown
> +Disable checking the support options for the license.
done

2023-01-31 10:55 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/start/licensing/force-update.markdown
> +  * You have an active connection to RavenDB's License Server.
done

2023-01-31 11:02 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/start/licensing/force-update.markdown
> +  then you can __force the update from Studio__.
@grisha-kotler @garayx 

As I understood so far (and pls correct me if I'm wrong):
The internet connection to api.ravendb.net 
**is required** only for checking if there are any existing changes/updates to the license
and **is not required** for the force-update / activate.

2023-01-31 11:19 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/start/licensing/force-update.markdown
> +  then you can __force the update from Studio__.
done

2023-01-31 11:19 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/start/licensing/force-update.markdown
> +   This will update your current license immediately.
done

2023-01-31 12:21 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/start/licensing/licensing-overview.markdown
> +  To renew your license see [renew license](../../start/licensing/renew-license).
IMHO - better to just provide the link to the 'renew' page and see all details there.
Q: When **commercial** licenses are renewed **automatically**, do you also get a new json file ?

2023-01-31 12:24 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/start/licensing/renew-license.markdown
> +* Copy the new license key from the mail and set it in either of the following ways:
This is about **manual (offline) renewal** - as I understand so far
@grisha-kotler ?

2023-01-31 12:26 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/start/licensing/replace-license.markdown
> +* If you have set up with the [Setup Wizard](../../start/installation/setup-wizard) and used a Let's Encrypt certificate,
this is about auto-renewal of **certificates** - as I understand so far

2023-01-31 12:30 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/start/licensing/replace-license.markdown
> +* Otherwise, changing your license ID will cause a mismatch between the new license ID
@garayx 
Do you mean it applies "only" to community license ?
It doesn't apply to professional/enterprize ?

2023-01-31 12:33 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/start/licensing/activate-license.markdown
> +   Click the _REGISTER LICENSE_ button
As I understand so far (correct me if I'm wrong)
If you **had a license already set up in the setting.json**
then when you open the Studio you will Not see this UI with this register button

@grisha-kotler ?

2023-01-31 12:34 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/start/licensing/activate-license.markdown
> +    * Or, a __relative__ path to the Server folder
done

2023-01-31 12:40 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/start/licensing/activate-license.markdown
> +  * Set the full license key in the RAVEN_LICENSE environment variable.
done

2023-01-31 13:13 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/start/licensing/activate-license.markdown
> +  * Embed the full license key as a string, e.g.:
yes, that is true, however, in this case,
it is a better "user experience" to see the details upfront instead of navigating away
as this info is **coupled** with the Env.Vars details that follow right after, 
(when you see it live it is clearer to see what I mean)

Also, the `manual (offline) renewal` paragraph from the 'renewal' page links here to this page to both titles:
"Activate license from settings.json" & "Activate license from environment variables" 
so better to avoid too many spaghetti links

2023-01-31 13:18 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/start/licensing/licensing-overview.markdown
> +{PANEL: License types}
Let's **talk** about this first - let me know the relevant details that are needed to be written
and - maybe better to make a separate issue on that after the licensing is merged ?

2023-02-01 20:16 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/start/licensing/activate-license.markdown
> +__"License.Path"__
removed the duplicate info - using links now

2023-02-01 20:17 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/start/licensing/activate-license.markdown
> +  * Embed the full license key as a string, e.g.:
removed the duplicate info - using links now

2023-02-06 10:47 UTC, Danielle9897 commented
@grisha-kotler  Can you pls review/approve ?

2023-02-15 09:09 UTC, Danielle9897 commented on Documentation/4.1/Raven.Documentation.Pages/server/configuration/configuration-options.markdown
> +_settings.json_ configuration values **override** their matching [environment variables](../../server/configuration/configuration-options#environment-variables) values.
@haludi ?

2023-02-28 09:44 UTC, Danielle9897 commented
@grisha-kotler pls review/approve

2023-03-14 16:01 UTC, grisha-kotler approved these changes

2023-03-14 16:01 UTC, grisha-kotler commented on Documentation/5.2/Raven.Documentation.Pages/start/licensing/force-update.markdown
> +   This action requires an active connection to the [License Server](../../start/licensing/licensing-overview#license-server).
if `DisableAutoUpdateFromApi` is set to `true` we'll update the license from the configuration.

2023-03-14 16:42 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/start/licensing/force-update.markdown
> +   This action requires an active connection to the [License Server](../../start/licensing/licensing-overview#license-server).
done
![image](https://user-images.githubusercontent.com/17376974/225076425-8f63e06a-ccef-4260-bd90-04325a595d58.png)

2023-03-14 16:42 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/start/licensing/force-update.markdown
> +  * Both [DisableAutoUpdate](../../server/configuration/license-configuration#license.disableautoupdate) and [DisableAutoUpdateFromApi](../../server/configuration/license-configuration#license.disabl
done

2023-03-14 16:42 UTC, Danielle9897 commented on Documentation/5.2/Raven.Documentation.Pages/start/licensing/renew-license.markdown
> +* Restart your server.
=>
* Restart your server (needed only if any configuration key was changed).

2023-03-14 16:46 UTC, grisha-kotler approved these changes

2023-03-16 12:18 UTC, merged