RDoc-2499_Corax-6.0-updates
ravendb/docs pull request #1689
Opened 2023-08-29 02:58 UTC by reebhub

Update the Corax documentation for RavenDB 6.0

2023-08-29 08:27 UTC, maciejaszyk commented on Documentation/6.0/Raven.Documentation.Pages/indexes/boosting.dotnet.markdown
> +When using [Corax](../indexes/search-engine/corax) as the search engine, [boosting is available](../indexes/search-engine/corax#supported-features)
Maybe `indexing-time boosting`, because it may suggest we do not support query-time boosting

2023-08-29 11:58 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/indexes/boosting.dotnet.markdown
> +When using [Corax](../indexes/search-engine/corax) as the search engine, [boosting is available](../indexes/search-engine/corax#supported-features)
done

2023-08-30 07:56 UTC, arekpalinski reviewed
There are some Corax issues marked with Documentation required tag:
https://issues.hibernatingrhinos.com/issues/RavenDB?q=%23Corax%20AND%20%20%23%7BDocumentation%20Required%7D

@reebhub @maciejaszyk please verify if something needs to be added to the docs. If it's already done then @reebhub please remove the tag.

2023-08-30 07:56 UTC, arekpalinski commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +  version 5.4 as an in-house searching alternative for Lucene.
Maybe "introduced in RavenDB  version 6.0" since in 5.4 it was an experimental feature with very limited set of features it supports. I'd like to avoid confusion that our users think that they can use Corax in 5.4. Corax is 6.0 is completely rewritten feature.

2023-08-30 07:56 UTC, arekpalinski commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +You must restart the server for the new settings to be read and applied.
What might be important info is that an already created index won't change the search engine if you modify the configuration. For example, my current setting is `Indexing.Static.SearchEngineType: Corax`. I have created a couple of static indexes - all of them use Corax. I change the configuration to `Indexing.Static.SearchEngineType: Lucene`. All existing indexes will still use Corax (unless I reset them). Only new indexes are going to use Lucene.

2023-08-30 07:56 UTC, arekpalinski commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +    | Dynamic Fields | `yes` | Corax' handling of dynamic fields is similar to Lucene's.
Why we have this comment? What does it mean? What was the intention here? CC @maciejaszyk

2023-08-30 07:56 UTC, arekpalinski commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +will generate a `System.NotImplementedException` exception and end the search.
It will throw `NotSupportedInCoraxException`. Right @maciejaszyk ?

2023-08-30 07:56 UTC, arekpalinski commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +Complex JSON properties **cannot currently be indexed and searched by Corax**.
Shouldn't it be mentioned in the above section about unsupported features? Maybe with a link in the comment to this section with explains details.

2023-08-30 07:56 UTC, arekpalinski commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +can still be **stored and projected**.
Maybe rephrase to "can still be stored so it might be used in [projection queries](https://ravendb.net/docs/article-page/5.4/csharp/indexes/querying/projections#projections-and-stored-fields)" with a link to: https://ravendb.net/docs/article-page/5.4/csharp/indexes/querying/projections#projections-and-stored-fields ?

2023-08-30 07:56 UTC, arekpalinski commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +  `System.NotSupportedException` to notify the user that a search
@maciejaszyk I checked the code and indeed it throws `NotSupportedException`. Shouldn't it be changed to NotSupportedInCoraxException?

2023-08-30 07:56 UTC, arekpalinski commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +---
Other unsupported features / cases that I found in code.

Querying:

- throw new NotSupportedInCoraxException($"{nameof(Corax)} doesn't support {nameof(Explanations)} yet.");
- throw new NotSupportedInCoraxException($"Corax doesn't support 'Distinct' operation on collection bigger than int32 ({int.MaxValue}).");


Indexing:
- throw new NotSupportedInCoraxException($"{nameof(Corax)} does not support indexing objects that are not points on a world map.");

CC @maciejaszyk

2023-08-30 07:56 UTC, arekpalinski commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +
We have more Corax specific settings. Look for "Indexing.Corax." here: https://github.com/ravendb/ravendb/blob/v6.0/src/Raven.Server/Config/Categories/IndexingConfiguration.cs

2023-08-30 12:10 UTC, arekpalinski commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +---
Also "Custom analyzers" aren't supported in Indexing - https://ravendb.net/docs/article-page/5.4/csharp/studio/database/settings/custom-analyzers

2023-08-30 13:21 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +You must restart the server for the new settings to be read and applied.
{NOTE: }
Selecting a new search engine will change the search engine only for indexes created from now on.  

E.g., If my configuration has been `"Indexing.Static.SearchEngineType": "Corax"` 
until now and i now change it to `"Indexing.Static.SearchEngineType": "Lucene"`, 
static indexes created from now on will use Lucene, but static indexes created 
while Corax was selected will continue using Corax.  

After selecting a new search engine using the above options, change the search 
engine used by an existing index by [resetting](../../client-api/operations/maintenance/indexes/reset-index) the index.  
{NOTE/}

2023-08-30 13:25 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +will generate a `System.NotImplementedException` exception and end the search.
done

2023-08-30 13:41 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +Complex JSON properties **cannot currently be indexed and searched by Corax**.
right
done

2023-08-30 13:48 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +can still be **stored and projected**.
done

2023-08-30 15:27 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +---
added `Explanations`, `Distinct` and **Custom analyzers**, waiting for an answer about _indexing objects_

2023-08-30 15:58 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +
done

2023-09-01 22:16 UTC, reebhub commented
"There are some Corax issues marked with Documentation required tag:
https://issues.hibernatingrhinos.com/issues/RavenDB?q=%23Corax%20AND%20%20%23%7BDocumentation%20Required%7D

@reebhub @maciejaszyk please verify if something needs to be added to the docs. If it's already done then @reebhub please remove the tag."

---

these are the issues, 3 of the 4 are done, the fourth isn't ready for documentation yet.

- [RavenDB-19603](https://issues.hibernatingrhinos.com/issue/RavenDB-19603/Implement-scoring-generated-by-relevance-of-the-documents-boosting) Implement scoring generated by relevance of the documents (boosting) 
	Boosting ranking: added a note to the boosting article
- [RavenDB-19990](https://issues.hibernatingrhinos.com/issue/RavenDB-19990/Allow-to-skip-over-int.Max-docs-in-query-for-Corax-but-limit-projection-up-to-int.Max) Allow to skip over int.Max docs in query (for Corax) but limit projection up to int.Max 
	Added a “limits” section to the corax page and an info box in the paging page.
- [RavenDB-20481](https://issues.hibernatingrhinos.com/issue/RavenDB-20481/Failing-test-on-Corax-Oregon.Fails) Failing test on Corax: Oregon.Fails 
	Added a note to the “Turn the complex property into a string” section.
- [RavenDB-21021](https://issues.hibernatingrhinos.com/issue/RavenDB-21021/Include-Corax-DebugView-expose-query-structure-in-Timings) Include Corax DebugView (expose query structure) in Timings() 
	To be documented when the feature is done.

2023-09-05 07:26 UTC, arekpalinski commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +  The maximum amount of memory that Corax can use for a memoization clause during query processing.
We just added a new config option related to initial dictionary creation:

https://github.com/ravendb/ravendb/pull/17146/files#diff-a26823a405dc6540477281200849f5d7918be61c063cd3228b6034fbbc852fd2R505-R510

2023-09-05 07:27 UTC, arekpalinski commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +  to force a retraining.
Note that 10000 docs is configurable via `Indexing.Corax.DocumentsLimitForCompressionDictionaryCreation` mentioned above. Also now we have `Indexing.Corax.MaxAllocationsAtDictionaryTrainingInMb` - 2GB on x64 machines and 128MB on 32bits machines

2023-09-05 07:30 UTC, arekpalinski commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +  In an index definition, add a compound field using the `CompoundFields.Add` method.
This is still in PR but we'll have a strongly types API:

https://github.com/ravendb/ravendb/pull/17176/commits/04d16c6516dd9974c952589f8d049b5907c90e0d

More specifically see the usage here:
https://github.com/ravendb/ravendb/pull/17176/commits/04d16c6516dd9974c952589f8d049b5907c90e0d#diff-948bc0c50471bb01c99e3fac74d035edc0a452dd6015dfad197f36dd03ecfc6dR149-R150

2023-09-05 07:31 UTC, arekpalinski commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +A compound field is a Corax index field comprised of multiple simple data elements.
Currently a compound field can be composed of exactly 2 fields.

2023-09-05 07:34 UTC, arekpalinski commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +# Search Engine: Corax
@redknightlois @ayende Can you please review this PR? The most important is this file

2023-09-05 09:03 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +  The maximum amount of memory that Corax can use for a memoization clause during query processing.
done

2023-09-05 09:36 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +A compound field is a Corax index field comprised of multiple simple data elements.
done

2023-09-05 10:17 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +  to force a retraining.
done

2023-09-05 13:51 UTC, redknightlois commented on Documentation/6.0/Raven.Documentation.Pages/server/configuration/indexing-configuration.markdown
> +{PANEL/}
Mark this as expert level.

2023-09-05 13:52 UTC, redknightlois commented
LGTM

2023-09-05 13:56 UTC, redknightlois commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +  `System.NotSupportedException` to notify the user that a search
Yes.

2023-09-05 13:57 UTC, redknightlois commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +
that in not supported in Corax

2023-09-05 14:13 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/server/configuration/indexing-configuration.markdown
> +{PANEL/}
done

2023-09-05 14:15 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +
done

2023-09-05 14:16 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +  `System.NotSupportedException` to notify the user that a search
@arekpalinski @maciejaszyk pls update me when it's implemented and i'll change it here

2023-09-06 08:14 UTC, ayende requested changes

2023-09-06 08:14 UTC, ayende commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +    Location = order.ShipTo.Location.ToString()
That would look the the user as if it would invoke the `Location.ToString()` here, no?

2023-09-06 08:14 UTC, ayende commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +Make sure your code handles failure scenarios such as `ToString` returning `null`
This is running server side, so there is not `null` possible, unless I missed something

2023-09-06 08:14 UTC, ayende commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +        CompoundField(x => x.Brand, x.Location);
```suggestion
        CompoundField(x => x.Brand, x => x.Location);
```

2023-09-06 08:14 UTC, ayende commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +    index included no compound field, but produce the results much faster.
Should add a note that this should be applied on very large datasets and specific queries. This is very much an expert only option.

2023-09-06 08:14 UTC, ayende commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +* Corax can create and use indexes of more than `int.MaxValue` documents.
`int.MaxValue` to number

2023-09-06 08:14 UTC, ayende commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +  Choose whether to include spatial information in document metadata when sorting by distance.
Why would I want one or the other? 
I assume there is a perf cost associated with enabling thos?

2023-09-06 08:14 UTC, ayende commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +  threshold (10000 docs by default) or the
```suggestion
  threshold (10,000 docs by default) or the 
```

2023-09-06 08:14 UTC, ayende commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +  threshold (2GB/128MB by default). Both thresholds are configurable.
What is 128MB here? You refer to 32 bits, which can safely be skipped

2023-09-06 08:14 UTC, ayende commented on Documentation/6.0/Raven.Documentation.Pages/server/configuration/indexing-configuration.markdown
> +- **Default**: 2 GB for x64, or 128 MB for x86 (32 bits)
```suggestion
- **Default**: 2 GB for 64 bits systems, or 128 MB for 32 bits systems
```

2023-09-06 08:14 UTC, ayende commented on Documentation/6.0/Raven.Documentation.Pages/server/configuration/indexing-configuration.markdown
> +- **Default**: `100000`
That says 10K above, which one is right?

2023-09-06 10:53 UTC, Danielle9897 commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +    | [MoreLikeThis](../../indexes/querying/morelikethis) | `yes`
Add that **Custom Sorters** are Not supported by Corax as well

2023-09-06 11:42 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/indexes/querying/paging.dotnet.markdown
> +indexes of more than `int.MaxValue` documents can be created and used.
done

2023-09-06 11:44 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/indexes/querying/paging.java.markdown
> +indexes of more than `int.MaxValue` documents can be created and used.
done

2023-09-06 11:46 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/indexes/querying/paging.js.markdown
> +indexes of more than `int.MaxValue` documents can be created and used.
done

2023-09-06 11:55 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +     selecting which search engine will be used by all the databases hosted by this server.
done

2023-09-06 12:07 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +    | [Distinct](../../indexes/querying/distinct) operation on a collection with more than int32 ({int.MaxValue}) documents | **no**
which is better, removing it completely or stating it isn't supported by both?

2023-09-06 12:41 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +* **Dynamic Fields**
done

2023-09-06 12:48 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +Corax [would fail](../../indexes/search-engine/corax#if-corax-encounters-a-complex-property-while-indexing).
{NOTE: }
The approach taken by Lucene, indexing such objects as a JSON string, usually makes no sense and is not supported by Corax.  
{NOTE/}

2023-09-06 13:03 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +        CompoundField(x => x.Brand, x.Location);
done

2023-09-06 13:17 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +    index included no compound field, but produce the results much faster.
added

2023-09-06 13:21 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +  Choose whether to include spatial information in document metadata when sorting by distance.
@redknightlois

2023-09-06 13:22 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +  threshold (10000 docs by default) or the
done

2023-09-06 13:23 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +  threshold (2GB/128MB by default). Both thresholds are configurable.
removed 128MB

2023-09-06 13:25 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/server/configuration/indexing-configuration.markdown
> +- **Default**: 2 GB for x64, or 128 MB for x86 (32 bits)
done

2023-09-06 13:34 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/server/configuration/indexing-configuration.markdown
> +- **Default**: `100000`
right
fixed

2023-09-06 13:43 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +    | [MoreLikeThis](../../indexes/querying/morelikethis) | `yes`
added, thanks

2023-09-06 14:12 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +    Location = order.ShipTo.Location.ToString()
--> 
Location = JsonConvert.Serialize(order.ShipTo.Location)

2023-09-08 05:44 UTC, ayende approved these changes

2023-09-08 12:41 UTC, arekpalinski commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +    Location = JsonConvert.Serialize(order.ShipTo.Location)
Such index will not compile:

```
(25,32): error CS0103: The name 'JsonConvert' does not exist in the current context
, IndexDefinitionProperty='', ProblematicText=''   at Raven.Server.Documents.Indexes.Static.IndexCompiler.CompileInternal(String originalName, String cSharpSafeName, MemberDeclarationSyntax class, IndexDefinition definition) in C:\Builds\RavenDB-6.0-Nightly\20230907-0851\src\Raven.Server\Documents\Indexes\Static\IndexCompiler.cs:line 244
```

2023-09-08 12:43 UTC, arekpalinski commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +  Choose whether to include spatial information in document metadata when sorting by distance.
Yes, IIRC this is related to performance. CC @maciejaszyk

2023-09-11 07:43 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +    Location = JsonConvert.Serialize(order.ShipTo.Location)
done

2023-09-11 08:43 UTC, merged

2023-09-12 05:58 UTC, arekpalinski commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +  `System.NotSupportedException` to notify the user that a search
@reebhub this got changed to `NotSupportedInCoraxException`

2023-09-22 08:35 UTC, arekpalinski commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +  threshold (2GB by default). Both thresholds are configurable.
Update: We changed that so now it's dependent the the amount of installed memory on the machine:
https://github.com/ravendb/ravendb/pull/17298/files#diff-a26823a405dc6540477281200849f5d7918be61c063cd3228b6034fbbc852fd2R44-R72

Maybe just mention that without saying explicitly exact number. It's up to 2GB.

2023-09-22 08:35 UTC, arekpalinski commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +{NOTE/}
Here we could reference Test Index feature article (once we'll have it)

2023-09-22 08:35 UTC, arekpalinski commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +       ![Per-Index Search Engine](images/corax-03_index-definition_searcher-select.png "Per-Index Search Engine")
I see on this image `Corax - experimental` - it's no longer experimental. We need to update the image.

2023-09-22 08:35 UTC, arekpalinski commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +  `System.NotSupportedException` to notify the user that a search
Update: We're gonna change that behavior for auto indexes: https://issues.hibernatingrhinos.com/issue/RavenDB-21430/Corax-Alert-users-about-indexing-of-complex-objects-in-auto-indexes-instead-of-throwing-an-error

2023-09-25 18:09 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +  threshold (2GB by default). Both thresholds are configurable.
--> or the [amount of memory](../../server/configuration/indexing-configuration#indexing.corax.maxallocationsatdictionarytraininginmb) threshold (up to 2GB).

changed in https://github.com/ravendb/docs/pull/1695

2023-09-25 19:56 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +       ![Per-Index Search Engine](images/corax-03_index-definition_searcher-select.png "Per-Index Search Engine")
retook all snapshots for the article

2023-09-25 20:26 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +  `System.NotSupportedException` to notify the user that a search
--> 

* If an auto index exists for the document Corax will alert the user:  
  `The value of '{fieldName}' field is a complex object. Indexing it as a text isn't supported. You should consider querying on individual fields of that object.`

changed in https://github.com/ravendb/docs/pull/1695