RDoc-2490_archiving
ravendb/docs pull request #1692
Opened 2023-09-07 04:03 UTC by reebhub

added an extensions-->archival page

2023-09-08 11:45 UTC, poissoncorp commented on Documentation/6.0/Raven.Documentation.Pages/server/extensions/archival.markdown
> +* In RavenDB, a document is marked as archived when an `@archived: true` property
In the context of the next sentence, the sentence `a document is marked as archived when an @archived: true property is included in metadata` might be misleading. The user may think that the metadata property is a ultimate indicator of document archival status. 

_Explaination/Reason of this comment:_
The document is marked as archived _internally_. Deleting or adding `@archived: true` to metadata, unfortunately, won't make a difference. The server archivist is the one to do the job here, and he is the only one who has access to do so.

So the only way to archive a document, is to instruct him to do so (archive the document) by providing the datetime when he should (`@archive-at`), as mentioned below.

2023-09-08 11:52 UTC, poissoncorp commented on Documentation/6.0/Raven.Documentation.Pages/server/extensions/archival.markdown
> +* RavenDB features and clients can recognize an archived document by its metadata
RavenDB **features** can recognize archived documents by its' **internal** flags.

`@archived: true` metadata property is for our users, to make it possible for them to e.g. apply various operations only on archived documents, basing on document metadata.

2023-09-08 12:04 UTC, poissoncorp commented on Documentation/6.0/Raven.Documentation.Pages/server/extensions/archival.markdown
> +for example, will continue to be updated no matter if the parent document is
The archived documents can be updated anyway, even after the archival.
The point is, that indexes of counters/time series won't be affected by parent document archival status.

Even more - we don't even support setting customized `ArchivedDataProcessingBehavior` for counters/time-series indexes

According to my personal feel of the feature, I think it's unnecessary to make statements about the archival status of document extensions. I wonder if we shouldn't refer to the document with its extensions as a monolith, with a few notes informing that document extensions will be indexed anyway.

2023-09-08 12:05 UTC, poissoncorp commented on Documentation/6.0/Raven.Documentation.Pages/server/extensions/archival.markdown
> +    Since indexes can recognize archived documents as such during indexation by their
_by their internal flags_

2023-09-08 12:44 UTC, poissoncorp commented on Documentation/6.0/Samples/csharp/Raven.Documentation.Samples/Server/Archival.cs
> +					session.Advanced.GetMetadataFor(user)[Constants.Documents.Metadata.Expires] = expiry;
Expires?

2023-09-08 12:45 UTC, poissoncorp commented on Documentation/6.0/Samples/csharp/Raven.Documentation.Samples/Server/Archival.cs
> +                    DeleteFrequencyInSec = 60
ArchiveFrequencyInSec

2023-09-08 12:46 UTC, poissoncorp requested changes
We lack an edit index panel description yet, where we can edit index archival behavior

2023-09-08 13:25 UTC, poissoncorp commented on Documentation/6.0/Raven.Documentation.Pages/server/extensions/archival.markdown
> +  * [Configuration Options](../../server/extensions/archival#configuration-options)
before mentioning configuration options, we should cover per-index or per-subscription settings
when we create an index or subscription, we can choose the behavior for processing archived documents - `ArchivedDataProcessingBehavior`

2023-09-08 13:27 UTC, poissoncorp commented on Documentation/6.0/Raven.Documentation.Pages/server/extensions/archival.markdown
> +  * [Configuration Options](../../server/extensions/archival#configuration-options)
we should also write that per-index/per-subscription settings aren't overwritten by database configuration

2023-09-08 13:28 UTC, poissoncorp commented on Documentation/6.0/Raven.Documentation.Pages/server/extensions/archival.markdown
> +     * [Data Subscriptions Handling of Archived Documents](../../server/extensions/archival#section-2)
we lack article about `unarchiving` by patching

> To undo the document archival, there's a new method in patching syntax.
When writing a patch script, use this method, to unarchive the document.
archived.unarchive(document)

2023-09-08 13:29 UTC, arekpalinski reviewed
TODO list:

- please make sure you go over https://issues.hibernatingrhinos.com/issue/RavenDB-19501/Data-archival-support#focus=Comments-67-505127.0-0 and below comments

- there is more features that are affected / related to data archival:
   - import / export (this is also no UI) - by default we import / export archived docs but this can be changed
   - in ETL script you can use `@archived: true` metadata and have some logic based on that (e.g. filter out archived documents)
   - backup will include archived docs (maybe obvious but worth to said it explicitly maybe)
   - querying - in particular collection queries - archived docs won't be excluded ( this might be counterintuitive) - see issue comment for details

2023-09-08 13:29 UTC, arekpalinski commented on Documentation/6.0/Raven.Documentation.Pages/server/extensions/archival.markdown
> +{PANEL/}
Important info about those config options. Those are _default_ options if a user doesn't specify anything specific in an index or subscription via dedicated properties.

I don't see they are documented (they should be). We have at index definition and subscription creation options new properties - `ArchivedDataProcessingBehavior? ArchivedDataProcessingBehavior {get; set; }` - as you can see they are nullable so if `null` is sent then the value is taken from above default configuration options.

Also we need to document that this is applied at the creation time (of an index or subscription). Meaning that changing the default config option won't affect existing indexes or subscriptions (similar to default search engine - corax or lucene).

2023-09-08 13:29 UTC, arekpalinski commented on Documentation/6.0/Samples/csharp/Raven.Documentation.Samples/Server/Archival.cs
> +				#endregion
We need to have code samples which show how to set `ArchivedDataProcessingBehavior` for indexes and subscriptions (at the definition level).

2023-09-08 13:29 UTC, arekpalinski commented on Documentation/6.0/Raven.Documentation.Pages/studio/database/settings/document-archival.markdown
> +
We need to have screenshots from index edit / new index views and subscription creation - there are options to choose archived data processing behavior per index / subscription.

(UI for that is already updated and it's final)

2023-09-08 13:29 UTC, poissoncorp commented on Documentation/6.0/Raven.Documentation.Pages/server/extensions/archival.markdown
> +     * [Data Subscriptions Handling of Archived Documents](../../server/extensions/archival#section-2)
also, we need to mention that there's also a possibility to filter out archived documents when exporting/importing a database in a separate text

2023-09-08 13:32 UTC, poissoncorp commented
We _may_ inform that while creating index by using `AbstractIndexCreationTask` API or by `IndexDefinitionBuilder` we may set `ArchivedDataProcessingBehavior`

2023-09-10 19:19 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/server/extensions/archival.markdown
> +* In RavenDB, a document is marked as archived when an `@archived: true` property
replaced with:
* A document can be **scheduled for archival** by adding its metadata an `@archive-at` 
  property with the requested archival time (in `UTC`) as a value.  
  RavenDB runs an archiving task that periodically scans the database for documents 
  scheduled for archiving. When it's time to archive a document, the task archives it 
  and replaces its metadata `@archive-at` property with an `@archived: true` property.  

    {INFO: }
    An `@archived: true` property is just an external indication that RavenDB has 
    archived a document. Users **cannot** archive documents manually by adding this 
    property to their metadata. To archive a document, schedule its archival.  
    {INFO/}

2023-09-10 19:44 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/server/extensions/archival.markdown
> +* RavenDB features and clients can recognize an archived document by its metadata
separated the two cases:

* Some **RavenDB features** recognize archived documents and can handle them accordingly.  
  Indexing and Data subscription tasks, for example, **refrain by default** from processing 
  archived documents. The exclusion of archived documents from indexation can improve  
  database performance significantly.  

* **RavenDB clients** can recognize archived documents by their metadata `@archived: true` 
  property and apply whatever specific logic suits them. A user-defined ETL task, for 
  example, can avoid sending its target documents that are marked as archived.

2023-09-10 19:59 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/server/extensions/archival.markdown
> +for example, will continue to be updated no matter if the parent document is
replaced it with:

* Archived documents and their document extensions **can** be updated regularly.  

* The document extensions of an archived document are **not** archived or affected 
  in any way by the archival status of their parent documents. A time series, for 
  example, **will** be indexed even if the document that owns it is archived.

2023-09-10 20:08 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/server/extensions/archival.markdown
> +    Since indexes can recognize archived documents as such during indexation by their
replaced with:

```
In addition, an index definition can include user-defined code that recognizes 
archived documents by their `@archived: true` property and handles them accordingly.  
```

2023-09-10 20:11 UTC, reebhub commented on Documentation/6.0/Samples/csharp/Raven.Documentation.Samples/Server/Archival.cs
> +					session.Advanced.GetMetadataFor(user)[Constants.Documents.Metadata.Expires] = expiry;
ignore this file, it's a placeholder (until your code is merged and then we can place it in a .cs files so errors will be recognizes). code snippets are currently included in the .markdown files.

2023-09-10 20:13 UTC, reebhub commented on Documentation/6.0/Samples/csharp/Raven.Documentation.Samples/Server/Archival.cs
> +			    await store.Maintenance.SendAsync(new ConfigureExpirationOperation(new ExpirationConfiguration
see above about code

2023-09-10 20:14 UTC, reebhub commented on Documentation/6.0/Samples/csharp/Raven.Documentation.Samples/Server/Archival.cs
> +                    DeleteFrequencyInSec = 60
see above about code

2023-09-10 23:26 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/server/extensions/archival.markdown
> +  * [Configuration Options](../../server/extensions/archival#configuration-options)
rearranged the configuration sections and added this information (there is now a small general configuration panel followed by a server/db configuration panel and feature definitions configuration panel)

2023-09-10 23:32 UTC, reebhub commented on Documentation/6.0/Samples/csharp/Raven.Documentation.Samples/Server/Archival.cs
> +				#endregion
done

2023-09-12 00:29 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/server/extensions/archival.markdown
> +     * [Data Subscriptions Handling of Archived Documents](../../server/extensions/archival#section-2)
done

2023-09-12 11:14 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/server/extensions/archival.markdown
> +  an `@archive-at` property with the designated archival time (**UTC**) as a value.
done

2023-09-12 11:56 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/server/extensions/archival.markdown
> +Archived documents are **compressed**.
done

2023-09-12 11:57 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/server/extensions/archival.markdown
> +{INFO/}
done

2023-09-12 12:09 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/server/extensions/archival.markdown
> +{PANEL/}
done

2023-09-12 14:36 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/studio/database/settings/document-archival.markdown
> +
done

2023-09-13 11:27 UTC, arekpalinski commented on Documentation/6.0/Raven.Documentation.Pages/server/extensions/archival.markdown
> +  RavenDB runs an archiving task that periodically scans the database for
Only when it's enabled. We don't do it by default

2023-09-13 11:33 UTC, arekpalinski commented on Documentation/6.0/Raven.Documentation.Pages/server/extensions/archival.markdown
> +indexes that exclude archived docs from the results).
Please remove `)` character

2023-09-13 11:34 UTC, arekpalinski commented on Documentation/6.0/Raven.Documentation.Pages/server/extensions/archival.markdown
> +  RavenDB runs an archiving task that periodically scans the database for
I see it's documented below

2023-09-13 11:36 UTC, arekpalinski approved these changes

2023-09-13 12:13 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/server/extensions/archival.markdown
> +indexes that exclude archived docs from the results).
-->
```
Collection queries **will** retrieve archived documents (since they do not run over 
indexes that exclude archived docs from the results).  
```

2023-09-13 12:16 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/server/extensions/archival.markdown
> +  RavenDB runs an archiving task that periodically scans the database for
--> 
```
When the archival feature is [enabled](../../server/extensions/archival#enabling-archiving-and-setting-scan-frequency), 
RavenDB runs an archiving task that periodically scans the database for documents scheduled for archival.  
```

2023-09-13 12:29 UTC, poissoncorp commented on Documentation/6.0/Raven.Documentation.Pages/studio/database/settings/document-archival.markdown
> +2. Provide the archival time (`UTC` time) as a value.
_Suggestion_ 
 We may provide a DateTime string format here, that users would be able to quickly copy-paste into their studio: `1970-01-01T12:00:00.0000000Z`

2023-09-13 12:50 UTC, poissoncorp commented on Documentation/6.0/Raven.Documentation.Pages/server/extensions/archival.markdown
> +importing archived and non-archived documents into different paths.
If I understood correctly, that user may separate archived documents from unarchived documents, and separately smuggle archived ones, I doubt if that's this simple - we have only an option to _skip_ archived documents, we can't smuggle only archived docs into a different path

2023-09-13 13:49 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/studio/database/settings/document-archival.markdown
> +2. Provide the archival time (`UTC` time) as a value.
done (added a link to the relevant server article section)

2023-09-13 13:55 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/server/extensions/archival.markdown
> +importing archived and non-archived documents into different paths.
fixed

2023-09-14 09:20 UTC, merged

2023-09-15 13:31 UTC, Lwiel commented on Documentation/6.0/Raven.Documentation.Pages/server/extensions/archival.markdown
> +if (isArchived === 'true')
I think we should use `return` instead of throwing an exception to show an example. We should also compare with `true` instead of `'true'`.
```js
var isArchived = this['@metadata']['@archived'];
if (isArchived === true) {
    return;
}
```

2023-09-15 13:32 UTC, arekpalinski commented on Documentation/6.0/Raven.Documentation.Pages/server/extensions/archival.markdown
> +if (isArchived === 'true')
Yes, let's use this syntax.