RDoc-1895 Add info on an option and setting up 2FA in cloud login article
ravendb/docs pull request #1742
Opened 2024-01-29 13:01 UTC by hiddenshadow21

2024-01-29 13:24 UTC, gregolsky approved these changes

2024-02-16 00:15 UTC, reebhub requested changes

2024-02-16 00:15 UTC, reebhub commented on Documentation/4.2/Raven.Documentation.Pages/cloud/cloud-overview.markdown
> +This will take you to configuration page.
configuration --> the configuration

2024-02-16 00:15 UTC, reebhub commented on Documentation/4.2/Raven.Documentation.Pages/cloud/cloud-overview.markdown
> +- Scan provided QR code or enter text code into authentication app of your choice.
--> Scan the provided QR code or enter the provided text code into an authentication app of your choice.

2024-02-16 00:15 UTC, reebhub commented on Documentation/4.2/Raven.Documentation.Pages/cloud/cloud-overview.markdown
> +- Type in 2FA code generated by your authentication app.
2FA code --> the 2FA code

2024-02-16 00:15 UTC, reebhub commented on Documentation/4.2/Raven.Documentation.Pages/cloud/cloud-overview.markdown
> +- Type in recovery phone number.
recovery --> a recovery

2024-02-16 00:15 UTC, reebhub commented on Documentation/4.2/Raven.Documentation.Pages/cloud/cloud-overview.markdown
> +After verifying you will be provided with recovery codes. Save them in secure place.
--> After verifying, you will be provided with recovery codes. Save them in a secure place.

2024-02-16 00:15 UTC, reebhub commented on Documentation/4.2/Raven.Documentation.Pages/cloud/cloud-overview.markdown
> +!["Add authenticator app"](images\mfa-001-add-authenticator.png "Add authenticator app")
![image](https://github.com/ravendb/docs/assets/43774704/03ebdfb3-c8aa-481f-aea5-ad29111de499)

2024-02-16 00:15 UTC, reebhub commented on Documentation/5.2/Raven.Documentation.Pages/cloud/cloud-overview.markdown
> +
see 4.2 comments above

2024-02-16 10:34 UTC, reebhub approved these changes

2024-02-19 14:24 UTC, gregolsky approved these changes

2024-02-19 14:29 UTC, merged