Python version for Open a Session
ravendb/docs pull request #1771
Opened 2024-02-29 00:01 UTC by reebhub

Related issue:
[RDoc-2630](https://issues.hibernatingrhinos.com/issue/RDoc-2630/Python-Client-API-Session-Open-a-session-Replace-C-samples)

2024-03-01 10:22 UTC, poissoncorp commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/opening-a-session.python.markdown
> +* Be sure to wrap the session variable with a 'using' statement to ensure proper disposal.
'with' statement

2024-03-01 10:23 UTC, poissoncorp commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/opening-a-session.python.markdown
> +* Be sure to wrap the session variable with a 'using' statement to ensure proper disposal.
```suggestion
* Be sure to wrap the session variable using a 'with' statement to ensure proper disposal.
```

2024-03-01 10:25 UTC, poissoncorp commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/opening-a-session.python.markdown
> +| **Database**                                            | string            | The Session will operate on this database,<br>overriding the Default Database.
`snake_case` every option

2024-03-01 10:26 UTC, poissoncorp commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/opening-a-session.python.markdown
> +| **NoTracking**                                          | bool              | `true` - The Session tracks changes made to all entities it loaded, stored, or queried for.<br>`false` - Tracking will
```suggestion
| **NoTracking**                                          | bool              | `True` - The Session tracks changes made to all entities it loaded, stored, or queried for.<br>`False` - Tracking will be turned off.<br>Learn more in [Disable tracking](../../client-api/session/configuration/how-to-disable-tracking) | `false`                                               |
```

In Python True and False begin with capital letter

2024-03-01 10:26 UTC, poissoncorp commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/opening-a-session.python.markdown
> +| **Database**                                            | string            | The Session will operate on this database,<br>overriding the Default Database.
```suggestion
| **Database**                                            | string            | The Session will operate on this database,<br>overriding the Default Database.                                                                                                                                                            | `None` - the Session operates on the Default Database |
```

in Python instead of null we use `None`

2024-03-01 10:26 UTC, poissoncorp commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/opening-a-session.python.markdown
> +| **Database**                                            | string            | The Session will operate on this database,<br>overriding the Default Database.
```suggestion
| **database**                                            | string            | The Session will operate on this database,<br>overriding the Default Database.                                                                                                                                                            | `null` - the Session operates on the Default Database |
```

2024-03-01 10:27 UTC, poissoncorp commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/opening-a-session.python.markdown
> +| **NoCaching**                                           | bool              | `true` - Server responses will Not be cached.<br>`false` - The Session caches the server responses.<br>Learn more in [D
```suggestion
| **NoCaching**                                           | bool              | `true` - Server responses will Not be cached.<br>`false` - The Session caches the server responses.<br>Learn more in [Disable caching](../../client-api/session/configuration/how-to-disable-caching)                                     | `false`                                               |
```
```suggestion
| **no_caching**                                           | bool              | `true` - Server responses will Not be cached.<br>`false` - The Session caches the server responses.<br>Learn more in [Disable caching](../../client-api/session/configuration/how-to-disable-caching)                                     | `false`                                               |
```

2024-03-01 10:32 UTC, poissoncorp commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/opening-a-session.python.markdown
> +| **Database**                                            | string            | The Session will operate on this database,<br>overriding the Default Database.
```suggestion
| **Database**                                            | str            | The Session will operate on this database,<br>overriding the Default Database.                                                                                                                                                            | `null` - the Session operates on the Default Database |
```

2024-03-01 10:33 UTC, poissoncorp commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/opening-a-session.python.markdown
> +| **Database**                                            | string            | The Session will operate on this database,<br>overriding the Default Database.
use `str` instead of 'string'

2024-03-01 10:33 UTC, poissoncorp commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/opening-a-session.python.markdown
> +| **TransactionMode**                                     | `TransactionMode` | Specify the Session's transaction mode<br>`SingleNode` / `ClusterWide`<br>Learn more in [Cluster-wide vs. Single-node](
```suggestion
| **TransactionMode**                                     | `TransactionMode` | Specify the Session's transaction mode<br>`SINGLE_NODE / `CLUSTER_WIDE`<br>Learn more in [Cluster-wide vs. Single-node](../../client-api/session/cluster-transaction/overview#cluster-wide-transaction-vs.-single-node-transaction)        | `SingleNode`                                          |
```

2024-03-01 10:34 UTC, poissoncorp commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/opening-a-session.python.markdown
> +| **DisableAtomicDocumentWrites-<br>InClusterWideTransaction** | bool?               | ( _Experts only_ ) <br>`true` - Disable Atomic-Guards in cluster-wide sessions.<br>`false` - Automatic atomic wr
there's no `?` operator in Python like in c#
```suggestion
| **DisableAtomicDocumentWrites-<br>InClusterWideTransaction** | bool               | ( _Experts only_ ) <br>`true` - Disable Atomic-Guards in cluster-wide sessions.<br>`false` - Automatic atomic writes in cluster-wide sessions are enabled.<br>Learn more in [Atomic-Guards](../../client-api/session/cluster-transaction/atomic-guards) | `false`       |
```

2024-03-01 10:39 UTC, poissoncorp requested changes
the comments apply for all future docs

2024-03-01 11:05 UTC, reebhub commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/opening-a-session.python.markdown
> +* Be sure to wrap the session variable with a 'using' statement to ensure proper disposal.
done

2024-03-01 11:06 UTC, reebhub commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/opening-a-session.python.markdown
> +* Be sure to wrap the session variable with a 'using' statement to ensure proper disposal.
done

2024-03-01 11:08 UTC, reebhub commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/opening-a-session.python.markdown
> +| **NoTracking**                                          | bool              | `true` - The Session tracks changes made to all entities it loaded, stored, or queried for.<br>`false` - Tracking will
done

2024-03-01 11:11 UTC, reebhub commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/opening-a-session.python.markdown
> +| **Database**                                            | string            | The Session will operate on this database,<br>overriding the Default Database.
done

2024-03-01 11:14 UTC, reebhub commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/opening-a-session.python.markdown
> +| **Database**                                            | string            | The Session will operate on this database,<br>overriding the Default Database.
done

2024-03-01 11:17 UTC, reebhub commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/opening-a-session.python.markdown
> +| **Database**                                            | string            | The Session will operate on this database,<br>overriding the Default Database.
done

2024-03-01 11:19 UTC, reebhub commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/opening-a-session.python.markdown
> +| **TransactionMode**                                     | `TransactionMode` | Specify the Session's transaction mode<br>`SingleNode` / `ClusterWide`<br>Learn more in [Cluster-wide vs. Single-node](
done

2024-03-01 11:21 UTC, reebhub commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/opening-a-session.python.markdown
> +| **TransactionMode**                                     | `TransactionMode` | Specify the Session's transaction mode<br>`SingleNode` / `ClusterWide`<br>Learn more in [Cluster-wide vs. Single-node](
also changed the default value in the last column (--> SINGLE_NODE)

2024-03-01 11:23 UTC, reebhub commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/opening-a-session.python.markdown
> +| **DisableAtomicDocumentWrites-<br>InClusterWideTransaction** | bool?               | ( _Experts only_ ) <br>`true` - Disable Atomic-Guards in cluster-wide sessions.<br>`false` - Automatic atomic wr
done

2024-03-06 09:44 UTC, poissoncorp commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/opening-a-session.python.markdown
> +* The following overloads are available:
i think we should drop this line, we have no overloads here

2024-03-06 09:45 UTC, poissoncorp commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/opening-a-session.python.markdown
> +| **no_caching**                                          | bool               | `True` - Server responses will Not be cached.<br>`False` - The Session caches the server responses.<br>Learn more in [
```suggestion
| **no_caching**                                          | bool               | `True` - Server responses will not be cached.<br>`False` - The Session caches the server responses.<br>Learn more in [Disable caching](../../client-api/session/configuration/how-to-disable-caching)                                     | `False`                                               |
```

2024-03-06 09:46 UTC, poissoncorp commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/opening-a-session.python.markdown
> +| **request_executor**                                    | `request_executor` | ( _Advanced option_ ) <br>The request executor the Session should use.
```suggestion
| **request_executor**                                    | `RequestExecutor` | ( _Advanced option_ ) <br>The request executor the Session should use.                                                                                                                                                                    | `None` - the default request executor is used         |
```

2024-03-06 09:46 UTC, poissoncorp commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/opening-a-session.python.markdown
> +| **transaction_mode**                                    | `transaction_mode` | Specify the Session's transaction mode<br>`SINGLE_NODE` / `CLUSTER_WIDE`<br>Learn more in [Cluster-wide vs. Single-nod
```suggestion
| **transaction_mode**                                    | `TransactionMode` | Specify the Session's transaction mode<br>`SINGLE_NODE` / `CLUSTER_WIDE`<br>Learn more in [Cluster-wide vs. Single-node](../../client-api/session/cluster-transaction/overview#cluster-wide-transaction-vs.-single-node-transaction)      | `SINGLE_NODE`                                         |
```

2024-03-06 09:47 UTC, poissoncorp requested changes
very last changes
after them we can be merge

2024-03-06 12:34 UTC, reebhub commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/opening-a-session.python.markdown
> +* The following overloads are available:
done

2024-03-06 12:35 UTC, reebhub commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/opening-a-session.python.markdown
> +| **no_caching**                                          | bool               | `True` - Server responses will Not be cached.<br>`False` - The Session caches the server responses.<br>Learn more in [
done

2024-03-06 12:37 UTC, reebhub commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/opening-a-session.python.markdown
> +| **request_executor**                                    | `request_executor` | ( _Advanced option_ ) <br>The request executor the Session should use.
done

2024-03-06 12:38 UTC, reebhub commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/opening-a-session.python.markdown
> +| **transaction_mode**                                    | `transaction_mode` | Specify the Session's transaction mode<br>`SINGLE_NODE` / `CLUSTER_WIDE`<br>Learn more in [Cluster-wide vs. Single-nod
done

2024-03-06 12:50 UTC, poissoncorp approved these changes

2024-03-08 14:49 UTC, merged