Python version for Storing Entities
ravendb/docs pull request #1772
Opened 2024-02-29 01:08 UTC by reebhub

Related issue:
[RDoc-2631](https://issues.hibernatingrhinos.com/issue/RDoc-2631/Python-Client-API-Session-Storing-entities-Replace-C-samples)

2024-03-01 10:41 UTC, poissoncorp commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/storing-entities.python.markdown
> +| **id** | string | Entity will be stored under this ID, (`null` to generate automatically) |
```suggestion
| **key** | str | Entity will be stored under this ID, (`None` to generate automatically) |
```

2024-03-01 10:43 UTC, poissoncorp requested changes
similar to https://github.com/ravendb/docs/pull/1771

2024-03-01 11:48 UTC, reebhub commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/storing-entities.python.markdown
> +| **id** | string | Entity will be stored under this ID, (`null` to generate automatically) |
done

2024-03-01 11:49 UTC, reebhub commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/storing-entities.python.markdown
> +| **change_vector** | string | Entity change vector, used for concurrency checks (`null` to skip check) |
done

2024-03-06 09:48 UTC, poissoncorp approved these changes
ready to go

2024-03-08 14:49 UTC, merged