[Python] querying articles batch 1 [Replace C# samples]
ravendb/docs pull request #1797
Opened 2024-03-15 01:05 UTC by reebhub

Related issues: 
[RDoc-2683](https://issues.hibernatingrhinos.com/issue/RDoc-2683/Python-Client-API-Session-Querying-Customize-query-Replace-C-samples) - customize query
[RDoc-2684](https://issues.hibernatingrhinos.com/issue/RDoc-2684/Python-Client-API-Session-Querying-Get-query-statistics-Replace-C-samples) - get query statistics
[RDoc-2685](https://issues.hibernatingrhinos.com/issue/RDoc-2685/Python-Client-API-Session-Querying-Count-query-results-Replace-C-samples) - count query results
[RDoc-2688](https://issues.hibernatingrhinos.com/issue/RDoc-2688/Python-Client-API-Session-Querying-Sort-query-results-Replace-C-samples) - sort query results
[RDoc-2682](https://issues.hibernatingrhinos.com/issue/RDoc-2682/Python-Client-API-Session-Querying-Document-Query-Query-vs-Document-Query-Replace-C-samples) - query vs document query

2024-03-15 11:01 UTC, poissoncorp commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/querying/document-query/query-vs-document-query.python.markdown
> +* RavenDB Queries can be executed using `query`, `document_query`, `raw_query`, or directly via [RQL](../../../../client-api/session/querying/what-is-rql).
I'm a bit confused with this line, `raw_query` is a way to pass RQL to the server

2024-03-15 11:05 UTC, poissoncorp commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/querying/document-query/query-vs-document-query.python.markdown
> +`query` and `document_query` can be converted to one another.
it's the same, so this section should be dropped

2024-03-15 12:07 UTC, reebhub commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/querying/document-query/query-vs-document-query.python.markdown
> +* RavenDB Queries can be executed using `query`, `document_query`, `raw_query`, or directly via [RQL](../../../../client-api/session/querying/what-is-rql).
--> 
RavenDB Queries can be executed using `query` or `document_query`, or by passing [RQL](../../../../client-api/session/querying/what-is-rql) directly to the server via `raw_query`.

2024-03-15 12:09 UTC, reebhub commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/querying/document-query/query-vs-document-query.python.markdown
> +`query` and `document_query` can be converted to one another.
done

2024-03-15 12:55 UTC, poissoncorp commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/querying/document-query/query-vs-document-query.python.markdown
> +* `query` is **immutable** while `document_query` is **mutable**.
this panel should be dropped too, all queries in Python (DocumentQuery) are mutable

2024-03-15 12:56 UTC, poissoncorp commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/querying/document-query/query-vs-document-query.python.markdown
> +* When using _query_, the query is translated into a _document_query_ object,
using query is the exact same thing as using document_query

2024-03-15 12:57 UTC, poissoncorp commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/querying/document-query/query-vs-document-query.python.markdown
> +    `query: from Users where startsWith(Name, 'A')`
`snake_case` the variables names like 'name'

2024-03-15 12:57 UTC, poissoncorp commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/querying/document-query/query-vs-document-query.python.markdown
> +    `eyeQuery: from Users where startsWith(Name, 'A') and EyeColor = 'blue'`
```suggestion
    `eyeQuery: from Users where startsWith(name, 'A') and eye_color = 'blue'`
```

2024-03-15 13:35 UTC, poissoncorp commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/querying/document-query/query-vs-document-query.python.markdown
> +* Both `query` and `document_query` use `AND` as the default operator.
`
```suggestion
* Queries use `AND` as the default operator.  
```

2024-03-15 13:37 UTC, poissoncorp commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/querying/how-to-count-query-results.python.markdown
> +where ShipTo.Country == "UK" limit 0, 0
```suggestion
where ship_to.country == "UK" limit 0, 0
```

2024-03-15 13:38 UTC, poissoncorp commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/querying/how-to-count-query-results.python.markdown
> +The number of results is available in the `QueryStatistics` object.
We should describe that user needs to write a function that takes QueryStatistics as an argument.
We'll call this function, that user provided (with his logic), using the retrieved QueryStatistics object

2024-03-15 13:39 UTC, poissoncorp commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/querying/how-to-count-query-results.python.markdown
> +The number of results is available in the `QueryStatistics` object.
Look on the example, i'm calling `with_statistics` and passing the function i wrote

2024-03-15 13:42 UTC, poissoncorp commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/querying/how-to-customize-query.python.markdown
> +* Use `customize()` to set the following customization options on a specific [query](../../../client-api/session/querying/how-to-query).
we don't call `customize` in Python, the approach is different - all necessary methods are available in the `query` like 

```py
 session.query(object_type=Employee).add_after_query_executed_listener(my_callback_function)
```

2024-03-15 13:43 UTC, poissoncorp commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/querying/how-to-customize-query.python.markdown
> +* Use `customize()` to set the following customization options on a specific [query](../../../client-api/session/querying/how-to-query).
`customize` isn't a thing here - but to mirror the results we're providing examples

2024-03-15 13:43 UTC, poissoncorp commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/querying/how-to-customize-query.python.markdown
> +* Each such customization can also be implemented via the [document_query](../../../client-api/session/querying/document-query/what-is-document-query) API.
let's drop that line

2024-03-15 13:45 UTC, poissoncorp commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/querying/how-to-customize-query.python.markdown
> +* A query can also be customized on the Store or Session level by subscribing to `on_before_query`.
```suggestion
* A query can also be customized on the Store or Session level by calling `add_before_query`.  
```

2024-03-15 13:46 UTC, poissoncorp commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/querying/how-to-customize-query.python.markdown
> +* Use `before_query_executed` to customize the query just before it is executed.
```suggestion
* Use `before_query` to customize the query just before it is executed.
```

2024-03-15 14:23 UTC, poissoncorp commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/querying/how-to-customize-query.python.markdown
> +* The timing statistics will be included in the query results.
similar case to `with_statistics`
`timings` takes `timings_callback` as an argument 


```py
    def timings(self, timings_callback: Callable[[QueryTimings], None]) -> DocumentQuery[_T]: ...
```

2024-03-15 14:24 UTC, poissoncorp commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/querying/how-to-customize-query.python.markdown
> +| **timings** | `QueryTimings` | An out param that will be filled with the timings results |
```suggestion
| **timings_callback** | `Callable[[QueryTimings], None]` | An callback method that will be called with the timings results |
```

2024-03-15 14:26 UTC, poissoncorp commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/querying/how-to-get-query-statistics.python.markdown
> +| **stats_callback** | `Callable[[QueryStatistics], None]` | An 'out' param for the query statistics |
```suggestion
| **stats_callback** | `Callable[[QueryStatistics], None]` | An _action_ that will be called with query statistics object|

```

2024-03-15 14:27 UTC, poissoncorp commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/querying/sort-query-results.python.markdown
> +* Use `OrderBy` or `OrderByDescending` to order the results by the specified document-field.
```suggestion
* Use `order_by` or `order_by_descending` to order the results by the specified document-field.
```

2024-03-15 14:27 UTC, poissoncorp commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/querying/sort-query-results.python.markdown
> +where UnitsInStock > 10
```suggestion
where units_in_stock > 10
```

2024-03-15 14:28 UTC, poissoncorp commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/querying/sort-query-results.python.markdown
> +where UnitsInStock < 5 or Discontinued == true
```suggestion
where units_in_stock < 5 or discontinued == true
```

2024-03-15 14:29 UTC, poissoncorp commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/querying/sort-query-results.python.markdown
> +* Use `RandomOrdering` to randomize the order of the query results.
```suggestion
* Use `RandomOrdering` to randomize the order of the query results.
```
```suggestion
* Use `random_ordering` to randomize the order of the query results.
```

2024-03-15 14:30 UTC, poissoncorp requested changes
lets cover more differences

2024-03-15 23:07 UTC, reebhub commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/querying/document-query/query-vs-document-query.python.markdown
> +* When using _query_, the query is translated into a _document_query_ object,
* `query` and `document_query` queries are translated to RQL and sent to the server.  
* Available _query_ methods are listed [here](../../../../client-api/session/querying/how-to-query#custom-methods).  
* Available _document_query_ methods and extensions are listed [here](../../../../client-api/session/querying/document-query/what-is-document-query#custom-methods-and-extensions).

2024-03-15 23:14 UTC, reebhub commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/querying/document-query/query-vs-document-query.python.markdown
> +* `query` is **immutable** while `document_query` is **mutable**.
changed the panel name to `Mutability` and the quoted line to:

All Python queries (`query` and `document_query`) are **mutable**.  
You may get different results if you try to *reuse* a query.

2024-03-15 23:19 UTC, reebhub commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/querying/document-query/query-vs-document-query.python.markdown
> +    `query: from Users where startsWith(Name, 'A')`
done

2024-03-15 23:20 UTC, reebhub commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/querying/document-query/query-vs-document-query.python.markdown
> +    `eyeQuery: from Users where startsWith(Name, 'A') and EyeColor = 'blue'`
done

2024-03-15 23:20 UTC, reebhub commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/querying/document-query/query-vs-document-query.python.markdown
> +* Both `query` and `document_query` use `AND` as the default operator.
done

2024-03-15 23:24 UTC, reebhub commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/querying/how-to-count-query-results.python.markdown
> +where ShipTo.Country == "UK" limit 0, 0
done

2024-03-16 00:10 UTC, reebhub commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/querying/how-to-count-query-results.python.markdown
> +The number of results is available in the `QueryStatistics` object.
done

2024-03-16 00:16 UTC, reebhub commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/querying/how-to-customize-query.python.markdown
> +* Each such customization can also be implemented via the [document_query](../../../client-api/session/querying/document-query/what-is-document-query) API.
dropped

2024-03-16 00:20 UTC, reebhub commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/querying/how-to-customize-query.python.markdown
> +* Use `customize()` to set the following customization options on a specific [query](../../../client-api/session/querying/how-to-query).
done

2024-03-16 00:23 UTC, reebhub commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/querying/how-to-customize-query.python.markdown
> +* A query can also be customized on the Store or Session level by subscribing to `on_before_query`.
done

2024-03-16 00:24 UTC, reebhub commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/querying/how-to-customize-query.python.markdown
> +* Use the `projection` method to customize and modify this behavior.
done

2024-03-16 00:42 UTC, reebhub commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/querying/how-to-customize-query.python.markdown
> +* The timing statistics will be included in the query results.
done

2024-03-16 00:44 UTC, reebhub commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/querying/how-to-customize-query.python.markdown
> +| **timings** | `QueryTimings` | An out param that will be filled with the timings results |
done
thx

2024-03-16 00:47 UTC, reebhub commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/querying/how-to-get-query-statistics.python.markdown
> +| **stats_callback** | `Callable[[QueryStatistics], None]` | An 'out' param for the query statistics |
done

2024-03-16 00:48 UTC, reebhub commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/querying/sort-query-results.python.markdown
> +* Use `OrderBy` or `OrderByDescending` to order the results by the specified document-field.
done

2024-03-16 00:49 UTC, reebhub commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/querying/sort-query-results.python.markdown
> +where UnitsInStock > 10
done

2024-03-16 00:50 UTC, reebhub commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/querying/sort-query-results.python.markdown
> +where UnitsInStock < 5 or Discontinued == true
done

2024-03-16 00:51 UTC, reebhub commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/querying/sort-query-results.python.markdown
> +* Use `RandomOrdering` to randomize the order of the query results.
done

2024-03-16 00:52 UTC, reebhub commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/querying/sort-query-results.python.markdown
> +order by QuantityPerUnit as alphanumeric
done

2024-03-18 09:43 UTC, poissoncorp commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/querying/document-query/query-vs-document-query.python.markdown
> +* Queries` use `AND` as the default operator.
you may get syntax bug here 
```suggestion
* Queries use `AND` as the default operator.  
```

2024-03-18 09:44 UTC, poissoncorp commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/querying/how-to-customize-query.python.markdown
> +* A query can also be customized on the Store or Session level by by calling `add_before_query`.
```suggestion
* A query can be customized on the Store or Session level by calling various methods from the rich API.  
```

2024-03-18 09:49 UTC, poissoncorp commented on Documentation/6.0/Raven.Documentation.Pages/client-api/session/querying/sort-query-results.python.markdown
> +* Use `OrderBy` or `OrderByDescending` to order the results by the specified document-field.
```suggestion
* Use `order_by` or `order_by_descending` to order the results by the specified document-field.
```

2024-03-18 09:49 UTC, poissoncorp commented on Documentation/6.0/Raven.Documentation.Pages/client-api/session/querying/sort-query-results.python.markdown
> +where UnitsInStock > 10
```suggestion
where units_in_stock > 10
```

2024-03-18 09:50 UTC, poissoncorp commented on Documentation/6.0/Raven.Documentation.Pages/client-api/session/querying/sort-query-results.python.markdown
> +order by UnitsInStock as long
```suggestion
order by units_in_stock as long
```

2024-03-18 09:51 UTC, poissoncorp commented on Documentation/6.0/Raven.Documentation.Pages/client-api/session/querying/sort-query-results.python.markdown
> +* Use `RandomOrdering` to randomize the order of the query results.
```suggestion
* Use `random_ordering` to randomize the order of the query results.
```

2024-03-18 09:51 UTC, poissoncorp commented on Documentation/6.0/Raven.Documentation.Pages/client-api/session/querying/sort-query-results.python.markdown
> +where UnitsInStock > 10
```suggestion
where units_in_stock > 10
```

2024-03-18 09:51 UTC, poissoncorp commented on Documentation/6.0/Raven.Documentation.Pages/client-api/session/querying/sort-query-results.python.markdown
> +group by Category
```suggestion
group by category
```

2024-03-18 09:51 UTC, poissoncorp commented on Documentation/6.0/Raven.Documentation.Pages/client-api/session/querying/sort-query-results.python.markdown
> +select key() as "Category", count()
```suggestion
select key() as "category", count()
```

2024-03-18 09:52 UTC, poissoncorp commented on Documentation/6.0/Raven.Documentation.Pages/client-api/session/querying/sort-query-results.python.markdown
> +group by Category
```suggestion
group by category
```

2024-03-18 09:52 UTC, poissoncorp commented on Documentation/6.0/Raven.Documentation.Pages/client-api/session/querying/sort-query-results.python.markdown
> +select key() as 'Category', sum(UnitsInStock) as Sum
```suggestion
select key() as 'category', sum(units_in_stock) as Sum
```

2024-03-18 09:53 UTC, poissoncorp commented on Documentation/6.0/Raven.Documentation.Pages/client-api/session/querying/sort-query-results.python.markdown
> +order by QuantityPerUnit as alphanumeric
```suggestion
order by quantity_per_unit as alphanumeric
```

2024-03-18 09:53 UTC, poissoncorp commented on Documentation/6.0/Raven.Documentation.Pages/client-api/session/querying/sort-query-results.python.markdown
> +where UnitsInStock > 10
```suggestion
where units_in_stock > 10
```

2024-03-18 09:54 UTC, poissoncorp commented on Documentation/6.0/Raven.Documentation.Pages/client-api/session/querying/sort-query-results.python.markdown
> +order by UnitsInStock as long desc, score(), Name
```suggestion
order by units_in_stock as long desc, score(), Name
```

2024-03-18 09:54 UTC, poissoncorp commented on Documentation/6.0/Raven.Documentation.Pages/client-api/session/querying/sort-query-results.python.markdown
> +where UnitsInStock > 10
```suggestion
where units_in_stock > 10
```

2024-03-18 09:54 UTC, poissoncorp commented on Documentation/6.0/Raven.Documentation.Pages/client-api/session/querying/sort-query-results.python.markdown
> +order by custom(UnitsInStock, "MySorter")
```suggestion
order by custom(units_in_stock, "MySorter")
```

2024-03-18 09:55 UTC, poissoncorp requested changes
looking great, let's just fix those few casing issues

2024-03-18 11:00 UTC, reebhub commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/querying/document-query/query-vs-document-query.python.markdown
> +* Queries` use `AND` as the default operator.
done

2024-03-18 11:01 UTC, reebhub commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/querying/how-to-customize-query.python.markdown
> +* A query can also be customized on the Store or Session level by by calling `add_before_query`.
done

2024-03-18 11:09 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/client-api/session/querying/sort-query-results.python.markdown
> +* Use `OrderBy` or `OrderByDescending` to order the results by the specified document-field.
seems like you're reviewing an old commit? these are already fixed

2024-03-18 11:10 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/client-api/session/querying/sort-query-results.python.markdown
> +where UnitsInStock > 10
already fixed

2024-03-18 11:10 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/client-api/session/querying/sort-query-results.python.markdown
> +order by UnitsInStock as long
already fixed

2024-03-18 11:10 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/client-api/session/querying/sort-query-results.python.markdown
> +where UnitsInStock < 5 or Discontinued == true
already fixed

2024-03-18 11:12 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/client-api/session/querying/sort-query-results.python.markdown
> +* Use `RandomOrdering` to randomize the order of the query results.
already fixed

2024-03-18 11:13 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/client-api/session/querying/sort-query-results.python.markdown
> +where UnitsInStock > 10
already fixed

2024-03-18 11:15 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/client-api/session/querying/sort-query-results.python.markdown
> +select key() as "Category", count()
done

2024-03-18 11:15 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/client-api/session/querying/sort-query-results.python.markdown
> +select key() as 'Category', sum(UnitsInStock) as Sum
done

2024-03-18 11:16 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/client-api/session/querying/sort-query-results.python.markdown
> +order by QuantityPerUnit as alphanumeric
already fixed

2024-03-18 11:17 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/client-api/session/querying/sort-query-results.python.markdown
> +where UnitsInStock > 10
already fixed

2024-03-18 11:17 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/client-api/session/querying/sort-query-results.python.markdown
> +order by UnitsInStock as long desc, score(), Name
already fixed

2024-03-18 11:19 UTC, reebhub commented on Documentation/6.0/Raven.Documentation.Pages/client-api/session/querying/sort-query-results.python.markdown
> +order by custom(UnitsInStock, "MySorter")
already fixed

2024-03-19 13:30 UTC, merged