[Python] querying articles batch 5 [Replace C# samples]
ravendb/docs pull request #1819
Opened 2024-04-16 12:56 UTC by reebhub

Related issues:
[RDoc-2739](https://issues.hibernatingrhinos.com/issue/RDoc-2739/Python-Client-API-Session-Querying-Text-search-Full-text-search-Replace-C-samples) - Full-text search
[RDoc-2740](https://issues.hibernatingrhinos.com/issue/RDoc-2740/Python-Client-API-Session-Querying-Text-search-Highlight-search-results-Replace-C-samples) - Highlight search results
[RDoc-2741](https://issues.hibernatingrhinos.com/issue/RDoc-2741/Python-Client-API-Session-Querying-Text-search-Fuzzy-search-Replace-C-samples) - Fuzzy search
[RDoc-2742](https://issues.hibernatingrhinos.com/issue/RDoc-2742/Python-Client-API-Session-Querying-Text-search-Using-Regex-Replace-C-samples) - Using Regex
[RDoc-2743](https://issues.hibernatingrhinos.com/issue/RDoc-2743/Python-Client-API-Session-Querying-Debugging-Include-query-explanations-Replace-C-samples) - Include query explanations
[RDoc-2744](https://issues.hibernatingrhinos.com/issue/RDoc-2744/Python-Client-API-Session-Querying-Debugging-Include-query-timings-Replace-C-samples) - Include query timings

2024-04-17 12:23 UTC, poissoncorp commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/querying/debugging/include-explanations.python.markdown
> +| **explanations_callback** | `Callable[[Explanations], None]` | <ul><li>A callback function with an output parameter.</li><li>The parameter passed to the callback will be filled with the `Explanatio
```suggestion
| **explanations_callback** | `Callable[[Explanations], None]` | <ul><li>A callback function (action) that takes Explanations as an argument. It will be called by the client with resulting Explanations.</li> <li>You can interact with resulting Explanations inside your callback.</li></ul> |
```

2024-04-17 12:29 UTC, poissoncorp commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/querying/text-search/full-text-search.python.markdown
> +| `DocumentQuery[_T]` | Query results |
```suggestion
| `DocumentQuery[_T]` | Document Query | 
```

to get results, we need to enumerate the query
like: `list(query.search(...))`

2024-04-17 12:30 UTC, poissoncorp commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/querying/text-search/fuzzy-search.python.markdown
> +| `DocumentQuery[_T]` | Query results |
```suggestion
| `DocumentQuery[_T]` | The same query object |
```

2024-04-17 12:32 UTC, poissoncorp commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/querying/text-search/highlight-query-results.python.markdown
> +| **highlightings_callback** | `Callable[[Highlightings], None]` | An 'out' param that will contain the highlighted text fragments for each returned result |
```suggestion
| **highlightings_callback** | `Callable[[Highlightings], None]` | A callback function (action) ... // like the rest |
```

2024-04-17 12:33 UTC, poissoncorp requested changes
after addressing these re-request my review 🙏

2024-04-17 19:11 UTC, reebhub commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/querying/debugging/include-explanations.python.markdown
> +| **explanations_callback** | `Callable[[Explanations], None]` | <ul><li>A callback function with an output parameter.</li><li>The parameter passed to the callback will be filled with the `Explanatio
done

2024-04-17 19:18 UTC, reebhub commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/querying/text-search/full-text-search.python.markdown
> +| **operator** | `SearchOperator ` | Logical operator to use between multiple terms in the same Search method.<br>**Can be**: `SearchOperator.OR` or `SearchOperator.AND`<br>**Default**: `SearchOperat
fixed

2024-04-17 19:20 UTC, reebhub commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/querying/text-search/full-text-search.python.markdown
> +| `DocumentQuery[_T]` | Query results |
done

2024-04-17 19:21 UTC, reebhub commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/querying/text-search/fuzzy-search.python.markdown
> +| `DocumentQuery[_T]` | Query results |
done

2024-04-17 19:24 UTC, reebhub commented on Documentation/5.4/Raven.Documentation.Pages/client-api/session/querying/text-search/highlight-query-results.python.markdown
> +| **highlightings_callback** | `Callable[[Highlightings], None]` | An 'out' param that will contain the highlighted text fragments for each returned result |
--> `A callback function to retrieve the highlighted text fragments for each returned result`

2024-04-18 12:52 UTC, poissoncorp approved these changes

2024-04-19 08:39 UTC, merged