[Python] Index querying pages batch [Replace C# samples]
ravendb/docs pull request #1845
Opened 2024-05-27 11:12 UTC by reebhub

[RDoc-2829](https://issues.hibernatingrhinos.com/issue/RDoc-2829/Python-Indexes-Querying-Querying-an-index-Replace-C-samples) Querying an index
[RDoc-2830](https://issues.hibernatingrhinos.com/issue/RDoc-2830/Python-ndexes-Querying-Filtering-Replace-C-samples) Filtering
[RDoc-2831](https://issues.hibernatingrhinos.com/issue/RDoc-2831/Python-ndexes-Querying-Exploration-queries-Replace-C-samples) Exploration queries
[RDoc-2832](https://issues.hibernatingrhinos.com/issue/RDoc-2832/Python-Indexes-Querying-Paging-Replace-C-samples) Paging
[RDoc-2833](https://issues.hibernatingrhinos.com/issue/RDoc-2833/Python-Indexes-Querying-Sorting-Replace-C-samples) Sorting
[RDoc-2834](https://issues.hibernatingrhinos.com/issue/RDoc-2834/Python-Indexes-Querying-Project-index-query-results-Replace-C-samples) Project index query results
[RDoc-2835](https://issues.hibernatingrhinos.com/issue/RDoc-2835/Python-Indexes-Querying-Full-Text-Search-Replace-C-samples) Full-Text Search
[RDoc-2836](https://issues.hibernatingrhinos.com/issue/RDoc-2836/Python-Indexes-Querying-Intersection-Replace-C-samples) Intersection
[RDoc-2837](https://issues.hibernatingrhinos.com/issue/RDoc-2837/Python-Indexes-Querying-Suggestions-Replace-C-samples) Suggestions
[RDoc-2838](https://issues.hibernatingrhinos.com/issue/RDoc-2838/Python-Indexes-Querying-Spatial-Replace-C-samples) Spatial
[RDoc-2839](https://issues.hibernatingrhinos.com/issue/RDoc-2839/Python-Indexes-Querying-Faceted-search-Replace-C-samples) Faceted search
[RDoc-2840](https://issues.hibernatingrhinos.com/issue/RDoc-2840/Python-Indexes-Querying-More-like-this-Replace-C-samples) More like this
[RDoc-2841](https://issues.hibernatingrhinos.com/issue/RDoc-2841/Python-Indexes-Querying-Highlighting-Replace-C-samples) Highlighting

2024-06-04 13:30 UTC, poissoncorp commented on Documentation/5.4/Raven.Documentation.Pages/indexes/querying/faceted-search.python.markdown
> +| **builder_or_facet** (Union) | `Callable[[FacetBuilder]`<br>**or**<br>`FacetBase` | Builder with a fluent API that constructs a `FacetBase` instance<br>**or**<br>`FacetBase` implementation defining
```suggestion
| **builder_or_facet** (Union) | `Callable[[FacetBuilder]`<br>**or**<br>`FacetBase` | Builder with a fluent API that constructs a `FacetBase` instance<br>**or**<br>`FacetBase` implementation instance|
```

2024-06-04 13:31 UTC, poissoncorp commented on Documentation/5.4/Raven.Documentation.Pages/indexes/querying/faceted-search.python.markdown
> +| **facets**                   | `List[FacetBase]`                                  | A list of `FacetBase` implementations. |
```suggestion
| **facets**                   | `List[FacetBase]`                                  | A list of `FacetBase` implementation instances. |
```

2024-06-04 13:32 UTC, poissoncorp commented on Documentation/5.4/Raven.Documentation.Pages/indexes/querying/faceted-search.python.markdown
> +| **\*ranges**     | `RangeBuilder` | Multiple index ranges (at least one), separated by `,` |
the `range_` argument is the first one
if user would like to pass more, we have *ranges for it

2024-06-04 13:46 UTC, poissoncorp commented on Documentation/5.4/Raven.Documentation.Pages/indexes/querying/morelikethis.python.markdown
> +| **MinimumTermFrequency** | `int` | Ignores terms with less than this frequency in the source doc |
please `snake_case` the fields names

2024-06-04 13:47 UTC, poissoncorp commented on Documentation/5.4/Raven.Documentation.Pages/indexes/querying/morelikethis.python.markdown
> +| **Fields** | `str[]` | Fields to compare |
```suggestion
| **Fields** | `List[str]` | Fields to compare |

```

2024-06-04 14:38 UTC, poissoncorp commented on Documentation/5.4/Raven.Documentation.Pages/indexes/querying/sorting.python.markdown
> +* E.g. in the above example, ordering by `x => x.UnitsInStock` will result in `OrderingType.Int`
```suggestion
* E.g. in the above example, ordering by `UnitsInStock` will result in `OrderingType.Int`  
```

2024-06-04 14:40 UTC, poissoncorp requested changes
let's fix these small issues & we good to go :]

2024-06-24 12:32 UTC, reebhub commented on Documentation/5.4/Raven.Documentation.Pages/indexes/querying/faceted-search.python.markdown
> +| **builder_or_facet** (Union) | `Callable[[FacetBuilder]`<br>**or**<br>`FacetBase` | Builder with a fluent API that constructs a `FacetBase` instance<br>**or**<br>`FacetBase` implementation defining
done

2024-06-24 12:33 UTC, reebhub commented on Documentation/5.4/Raven.Documentation.Pages/indexes/querying/faceted-search.python.markdown
> +| **facets**                   | `List[FacetBase]`                                  | A list of `FacetBase` implementations. |
done

2024-06-24 12:35 UTC, reebhub commented on Documentation/5.4/Raven.Documentation.Pages/indexes/querying/faceted-search.python.markdown
> +| **\*ranges**     | `RangeBuilder` | Multiple index ranges (at least one), separated by `,` |
done

2024-06-24 12:38 UTC, reebhub commented on Documentation/5.4/Raven.Documentation.Pages/indexes/querying/morelikethis.python.markdown
> +| **MinimumTermFrequency** | `int` | Ignores terms with less than this frequency in the source doc |
done

2024-06-24 12:39 UTC, reebhub commented on Documentation/5.4/Raven.Documentation.Pages/indexes/querying/morelikethis.python.markdown
> +| **Fields** | `str[]` | Fields to compare |
done

2024-06-24 12:40 UTC, reebhub commented on Documentation/5.4/Raven.Documentation.Pages/indexes/querying/projections.python.markdown
> +The `aelect_fields` methods can also take a `ProjectionBehavior` parameter, which
done

2024-06-24 12:42 UTC, reebhub commented on Documentation/5.4/Raven.Documentation.Pages/indexes/querying/sorting.python.markdown
> +* E.g. in the above example, ordering by `x => x.UnitsInStock` will result in `OrderingType.Int`
done

2024-06-24 13:31 UTC, merged