RavenDB 6.1 breaking changes
ravendb/docs pull request #1890
Opened 2024-08-20 11:49 UTC by reebhub

Related issues:
[RDoc-2951](https://issues.hibernatingrhinos.com/issue/RDoc-2951/Document-breaking-changes-for-6.1) - Document breaking changes for 6.1
[RDoc-2968](https://issues.hibernatingrhinos.com/issue/RDoc-2968/Add-6.1-breaking-changes-to-existing-pages) - Add 6.1 breaking changes to related 6.1 articles

2024-08-20 19:54 UTC, reebhub commented
To reviewers:
there are two pages dedicated to breaking changes, one for client issues and a second for server issues, please enter them to find the sections you're related to.
* The server page is at: [migration/server/server-breaking-changes.markdown](https://github.com/ravendb/docs/pull/1890/files#diff-a74241ed82ea88cfadbcb334eb9ead025bfbe55012f8d247183e89e95cac0fc2)
  it includes:
   - Tracking operations using the Changes API now requires Node Tag (@ppekrol)
   - Custom identity parts-separator is operative (@ppekrol)
   - MsSql connection string requires an Encrypt property (@Lwiel)
   - Corax handling of complex JSON objects in static indexes is configurable (@maciejaszyk)

* the client page is at: [migration/client-api/client-breaking-changes.markdown](https://github.com/ravendb/docs/pull/1890/files#diff-d0ed161c6d54ed9e3570bd4ea794f279f6284bba8df5ad7fe7cfe52ab1774747)
  it includes: 
   - Consistency in null handling (Pawel)
   - CounterBatchOperation default increment Delta is 1 (@ppekrol)
   - CmpXchg item can only be created with its index set to 0 (@shaharhikri)
   - Dynamic Linq query cannot apply .Any with logical AND (&&) (@Lwiel)
   - LoadDocument must be provided with a collection name string (@Lwiel)

Besides these:
@shaharhikri  - please take a look at [put-compare-exchange-value.dotnet.markdown](https://github.com/ravendb/docs/pull/1890/files#diff-b7e5edf847a8c90c2bfa03d4eda38b946e6f026fb08579856ba361762ee31c86) (the additional point you requested at the top and the third example you requested at the bottom)
@ppekrol - please take a look at [what-is-changes-api.dotnet.markdown](https://github.com/ravendb/docs/pull/1890/files#diff-862c98db387d8ef52bc4375cc9799445aac3c894df8d0a04584729541a228772) and [how-to-subscribe-to-operation-changes.dotnet.markdown](https://github.com/ravendb/docs/pull/1890/files#diff-8df0ef35482c59b0963bfeacd377780a797f4b988e0acd67591a5b1b52a02a5f) (just added the new overload and a few notes there)

thanks (o:

2024-08-21 07:30 UTC, arekpalinski commented on Documentation/6.1/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +#### 3. Disable the Indexing of the Complex Field
I think we need to rephrase this section. Saying that you can disable the indexing on a specific field isn't the "solution". The whole point is that a user needs to revise the index definition and the usage of fields that they intended for indexing.

Can we emphasize the need of revising the definition? I'd like to force a users make him/her more aware of what they are doing. I'm afraid that just saying "disable the indexing on that field and store it" might sound like a solution. While maybe they don't event need that field at all.

So maybe we can say (similar to what you have here but from slightly different angle):

- searching over a complex field isn't typically indented, so it's likely you don't actually need that field at all
- although if you needed this complex field because of projecting it during queries then you might still keep it but then disable the indexing and explicitly mark that it's stored

@reebhub if you have any doubts please ping me directly

2024-08-21 07:30 UTC, arekpalinski commented on Documentation/6.1/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +* To disable indexing for a specified field **using Code**:
Please note that this sample code does 2 things, marks the field as non indexed _and_ marks it for storing inside index

2024-08-21 07:30 UTC, arekpalinski commented on Documentation/6.1/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +You can handle the complex property as a string.
Let's underline that this is an option only if you _really_ need to index it as a JSON, and search over it. Note it will keep JSON structure so all `{ }` and propetry names like `{ "Latitude":... , "Longitude": ... }` will be processed as well (by the specified analyzer etc)

2024-08-21 07:30 UTC, arekpalinski commented on Documentation/6.1/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +You can handle the complex property as a string.
Oh, I see we talk about that below. So it's fine. Maybe just underline that this is last resort option, if you really need that.

2024-08-21 07:30 UTC, arekpalinski commented on Documentation/6.1/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +
This is not longer the case. We no longer have any distinction between setting explicitly Indexing: Yes, and having the default (which is also Indexing: Yes).

The behavior is the same now. We simply relay on `Indexing.Corax.Static.ComplexFieldIndexingBehavior` option. I think it's worth mentioning here that this is _only_ for new deployed indexes to version 6.1 (or if they will be reset on 6.1, since it's effectively the same as deploying a new index). Old indexes will keep the old behavior.

2024-08-21 07:30 UTC, arekpalinski commented on Documentation/6.1/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +     If the static index explicitly sets the Indexing flag in any other way
Same here, we can drop "If the static index explicitly sets the Indexing flag in any other way but "no""

2024-08-21 07:30 UTC, arekpalinski commented on Documentation/6.1/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +         fields of that object.**
The message will be different:

https://github.com/ravendb/ravendb/pull/19035/files#diff-32e55cbc24468e2b2d3ad17fca814f4ac0922689c702c519c6a21c456f532185R541

```
The value of '{fieldName}' field is a complex object. Typically a complex field is not intended to be indexed as as whole hence indexing it as a text isn't supported in Corax. The field is supposed to have 'Indexing' option set to 'No' (note that you can still store it and use it in projections).
Alternatively you can switch 'Indexing.Corax.Static.ComplexFieldIndexingBehavior' configuration option from 'Throw' to 'Skip' to disable the indexing of all complex fields in the index or globally for all indexes (index reset is required).
If you really need to use this field for searching purposes, you have to call ToString() on the field value in the index definition. Although it's recommended to index individual fields of this complex object. Read more at: https://ravendb.net/l/OB9XW4/6.1
```

2024-08-21 07:30 UTC, arekpalinski commented on Documentation/6.1/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +         Corax will skip the complex field without throwing an exception.
```suggestion
         Corax will skip indexing the complex field without throwing an exception.  
```

2024-08-21 07:30 UTC, arekpalinski commented on Documentation/6.1/Raven.Documentation.Pages/migration/client-api/client-breaking-changes.markdown
> +{CODE-BLOCK/}
Maybe we can add more explanation here? Basically in order to handle a query like that we need a fanout index. That is no supported by auto indexes, hence the solution is to use a static fanout index.

2024-08-21 07:30 UTC, arekpalinski commented on Documentation/6.1/Raven.Documentation.Pages/migration/server/server-breaking-changes.markdown
> +{PANEL: Tracking operations using the Changes API now requires Node Tag}
This is client side change

2024-08-21 07:30 UTC, arekpalinski commented on Documentation/6.1/Raven.Documentation.Pages/server/configuration/indexing-configuration.markdown
> +     None,
I would rather not mention `None` option here

2024-08-21 09:55 UTC, Lwiel requested changes

2024-08-21 09:55 UTC, Lwiel commented on Documentation/6.1/Raven.Documentation.Pages/migration/server/server-breaking-changes.markdown
> +by the `Microsoft.Data.SqlClient` package it utilizes to include in its
Maybe we could mention the reason of this change, e.g. 

by the `Microsoft.Data.SqlClient` package (that replaced deprecated `System.Data.SqlClient` in [version 6.0.105](https://github.com/ravendb/ravendb/releases/tag/6.0.105))

2024-08-21 09:55 UTC, Lwiel commented on Documentation/6.1/Raven.Documentation.Pages/migration/server/server-breaking-changes.markdown
> +Recent RavenDB versions added this property to their connection strings
It only applies to versions 6.0.105 up to 6.1.0 (excluded)

2024-08-21 09:55 UTC, Lwiel commented on Documentation/6.1/Raven.Documentation.Pages/migration/server/server-breaking-changes.markdown
> +To encrypt the connection include an `Encrypt=true` in your connection
`Encrypt` is [an enum](https://learn.microsoft.com/en-us/dotnet/api/microsoft.data.sqlclient.sqlconnectionstringbuilder.encrypt?view=sqlclient-dotnet-standard-5.2), so maybe we should just mention they should either set it to `Strict` or `Mandatory`

2024-08-21 09:55 UTC, Lwiel commented on Documentation/6.1/Raven.Documentation.Pages/migration/client-api/client-breaking-changes.markdown
> +{CODE-BLOCK/}
Yes, we should mention this

2024-08-21 09:55 UTC, Lwiel commented on Documentation/6.1/Raven.Documentation.Pages/migration/client-api/client-breaking-changes.markdown
> +    ComapnyName = LoadDocument(doc.Company, doc.Company.Split('/')[0]).Name
`CompanyName`

2024-08-21 12:31 UTC, Lwiel commented on Documentation/6.1/Raven.Documentation.Pages/migration/server/server-breaking-changes.markdown
> +To encrypt the connection include an `Encrypt=true` in your connection
Yes, but not if they want to encrypt the connection. `Optional` will make it unencrypted

2024-08-21 12:34 UTC, arekpalinski commented on Documentation/6.1/Raven.Documentation.Pages/migration/server/server-breaking-changes.markdown
> +To encrypt the connection include an `Encrypt=true` in your connection
Yeah, but this is up to user. We just say what are the options

2024-08-21 12:52 UTC, ppekrol commented on Documentation/6.1/Raven.Documentation.Pages/migration/server/server-breaking-changes.markdown
> +   * [MsSql connection string requires an Encrypt property](../../migration/server/server-breaking-changes#mssql-connection-string-requires-an-encrypt-property)
MSSQL

2024-08-21 12:52 UTC, ppekrol commented on Documentation/6.1/Raven.Documentation.Pages/migration/server/server-breaking-changes.markdown
> +{PANEL: MsSql connection string requires an Encrypt property}
MSSQL

2024-08-21 12:52 UTC, ppekrol commented on Documentation/6.1/Raven.Documentation.Pages/migration/server/server-breaking-changes.markdown
> +The configuration option was available in Studio's **Client Configuration** for a while, but
I would phrase that differently. Because previously that value could be set in server-wide client configuration, but wasn't taken into account for Database IdentityPartsSeparator. This means that if user set that value prior to 6.1 it was not active, but migrating to 6.1 will immediately activate it.

2024-08-21 12:52 UTC, ppekrol commented on Documentation/6.1/Raven.Documentation.Pages/migration/client-api/client-breaking-changes.markdown
> +by a default `Delta` of `1`.
write that it was 0 before and that 1 is consistent with rest of the API

2024-08-22 07:31 UTC, maciejaszyk commented on Documentation/6.1/Raven.Documentation.Pages/migration/server/server-breaking-changes.markdown
> +  It is recommended, though, to index individual properties of the complex field.
LGTM
cc @arekpalinski

2024-08-22 18:40 UTC, reebhub commented on Documentation/6.1/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +#### 3. Disable the Indexing of the Complex Field
As [shown above](../../indexes/search-engine/corax#index-a-simple-property-contained-in-the-complex-field), indexing a whole complex field is rarely needed, and users would typically index and search only the simple properties such a field contains.  
Queries may sometimes need, however, to **project** the content of an entire complex field.  
When this is the case, you can revise the index definition (see below) to **disable the indexing** of the complex field but **store its content** so [projection queries](../../indexes/querying/projections#projections-and-stored-fields) would be able to project it.

2024-08-22 18:47 UTC, reebhub commented on Documentation/6.1/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +     4. Set to **Yes** when Corax is used since Corax will not index the value.
--> 

{NOTE: }
Content we retrieve from the database and store in indexes becomes available for projection and will be henceforth retrieved directly from the indexes, accelerating its retrieval at the expense of indexes storage space.
{NOTE/}

2024-08-22 18:48 UTC, reebhub commented on Documentation/6.1/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +* To disable indexing for a specified field **using Code**:
--> 

* To store a field's content and disable its indexing **via Studio**:  
  
     ![Disable indexing of a Nested Field](images/corax-08_disable-indexing-of-nested-field.png "Disable indexing of a Nested Field ")

     1. Open the index definition's **Fields** tab.  
     2. Click **Add Field** to specify what field Corax shouldn't index.  
     3. Enter the name of the field Corax should not index.  
     4. Select **Yes** to Store the field's content  
     5. Select **No** to disable the field's indexing  

* To store a field's content and disable its indexing **using Code**:  
  {CODE:csharp index-definition_disable-indexing-for-specified-field@Indexes/SearchEngines.cs /}

2024-08-22 18:54 UTC, reebhub commented on Documentation/6.1/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +You can handle the complex property as a string.
yeah the warning is kind of sharp as it is. added "as a last resort" in any case.

--> 

{NOTE: }
Serializing all the properties of a complex property into a single string, including names, values, brackets, and so on, can be used as a last resort to produce a string that **doesn't** make a good feed for analyzers and is not commonly used for searches.  
It does, however, make sense in some cases to **project** such a string.  
{NOTE/}

2024-08-22 22:16 UTC, reebhub commented on Documentation/6.1/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +         fields of that object.**
done

2024-08-22 22:18 UTC, reebhub commented on Documentation/6.1/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +     If the static index explicitly sets the Indexing flag in any other way
dropped for a **new** static index, kept (phrased differently) for an **old** static index

2024-08-22 22:21 UTC, reebhub commented on Documentation/6.1/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +
changed it to a description of the three scenarios - 
- auto index (same description as before)
- old static index (same description as before)
- new static index (behavior set by `ComplexFieldIndexingBehavior `)

2024-08-22 22:22 UTC, reebhub commented on Documentation/6.1/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +         Corax will skip the complex field without throwing an exception.
done

2024-08-22 22:28 UTC, reebhub commented on Documentation/6.1/Raven.Documentation.Pages/migration/client-api/client-breaking-changes.markdown
> +by a default `Delta` of `1`.
done

2024-08-23 00:01 UTC, reebhub commented on Documentation/6.1/Raven.Documentation.Pages/migration/client-api/client-breaking-changes.markdown
> +{CODE-BLOCK/}
added:

{INFO: }
While _auto_ indexes do not currently support this type of query, _static_ indexes do.  
You can define a **static fanout index** that creates separate index entries for different document sub-objects, and run your query over these entries.  
Read about the indexing of nested data [here](../../indexes/indexing-nested-data),  
and find explanations and samples for fanout indexes [here](../../indexes/indexing-nested-data#fanout-index---multiple-index-entries-per-document).  
{INFO/}

2024-08-23 00:09 UTC, reebhub commented on Documentation/6.1/Raven.Documentation.Pages/migration/server/server-breaking-changes.markdown
> +   * [MsSql connection string requires an Encrypt property](../../migration/server/server-breaking-changes#mssql-connection-string-requires-an-encrypt-property)
done

2024-08-23 00:09 UTC, reebhub commented on Documentation/6.1/Raven.Documentation.Pages/migration/server/server-breaking-changes.markdown
> +{PANEL: MsSql connection string requires an Encrypt property}
done

2024-08-23 00:18 UTC, reebhub commented on Documentation/6.1/Raven.Documentation.Pages/migration/server/server-breaking-changes.markdown
> +{PANEL: Tracking operations using the Changes API now requires Node Tag}
moved to the client-breaking-changes page

2024-08-23 00:33 UTC, reebhub commented on Documentation/6.1/Raven.Documentation.Pages/migration/server/server-breaking-changes.markdown
> +by the `Microsoft.Data.SqlClient` package it utilizes to include in its
done

2024-08-23 00:39 UTC, reebhub commented on Documentation/6.1/Raven.Documentation.Pages/migration/server/server-breaking-changes.markdown
> +Recent RavenDB versions added this property to their connection strings
-->

Some RavenDB versions preceding `6.1` (down to `6.0.105`) added this..

2024-08-23 01:04 UTC, reebhub commented on Documentation/6.1/Raven.Documentation.Pages/migration/server/server-breaking-changes.markdown
> +To encrypt the connection include an `Encrypt=true` in your connection
done

2024-08-23 01:32 UTC, reebhub commented on Documentation/6.1/Raven.Documentation.Pages/migration/server/server-breaking-changes.markdown
> +  It is recommended, though, to index individual properties of the complex field.
thx
changed it a bit and added a few links to the revised Corax section

2024-08-23 02:35 UTC, reebhub commented on Documentation/6.1/Raven.Documentation.Pages/server/configuration/indexing-configuration.markdown
> +     None,
done

2024-08-23 02:42 UTC, reebhub commented on Documentation/6.1/Raven.Documentation.Pages/migration/client-api/client-breaking-changes.markdown
> +    ComapnyName = LoadDocument(doc.Company, doc.Company.Split('/')[0]).Name
fixed, thx

2024-08-23 04:49 UTC, reebhub commented on Documentation/6.1/Raven.Documentation.Pages/migration/server/server-breaking-changes.markdown
> +The configuration option was available in Studio's **Client Configuration** for a while, but
done

2024-08-23 05:44 UTC, arekpalinski commented on Documentation/6.1/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +     4. Set to **Yes** when Corax is used since Corax will not index the value.
perfect

2024-08-23 05:50 UTC, arekpalinski commented on Documentation/6.1/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +     Corax will throw a `NotSupportedInCoraxException ` exception.
But it will do it just once, since we _also_ disable the indexing of that field. So it won't attempt to index next values from that field

2024-08-23 05:51 UTC, arekpalinski commented
Please check one, new comment from. Other than that it LGTM

2024-08-23 10:14 UTC, Lwiel commented on Documentation/6.1/Raven.Documentation.Pages/migration/server/server-breaking-changes.markdown
> +by the `Microsoft.Data.SqlClient` package it utilizes to include in its
Looks good

2024-08-23 10:15 UTC, Lwiel commented on Documentation/6.1/Raven.Documentation.Pages/migration/server/server-breaking-changes.markdown
> +Recent RavenDB versions added this property to their connection strings
Just `RavenDB versions preceding 6.1 (down to 6.0.105) added this...` will be better

2024-08-26 02:12 UTC, reebhub commented on Documentation/6.1/Raven.Documentation.Pages/migration/server/server-breaking-changes.markdown
> +Recent RavenDB versions added this property to their connection strings
done

2024-08-26 02:39 UTC, reebhub commented on Documentation/6.1/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +     Corax will throw a `NotSupportedInCoraxException ` exception.
--> 

 * If the Indexing flag is set to anything but "no" -  
   Corax will throw a `NotSupportedInCoraxException` exception.  
   As disabling indexing for this field will prevent additional attempts to index its values, 
   the exception will be thrown just once.

2024-08-26 05:56 UTC, arekpalinski commented on Documentation/6.1/Raven.Documentation.Pages/indexes/search-engine/corax.markdown
> +     Corax will throw a `NotSupportedInCoraxException ` exception.
great

2024-08-26 05:56 UTC, arekpalinski approved these changes

2024-08-26 08:54 UTC, reebhub commented on Documentation/6.1/Raven.Documentation.Pages/client-api/operations/compare-exchange/put-compare-exchange-value.dotnet.markdown
> +* Creating a new compare exchange item is possible only when the passed _index_ is `0`.
will be able to do that only when a 6.1 client is available for these languages..

2024-08-26 09:13 UTC, Lwiel approved these changes

2024-08-26 09:29 UTC, maciejaszyk approved these changes

2024-08-26 09:33 UTC, shaharhikri approved these changes

2024-08-27 09:53 UTC, merged