[PHP] PHP operations batch 3 - Maintenance Indexes [Replace C# samples]
ravendb/docs pull request #1941
Opened 2024-11-11 02:14 UTC by reebhub

Related issues:
[RDoc-3081](https://issues.hibernatingrhinos.com/issue/RDoc-3081/PHP-Client-API-Operations-Maintenance-Indexes-Put-indexes-Replace-C-samples) Client API > Operations > Maintenance > Indexes > Put indexes
[RDoc-3082](https://issues.hibernatingrhinos.com/issue/RDoc-3082/PHP-Client-API-Operations-Maintenance-Indexes-Resume-indexing-Replace-C-samples) Client API > Operations > Maintenance > Indexes > Resume indexing (start indexing)
[RDoc-3083](https://issues.hibernatingrhinos.com/issue/RDoc-3083/PHP-Client-API-Operations-Maintenance-Indexes-Pause-indexing-Replace-C-samples) Client API > Operations > Maintenance > Indexes > Pause indexing (stop indexing)
[RDoc-3084](https://issues.hibernatingrhinos.com/issue/RDoc-3084/PHP-Client-API-Operations-Maintenance-Indexes-Resume-index-Replace-C-samples) Client API > Operations > Maintenance > Indexes > Resume index (start index)
[RDoc-3085](https://issues.hibernatingrhinos.com/issue/RDoc-3085/PHP-Client-API-Operations-Maintenance-Indexes-Pause-index-Replace-C-samples) Client API > Operations > Maintenance > Indexes > Pause index (stop index)
[RDoc-3086](https://issues.hibernatingrhinos.com/issue/RDoc-3086/PHP-Client-API-Operations-Maintenance-Indexes-Delete-index-Replace-C-samples) Client API > Operations > Maintenance > Indexes > Delete index
[RDoc-3087](https://issues.hibernatingrhinos.com/issue/RDoc-3087/PHP-Client-API-Operations-Maintenance-Indexes-Delete-index-errors-Replace-C-samples) Client API > Operations > Maintenance > Indexes > Delete index errors
[RDoc-3088](https://issues.hibernatingrhinos.com/issue/RDoc-3088/PHP-Client-API-Operations-Maintenance-Indexes-Disable-index-Replace-C-samples) Client API > Operations > Maintenance > Indexes > Disable index
[RDoc-3089](https://issues.hibernatingrhinos.com/issue/RDoc-3089/PHP-Client-API-Operations-Maintenance-Indexes-Enable-index-Replace-C-samples) Client API > Operations > Maintenance > Indexes > Enable index
[RDoc-3090](https://issues.hibernatingrhinos.com/issue/RDoc-3090/PHP-Client-API-Operations-Maintenance-Indexes-Reset-index-Replace-C-samples) Client API > Operations > Maintenance > Indexes > Reset index
[RDoc-3091](https://issues.hibernatingrhinos.com/issue/RDoc-3091/PHP-Client-API-Operations-Maintenance-Indexes-Set-index-lock-mode-Replace-C-samples) Client API > Operations > Maintenance > Indexes > Set index lock mode
[RDoc-3092](https://issues.hibernatingrhinos.com/issue/RDoc-3092/PHP-Client-API-Operations-Maintenance-Indexes-Set-index-priority-Replace-C-samples) Client API > Operations > Maintenance > Indexes > Set index priority
[RDoc-3093](https://issues.hibernatingrhinos.com/issue/RDoc-3093/PHP-Client-API-Operations-Maintenance-Indexes-Get-index-errors-Replace-C-samples) Client API > Operations > Maintenance > Indexes > Get index errors
[RDoc-3094](https://issues.hibernatingrhinos.com/issue/RDoc-3094/PHP-Client-API-Operations-Maintenance-Indexes-Get-index-names-Replace-C-samples) Client API > Operations > Maintenance > Indexes > Get index names
[RDoc-3095](https://issues.hibernatingrhinos.com/issue/RDoc-3095/PHP-Client-API-Operations-Maintenance-Indexes-Get-index-Replace-C-samples) Client API > Operations > Maintenance > Indexes > Get index
[RDoc-3096](https://issues.hibernatingrhinos.com/issue/RDoc-3096/PHP-Client-API-Operations-Maintenance-Indexes-Get-indexes-Replace-C-samples) Client API > Operations > Maintenance > Indexes > Get indexes
[RDoc-3097](https://issues.hibernatingrhinos.com/issue/RDoc-3097/PHP-Client-API-Operations-Maintenance-Indexes-Get-terms-Replace-C-samples) Client API > Operations > Maintenance > Indexes > Get terms
[RDoc-3098](https://issues.hibernatingrhinos.com/issue/RDoc-3098/PHP-Client-API-Operations-Maintenance-Indexes-Index-has-changed-Replace-C-samples) Client API > Operations > Maintenance > Indexes > Index has changed

2024-11-12 11:29 UTC, alxsabo approved these changes

2024-11-12 16:34 UTC, alxsabo requested changes

2024-11-12 22:14 UTC, reebhub commented on Documentation/5.4/Raven.Documentation.Pages/client-api/operations/maintenance/indexes/enable-index.php.markdown
> +| **clusterWide** | `bool` | `true` - Enable index on all database-group nodes<br>`false` - Enable index only on a single node (the preferred node) |
done

2024-11-12 22:15 UTC, reebhub commented on Documentation/5.4/Raven.Documentation.Pages/client-api/operations/maintenance/indexes/get-index-errors.php.markdown
> +| **\*$indexNames** | `array` | List of index names to get errors for |
we really don't (o:
removed

2024-11-13 13:13 UTC, alxsabo approved these changes

2024-11-13 15:00 UTC, merged