Studio all-revisions view
ravendb/docs pull request #1961
Opened 2024-12-19 20:10 UTC by reebhub

related issue: [RDoc-3121](https://issues.hibernatingrhinos.com/issue/RDoc-3121/Document-All-Revisions-view-7.0)

2025-01-26 09:00 UTC, shaharhikri commented
Maybe add a few words about the search?
You can find the documents that have revisions by prefix, like that:
![image](https://github.com/user-attachments/assets/a6d164a5-905d-4b12-8a27-23161db8ac1d)
Only a suggestion, I don't know if it's related to here.

2025-01-26 09:31 UTC, shaharhikri requested changes

2025-01-28 21:53 UTC, reebhub commented on Documentation/7.0/Raven.Documentation.Pages/studio/database/document-extensions/revisions/all-revisions.markdown
> +
* The search bar seems unrelated (a "revision" result always appears when typing an ID in the bar, but it's for a single revision and clicking it leads to the document view)
* added several bullets to the "remove revision" button section, with details about removing regular vs deletion revisions (and additional info). the deletion revision bit includes a reference to the "revision bin" panel that explains is thoroughly.

2025-01-29 10:14 UTC, shaharhikri commented on Documentation/7.0/Raven.Documentation.Pages/studio/database/document-extensions/revisions/all-revisions.markdown
> +
ok :)

2025-01-29 10:16 UTC, shaharhikri approved these changes

2025-01-30 14:52 UTC, merged